### ISSUE TITLE
Don't compress my webapp 

### ISSUE THREAD

**Issue by mightmay** [microsoft/Oryx#1003]
### Feature Request

After deploying into Azure, my webapp get compress into `output.tar.gz` instead of having all the files like in my local computer.
Can we have an option to turn this off ?

Also, I can't set` CompressDestinationDir="false" `in my `oryx-manifest `file because it keep reverting back to `true `every time I deploy.

```

     11:14:58 AM Preparing output...
     11:14:58 AM Copying files to destination directory '/tmp/_preCompressedDestinationDir'...
     11:14:59 AM Done in 1 sec(s).
     11:14:59 AM Compressing content of directory '/tmp/_preCompressedDestinationDir'...
     11:15:03 AM Copied the compressed output to '/home/site/wwwroot'
```

**Comment by qianz2** [comment]
@mightmay, please try a workaround. Setting up an environment variable `COMPRESS_DESTINATION_DIR` to be false.

**Comment by qianz2** [comment]
@mightmay, closing this issue, feel free to reopen if you have other questions.

**Comment by bernardotavares** [comment]
Hey @quianz2, a couple of years too late but I am also trying to turn this compression off.
But `COMPRESS_DESTINATION_DIR` had no effect.
Would it even apply to Python? In the [documentation](https://github.com/microsoft/Oryx/blob/main/doc/configuration.md) this setting only exists for nodejs

**Comment by m-araujo-voltalia** [comment]
I'm having the same problem here...

**Comment by bernardotavares** [comment]
@AtitBimali @m-araujo-voltalia I was suggested some alternative approaches [here](https://stackoverflow.com/questions/77402221/improving-deployment-time-for-django-project-on-azure-web-app).
But none of them are as simple as I would have hoped so I haven't tried them yet
