### ISSUE TITLE
Onyx Fails to deploy at `[20:43:03+0000] Downloading torch-1.8.1-cp37-cp37m-manylinux1_x86_64.whl (804.1 MB)` (downloading Torch)

### ISSUE THREAD

**Issue by adammpolak** [microsoft/Oryx#1013]
### Bug Report

- At what date and time did you most recently experience the problem?
**5/18/21 4:45PM ET**

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
**Azure App Service**

- If your repo is publicly available please share its URL:

- What happened?
**I ran "azure webapp up" and it fails without telling me why**

- What did you expect or want to happen?
**The app should be deployed and running**

- How can we reproduce it?
**Checkout the logs for adammpolak@gmail.com eycoachbackend app service**

- Do you have log output? Please include between the backticks:
![image](https://user-images.githubusercontent.com/12940507/118721259-9e449800-b7f8-11eb-959f-1b78d780bcec.png)

```
Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.7 -i /tmp/8d91a3d76d577ea --compress-destination-dir -p virtualenv_name=antenv --log-file /tmp/build-debug.log
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20210225.2, Commit: f7b557f29a83aa078cc94c0056e7337c07f14271, ReleaseTagName: 20210225.2

Build Operation ID: |+IpdI71vtzI=.78d5aad5_
Repository Commit : ecbf9b11-480e-4de6-980e-5317ddeee001

Detecting platforms...
Detected following platforms:
python: 3.7.9
Warning: An outdated version of python was detected (3.7.9). Consider updating.\nVersions supported by Oryx: https://github.com/microsoft/Oryx


Using intermediate directory '/tmp/8d91a3d76d577ea'.

Copying files to the intermediate directory...
Done in 0 sec(s).

Source directory : /tmp/8d91a3d76d577ea
Destination directory: /home/site/wwwroot

Python Version: /opt/python/3.7.9/bin/python3.7
Python Virtual Environment: antenv
Creating virtual environment...
Activating virtual environment...
Running pip install...
[20:42:57+0000] Collecting Flask>=2.0
[20:42:57+0000] Downloading Flask-2.0.0-py3-none-any.whl (93 kB)
[20:42:57+0000] Collecting Flask-Cors>=3.0
[20:42:57+0000] Downloading Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
[20:42:58+0000] Collecting spacy>=3.0
[20:42:58+0000] Downloading spacy-3.0.6-cp37-cp37m-manylinux2014_x86_64.whl (12.8 MB)
[20:43:01+0000] Collecting spacytextblob>=3.0.1
[20:43:01+0000] Downloading spacytextblob-3.0.1-py3-none-any.whl (4.1 kB)
[20:43:02+0000] Collecting sentence-transformers>=1.1.1
[20:43:02+0000] Downloading sentence-transformers-1.1.1.tar.gz (81 kB)
[20:43:03+0000] Collecting torch>=1.8.1
[20:43:03+0000] Downloading torch-1.8.1-cp37-cp37m-manylinux1_x86_64.whl (804.1 MB)
```

**Comment by adammpolak** [comment]
FYI I upgraded the box and it seems to have gotten past this part.

I would expect Onyx to return something along the lines of "box too small, upgrade memory"

**Comment by qianz2** [comment]
Hi @adammpolak , torch is a relatively large sized dependency, it's hard to know what happened during the pip install process, so it'll always good to check if the memory is enough for large dependencies. Will close this issue. Feel free to reopen if you have questions.
