### ISSUE TITLE
Python app fails to deploy to a function app in vnet

### ISSUE THREAD

**Issue by tech7857** [microsoft/Oryx#1015]
When deploying python code to our function app in a vnet with private end points it fails at detecting platforms step

- At what date and time did you most recently experience the problem?
05/20/2021 entire day

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
- Azure functions

- If your repo is publicly available please share its URL:
- No
- 

- What happened?
- Getting deployment failed error. I am deploying through vscode

- What did you expect or want to happen?
Deployment should succeed. Note i am just deploying the sample basic python http trigger

- How can we reproduce it?
Try deploying the code to a linux based function in a vnet controlled env with private endpoint attached

- Do you have log output? Please include between the backticks:

An unexpected error has occurred.\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /tmp/build/expressbuild --platform python --platform-version 3.8 -i /tmp/8d8f5386e9b06e3 -p packagedir=.python_packages/lib/site-packages

Please assist

thanks

**Comment by drumph33** [comment]
I am having this same issue.  What seems to be happening is that the oryx build command needs access to the internet.  A common reason people are running function apps in vnet integrations is to restrict outbound traffic.  If we know what IPs the oryx build command is hitting then we could allow it in the NSG which should fix the problem.   I had a DenyAll rule as my only rule in the NSG.  I added a rule to allow internet from vnet on 443 and it deploys now.

**Comment by arroyc** [comment]
#971 .. duplicate
