### ISSUE TITLE
Add support for Nx monorepo

### ISSUE THREAD

**Issue by thefinitemonkey** [microsoft/Oryx#1018]
### Feature Request

Deploying with Azure static apps is a very attractive opportunity for us given our Angular / Node stack. However, we build and maintain our code in a Nx monorepo (https://nx.dev). So the files to be hosted are currently supported by Oryx, but the build path with Nx is somewhat different.

Specifically, support for Nx would:

- Treat app_location as project name for "nx build" command
- Treat api_location as project name for "nx build" command (as the api also needs to be built)
- Not use output_location, instead reading output locations for app and api from the outputPath property of each project in the angular.json (or other appropriate file for React, etc.)

**Comment by escreengithub** [comment]
Yes support for this would be really nice!

@thefinitemonkey, do you have a work around for publishing a static site? I may have to try to switch back to a standard Azure app service.

**Comment by collinbarrett** [comment]
@escreengithub , looks like you edited it out of your comment, but, if it's helpful, I am working around this by explicitly building in a separate step from the static web app publish. then, just `skip_app_build`. so, I'm bypassing oryx altogether.

see here: https://github.com/collinbarrett/FilterLists/blob/vNext/.github/workflows/azure-static-web-apps-lemon-stone-084516c10.yml

**Comment by simonjj** [comment]
We're closing this issue due to its age. If this is still impacting you please open a new issue and simply link back to this one.
