### ISSUE TITLE
Provide CLI flags to Hugo

### ISSUE THREAD

**Issue by aaronpowell** [microsoft/Oryx#1023]
A question has come in on the docs for Static Web Apps (https://github.com/MicrosoftDocs/azure-docs/issues/75856) about providing the `--minify` flag to Hugo on build.

Having a bit of a poke around the code myself, I'm not sure if there is a way to provide CLI flags to Hugo.

Can CLI flags be provided to Hugo? If not, can I raise the feature request to allow them to be provided?

**Comment by anthonychu** [comment]
In general, with Static Web Apps, we try to treat Oryx as an implementation detail and prefer customers to configure their app using the GitHub Actions input parameters. The Action has an input named `app_build_command`, which sets `RUN_BUILD_COMMAND` in Oryx during the frontend build. It would be better if we can add support for `RUN_BUILD_COMMAND` for Hugo and other platforms. #1027

**Comment by anthonychu** [comment]
Yep that's a good point. Should be able to do this if I'm not mistaken: https://gohugo.io/getting-started/configuration/#configure-minify

**Comment by arroyc** [comment]
@BhargaviAnnadevara-MSFT @anthonychu  should we consider this to be closed then?

**Comment by arroyc** [comment]
please feel free to reach out if u see this issue again or in case of any other issues
