### ISSUE TITLE
Support Blazor WebAssembly AOT compilation

### ISSUE THREAD

**Issue by anthonychu** [microsoft/Oryx#1026]
### Feature Request

This is a request for .NET 6 Preview 5, which is not out yet. There's a bug in Preview 4 that prevents AOT workloads from working. https://github.com/dotnet/sdk/issues/17865

* When it's a .NET app
* And the csproj contains
    * `<TargetFramework>net6.0</TargetFramework>`
    * a package reference to `Microsoft.AspNetCore.Components.WebAssembly`
* Before running `dotnet publish` or `dotnet build`, run this command to install the Blazor WebAssembly workload
    `dotnet workload install wasm-tools`
* The remaining build steps remain unchanged.

Sample app: https://github.com/anthonychu/ConwayBlazor/tree/3460b8877f05a9bf099e2e473def3f45dc8924fd/Client

**Comment by anthonychu** [comment]
After discussion with @danroth27, updated the detection logic slightly. Any Blazor WebAssembly app on .NET 6 should have the workload installed.

**Comment by qianz2** [comment]
@anthonychu, does that mean we don't need to pass in "static-sites" parameter, it will go run this command generally for .NET 6 Blazor Wasm apps? We've just opened a PR for this issue. Feel free to look into it and left some comments there. Thanks!

**Comment by anthonychu** [comment]
From what I can see in the PR, it looks great. Agree with not needing to check static-sites. Thanks.

**Comment by anthonychu** [comment]
@qianz2 @arroyc It looks like the Blazor AoT build has a dependency on Python 3.6 or higher. By default, Oryx includes Python 2.7 (`python`) and Python 3.5.3 (`python3`). Is it possible to install a newer version of Python 3 when we install this workload?

**Comment by anthonychu** [comment]
In .NET 6 preview 7, the workload will be renamed from `microsoft-net-sdk-blazorwebassembly-aot` to `wasm-tools`. Let's resume working on this after preview 7 is released next week and added to Oryx.

**Comment by loganmarshall1** [comment]
Oooooh sounds like a show a tell! Love it! 

Let me know if you guys want to feature any of my 7 blazor standalone pwa wasm apps running aot on azure static web apps! ;) <3. 

Thank you my friend!

**Comment by anthonychu** [comment]
@loganmarshall1 Send me an email. Would love to hear about your projects. If any of them are on GitHub, I can share with you a totally unsupported private build of the GitHub Action that has this enabled. Interested to test it out with your apps to make sure all is working. anthony.chu@microsoft.com

**Comment by loganmarshall1** [comment]
Hi @anthonychu VS 2022 launch today! ya! 👯 . Looking forward to this update! best of luck today!

**Comment by arroyc** [comment]
This is done.. closing it
