### ISSUE TITLE
Deployment Fail :  Error: Couldn't detect a version for the platform 'python' in the repo.

### ISSUE THREAD

**Issue by tamathew** [microsoft/Oryx#1028]
Getting the below error while deploying azure python functionapp through azure devops and azure cli with REMOTE BUILD enabled.

Command used to deployment :
az functionapp deployment source config-zip --src <local_file_path> --build-remote true --name <appn_ame> --resource-group <rg_name>

----------------
ERROR-----------------------------

Command: oryx build /tmp/zipdeploy/extracted -o /tmp/build/expressbuild --platform python --platform-version 3.8 -i /tmp/8d9252624b79bc4 -p packagedir=.python_packages/lib/site-packages
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Error: Couldn't detect a version for the platform 'python' in the repo.
Oryx Version: 0.2.20210225.2, Commit: f7b557f29a83aa078cc94c0056e7337c07f14271, ReleaseTagName: 20210225.2

Build Operation ID: |Ml0So+Uou20=.afcf4c05_
Repository Commit : 52ebd8a6-d33a-4383-a677-3a5e07b85b25

Detecting platforms...
Could not detect any platform in the source directory.
Error: Couldn't detect a version for the platform 'python' in the repo.\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /tmp/build/expressbuild --platform python --platform-version 3.8 -i /tmp/8d9252624b79bc4 -p packagedir=.python_packages/lib/site-packages

INFO----------------

2021-06-01T17:51:19.0930782Z {
2021-06-01T17:51:19.0932251Z   "azure-cli": "2.23.0",
2021-06-01T17:51:19.0933177Z   "azure-cli-core": "2.23.0",
2021-06-01T17:51:19.0933927Z   "azure-cli-telemetry": "1.0.6",
2021-06-01T17:51:19.0934440Z   "extensions": {
2021-06-01T17:51:19.0935108Z     "azure-devops": "0.18.0"
2021-06-01T17:51:19.0935616Z   }
2021-06-01T17:51:19.0936115Z }

**Comment by arroyc** [comment]
@tamathew ... can you check what are the contents in /tmp/zipdeploy/extracted?

My doubt is there is another folder (say foo) inside extracted but oryx running in /tmp/zipdeploy/extracted ... so its not able to find any python files and hence its not detecting it
