### ISSUE TITLE
Jamstack image - include .NET Core 3.1 SDK in base image

### ISSUE THREAD

**Issue by anthonychu** [microsoft/Oryx#1032]
### Feature Request

In order to build .NET isolated function apps for Static Web Apps, we need .NET Core 3.1 _and_ the version of .NET specified in `<TargetFramework>` to be installed.

After discussion with @arroyc, the best way to support this might be to always include .NET Core 3.1 in the Jamstack image. Can we see how much the image size increases if we do this?

**Comment by qianz2** [comment]
After installing .NET 3.1 SDKs into Jamstack image, it increased by 336M. The total size of image is 2.3G. If it's ok, we will proceed to add .NET Core 3.1 SDK on it.

**Comment by qianz2** [comment]
@anthonychu, we've recently supported it, so closing this issue now.
