### ISSUE TITLE
Python images are being built with PTVSD instead of debugpy

### ISSUE THREAD

**Issue by tonybaloney** [microsoft/Oryx#1035]
When launching a Python app in debug mode (remote debugging enabled), it will run the generator with

```default
Launching oryx with: create-script -appPath /home/site/wwwroot -output /opt/startup/startup.sh -virtualEnvName antenv -defaultApp /opt/defaultsite -debugAdapter ptvsd -debugPort 49494
```

This restarts the application under PTVSD https://github.com/microsoft/Oryx/blob/a09410ab72c54829d8fd5f9f47591656940f903e/src/startupscriptgenerator/src/python/scriptgenerator.go#L307-L322

PTVSD is a deprecated debugger and no longer maintained. 

DebugPy is the replacement debugger used in VS Code. VS Code remote debugging is not compatible with PTVSD (or at least I couldn't get it to work).

please can we update the script generator to use DebugPY

**Comment by arroyc** [comment]
closing because #1050  #1036
