### ISSUE TITLE
Where are Python packages installed from?

### ISSUE THREAD

**Issue by ericthomas1** [microsoft/Oryx#1045]
When publishing an Azure Function from local machine using `func azure functionapp publish <function-name> --publish-local-settings`, where are the Python packages installed from?

- Are they installed from a directory in the local `.venv`? OR
- Are they installed directly from `pip` repos?

**I ask because:**
- All our Python packages must be scanned for malware
- We have our own ArtiFactory setup
- As part of local dev, we install packages using `pip` which is configured to pull from our own ArtiFactory
- I need to make sure that Oryx isn't installing directly from `pip` repos and circumventing our scans, but is rather using the packages installed locally on the dev machine

How can I verify this?
Most importantly, how do I specify the `pip` source from which Oryx installs packages?

**Comment by arroyc** [comment]
if you dont have any fancy setup, your python packages are installed directly from pip ... you can add a pre install command as pip source to verify it

**Comment by ericthomas1** [comment]
Hm... locally I have `pip` setup to pull packages from on-prem ArtiFactory. 
- How do I force Oryx to install packages from a specific location (either from a directory in my local project or from on-prem ArtiFactory)?

**Comment by arroyc** [comment]
is it the case that all of your packages are from on-prem artifactory? or is it mixed like some are from on-prem and some are from public?

usually there is --index-url that you can set as environment 

Refer these docs ..

https://docs.readthedocs.io/en/stable/guides/private-python-packages.html
https://pip.pypa.io/en/stable/cli/pip_install/#requirements-file-format

**Comment by ericthomas1** [comment]
Yes, all packages are from on-prem ArtiFactory. I am able to `pip install` all packages from on-prem ArtiFactory just fine _from my local dev machine_. 

**My specific question is:** 

- When I run `func azure functionapp publish <function-name> --publish-local-settings` is **oryx** using my pip config or is it using its own pip config and installing the packages from the internet?

**Comment by ericthomas1** [comment]
@t4nguy3n, I think the only way to control where packages are installed from is to use custom Azure DevOps pipelines.
