### ISSUE TITLE
Spatial libraries on AppService (Python / Django -> GeoDjango)

### ISSUE THREAD

**Issue by spechtx** [microsoft/Oryx#1049]
### System Package Request

Django offers support for spatial data. All you have to do in order to use spatial data in Django is to change the 'ENGINE' variable from postgresql to postgis:
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresq',
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
```

And activate GIS as an installed app:
```
INSTALLED_APPS = [
   'django.contrib.gis',
```

This typically requires external libraries like GDAL. Please have a look in the Django documentation to see which libraries are required: [https://docs.djangoproject.com/en/3.2/ref/contrib/gis/install/geolibs/](https://docs.djangoproject.com/en/3.2/ref/contrib/gis/install/geolibs/)

On Linux this can be achieved as we run the shell command:
`apt-get update && apt-get install binutils libproj-dev gdal-bin`

Is there any possibility in Azure App Service to achieve this? It seems more users are facing this issue:
[https://stackoverflow.com/questions/37309035/install-gdal-and-geos-libraries-for-windows-on-azure-app-service](https://stackoverflow.com/questions/37309035/install-gdal-and-geos-libraries-for-windows-on-azure-app-service)
[https://github.com/MicrosoftDocs/azure-docs/issues/36927](https://github.com/MicrosoftDocs/azure-docs/issues/36927) (<- solution provided here in 2019 no longer works)

- Why do you need this package? For example, are you using a language-level package which depends on this system package?
Any app should be able to work with spatial data. Even Azure Databases supports PostGIS. It's a very common field of application. It seems like it went unnoticed, that spatial applications like GeoDjango needs geo-packages installed.

- Which Oryx language runtime and version are you using? For example, "Node.js v10.14" or "Python v3.7".
Python v3.8

- What is the name of the package in the latest stable Debian release?For examples, see <https://packages.debian.org/stable/>.
gdal-bin
libgdal-dev
binutils
libproj-dev

- Do you need a specific version? If so, which and why?
No specific version needed.

Thanks for considering!

**Comment by askiefer** [comment]
I second this request! I have a simple app that uses GeoDjango and Postgres and am receiving this error when trying to deploy it:
```
raise ImproperlyConfigured(
2021-07-09T21:01:39.158003221Z django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal3.2.0", "gdal3.1.0", "gdal3.0.0", "gdal2.4.0", "gdal2.3.0", "gdal2.2.0", "gdal2.1.0", "gdal2.0.0"). Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.
```
Seems like this could be the reason my app is failing? I tried setting the GDAL_LIBRARY_PATH in the settings module but no luck

**Comment by gpcastro** [comment]
Thanks for your suggestion and for bringing this gap to our attention.
Do you know of any sample app that uses GeoDjango and is representative of a typical use of the library? We can add it as validation to our test suite.

**Comment by spechtx** [comment]
Hi @gpcastro, an example app, that uses GeoDjango could be Django itself, since GeoDjango is an App that can be activated in the Django setup.

You could include a Django instance with activated GeoDjango app in the validation.

By changing some settings in the settings.py file, Django becomes GeoDjango. It will then check for the geospatial libraries on startup. Without them installed on the local machine, it will show the error message @askiefer got. (<- in this example the GDAL library is missing.)

I'm referring to this tutorial:
[https://docs.djangoproject.com/en/3.2/ref/contrib/gis/install/](https://docs.djangoproject.com/en/3.2/ref/contrib/gis/install/)

Here is an example of the installed apps section my settings.py file:

````
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',  # adds PostGIS / GeoDjango functionality
]`
````

This is my database configuration. Please note that usually only the ENGINE parameter has to be changed.

````
`DATABASES = {
    "default": {
        "ENGINE": 'django.contrib.gis.db.backends.postgis',  # old 'ENGINE': 'django.db.backends.postgresql',
        "NAME": YOUR_DB_NAME,
        "USER": YOUR_DB_USERNAME,
        "PASSWORD": YOUR_DB_PASSWORD,
        "HOST": YOUR_DB_HOST,  # anything.postgres.database.azure.com
        "PORT": YOUR_DB_PORT,
    }
}
````

Also, the database itself needs to have the POSTGIS module installed, like described here:
[https://postgis.net/install/](https://postgis.net/install/)

As admin, run this SQL on the postgres-database used for GeoDjango:
````
CREATE EXTENSION postgis;
````

I hoped that helped. Feel free to respond and i will give further information. Thanks!

**Comment by askiefer** [comment]
@gpcastro I saw that you merged the PR above - does this mean that you were able to get Azure App Service to successfully deploy a GeoDjango app? Is it able to find the GDAL library now?

**Comment by askiefer** [comment]
@spechtx I think the issue might be fixed - have you tried deploying your geodjango app again by any chance?

**Comment by gpcastro** [comment]
@askiefer The fix will be available in the next release of App Service, next month.

**Comment by askiefer** [comment]
Ah okay awesome, thanks!

**Comment by askiefer** [comment]
One other question @gpcastro (if you don't mind) - do you know when in August App Service will next be released?

Just wondering if I should wait or go ahead with an alternative method of hosting. Thanks.

**Comment by ph-eip** [comment]
> askiefer The fix will be available in the next release of App Service, next month.

Do we have an update on when the next release will be? I have a pending deployment with a GDAL dependency.

**Comment by gme5k** [comment]
Is it possible to deploy GeoDjango web apps on App Service at this time?
