### ISSUE TITLE
Add support for .NET 6 Preview 6

### ISSUE THREAD

**Issue by csharpfritz** [microsoft/Oryx#1057]
### Feature Request

Please add support for .NET 6 Preview 6, similar to the update applied for Preview 5 in #1040

**Comment by arroyc** [comment]
@csharpfritz .. thanks for raising this .. we will work on this soon.

**Comment by IEvangelist** [comment]
Thank you for posting this issue @csharpfritz, I too need support for .NET 6 Preview 6. Would love to see this happen soon. 😬

**Comment by IEvangelist** [comment]
Hi @arroyc, I wanted to ask - when do you think you'll get to this?

**Comment by csharpfritz** [comment]
We're nearing a point where it makes more sense to prepare for Preview 7



Jeff

**Comment by arroyc** [comment]
once they release preview 7 we can release it, but im not sure when that will be available via appservice. Can you please log a seperate ticket for peview 7 when its available .. closing current issue as the changes has been checked in .. a tag will be created soon (release in process) which will have preview 6 support.
