### ISSUE TITLE
Error: Encountered an error (InternalServerError) from host runtime.

### ISSUE THREAD

**Issue by swethasharma92** [microsoft/Oryx#1060]
am trying to deploy function to a function app on azure(i had used the same function on another app & it worked fine) via VS code, but facing this error
![final](https://user-images.githubusercontent.com/64375753/126308749-e9812d8e-259f-4da4-8842-7dd243bfb03e.JPG)

other specs:
appservice plan tier: ElasticPremium
function app type: linux

Is there a different way to deploy functions in case of elastic premium ? because the exact same function ran successfully on a 'consumption' tier app.

**Comment by arroyc** [comment]
@swethasharma92  are you using any vpn and special network settings? Can you check if you can access https://oryx-cdn.microsoft.io within that network? if not, you need to whitelist this because oryx needs this to be accessible  to have a successful build. looks like duplicate #971 to me

**Comment by arroyc** [comment]
this looks like an intermittent issue, couldn't repro. closing this issue. Feel free to reopen if you see this again, add more logs to the issue
