### ISSUE TITLE
npm used despite specifying yarn in package.json > engines

### ISSUE THREAD

**Issue by jeroenvdmeer** [microsoft/Oryx#1073]
### Bug Report
In my Azure Static Web Apps monorepo project I've specified in my `package.json` files of my workspaces that yarn should be used as package manager instead of npm. I've done so using the `engines` property as specified in the [Oryx NodeJS runtime documentation](https://github.com/microsoft/Oryx/blob/main/doc/runtimes/nodejs.md#package-manager): _"If a `yarn.lock` file is found in your repo root **or if you specify "yarn" in the engines field of package.json**, the latest or specified version of yarn will be used instead of npm."_

When Oryx built my packages, I noticed my configuration was ignored and npm is still being used. Also after I removed the version number and changed it to `"*"` and added the [`engineStrict`](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines) property to `package.json`:

```json
  "engines": {
    "yarn": "~1.22.11"
  },
  "engineStrict": true,
```

My workaround was to add empty `yarn.lock` files to my workspaces. This was enough to trigger Oryx to use yarn instead of npm, but it feels dirty. Oddly enough, after I added my dummy lock files the `engines` property was used to check the version of yarn. This triggered the following error: `The engine "yarn" is incompatible with this module. Expected version "~1.22.11". Got "1.22.10"`

My suggestion is to follow the [Oryx NodeJS runtime documentation](https://github.com/microsoft/Oryx/blob/main/doc/runtimes/nodejs.md#package-manager) and ditch npm based on the `engines` property in `package.json`.

**Comment by arroyc** [comment]
Thanks for bringing this to our notice. We created an workitem and we will work on this at our earliest  to get this out. Till then I suggest you to use a valid yarn.lock file (can be created locally) and check it in

**Comment by william-msft** [comment]
Hi @jeroenvdmeer, a fix for this has been released. Thank you for your patience. Feel free to reach out regarding addition Oryx related questions. Best regards!

**Comment by radoslavrobes** [comment]
Hi, i saw this bug and i'd like to ask, is there a version to upgrade yarn version?

i'm having similar issue that it complains
The engine "yarn" is incompatible with this module. Expected version "~1.22.11". Got "1.22.10"
(i have different version), but yarn that is used is basically older than the one that it's needed.

Is it possible to upgrade it somehow? to the latest version? 
thanks a lot
rado

**Comment by OrlandoLabao43** [comment]
Hi,
  I'll try to fix this issue later.

**Comment by radoslavrobes** [comment]
Cool, tx a lot
rado
