### ISSUE TITLE
App fails to build monorepo with yarn workspaces

### ISSUE THREAD

**Issue by jeroenvdmeer** [microsoft/Oryx#1085]
**Introduction**
[I also posted this as a bug in the Azure/static-web-apps project](https://github.com/Azure/static-web-apps/issues/542), but as it received no response I realized this issue maybe makes more sense to be reported here?

**Describe the bug**
After repackaging my multirepo project into a monorepo based on yarn workspaces, I noticed the app won't deploy to Azure Static Web Apps anymore.  The issue is that when building the Functions app yarn does not pick up one of the dependencies is found in one of the yarn workspace packages. As a result it tries to find the package in the public registry and fails.

**To Reproduce**
See [this test repo](https://github.com/jeroenvdmeer/aswa-yarntest) I've created based on my setup.

**Expected behavior**
Similar to my development setup: after building the Functions app should be able to run.

**Screenshots**
More details can be found in [my test repo](https://github.com/jeroenvdmeer/aswa-yarntest).

![image](https://user-images.githubusercontent.com/1658477/128810101-459a4ef2-5460-4502-b148-1e030bd77ef9.png)

**Additional context**
One part I'm a bit concerned about is that I added a dummy yarn.lock file in the `packages/api` folder [to trigger Oryx to use yarn instead of npm](https://github.com/microsoft/Oryx/issues/1073). The lockfile didn't hinder me to build the Functions app locally, but if there are better ways to trigger Oryx to use yarn, I'm happy to give them a try to rule out this could affect the build process.

**Comment by arroyc** [comment]
@jeroenvdmeer .. having a dummy yarn.lock is not a good idea .. can you please try creating an yarn.lock locally and then deploy it?

**Comment by jeroenvdmeer** [comment]
@arroyc I understand, but unfortunately individual `yarn.lock` files for each yarn workspace is [not possible at the moment](https://github.com/yarnpkg/berry/issues/1223). The `yarn generate-lock-entry` command did not do the trick, as yarn still tries to find the package in the public registry. There are [yarn plugins available](https://github.com/JanVoracek/yarn-plugin-entrypoint-lockfiles) that could accommodate for this, but that would require at least yarn 2.0, because yarn 1.x does not support plugins. Unfortunately Azure/static-web-apps-deploy@v1 gives yarn v1.22.10 to work with. Requiring a different yarn version in the `engine` property of `package.json` results in a build error. If you see a way to generate a `yarn.lock` file for each yarn workspace, I'm happy to give it a go!

Furthermore, I must note that the app builds perfectly fine locally despite the dummy `yarn.lock` file. And ideally I'd delete it, but it's the only way I figured out to [trick Oryx to use yarn instead of npm](https://github.com/microsoft/Oryx/issues/1073) using Azure/static-web-apps-deploy@v1. I'm happy to try any suggestions you might have.

**Comment by arroyc** [comment]
would it be possible for you to provide a sample app which is very similar to yours .. it will help us troubleshoot and possibly fix the issue sooner @jeroenvdmeer

**Comment by jeroenvdmeer** [comment]
@arroyc Sure, but what would you like to see differently from the test repo I linked to in the issue?

**Comment by gorootde** [comment]
Any news here? This issue makes it impossible to share code between frontend and functions via workspaces

**Comment by erwinsmit** [comment]
I had the same problem with Azure Static Websites using the hybrid Next.js stuff. It was trying to deploy a "static next.js" website because the Next.js dependency was listed in a subdirectory, not the root. 

I use NPM workspaces. I can see there is some Lerna & Lage stuff in this code:
https://github.com/microsoft/Oryx/blob/e805ef4a86e4edb65a4bd0bf4f5a851a8c26c562/src/Detector/Node/NodeDetector.cs

I guess it needs updating so it also works with NPM workspaces and Yarn workspaces. 

Would it also not be nice if you could specify the platforms to use as build parameters? That way this code detection stuff is not necessary.

**Comment by simonjj** [comment]
We're closing this issue due to its age and there seems to be a workaround available at https://github.com/Azure/static-web-apps/issues/542#issuecomment-1010356845. If you feel strongly about a more complete fix to this please open a new issue and simply link back to this one.
