### ISSUE TITLE
Oryx Build Failing: nodejs' version '10.22.0' is unsupported despite not using nodejs

### ISSUE THREAD

**Issue by chrisleduc** [microsoft/Oryx#1086]
### Bug Report

- At what date and time did you most recently experience the problem?
It started somewhere between August 16, 15:54 UTC and August 18, 11:58 UTC. This represent the times between the last successful commit and the first failed one.

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Web Apps

- If your repo is publicly available please share its URL:
It's not public.

- What happened?
Building fails due to _Platform 'nodejs' version '10.22.0' is unsupported_. However, we're not using nodejs and our environment is PHP 4.7.

- What did you expect or want to happen?
It should just build successfully.

- How can we reproduce it?
I'm not sure. Can you try to build a PHP 4.7 project?

- Do you have log output? Please include between the backticks:

```
 Detecting platforms...
 Error: Platform 'nodejs' version '10.22.0' is unsupported. Supported versions: 8.0.0, 8.1.4, 8.2.1, 8.8.1, 8.9.4, 8.11.4, 8.12.0, 8.15.1, 8.17.0, 9.4.0, 10.1.0, 10.10.0, 10.14.2, 10.21.0, 10.23.0, 12.18.2, 12.19.0, 14.15.1
 Error: Platform 'nodejs' version '10.22.0' is unsupported. Supported versions: 8.0.0, 8.1.4, 8.2.1, 8.8.1, 8.9.4, 8.11.4, 8.12.0, 8.15.1, 8.17.0, 9.4.0, 10.1.0, 10.10.0, 10.14.2, 10.21.0, 10.23.0, 12.18.2, 12.19.0, 14.15.1\n/opt/Kudu/Scripts/starter.sh oryx build /home/site/repository -o /home/site/wwwroot --platform php --platform-version 7.4 -i /tmp/8d9624b354f2a5b --log-file /tmp/build-debug.log
```

**Comment by iomariani** [comment]
Same issue here, using PHP 7.4 and the auto-generated CI by Azure WebApp's service provider.

```log
Command: oryx build /home/site/repository -o /home/site/wwwroot --platform php --platform-version 7.4 -i /tmp/8d9626a8ae0ef63 --log-file /tmp/build-debug.log
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20210605.4, Commit: d2189daf082e06fece90175ba65603f21421cc64, ReleaseTagName: 20210605.4

Build Operation ID: |691659r+jfw=.bfd4a87_
Repository Commit : c66b81b107bb706f777f8439f0e42cd3abf01e28

Detecting platforms...
Error: Platform 'nodejs' version '10.22.0' is unsupported. Supported versions: 8.0.0, 8.1.4, 8.2.1, 8.8.1, 8.9.4, 8.11.4, 8.12.0, 8.15.1, 8.17.0, 9.4.0, 10.1.0, 10.10.0, 10.14.2, 10.21.0, 10.23.0, 12.18.2, 12.19.0, 14.15.1
Error: Platform 'nodejs' version '10.22.0' is unsupported. Supported versions: 8.0.0, 8.1.4, 8.2.1, 8.8.1, 8.9.4, 8.11.4, 8.12.0, 8.15.1, 8.17.0, 9.4.0, 10.1.0, 10.10.0, 10.14.2, 10.21.0, 10.23.0, 12.18.2, 12.19.0, 14.15.1\n/opt/Kudu/Scripts/starter.sh oryx build /home/site/repository -o /home/site/wwwroot --platform php --platform-version 7.4 -i /tmp/8d9626a8ae0ef63 --log-file /tmp/build-debug.log
```

Tried detach the deploy and attach again, but no dice.

**Comment by arroyc** [comment]
@iomariani  interesting .. why is it showing nodejs error if your platform is php .. do you have any package.json or yarn.lock in the root level or in sub directories?

**Comment by iomariani** [comment]
> @chrisleduc @iomariani interesting .. why is it showing nodejs error if your platform is php .. do you have any package.json or yarn.lock in the root level or in sub directories?

In my case, yes, there's a `package.json` at the root directory, with devDependencies only.
Our last successful build was also in August 16, at 12:49:41 UTC.

**Comment by chrisleduc** [comment]
> @chrisleduc @iomariani interesting .. why is it showing nodejs error if your platform is php .. do you have any package.json or yarn.lock in the root level or in sub directories?

Yes, we also have yarn.lock and package.json but nodejs is not specified in them (they were not changed since the builds started failing…)

**Comment by arroyc** [comment]
@chrisleduc @iomariani ideally if you are deploying a php app, we assume package.json or yarn.lock should not reside in the root directory else it will be detected as node.js app .. can you put it in some subdirectory and accordingly adjust your scripts/code to refer to new package.json/yarn.lock path

**Comment by iomariani** [comment]
> @chrisleduc @iomariani ideally if you are deploying a php app, we assume package.json or yarn.lock should not reside in the root directory else it will be detected as node.js app .. can you put it in some subdirectory and accordingly adjust your scripts/code to refer to new package.json/yarn.lock path

I had to use another service builder, so I can't test that anymore...
However that doesn't seem to be a viable solution, the error explicitly implies just that the node version oryx uses (10.22.0) is not on the compatible versions it expects.

That list must've changed since Aug 16, otherwise we wouldn't be able to deploy it before.

**Comment by chrisleduc** [comment]
> > @chrisleduc @iomariani ideally if you are deploying a php app, we assume package.json or yarn.lock should not reside in the root directory else it will be detected as node.js app .. can you put it in some subdirectory and accordingly adjust your scripts/code to refer to new package.json/yarn.lock path
> 
> I had to use another service builder, so I can't test that anymore...
> However that doesn't seem to be a viable solution, the error explicitly implies just that the node version oryx uses (10.22.0) is not on the compatible versions it expects.
> 
> That list must've changed since Aug 16, otherwise we wouldn't be able to deploy it before.

I can confirm that removing package.json/yarn.lock from root clears the error. Since we migrated to PHP 8, we still cannot build, but this is expected since it's not a supported version in Oryx. We've now at least temporarily moved away to Oryx as well. We can't confirm this would resolve the issue but it's likely — I'll close the issue with this.

> ### Issue
> When a yarn.lock and/or package.json file is located in the root of the repository, Oryx may incorrectly assume that it is a nodejs project and fail to build.

> ### Solution
> Remove yarn.lock and/or package.json from the root of the repository and place them in a subfolder.
