### ISSUE TITLE
Error: Couldn't detect a version for the platform 'nodejs' in the repo.

### ISSUE THREAD

**Issue by HarshaHirpara** [microsoft/Oryx#1088]
### Bug Report

- At what date and time did you most recently experience the problem?

August 20, 2021
- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.

12:53:18 PM test-aj-dev: Detecting platforms...
12:53:18 PM test-aj-dev: Could not detect any platform in the source directory.
12:53:18 PM test-aj-dev: Error: Couldn't detect a version for the platform 'nodejs' in the repo.
12:53:22 PM test-aj-dev: /opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 12 -i /tmp/8d96403638635c5 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
12:53:30 PM quintrx-aj-dev: Deployment failed.
- If your repo is publicly available please share its URL:

- What happened?

- What did you expect or want to happen?

- How can we reproduce it?

- Do you have log output? Please include between the backticks:

```

```

**Comment by arroyc** [comment]
can you add more information about your app .. this is too little info to start with

**Comment by sshojiro** [comment]
@HarshaHirpara [Documentation for NodeJS](https://github.com/microsoft/Oryx/blob/main/doc/runtimes/nodejs.md#detect) may help you.

**Comment by william-msft** [comment]
Hi @HarshaHirpara, are you able to confirm if the following were met:
The Node.js toolset is run when the following conditions are met per https://github.com/microsoft/Oryx/blob/main/doc/runtimes/nodejs.md#detect:

One of these files is found in the root of the repo:
- package.json
- package-lock.json
- yarn.lock

One of these files is found in the root of the repo:
- server.js
- app.js

If issue still persists, may let us know what node related files are at the root of the application in question please?

**Comment by william-msft** [comment]
Closing issue. Please feel free to reopen with more details if issue persists.

**Comment by nickchaperon** [comment]
Hi

I have completed this tutorial
https://docs.microsoft.com/en-us/azure/app-service/tutorial-nodejs-mongodb-app?tabs=azure-cli%2Cterminal-bash%2Cazure-cli-deploy%2Cdeploy-instructions-azcli%2Cdeploy-zip-linux-mac%2Cdeploy-instructions--zip-azcli#sample-application

I can deploy it successfully when using VS code to deploy the app.

When I try to deploy the app either with _az webapp deploy_ or _az webapp deployment source config-zip_ in cli, I receive the same error. 

Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 14 -i /tmp/8da05724f722e99 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20211207.1, Commit: 46633df49cc8fbe9718772a3c894df221273b2af, ReleaseTagName: 20211207.1

Build Operation ID: |cJzrP4bpEHA=.3a5bad09_
Repository Commit : 77934ee5-786a-4bdf-8cc5-fd55cb2e68e3

Detecting platforms...
Could not detect any platform in the source directory.
Error: Couldn't detect a version for the platform 'nodejs' in the repo.
Error: Couldn't detect a version for the platform 'nodejs' in the repo.\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 14 -i /tmp/8da05724f722e99 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 

The source application file is identical to the file successfully deployed using VS code (except zipped) and has
package.json
package-lock.json
app.js

in the root.

Checking https://lxxx.scm.azurewebsites.net/ reveals that the zip file has not been extracted and placed in the root folder.

This has occured multiple times 13 and 14 March 22. 
As per the tutorial I am expecting that the task app is deployed correctly. 
It is built on Linux and Node 14 LTS

**Comment by rudymiked** [comment]
I am experiencing the same issue, "Error: Couldn't detect a version for the platform 'nodejs' in the repo.", has anyone solved this?

Trying to deploy a new React app to Azure App Service via VS Code.
