### ISSUE TITLE
Static Web App Powershell function not supported

### ISSUE THREAD

**Issue by Orycs** [microsoft/Oryx#1104]
### Bug Report

(last run on 14.09.2021)

Azure Devops pipeline for Static Web App succeeds, yet function host won't start:
- Orys build starts and then log says "Error: Could not detect the language from repo."
- Function host defaulting to 'node' although /api contains powershell code
- no way to pass parameters to Oryx

**Comment by anthonychu** [comment]
For Static Web Apps, the request is tracked here. It's not enough for Oryx to support building it, Static Web Apps needs to support deploying these apps too. At this time, we have not committed to adding this support and recommend using the [Bring Your Own Function App](https://docs.microsoft.com/en-us/azure/static-web-apps/functions-bring-your-own) feature.

**Comment by simonjj** [comment]
We're closing this issue due to its age. If this is still impacting you please open a new issue and simply link back to this one.
