### ISSUE TITLE
Add PHP pdo_sqlsrv extension in build image

### ISSUE THREAD

**Issue by saicsm** [microsoft/Oryx#1105]
### Feature Request

Looks like App Service with PHP 8.0 currently not support pdo_sqlsrv driver. I have reached out to MS support and was informed to install the driver manually.

Can you install the extension for PHP 8.0 in app service?

**Comment by arroyc** [comment]
@saicsm @DiscoParadise thanks for reporting this, yes we are going to add this in php 8.0 and it will available in next deployment of appservice usually November timeframe
