### ISSUE TITLE
PHP not automatically on PATH on build image

### ISSUE THREAD

**Issue by derekbekoe** [Microsoft/Oryx#112]
### Bug Report

- At what date and time did you most recently experience the problem?
May 2, 2019

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Offline

- If your repo is publicly available please share its URL:
n/a

- What happened?
php not found.

- What did you expect or want to happen?
php command should be found.

- How can we reproduce it?
```
$ docker run -it oryxprod/build:latest
root@43ae7ffbd715:/# php
bash: php: command not found
root@43ae7ffbd715:/# ls /opt/php
5.6.40  7.0.33  7.2.17  7.3.4
root@43ae7ffbd715:/# source benv php=7.3.4
root@43ae7ffbd715:/# php --version
PHP 7.3.4 (cli) (built: Apr 17 2019 12:24:39) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.4, Copyright (c) 1998-2018 Zend Technologies
root@43ae7ffbd715:/# 
```

**Comment by gpcastro** [comment]
Thanks Derek. I can repro the issue, working on a fix.

**Comment by gpcastro** [comment]
@derekbekoe tag 20190507.2 has the fix for this issue.

**Comment by derekbekoe** [comment]
Thanks!
