### ISSUE TITLE
Support mkdocs static site generator

### ISSUE THREAD

**Issue by simonaco** [microsoft/Oryx#1124]
### Feature Request

[mkdocs](https://github.com/mkdocs/mkdocs/) is a python static site generator that requires us to run a custom app build command to generate the static assets. Currently the Oryx build fails with Error: Could not detect the language from repo. 

My requirements.txt includes mkdocs==1.2.2 
Config:

app_location: "/docs" # App source code path
api_location: "api" # Api source code path - optional
output_location: "site" # Built app content directory - optional
app_build_command: "mkdocs build"

Expected behavior is that Oryx runs the custom build command and generates the static files.

**Comment by anthonychu** [comment]
Related: https://github.com/microsoft/Oryx/issues/1027

**Comment by william-msft** [comment]
Closing per https://github.com/microsoft/Oryx/issues/1124#issuecomment-932526316
