### ISSUE TITLE
AzureStaticWebApp: An unknown exception has occurred

### ISSUE THREAD

**Issue by MalteToenjes** [microsoft/Oryx#1125]
### Bug Report

- At what date and time did you most recently experience the problem?
Since the 09/30/21

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure StaticWebApp

- If your repo is publicly available please share its URL:
not public but I can share the structure of the repo
![image](https://user-images.githubusercontent.com/4049686/135457793-ad1d7bc9-4c1d-4a46-b2f2-ec15531f4f00.png)

- What happened?
In the task AzureStaticWebApp an Error occurs and the task fails

> Detecting platforms...
> Could not detect any platform in the source directory.
> Error: Could not detect the language from repo.
> 
> 
> ---End of Oryx build logs---
> Oryx was unable to determine the build steps. Continuing assuming the assets in this folder are already built. If this is an unexpected behavior please contact support.
> An unknown exception has occurred

This issue came out of nowhere, yesterday it worked. Also strange is in the builds before which were succeeded the error "Error: Could not detect the language from repo." also occurred (but it worked). But this "An unknown exception has occurred" is a new message.

- What did you expect or want to happen?
A successful build

- How can we reproduce it?

- Do you have log output? Please include between the backticks:

```
Starting: AzureStaticWebApp
==============================================================================
Task         : Deploy Azure Static Web App
Description  : [PREVIEW] Build and deploy an Azure Static Web App
Version      : 0.187.2
Author       : Microsoft Corporation
Help         : https://aka.ms/swadocs
==============================================================================
/usr/bin/bash /home/vsts/work/_tasks/AzureStaticWebApp_18aad896-e191-4720-88d6-8ced4806941a/0.187.2/launch-docker.sh
Unable to find image 'mcr.microsoft.com/appsvc/staticappsclient:stable' locally
stable: Pulling from appsvc/staticappsclient
a0edb687a3da: Pull complete
6891892cc2ec: Pull complete
684eb726ddc5: Pull complete
b0af097f0da6: Pull complete
2ed41dfdfeca: Pull complete
f365d77bcf6d: Pull complete
25af1a48b49f: Pull complete
e2b88c95fb92: Pull complete
6a056db05452: Pull complete
5f9676349597: Pull complete
e626f4616ba2: Pull complete
691b82e2d0a5: Pull complete
f6ce4cbbe3d5: Pull complete


Digest: sha256:ab19e4b2e97ab152787906b9fc50a8e40fc69b8b6a5116e259ee7fe533f93cfe
Status: Downloaded newer image for mcr.microsoft.com/appsvc/staticappsclient:stable
DeploymentId: 811dbb2a-8f5f-47a1-9f02-ed632ff2bb57

App Directory Location: 'DevCryptotrackingFrontend' was found.
Api Directory Location: 'DevCryptotrackingFrontend/src/api' was found.
Looking for event info
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
---Oryx build logs---


Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20210410.1, Commit: e73613ae1fd73c809c00f357f8df91eb984e1158, ReleaseTagName: 20210410.1

Build Operation ID: |QYqaQV9XRKw=.b6d88af3_
Repository Commit : e36504c137e3373488801de4898ef2809d0c657b

Detecting platforms...
Detected following platforms:
  nodejs: 14.17.6
  php: 7.3.27
Version '14.17.6' of platform 'nodejs' is not installed. Generating script to install it...
Version '7.3.27' of platform 'php' is not installed. Generating script to install it...


Source directory     : /working_dir/DevCryptotrackingFrontend
Destination directory: /ss-oryx/app


Downloading and extracting 'nodejs' version '14.17.6' to '/tmp/oryx/platforms/nodejs/14.17.6'...
Downloaded in 3 sec(s).
Verifying checksum...
Extracting contents...
Done in 4 sec(s).


Downloading and extracting 'php' version '7.3.27' to '/tmp/oryx/platforms/php/7.3.27'...
Downloaded in 0 sec(s).
Verifying checksum...
Extracting contents...
Done in 0 sec(s).


Downloading and extracting 'php-composer' version '2.0.8' to '/tmp/oryx/platforms/php-composer/2.0.8'...
Downloaded in 1 sec(s).
Verifying checksum...
Extracting contents...
Done in 1 sec(s).

Using Node version:
v14.17.6

Using Yarn version:
1.22.10

Running 'yarn install --prefer-offline'...

yarn install v1.22.10
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning node-sass > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning node-sass > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning node-sass > request > har-validator@5.1.5: this library is no longer supported
warning tempusdominus-bootstrap-4 > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning @types/flatpickr@3.1.2: This is a stub types definition for flatpickr (https://github.com/chmln/flatpickr). flatpickr provides its own type definitions, so you don't need @types/flatpickr installed!
warning @types/moment@2.13.0: This is a stub types definition for Moment (https://github.com/moment/moment). Moment provides its own type definitions, so you don't need @types/moment installed!
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > styled-components@5.3.0" has unmet peer dependency "react-is@>= 16.8.0".
warning " > @fortawesome/react-fontawesome@0.1.15" has unmet peer dependency "@fortawesome/fontawesome-svg-core@^1.2.32".
warning " > bootstrap@5.1.1" has incorrect peer dependency "@popperjs/core@^2.10.1".
warning "graphql.macro > babel-literal-to-ast@2.1.0" has unmet peer dependency "@babel/core@^7.1.2".
warning " > react-axios@2.0.5" has unmet peer dependency "prop-types@^15.7.0".
warning " > eslint-plugin-react-hooks@4.2.0" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0".
warning " > tempusdominus-bootstrap-4@5.39.0" has unmet peer dependency "popper.js@^1.16.1".
warning " > tempusdominus-bootstrap-4@5.39.0" has unmet peer dependency "tempusdominus-core@5.19.0".
warning " > @testing-library/user-event@7.2.1" has unmet peer dependency "@testing-library/dom@>=5".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 54.33s.

Running 'yarn run build'...

yarn run v1.22.10
$ react-scripts build
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  329.22 KB (-4.64 KB)  build/static/js/2.47fbd00e.chunk.js
  56.69 KB (+945 B)     build/static/css/3.410b0fbf.chunk.css
  56.46 KB (+945 B)     build/static/css/4.b17227d4.chunk.css
  39.25 KB (-64 B)      build/static/js/main.cbd1cf90.chunk.js
  13.73 KB (+19 B)      build/static/css/main.70b1e9d1.chunk.css
  2.94 KB               build/static/css/2.1f56c446.chunk.css
  1.5 KB (-3 B)         build/static/js/runtime-main.77fc1d41.js
  250 B                 build/static/js/3.a3a185d2.chunk.js
  248 B (-1 B)          build/static/js/4.aff5ce4c.chunk.js

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  yarn global add serve
  serve -s build

Find out more about deployment here:

  https://cra.link/deployment

Done in 66.66s.
Preparing output...

Copying files to destination directory '/ss-oryx/app'...
Done in 7 sec(s).


Removing existing manifest file
Creating a manifest file...
Manifest file created.

Done in 133 sec(s).


---End of Oryx build logs---
Oryx has determined that the app build artifacts are in the 'build' directory. If this is incorrect please specify the app artifact location.
Finished building app with Oryx
Found and validated 'routes.json' within build artifacts folder.
Starting to build function app with Oryx
---Oryx build logs---


Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20210410.1, Commit: e73613ae1fd73c809c00f357f8df91eb984e1158, ReleaseTagName: 20210410.1

Build Operation ID: |mbeawjk9gtI=.15f0f233_
Repository Commit : e36504c137e3373488801de4898ef2809d0c657b

Detecting platforms...
Could not detect any platform in the source directory.
Error: Could not detect the language from repo.


---End of Oryx build logs---
Oryx was unable to determine the build steps. Continuing assuming the assets in this folder are already built. If this is an unexpected behavior please contact support.
An unknown exception has occurred

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting

Finishing: AzureStaticWebApp

```

**Comment by arcticdba** [comment]
Unfortunately I'm facing the exact same issue despite both the Hugo and Oryx versions being the same between when it worked and when it doesn't. The issue literally came out of nowhere.

**Comment by anthonychu** [comment]
@arcticdba Is your build failing at the function app build too? Can you share your workflow file and logs? GitHub or Azure Pipelines?

@MalteToenjes  Can you share your pipeline file?

**Comment by arcticdba** [comment]
Yep, the exact same place., running GitHub actions. Let me know if I attached the right logs - I really don't know what I'm doing 😶

[4_Build And Deploy.txt](https://github.com/microsoft/Oryx/files/7269995/4_Build.And.Deploy.txt)
[azure-static-web-apps-black-moss-08cc4b203.yml.txt](https://github.com/microsoft/Oryx/files/7270001/azure-static-web-apps-black-moss-08cc4b203.yml.txt)

**Comment by anthonychu** [comment]
@arcticdba do you have an api in your repo? Blank out api_location if you don’t have an api. If you have one, we’ll need to see the folder’s contents.

**Comment by arcticdba** [comment]
@anthonychu I do not, and blanking out the api_location did the trick! I'm guessing something changed in the backend that did not take kindly to the api_location setting (which was default from the Azure static website, by the way)?

**Comment by MalteToenjes** [comment]
Hey @anthonychu, thanks for your answer.

our FunctionApp Pipeline has no issues. We are using Azure Pipelines.

Here is the pipeline file:
`# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-20.04

steps:
- checkout: self
- checkout: git://CryptoProject/DevCommon
  persistCredentials: true
  clean: true
  submodules: true
  path: s/DevCryptotrackingFrontend/src/common

- task: NodeTool@0
  inputs:
    versionSpec: '14.17.1'
  displayName: 'Install Node.js'


- script: |
    npm install
    npm run build
    npm audit fix
  displayName: 'npm install, build and audit fix'
  workingDirectory: '$(Build.SourcesDirectory)/DevCryptotrackingFrontend'

- task: AzureStaticWebApp@0
  continueOnError: false
  inputs:
      app_location: "DevCryptotrackingFrontend"
      api_location: "DevCryptotrackingFrontend/src/api"
      output_location: ""
  env:
    azure_static_web_apps_api_token: $(deployment_token)
    REACT_APP_CRYPTO_API_URL: $(REACT_APP_CRYPTO_API_URL)
    REACT_APP_AUTH0_DOMAIN: $(REACT_APP_AUTH0_DOMAIN)
    REACT_APP_AUTH0_CLIENT_ID: $(REACT_APP_AUTH0_CLIENT_ID)
    REACT_APP_AUTH0_audience: $(REACT_APP_AUTH0_audience)`

Since we are using a api this is the content:
![image](https://user-images.githubusercontent.com/4049686/135802107-b9061586-58bf-4c6d-a840-1aeb4e82167c.png)

**Comment by anthonychu** [comment]
@MalteToenjes Based on your screenshot, your src/api folder doesn't appear to contain a valid Azure Functions app. For a TypeScript function app, I would expect to see a package.json and host.json in that folder.

@arcticdba Do you have a folder in your source named `api`? If `api_location` is specified but the folder doesn't exist, it should print `Either no Api directory was specified, or the specified directory was not found. Azure Functions will not be created.` and the build should not fail.

**Comment by MalteToenjes** [comment]
Well its not a FunctionApp its a StaticWebApp

**Comment by MalteToenjes** [comment]
I just removed api_location and now the pipeline is running again. Since it seems that api_location is unnecessary for us the issue is fixed.
I have to say its really weird and frustrating that a update caused this type of issues and the system acts like a blackbox with inaccurate error messages. But thanks anyway for your help.
