### ISSUE TITLE
Unable to deploy gatsby based Azure Static Web App with Azure functions enabled using Azure DevOps and deployment in multiple environments 

### ISSUE THREAD

**Issue by Saksham2514** [microsoft/Oryx#1132]
While trying to deploy a SWA using Azure DevOps in multiple environments but while deploying via yaml filr oryx error is being encountered as language not found.The SWA is in gatsby and is using azure functions. I've tried npm install and gatsby build but it's not getting processed. The Yaml code is attached below 

trigger:
  - main
stages:
  - stage: deploy
    jobs:
    - deployment: DeployWeb
      displayName: deploy Web App
      pool:
        vmImage: 'ubuntu-latest'
      environment: Production
      strategy: 
        runOnce:
          deploy:
            steps:
            - script: npm install -g gatsby-cli
              displayName: 'CLI Install'
            - script: npm --save install
              displayName: 'npm install'
            - script: npm --save install gatsby
              displayName: 'gatsby install'
            - script: gatsby build 
              displayName : 'gatsby build'
            - task: AzureStaticWebApp@0
              inputs:               
                app_location: "/"
                api_location: "/api"
                output_location: "/public"
                azure_static_web_apps_api_token: $(deployment_token)

![image](https://user-images.githubusercontent.com/78557522/136460632-197cd343-4401-4468-8baa-7ff113a5672b.png)

**Comment by william-msft** [comment]
Hi @Saksham2514 may you confirm the Node detection requirements listed in the following are satisfied:
https://github.com/microsoft/Oryx/blob/main/doc/runtimes/nodejs.md#detect

The provided screenshot suggests the `package.json` may be invalid.

Would you be able to provide more of the stacktrace? I do not see Oryx error in the screenshot that has been provided. Thank you for your patience.

**Comment by william-msft** [comment]
Closing issue. Please feel free to reopen with additional details.
