### ISSUE TITLE
Support for dotnet5 Azure functions in static Webapps

### ISSUE THREAD

**Issue by fnandocontreras** [microsoft/Oryx#1141]
### Feature Request

Last time occurrence: 23/10/2021
Failure when building/deploying Azure static Webapps with Azure functions targeting **net5.0**
I found out in this [StackOverflow ](https://stackoverflow.com/questions/68077956/oryx-the-framework-microsoft-netcore-app-version-3-1-0-was-not-found) that dotnet5 is not supported in azure functions for static web apps.
Du you plan to support it in the near future?
Thanks in advance

#### Build and Deploy job logs
/usr/bin/docker run --name f884204762e61e11624e73a9b9475569cf06ef_3a05b3 --label f88420 --workdir /github/workspace --rm -e INPUT_AZURE_STATIC_WEB_APPS_API_TOKEN -e INPUT_REPO_TOKEN -e INPUT_ACTION -e INPUT_APP_LOCATION -e INPUT_API_LOCATION -e INPUT_OUTPUT_LOCATION -e INPUT_API_BUILD_COMMAND -e INPUT_APP_ARTIFACT_LOCATION -e INPUT_APP_BUILD_COMMAND -e INPUT_ROUTES_LOCATION -e INPUT_SKIP_APP_BUILD -e INPUT_CONFIG_FILE_LOCATION -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/DevBlog/DevBlog":"/github/workspace" f88420:4762e61e11624e73a9b9475569cf06ef
DeploymentId: 8f3f5d8d-9ebf-402a-a488-e599893b798d

App Directory Location: 'BlazorWebApp' was found.
Api Directory Location: 'Blog.Functions' was found.
Looking for event info
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
---Oryx build logs---

Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20210410.1, Commit: e73613ae1fd73c809c00f357f8df91eb984e1158, ReleaseTagName: 20210410.1

Build Operation ID: |CJ0wwxjynxw=.26ebb98d_
Repository Commit : c33faf53cb9535553a02a0e86109483d8edef454

Detecting platforms...
Detected following platforms:
  dotnet: 5.0.9
Version '5.0.9' of platform 'dotnet' is not installed. Generating script to install it...

Source directory     : /github/workspace/BlazorWebApp
Destination directory: /bin/staticsites/ss-oryx/app

Downloading and extracting 'dotnet' version '5.0.400' to '/tmp/oryx/platforms/dotnet/5.0.400'...
Downloaded in 2 sec(s).
Verifying checksum...
Extracting contents...
Done in 6 sec(s).

Using .NET Core SDK Version: 5.0.400

Welcome to .NET 5.0!
---------------------
SDK Version: 5.0.400

Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20210410.1, Commit: e73613ae1fd73c809c00f357f8df91eb984e1158, ReleaseTagName: 20210410.1

Build Operation ID: |83uD9lM93eY=.1945fe63_
Repository Commit : c33faf53cb9535553a02a0e86109483d8edef454

Detecting platforms...
Detected following platforms:
  dotnet: 5.0.9

Source directory     : /github/workspace/Blog.Functions
Destination directory: /bin/staticsites/ss-oryx/api

Using .NET Core SDK Version: 5.0.400
  Determining projects to restore...
  Restored /github/workspace/Blog.Functions/Blog.Functions.csproj (in 2.75 sec).
  1 of 2 projects are up-to-date for restore.

Publishing to directory /bin/staticsites/ss-oryx/api...

Microsoft (R) Build Engine version 16.11.0+0538acc04 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  BlogShared -> /github/workspace/Shared/bin/Release/net5.0/BlogShared.dll
  Blog.Functions -> /github/workspace/Blog.Functions/bin/Release/net5.0/Blog.Functions.dll
  Determining projects to restore...
  Restored /tmp/ptpyls2i.xvj/WorkerExtensions.csproj (in 4.48 sec).
  WorkerExtensions -> /tmp/ptpyls2i.xvj/buildout/Microsoft.Azure.Functions.Worker.Extensions.dll
/var/nuget/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : It was not possible to find any compatible framework version [/tmp/ptpyls2i.xvj/WorkerExtensions.csproj]
/var/nuget/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : The framework 'Microsoft.NETCore.App', version '3.1.0' was not found. [/tmp/ptpyls2i.xvj/WorkerExtensions.csproj]
/var/nuget/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :   - The following frameworks were found: [/tmp/ptpyls2i.xvj/WorkerExtensions.csproj]
/var/nuget/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :       5.0.9 at [/tmp/oryx/platforms/dotnet/5.0.400/shared/Microsoft.NETCore.App] [/tmp/ptpyls2i.xvj/WorkerExtensions.csproj]
/var/nuget/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [/tmp/ptpyls2i.xvj/WorkerExtensions.csproj]
/var/nuget/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : You can resolve the problem by installing the specified framework and/or SDK. [/tmp/ptpyls2i.xvj/WorkerExtensions.csproj]
/var/nuget/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [/tmp/ptpyls2i.xvj/WorkerExtensions.csproj]
/var/nuget/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : The specified framework can be found at: [/tmp/ptpyls2i.xvj/WorkerExtensions.csproj]
/var/nuget/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :   - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=debian.9-x64 [/tmp/ptpyls2i.xvj/WorkerExtensions.csproj]
/var/nuget/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [/tmp/ptpyls2i.xvj/WorkerExtensions.csproj]
/var/nuget/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : Metadata generation failed. [/tmp/ptpyls2i.xvj/WorkerExtensions.csproj]

---End of Oryx build logs---
Oryx has failed to build the solution.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting

#### Github workflow YAML:
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - testing-blazor
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - testing-blazor

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_SEA_0B0A35F03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "BlazorWebApp" # App source code path
          api_location: "Blog.Functions" # Api source code path - optional
          output_location: "wwwroot" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_SEA_0B0A35F03 }}
          action: "close"

**Comment by anthonychu** [comment]
.NET 6 LTS functions is now supported in Static Web Apps. We have no plans to support .NET 5.

**Comment by viru06** [comment]
I am facing a deployment issue.

happytransformer


/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.9 -p packagedir=.python_packages/lib/site-packages
18:30:11 NLPQK: Deployment failed.

**Comment by anthonychu** [comment]
@viru06 Is this for Functions running outside of Static Web Apps?

/cc @balag0

**Comment by fnandocontreras** [comment]
Hey @anthonychu thanks for your answer, that's great that dotnet6 is now supported.
Am closing the issue.
