### ISSUE TITLE
Update NodeJS with 16.13.0 LTS support

### ISSUE THREAD

**Issue by Strepto** [microsoft/Oryx#1145]
### Feature Request

![image](https://user-images.githubusercontent.com/3185998/139415658-1ba12103-0bc2-467b-8d29-cba23c0cffc0.png)
https://nodejs.org/en/about/releases/

Node JS 16.13 is released as the new LTS version, but is not yet available on Oryx.

It would be nice to have an update on the supported Node JS version to v16.13.0

**Comment by arroyc** [comment]
thanks we are working on this right now .. very soon you should be able to see the updated version
