### ISSUE TITLE
Detecting platforms... Error: Oops... An unexpected error has occurred. 

### ISSUE THREAD

**Issue by bugwrangler** [microsoft/Oryx#1179]
### Bug Report

- At what date and time did you most recently experience the problem?
Around 2021-05-12 17h00 GMT

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Locally while trying to deploy Azure Functions

- If your repo is publicly available please share its URL:
Private Repo

- What happened?
I am trying to deploy a python function app and the function deployment failed with the error detecting platforms. It works when I'm deploying it to a different function app that has the exact same settings.

Similar issue -  

https://github.com/microsoft/Oryx/issues/971
https://github.com/microsoft/Oryx/issues/929

- What did you expect or want to happen?
I'd expect the deployment to succeed, or at least there should be an easy way to find out what went wrong from the logs.

- How can we reproduce it?

Deploy the premium Azure function in West Europe Region

- Do you have log output? Please include between the backticks:

```
> func version
4.0.3971

> ls
__init__.py         __pycache__         function.json       host.json           local.settings.json requirements.txt    sample.dat


17:43:17: Detecting platforms...
17:44:57: Error: Oops... An unexpected error has occurred.
17:45:00: /opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /tmp/build/expressbuild --platform python --platform-version 3.9 -i /tmp/8d9b9a90c273278 -p packagedir=.python_packages/lib/site-packages
17:45:08 : Deployment failed.
```

**Comment by anthonychu** [comment]
Not sure if this is causing your problem, but this doesn't look like a valid function app. `function.json` and `__init__.py` should be in a subfolder. Can you share your code and the commands you ran? (is it `func azure functionapp publish --build remote ...`?)

**Comment by simonjj** [comment]
We're closing this issue due to its age. If this is still impacting you please open a new issue and simply link back to this one.
