### ISSUE TITLE
Java LTS symlinks incorrectly [codespaces]

### ISSUE THREAD

**Issue by joshspicer** [microsoft/Oryx#1199]
### Bug Report

- At what date and time did you most recently experience the problem?
Yesterday

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
GitHub Codespaces

- If your repo is publicly available please share its URL:
https://github.com/xmolecules/jmolecules-integrations (using the default vso image)

- What happened?
See https://github.com/microsoft/vscode-dev-containers/issues/1245 - Java LTS is linked to 17.0.1 but actually installs 1.8

- What did you expect or want to happen?

Symlinking the proper version of Java

- How can we reproduce it?
Create a codespace (or do an oryx build with [this current oryx vso image version used](https://github.com/microsoft/vscode-dev-containers/blob/main/containers/codespaces-linux/.devcontainer/base.Dockerfile#L5).

- Do you have log output? Please include between the backticks:

```

```

**Comment by william-msft** [comment]
Hi @joshspicer a fix has been released. Here is the new Oryx tag: https://github.com/microsoft/Oryx/releases/tag/20220120.1

**Comment by joshspicer** [comment]
thank you!
