### ISSUE TITLE
[codespaces] when uid/gid is not 1000, user/oryx does not have adequate permissions 

### ISSUE THREAD

**Issue by joshspicer** [microsoft/Oryx#1206]
In our codespaces image we run into false negative test failures because the test runner executing our code is not UID 1000.

Relevant test failures are illustrated here: https://github.com/microsoft/vscode-dev-containers/pull/1255#issuecomment-1017737126 and [this ci run](https://github.com/microsoft/vscode-dev-containers/actions/runs/1724541369)

cc/ @william-msft @Chuxel

**Comment by joshspicer** [comment]
our test prints out the current uid/gid for the test run: https://github.com/microsoft/vscode-dev-containers/runs/4885465855?check_suite_focus=true#step:3:6752

**Comment by simonjj** [comment]
Looks like this issue has been resolved. Closing this issue now, if this happens to still be an issue please open an new issue and link back to this issue from there.
