### ISSUE TITLE
[codespaces] Default version of node is 14

### ISSUE THREAD

**Issue by joshspicer** [microsoft/Oryx#1207]
The default (symlinked to `current`) version of node in the vso image is node 14, when it should be the latest version 16.

```
@joshspicer ➜ /workspaces/almost-empty (main ✗) $ node -v
v14.17.6
@joshspicer ➜ /workspaces/almost-empty (main ✗) $ which node
/home/codespace/.nodejs/current/bin/node
@joshspicer ➜ /workspaces/almost-empty (main ✗) $ 
```

cc/ @william-msft @chuxel

**Comment by qianz2** [comment]
@joshspicer We've updated node lts versions to 16 in vso images: https://github.com/microsoft/Oryx/pull/1218, which will be available in our next release.

**Comment by joshspicer** [comment]
Great! Thanks!

**Comment by joshspicer** [comment]
Hey guys - should [this version of the vso image have node 16 by default on the path?](https://github.com/microsoft/vscode-dev-containers/pull/1299/files#diff-94a40bc2757cdd12c21fcc08f9694dea5c174a7fe08a4a7665b45e640d154822R5), if you look at our CI run and search for `node`, you'll see it's defaulting to 14.
