### ISSUE TITLE
Custom location for requirements.txt

### ISSUE THREAD

**Issue by anguspmitchell** [microsoft/Oryx#1210]
### Feature Request

For python function apps, requirements.txt must be in the project root. We have multiple requirements.txt and would like to store it in a separate location, e.g. `./requirements/azure-prod.txt`. 

https://docs.microsoft.com/en-us/azure/app-service/configure-language-python#customize-build-automation
> Run pip install -r requirements.txt. The requirements.txt file must be present in the project's root folder. Otherwise, the build process reports the error: "Could not find setup.py or requirements.txt; Not running pip install."

**Comment by qianz2** [comment]
Closing the issue as we checked in the PR for supporting the feature. Please let us know if there's further questions. Thanks!

**Comment by anguspmitchell** [comment]
@qianz2 How do Oryx changes make their way into `azure-functions-core-tools@4`? I use `func azure functionapp publish <name>`
