### ISSUE TITLE
Deployment failed to Azure App service

### ISSUE THREAD

**Issue by Shruti700** [microsoft/Oryx#1215]
### Bug Report

- At what date and time did you most recently experience the problem?
29/01/2022 

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Web Apps 

- If your repo is publicly available please share its URL:
https://github.com/Shruti700/betterbuys02  
- What happened?
I am unable to deploy this code to the Azure app service. It failed several times with an error saying "Could not detect any platform in the source directory". 

- What did you expect or want to happen?
It should be deployed.

- How can we reproduce it?
![Screenshot 2022-01-29 222352](https://user-images.githubusercontent.com/63151043/151669725-ccc96c00-868d-453b-82ed-6614ddecd8c3.png)

- Do you have log output? Please include between the backticks:

```
Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 12 -i /tmp/8d9e341d4a5bd0a -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20210826.1, Commit: f8651349d0c78259bb199593b526450568c2f94a, ReleaseTagName: 20210826.1

Build Operation ID: |nCoP2+6l8e4=.204ebdd2_
Repository Commit : 1d4b5f096d674d18a3bcff69e1665dab

Detecting platforms...
Could not detect any platform in the source directory.
Error: Couldn't detect a version for the platform 'nodejs' in the repo.
Error: Couldn't detect a version for the platform 'nodejs' in the repo.\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 12 -i /tmp/8d9e341d4a5bd0a -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
```

**Comment by QSerr** [comment]
Hi we have had the same issue though we managed to get it deployed by following this [post](https://docs.microsoft.com/en-us/visualstudio/javascript/publish-nodejs-app-azure?view=vs-2022) and adding the two settings it recommends. Those being WEBSITE_NODE_DEFAULT_VERSION to your desired node version and SCM_SCRIPT_GENERATOR_ARGS with a value of --node, in the application settings tab of the app.

**Comment by simonjj** [comment]
Hoping this issue has found a solution. Closing this issue, please open a new issue if it's still impacting you and link back to this issue.
