### ISSUE TITLE
Deployment from local to Azure Function failing

### ISSUE THREAD

**Issue by userdevop** [microsoft/Oryx#1216]
### Bug Report

- At what date and time did you most recently experience the problem?
Faced issue on Feb 4 2022.

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.

Faced issue wile deploying local code to Azure function app via Azure CLI command prompt

- If your repo is publicly available please share its URL:
Not available.

- What happened?
Have python script and an NLP model (script calls the NLP model). This code/script works perfectly fine on local system and now needs to be deployed from local to Azure Function App(Python based). However the deployment fails without and details on error message/reason of failure, even when verbose logging has been enabled.

- What did you expect or want to happen?
Deployment to Azure function app to succeed successfully.

- How can we reproduce it?
NA

- Do you have log output? Please include between the backticks:
Log output is attached as well as shown as below:

![image](https://user-images.githubusercontent.com/88434126/152490773-bed8629c-4b4e-4cbe-82cd-fafe03a1c12d.png)

![image](https://user-images.githubusercontent.com/88434126/152490823-db474ed7-0d76-4bb4-a154-7313fbd88d3d.png)

---------------------------LOG Details----------------------------------------------------------------------------------------------

PS C:\New folder> func azure functionapp publish <function app name> --build remote --verbose

Local python version '3.8.8' is different from the version expected for your deployed Function App. This may result in 'ModuleNotFound' errors in Azure Functions. Please create a Python Function App for version 3.8 or change the virtual environment on your local machine to match 'Python|3.9'.
Getting site publishing info...
Creating archive for current directory...
Performing remote build for functions project.
Deleting the old .python_packages directory
Uploading 159.47 MB [#############################################################################]
Remote build in progress, please wait...
Updating submodules.
Preparing deployment for commit id '1a73f7a4e2'.
Repository path is /tmp/zipdeploy/extracted
Running oryx build...
Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.9 -p packagedir=.python_packages/lib/site-packages
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20201015.1, Commit: 1a35fbce482b20b71290f3a837a3469803ce4b44, ReleaseTagName: 20201015.1

Build Operation ID: |YctxzV/Y1xY=.b350f4b3_
Repository Commit : 1a73f7a4e279435e8168f1d7febe7e80

Detecting platforms...
Detected following platforms:
  python: 3.9.7
Version '3.9.7' of platform 'python' is not installed. Generating script to install it...

Source directory     : /tmp/zipdeploy/extracted
Destination directory: /home/site/wwwroot

Downloading and extracting 'python' version '3.9.7' to '/tmp/oryx/platforms/python/3.9.7'...
Downloaded in 1 sec(s).
Verifying checksum...
Extracting contents...
Done in 5 sec(s).

Python Version: /tmp/oryx/platforms/python/3.9.7/bin/python3.9

Running pip install...
[07:06:11+0000] Collecting azure-functions
[07:06:11+0000]   Downloading azure_functions-1.8.0-py3-none-any.whl (137 kB)
[07:06:11+0000] Collecting pandas
[07:06:11+0000]   Downloading pandas-1.4.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
[07:06:13+0000] Collecting numpy==1.20.1
[07:06:13+0000]   Downloading numpy-1.20.1-cp39-cp39-manylinux2010_x86_64.whl (15.4 MB)
[07:06:13+0000] Collecting sentence-transformers==2.1.0
[07:06:13+0000]   Downloading sentence-transformers-2.1.0.tar.gz (78 kB)
[07:06:14+0000] Collecting pytz>=2020.1
[07:06:14+0000]   Downloading pytz-2021.3-py2.py3-none-any.whl (503 kB)
[07:06:14+0000] Collecting python-dateutil>=2.8.1
[07:06:14+0000]   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
[07:06:14+0000] Collecting transformers<5.0.0,>=4.6.0
[07:06:14+0000]   Downloading transformers-4.16.2-py3-none-any.whl (3.5 MB)
[07:06:16+0000] Collecting tokenizers>=0.10.3
[07:06:16+0000]   Downloading tokenizers-0.11.4-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (6.8 MB)
[07:06:16+0000] Collecting tqdm
[07:06:16+0000]   Downloading tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
[07:06:16+0000] Collecting torch>=1.6.0
[07:06:16+0000]   Downloading torch-1.10.2-cp39-cp39-manylinux1_x86_64.whl (881.9 MB)
Done in 23 sec(s).
\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.9 -p packagedir=.python_packages/lib/site-packages
Remote build failed!

```

```

**Comment by kaibocai** [comment]
@userdevop this should be the memory limitation on lower plan (each instance get 1.5GB memory on consumption plan), try to scale up to Premium plan and try again.

**Comment by odoo-ce-modules** [comment]
@kaibocai It's not a memory limitation. I have the same issue when deploy from a machine that has a different version of Python and no issue deploying when the version of Python matches. I think the error message makes that clear, that its an issue with the version of Python not matching.  It should need to match when doing a REMOTE build. This is supposed to be one of the benefits of a remote build.

**Comment by ormu5** [comment]
I resolved this by updating the configuration for my [linux] function app:

```
az functionapp config set --name my-linux-function-app --resource-group my-resource-group --linux-fx-version "PYTHON|3.9"
```

fwiw, in Terraform, this seems to line up with `azurerm_linux_function_app.site_config.application_stack.python_version = 3.9`.

**Comment by gregoryrcurlewis** [comment]
I had a problem whilst installing tensorflow to azure functions. It was fixed by specifying the version of tensorflow (tensorflow==2.8.0 to be exact). 
I have noticed your problem occurs after installing torch so change the version and try again maybe?

**Comment by simonjj** [comment]
This issue seems resolved. Will be closing this issue. If this is still relevant and impacting you please open a new issue and link back to this issue for reference.
