### ISSUE TITLE
POST_BUILD_COMMAND documentation

### ISSUE THREAD

**Issue by samaritanau** [microsoft/Oryx#1265]
### Feature Request

Hi, we are building our repo and deploying it successfully using the linux app service deployment Oryx, we are using the POST_BUILD_COMMAND to curl a message to a webhook when the deployment has finished which is working correctly. 

We want to be able to send some detail through about the build with that message, is it possible to get at some information in the post build command, such as if the Oryx script ran successfully, maybe details about the GIT push that triggered the build? I can't find any info about that.

Regards,
Henry

**Comment by simonjj** [comment]
Any script you want to reference we will execute. There's no additional documentation unfortunately. Will be closing this issue. If this is still relevant and impacting you please open a new issue and link back to this issue for reference.
