### ISSUE TITLE
Make python pip '--prefer-binary' optional during Oryx builds.

### ISSUE THREAD

**Issue by thiezn** [microsoft/Oryx#1311]
### Feature Request

Hi,

At the moment when performing a remote python build using Oryx, pip install is [called with the --prefer-binary command](https://github.com/microsoft/Oryx/blob/8fc97e814a4db6df6c8b0a6be294eaa9bc7d2551/src/BuildScriptGenerator/Python/PythonBashBuildSnippet.sh.tpl#L125). As per documentation of pip, this command will prefer older binary packages (e.g. python wheels) over newer source packages.

Effectively this means you will not be able to override this setting when using oryx remote build. To get around the problem, I am pinning to specific versions, but would rather retrieve the latest available.

Would it be possible to optionally remove the '--prefer-binary' flag, for instance by setting a specific environment variable? Alternatively, perhaps introduce an environment variable that allows you to completely override any flags/parameters passed onto pip install for maximum flexibility.

Kind regards,
Thiezn

**Comment by qianz2** [comment]
Hi @thiezn ,

Thanks for the feature request. Yes, Oryx uses this command as a default command to run pip install command, it will work in most of cases, but if customers would like to any other custom command, we can add more options.
Introducing a new environment variable usually will work. I'll open a backlog item in our team and will work on this. Thanks.

**Comment by simonjj** [comment]
We're closing this issue due to its age. If this is still impacting you please open a new issue and simply link back to this one.
