### ISSUE TITLE
Flag to install Python requirements to user scope

### ISSUE THREAD

**Issue by jungaretti** [microsoft/Oryx#1317]
### Feature Request

Is it possible to force Oryx to install Python requirements to the user scope instead of a new virtual environment? [PythonBashBuildSnippet.sh.tpl](https://github.com/microsoft/Oryx/blob/8fc97e814a4db6df6c8b0a6be294eaa9bc7d2551/src/BuildScriptGenerator/Python/PythonBashBuildSnippet.sh.tpl#L32) gives me the impression that a blank virtual environment name (e.g., `-p virtualenv_name=""`) should work, but instead I see an error: `the following arguments are required: ENV_DIR`

#### Relevant Links

- https://github.com/microsoft/Oryx/blob/main/doc/runtimes/python.md#build

**Comment by daniv-msft** [comment]
Adding @qianz2, as per our parallel email thread

**Comment by simonjj** [comment]
We're closing this issue due to its age. If this is still impacting you please open a new issue and simply link back to this one.
