### ISSUE TITLE
ISSUE:Detecting platforms...

### ISSUE THREAD

**Issue by pochodaj** [microsoft/Oryx#1357]
ISSUE while deploying Azure function via VSC :
Detecting platforms...
Error: Oops... An unexpected error has occurred.
/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.9 -p packagedir=.python_packages/lib/site-packages
Deployment Failed.

**Comment by qianz2** [comment]
@[pochodaj](https://github.com/pochodaj) Could you try it again? It may be a random issue that occurred when we upload and remove SDKs from the storage account.

**Comment by simonjj** [comment]
We're closing this issue due to its age. If this is still impacting you please open a new issue at https://github.com/projectkudu/kudu and simply link back to this one.
