### ISSUE TITLE
Publishing more Oryx runtime images

### ISSUE THREAD

**Issue by KonoMaxi** [microsoft/Oryx#1391]
### Feature Request

Hello Oryx-Team,

first of all: thanks for making azure app service deployments breeze... well, 9 out of 10 times at least ;-)

We recently ran into a 1 out of 10 scenario and hit the ground hard. We wanted to setup a python3.8 azure web app with a postgresql database, but the driver-version mismatched (libpq-dev=9.6 installed, [azure postgres flexible server](https://docs.microsoft.com/de-de/azure/postgresql/flexible-server/overview) offers 11, 12 or 13).
Our (counter-intuitive) fix was to upgrade our appsvc to python 3.9. The underlying docker-image mcr.microsoft.com/appsvc/python:3.9_20220518.1 is debian 10, which ships with libpq-dev=11 -> driver problem solved

But we actually expected to have a full range of oryx runtime-images at our disposal, as specified [here](https://github.com/microsoft/Oryx/blob/main/README.md#supported-platforms).
When looking at the published [oryx/python-images](https://mcr.microsoft.com/v2/oryx/python/tags/list), the tags only differentiate between the python versions 2.7,3.7,3.8,3.9,3.10, but no mentioning of the underlying base images like stretch, buster and bullseye/focal.
When on the other hand looking at [oryx/build](https://mcr.microsoft.com/v2/oryx/build/tags/list) I see a nice selection of buster and bullseye images.

When looking at your pipelines, it appears like you're building buster and bullseye images for all variations, but you just don't publish them.

**Feature Request**: is it possible to also publish the other debian flavour images under oryx/<platform>?
That way we could easily derive our own appsvc-images, while still using the standard oryx runtime images.

How do you think about this?

**Comment by qianz2** [comment]
Hi @KonoMaxi, thanks for your feedbacks. Oryx runtime images use different debian flavor and gradually migrate older debian flavor images like Stretch to newer debian flavor Bullseye images. 
The information won't show in runtime image tags, but we can always check the debian version by checking the environment variable `DEBIAN_FLAVOR` within that image. 
Does it sounds good if we specify these information in a doc?
It's not easy for us to publish multiple debian flavour images for a single platform version, since some platform versions require libraries that would only be supported in a specific debian image.

**Comment by KonoMaxi** [comment]
It would've saved a bit of time, if we had known there is a tight coupling between DEBIAN_FLAVOR and Platform-Version :-)
There definitely is some confusion with the list located  in your supported platforms. https://github.com/microsoft/Oryx/blob/main/doc/supportedPlatformVerions.md

Choice between a python3.8 runtime-image with multiple DEBIAN_FLAVORs was my expectation when reading the list... I understand your point regarding the implications/challenges of offering different OS-Versions! Aligning the docs with the actually present runtime-images would clarify that, so nobody else seeks what is not there ;-)

**Comment by qianz2** [comment]
Hi @KonoMaxi, thanks for the feedbacks. I've created a backlog to add these information to the docs. We'll expect to have these info soon in the docs.

**Comment by KonoMaxi** [comment]
Thank you. Closing this issue :-)
