### ISSUE TITLE
Unable to deploy static web app from different project

### ISSUE THREAD

**Issue by pallabiroutfnf** [microsoft/Oryx#1404]
i am trying to deploy a React app with NodeJs. package.json file is already present in my source code. 
Still getting below error.

Detecting platforms...
Error: Could not find the .NET Core project file.

---End of Oryx build logs---
Oryx has failed to build the solution.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting
##[error]Error: The process '/usr/bin/bash' failed with exit code 1
Finishing: AzureStaticWebApp

**Comment by qianz2** [comment]
Hello @[pallabiroutfnf](https://github.com/pallabiroutfnf), it looks that Oryx detects your app as a dotnet app but your app is a React app. It's possible that you've set up options or environment variable such as `PROJECT` (which indicates the path to the project file), and Oryx failed to find the .NET Core project file. Could you check if those configs were set up in your app?

**Comment by pallabiroutfnf** [comment]
> Hello @[pallabiroutfnf](https://github.com/pallabiroutfnf), it looks that Oryx detects your app as a dotnet app but your app is a React app. It's possible that you've set up options or environment variable such as `PROJECT` (which indicates the path to the project file), and Oryx failed to find the .NET Core project file. Could you check if those configs were set up in your app?

Thanks much! Exactly that's what caused the problem. We were using Project variable in our templated, which caused the error. After removing the variable, it's working now.

**Comment by qianz2** [comment]
@[pallabiroutfnf](https://github.com/pallabiroutfnf), thanks for the updates! Closing the issue now. Please feel free to reopen if you have any other questions.
