### ISSUE TITLE
azure static website builds are failing since 2 days ::  Oryx now using node JS 18.2.0

### ISSUE THREAD

**Issue by robert-hoffmann** [microsoft/Oryx#1439]
My azure static website builds are failing since 2 days, i can see in the logs that it was using node 17.6.0 previously (when it was working)

Using 
Azure/static-web-apps-deploy@v1
(which was generated automatically by windows azure))

        Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
        You can report issues at https://github.com/Microsoft/Oryx/issues
        Oryx Version: 0.2.[20](https://github.com/itechnology/hutchinson/runs/7003776454?check_suite_focus=true#step:5:21)[22](https://github.com/itechnology/hutchinson/runs/7003776454?check_suite_focus=true#step:5:23)0401.1, Commit: afed4f696a08bfd4c8e4109704a082bf9fb20515, ReleaseTagName: 20220401.1
        Build Operation ID: |WsKD41No8o0=.8faa43d2_
        Repository Commit : 59d51c90ae180[24](https://github.com/itechnology/hutchinson/runs/7003776454?check_suite_focus=true#step:5:25)63b81e0351100ab6769cad7b5
        Detecting platforms...
        Detected following platforms:
          nodejs: 18.2.0
        Version '18.2.0' of platform 'nodejs' is not installed. Generating script to install it...
        Detected the following frameworks: Vue.js
        Source directory     : /github/workspace
        Destination directory: /bin/staticsites/ss-oryx/app
        Downloading and extracting 'nodejs' version '18.2.0' to '/opt/nodejs/18.2.0'...
        Downloaded in 1 sec(s).
        Verifying checksum...
        Extracting contents...
        performing sha512 checksum for: nodejs...
        Done in 2 sec(s).
        Removing existing manifest file
        Creating directory for command manifest file if it does not exist
        node: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by node)
        node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.[25](https://github.com/itechnology/hutchinson/runs/7003776454?check_suite_focus=true#step:5:26)' not found (required by node)
        node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.[28](https://github.com/itechnology/hutchinson/runs/7003776454?check_suite_focus=true#step:5:29)' not found (required by node)
        Creating a manifest file...
        Node Build Command Manifest file created.

**Comment by robert-hoffmann** [comment]
I did try setting node version via
https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs#specifying-the-nodejs-version

Didn't work

**Comment by qianz2** [comment]
Hi @[robert-hoffmann](https://github.com/robert-hoffmann)), we've removed node 18 SDKs from the prod storage account and the builds would not be automatically selecting node 18 from now on. Please try it again, thanks!

**Comment by anttti** [comment]
We encountered this exact issue too, and now our build is working, so that's good. However this was mildly disturbing - what was the root cause? Will this happen again? Why Node 18 failed? Is there any way we, as app developers, could control the used Node version?

**Comment by robert-hoffmann** [comment]
Thanks for the quick resolution

Everything is working again
