### ISSUE TITLE
Trivial site fails to build when specifying routes in staticwebapp.config.json

### ISSUE THREAD

**Issue by fuglede** [microsoft/Oryx#1455]
### Bug Report

If I use [this `staticwebapp.config.json`](https://github.com/fuglede/az-static-web-app-test/blob/2bd588a5262ff1821573e29342bf3b8778aa30be/staticwebapp.config.json), the auto-generated pipeline reports a failure. If I remove the `"routes"` section, the build is green.

[Build log](https://github.com/fuglede/az-static-web-app-test/runs/7127689289?check_suite_focus=true):

```
App Directory Location: '/' was found.
No Api directory specified. Azure Functions will not be created.
Looking for event info
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
---Oryx build logs---
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues
Oryx Version: 0.2.20220401.1, Commit: afed4f696a08bfd4c8e4109704a082bf9fb20515, ReleaseTagName: 20220401.1
Build Operation ID: |4jhP6QIGw4M=.675f18f2_
Repository Commit : 2bd588a5262ff1821573e29342bf3b8778aa30be
Detecting platforms...
Could not detect any platform in the source directory.
Error: Could not detect the language from repo.
---End of Oryx build logs---
Oryx was unable to determine the build steps. Continuing assuming the assets in this folder are already built. If this is an unexpected behavior please contact support.
Finished building app with Oryx
An unknown exception has occurred
```

**Comment by fuglede** [comment]
Ah, there's a comma missing around
```
  }
  "routes": [
    {
```
so I suppose the cause is a JSON parsing issue. Not very clear from the error message.

**Comment by fuglede** [comment]
@cormacpayne: As mentioned in the comment above, this was all due to a JSON parsing issue. Indeed, any invalid JSON in `staticwebapp.config.json` will cause the "Could not detect any platform in the source directory." So you could take this issue to mean "improve the error message given when encountering invalid JSON" if you like.

**Comment by simonjj** [comment]
This issue seems resolved. Will be closing this issue. If this is still relevant and impacting you please open a new issue and link back to this issue for reference.
