### ISSUE TITLE
Issues on deploy ReactJs + NodeJs App on Azure Web App Service

### ISSUE THREAD

**Issue by CFMazzarago** [microsoft/Oryx#1474]
### Bug Report

Hi, i have an issue with deploy ReactJs + NodeJs web app to my Azure resource group.
I try to deploy via VsCode + Azure Plugin.

this is my directory tree: 
client --> contain reactJs FrontEnd
server --> contain NodeJs Backend
any ideas ?

- At what date and time did you most recently experience the problem?
- 12/07/2022

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Web Apps

- Do you have log output? Please include between the backticks:

```
10:06:47 AM scfEtsBilanci: Starting deployment...
10:07:20 AM scfEtsBilanci: Creating zip package...
10:14:45 AM scfEtsBilanci: Zip package size: 980 MB
10:14:52 AM scfEtsBilanci: Fetching changes.
10:14:53 AM scfEtsBilanci: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/1b6b2829-ae8d-40f5-a2b7-3897972eb19a.zip (947.02 MB) to /tmp/zipdeploy/extracted
10:17:58 AM scfEtsBilanci: Updating submodules.
10:17:59 AM scfEtsBilanci: Preparing deployment for commit id '694c0446-1'.
10:17:59 AM scfEtsBilanci: PreDeployment: context.CleanOutputPath False
10:17:59 AM scfEtsBilanci: PreDeployment: context.OutputPath /home/site/wwwroot
10:17:59 AM scfEtsBilanci: Repository path is /tmp/zipdeploy/extracted
10:18:00 AM scfEtsBilanci: Running oryx build...
10:18:00 AM scfEtsBilanci: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 16 -i /tmp/8da63df0867fe28 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log  | tee /tmp/oryx-build.log
10:18:08 AM scfEtsBilanci: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
10:18:08 AM scfEtsBilanci: You can report issues at https://github.com/Microsoft/Oryx/issues
10:18:09 AM scfEtsBilanci: Oryx Version: 0.2.20220308.4, Commit: c92fa6a2d6fc14dc9646f80e2bb2e393a5cdc258, ReleaseTagName: 20220308.4
10:18:09 AM scfEtsBilanci: Build Operation ID: |+8IaXq1GkpQ=.814fcd09_
10:18:09 AM scfEtsBilanci: Repository Commit : 694c0446-1eef-4562-ad32-7b9a3913e5a0
10:18:09 AM scfEtsBilanci: Detecting platforms...
10:18:28 AM scfEtsBilanci: Detected following platforms:
10:18:28 AM scfEtsBilanci:   php: 7.3.27
10:18:28 AM scfEtsBilanci: Error: Couldn't detect a version for the platform 'nodejs' in the repo.
10:18:30 AM scfEtsBilanci: /bin/bash -c "oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 16 -i /tmp/8da63df0867fe28 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log  | tee /tmp/oryx-build.log ; exit $PIPESTATUS "
10:18:30 AM scfEtsBilanci: Generating summary of Oryx build
10:18:30 AM scfEtsBilanci: Parsing the build logs
10:18:30 AM scfEtsBilanci: Found 0 issue(s)
10:18:30 AM scfEtsBilanci: Build Summary :
10:18:30 AM scfEtsBilanci: ===============
10:18:31 AM scfEtsBilanci: Errors (0)
10:18:31 AM scfEtsBilanci: Warnings (0)
10:18:31 AM scfEtsBilanci: Deployment Failed.
10:18:38 AM scfEtsBilanci: Deployment failed.
```

**Comment by PratikRogers** [comment]
It's same issue I am facing during app service deploy in Node 16LTS.

An unknown error has occurred. Check the diagnostic log for details.
Error: Failed to deploy web package to App Service.
Error: Deployment Failed with Error: Package deployment using ZIP Deploy failed. Refer logs for more details.

**Comment by william-msft** [comment]
Hi Team, would someone be able to provide a sample application to help us troubleshoot on our end?

**Comment by CFMazzarago** [comment]
Hi, a little while ago I tried to create a test distribution by following step by step the guide on this page:
https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-vscode

The local server works correctly but when I proceed with the deployment on Auzure I get the following error (log):

9:46:30 AM testnodeonly: Starting deployment...
9:46:33 AM testnodeonly: Creating zip package...
9:46:34 AM testnodeonly: Zip package size: 680 kB
9:46:39 AM testnodeonly: Updating submodules.
9:46:40 AM testnodeonly: Preparing deployment for commit id 'dd3fa47f-5'.
9:46:41 AM testnodeonly: PreDeployment: context.CleanOutputPath False
9:46:41 AM testnodeonly: PreDeployment: context.OutputPath /home/site/wwwroot
9:46:41 AM testnodeonly: Repository path is /tmp/zipdeploy/extracted
9:46:41 AM testnodeonly: Running oryx build...
9:46:41 AM testnodeonly: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 16 -i /tmp/8da663627d5145b -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log  | tee /tmp/oryx-build.log
9:46:42 AM testnodeonly: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
9:46:42 AM testnodeonly: You can report issues at https://github.com/Microsoft/Oryx/issues
9:46:42 AM testnodeonly: Oryx Version: 0.2.20220308.4, Commit: c92fa6a2d6fc14dc9646f80e2bb2e393a5cdc258, ReleaseTagName: 20220308.4
9:46:42 AM testnodeonly: Build Operation ID: |bes8jVtPLlk=.b8ab665a_
9:46:42 AM testnodeonly: Repository Commit : dd3fa47f-5234-4dac-bb7e-82b7cb07597f
9:46:42 AM testnodeonly: Detecting platforms...
9:46:42 AM testnodeonly: Could not detect any platform in the source directory.
9:46:42 AM testnodeonly: Error: Couldn't detect a version for the platform 'nodejs' in the repo.
9:46:43 AM testnodeonly: /bin/bash -c "oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 16 -i /tmp/8da663627d5145b -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log  | tee /tmp/oryx-build.log ; exit $PIPESTATUS "
9:46:43 AM testnodeonly: Generating summary of Oryx build
9:46:44 AM testnodeonly: Parsing the build logs
9:46:44 AM testnodeonly: Found 0 issue(s)
9:46:44 AM testnodeonly: Build Summary :
9:46:44 AM testnodeonly: ===============
9:46:44 AM testnodeonly: Errors (0)
9:46:44 AM testnodeonly: Warnings (0)
9:46:44 AM testnodeonly: Deployment Failed.
9:46:54 AM testnodeonly: Deployment failed.

**Comment by qianz2** [comment]
Hello [CFMazzarago](https://github.com/CFMazzarago), [PratikRogers](https://github.com/PratikRogers):

The Node.js platform will be detected and build when the following conditions are met:

One of these files is found in the root of the repo:
package.json
package-lock.json
yarn.lock
One of these files is found in the root of the repo:
server.js
app.js

From the logging, looks that oryx failed to detect the apps to be nodejs app. Could you double check if the repo met above conditions?

**Comment by simonjj** [comment]
We're closing this issue due to its age. If this is still impacting you please open a new issue and simply link back to this one.
