### ISSUE TITLE
Error: Platform 'nodejs' version '16.16.0' is unsupported.

### ISSUE THREAD

**Issue by hornta** [microsoft/Oryx#1518]
Since 16.16.0 is the current LTS version of Node.js I think it should be supported by Oryx. What do you think?

**Comment by cormacpayne** [comment]
@hornta Hey there, thanks for filing this issue -- Oryx is in the process of designing a mechanism by which we will automatically uptake the latest versions release of our platform binaries and publish them for dynamic installation usage and/or bake them into our build images. Typically, we reserve supporting new versions of platforms for when the Azure service teams that depend on Oryx explicitly ask for them, so I'd love to hear about your personal usage for the new version of node 16 (as of now, 16.17.0 has been released) and we can prioritize the work necessary to support it accordingly.

**Comment by staizen-arnel-cuanico** [comment]
Hi @cormacpayne, when are you going to support node 16 and up? Currently we are using an existing node package that relies on LTS 16.16 version of node. This is a major blocker on us because we are exploring with Azure Static Web apps. We might scrap the service and explore other options if this would take too long :(

**Comment by cormacpayne** [comment]
@staizen-arnel-cuanico Hey there, thanks for the reply -- we do have a work item filed to update the minor versions of both node 14 and 16 supported by Oryx to the latest releases for each (current versions supported by Oryx are from March 2022). We'll have an engineer prioritize this work and optimistically are looking at next week for the SDKs to be consumed via dynamic installation.

As a note: the Oryx build image that Azure Static Web Apps relies on _does_ leverage dynamic installation, so as soon as the SDKs for the new node versions are published to our storage account, users are able to consume them instantaneously; however, there are other Azure services that rely on Oryx build images that _do not_ use dynamic installation and will have to wait for an updated version of the build image to be adopted by the service before seeing the functionality live. Just an FYI for any future reader :smile:

**Comment by johnnyreilly** [comment]
Similar issues for node 18 which is impacting me (and others) here https://github.com/johnnyreilly/blog.johnnyreilly.com/pull/317

Related for Azure Static Web Apps: https://github.com/Azure/static-web-apps/issues/961

**Comment by simonjj** [comment]
This issue seems resolved. Will be closing this issue. If this is still relevant and impacting you please open a new issue and link back to this issue for reference.
