### ISSUE TITLE
Oryx has failed to build the solution

### ISSUE THREAD

**Issue by FakeRayBanz** [microsoft/Oryx#1549]
### Bug Report

- At what date and time did you most recently experience the problem?
5th September 2022 9:30pm AEST

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Github workflow, building an azure static web app (blazor)

- If your repo is publicly available please share its URL:
https://github.com/FakeRayBanz/SoilClassifier-Blazor

- What happened?
I pushed a new commit to my repo and github ran the action to build and deploy it to my azure static web app site, however the build failed. I tried to run it again and still failed. I reran an action from a previous commit which had passed and it somehow failed too, so I don't believe its a change in my code causing this issue. All my builds compile locally.

- What did you expect or want to happen?
Oryx to build and deploy my static web app

- How can we reproduce it?
Clone my repo and attempt to build and deploy it

- Do you have log output? Please include between the backticks:

```
DeploymentId: 4e600a9b-b458-47e6-928b-1775cd379ffa

App Directory Location: '/' was found.
Looking for event info
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
---Oryx build logs---


Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20220621.1, Commit: 82ed84f0f3fd3a25ded3029f137601f54e7a1d05, ReleaseTagName: 20220621.1

Build Operation ID: |+SEeE+jmwDE=.fcf390cf_
Repository Commit : b496e546c9e450f27342e2e05190531bc6c0fb21

Detecting platforms...
Detected following platforms:
  dotnet: 6.0.6
Version '6.0.6' of platform 'dotnet' is not installed. Generating script to install it...
Detected the following frameworks: blazor


Source directory     : /github/workspace
Destination directory: /bin/staticsites/ss-oryx/app


Downloading and extracting 'dotnet' version '6.0.301' to '/opt/dotnet/6.0.301'...


---End of Oryx build logs---
Oryx has failed to build the solution.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting
```

**Comment by FakeRayBanz** [comment]
Just ran it again for like the 10th and it was successful, not sure what the issue is/was

**Comment by alexandru-travels** [comment]
Bump. Having similar issues:

```---Oryx build logs---


Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20220621.1, Commit: abc-xyz, ReleaseTagName: 20220621.1

Build Operation ID: |AxWbAIMViUo=.c8e7317c_
Repository Commit : abc-xyz

Detecting platforms...
Error: Oops... An unexpected error has occurred.


---End of Oryx build logs---
Oryx has failed to build the solution.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting
##[error]Error: The process '/usr/bin/bash' failed with exit code 1
```

**Comment by zakstone7** [comment]
this is currently happening to me as well

**Comment by daniv-msft** [comment]
Thanks everyone. We're looking this. +@william-msft from our team.

**Comment by deven-gqc** [comment]
@daniv-msft Thanks for the prompt reply! Idk, if this will help, but I faced this issue when I tried to deploy the static web app in the Free tier as well as the Standard tier.

**Comment by daniv-msft** [comment]
Thanks everyone for your patience. From our investigation so far, we seem to be impacted by the Azure Front Door outage: https://status.azure.com/en-us/status

Oryx relies on a CDN to deliver the binaries to build, and Azure CDN has a dependency on Azure Front Door. Apologies for the inconvenience, we'll keep monitoring the situation.

**Comment by william-msft** [comment]
Hi Team, I check on Oryx side and does seem Front Door related. Standing by...

**Comment by deven-gqc** [comment]
@daniv-msft @william-msft My deployments just went through. The apps are working again. Thanks a lot!

**Comment by daniv-msft** [comment]
I'm going to close this issue, as multiple customers here and on the Static Web Apps repo (https://github.com/Azure/static-web-apps/issues/912) reported that things now work. Thank you everyone, and apologies again for the inconvenience!
