### ISSUE TITLE
I can't deploy azure function/ ERROR: Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/azure-functions/

### ISSUE THREAD

**Issue by freitassvitor** [microsoft/Oryx#1602]
1. before I cant deploy because the firewall was not permited to oryx-cdn.microsoft.io on port 443
2. I change my firewall rules and now I having this issue above:
16:43:38 cg-dev-func-iot-importadados-001: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/azure-functions/
16:43:38 cg-dev-func-iot-importadados-001: WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/azure-functions/
16:43:39 cg-dev-func-iot-importadados-001: WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/azure-functions/
16:43:39 cg-dev-func-iot-importadados-001: WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/azure-functions/
16:43:39 cg-dev-func-iot-importadados-001: WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/azure-functions/
16:43:39 cg-dev-func-iot-importadados-001: ERROR: Could not find a version that satisfies the requirement azure-functions (from -r requirements.txt (line 5)) (from versions: none)
16:43:39 cg-dev-func-iot-importadados-001: ERROR: No matching distribution found for azure-functions (from -r requirements.txt (line 5))
16:43:39 cg-dev-func-iot-importadados-001: "2022-10-10 19:43:38"|ERROR|WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/azure-functions/
16:43:39 cg-dev-func-iot-importadados-001: WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/azure-functions/
16:43:39 cg-dev-func-iot-importadados-001: WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/azure-functions/
16:43:39 cg-dev-func-iot-importadados-001: WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/azure-functions/
16:43:39 cg-dev-func-iot-importadados-001: WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/azure-functions/
16:43:39 cg-dev-func-iot-importadados-001: ERROR: Could not find a version that satisfies the requirement azure-functions (from -r requirements.txt (line 5)) (from versions: none)
16:43:39 cg-dev-func-iot-importadados-001: ERROR: No matching distribution found for azure-functions (from -r requirements.txt (line 5)) | Exit code: 1 | Please review your requirements.txt | More information: https://aka.ms/troubleshoot-python
16:43:40 cg-dev-func-iot-importadados-001: /opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /tmp/build/expressbuild --platform python --platform-version 3.9.7 -i /tmp/8daaaf7b2b6359c -p packagedir=.python_packages/lib/site-packages
16:43:40 cg-dev-func-iot-importadados-001: Generating summary of Oryx build
16:43:40 cg-dev-func-iot-importadados-001: Deployment Log file does not exist in /tmp/oryx-build.log
16:43:41 cg-dev-func-iot-importadados-001: The logfile at /tmp/oryx-build.log is empty. Unable to fetch the summary of build
16:43:43 cg-dev-func-iot-importadados-001: Deployment Failed. deployer = Push-Deployer deploymentPath = Functions App ZipDeploy. Extract zip. Remote build.
16:43:57 cg-dev-func-iot-importadados-001: Deployment failed.

**Comment by william-msft** [comment]
Hi @freitassvitor this seems related to a firewall issue @dsashishgarg was having. 
https://github.com/microsoft/Oryx/issues/1017#issuecomment-850942009

Looping @vijay-microsoft  @tulikac from App Service if there any firewall recommendations for this?

**Comment by simonjj** [comment]
Dup of #1017. Will be closing this issue. If this is still relevant and impacting you please open a new issue and link back to this issue for reference.
