### ISSUE TITLE
Oryx fails to detect PHP platform version even when platform and version are specified on the command line

### ISSUE THREAD

**Issue by vml-aledonne** [microsoft/Oryx#1619]
### Bug Report

- At what date and time did you most recently experience the problem?
2022-10-20, at 0945 US Central time

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Attempting to deploy a new small web app to App Services

- What happened?

Attempting to deploy basic HTML to App Service.

Following ~~https://learn.microsoft.com/en-us/cli/azure/webapp~~  https://learn.microsoft.com/en-us/azure/app-service/quickstart-html

Chose to use --os-type linux --runtime "PHP:8.1" instead of --html in order to deploy to linux.

Attempted to deploy with command 

az webapp up --location southcentralus --resource-group MyTestResGroup --plan MyTestPlan --name MyTestApp --os-type linux --runtime "PHP:8.1"

Oryx deployment fails with log output below.

- What did you expect or want to happen?

**Oryx should skip detection when platform and platform-version are specified.** How can I work around this?

- How can we reproduce it?

Walk through ~~https://learn.microsoft.com/en-us/cli/azure/webapp~~  https://learn.microsoft.com/en-us/azure/app-service/quickstart-html

specify linux and php 8.1

- Do you have log output? Please include between the backticks:

```
Detecting platforms...
Could not detect any platform in the source directory.
Error: Couldn't detect a version for the platform 'php' in the repo.
Error: Couldn't detect a version for the platform 'php' in the repo.\n/bin/bash -c "oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform php --platform-version 8.1 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8dab2a971dd7c98 | tee /tmp/oryx-build.log ; exit $PIPESTATUS "
```

**Comment by pauld-msft** [comment]
Yes. Sorry for the very late reply, but @jormaster3k has a good tip here. We generally see issues like this when the command is being executed from the wrong directory. The working directory has to be the root directory, which for PHP's case, means that there will either be a `composer.json` or `*.php` files.

**Comment by vml-aledonne** [comment]
I cited the documentation which suggests using linux/PHP for deploying plain HTML, which would have neither a `composer.json` nor `*.php` files... which gets to my point precisely: if the os and runtime are specified on the command line I shouldn't need to `touch empty.php` to make the deployment work, IMO.
At a minimum, the cli documentation I cited would need to be updated to reflect that requirement.

**Comment by pauld-msft** [comment]
Hi @vml-aledonne, so sorry, but I can't seem to find the section of the linked docs you mentioned that tells you to use PHP for a plain HTML project? Would you be able to share that?

I was able to find the following example for `az webapp up` [here](https://learn.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-up-examples), if that helps!
![image](https://user-images.githubusercontent.com/107068277/224404372-fd4ab33b-a559-48ad-96b7-7cecda77d3b5.png)

**Comment by vml-aledonne** [comment]
Apologies - I had the wrong link. Correct link: https://learn.microsoft.com/en-us/azure/app-service/quickstart-html

Here's the highlighted "Note" on the page:
If you want to host your static content on a Linux based App Service instance configure PHP as your runtime using the `--runtime` and `--os-type` flags:

`az webapp up --location westeurope --name <app_name> --runtime "PHP:8.1" --os-type linux`

The PHP container includes a web server that is suitable to host static HTML content.

**Comment by simonjj** [comment]
We're closing this issue due to its age. If this is still impacting you please open a new issue and simply link back to this one.
