### ISSUE TITLE
Nuxt 3 PWA on SWA - manifest.json replaced on build

### ISSUE THREAD

**Issue by AscaL** [microsoft/Oryx#1622]
Hi, I'm trying to deploy a SPA to SWA. I'm using Nuxt 3 with the Nitro preset [azure](https://nitro.unjs.io/deploy/providers/azure) .
The issue is that my `manifest.json` file, which is correctly loaded in `dev` and when building locally using `npx @azure/static-web-apps-cli start .output/public --api-location .output/server`, seems to be replaced by another file (`.output/server/functions/chunks/client.manifest.mjs`).

using `pnpm dev` i get this manifest on `localhost://3000/manifest.json`: 
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/8880943/197169876-c5489292-58a6-459f-b48e-5abaa4b5ba1a.png">

 using `pnpm build` and then `npx @azure/static-web-apps-cli start .output/public --api-location .output/server`:
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/8880943/197170175-e1aa0165-b3ad-4bc4-8b58-0185c837e248.png">

and finally deploying i get the wrong one:
<img width="528" alt="image" src="https://user-images.githubusercontent.com/8880943/197170382-fba9fc6c-e94f-483c-94f1-31ff4b92f84b.png">

The correct `manifest.json` file is found in the `.output/public` dir after running `pnpm build`.
<img width="439" alt="image" src="https://user-images.githubusercontent.com/8880943/196954213-751870de-ab4d-4d6a-9f6d-1132b08c598a.png">

And here you can see it gets replaced (I think, not 100% sure):
<img width="251" alt="image" src="https://user-images.githubusercontent.com/8880943/196954917-02f4cccd-97c6-4353-9f69-59e995b51887.png">
<img width="487" alt="image" src="https://user-images.githubusercontent.com/8880943/196955091-8cd0d51a-2936-44b5-9dcd-4d208e582eed.png">
<img width="406" alt="image" src="https://user-images.githubusercontent.com/8880943/196955182-f4b066d1-858f-4e13-9bab-435c272b0e87.png">

And I end up with this manifest:
<img width="336" alt="image" src="https://user-images.githubusercontent.com/8880943/196955517-4360410b-79ba-4078-8498-b0d9f01219ad.png">

which seems to be taken from the file `.output/server/functions/chunks/client.manifest.mjs` 
<img width="524" alt="image" src="https://user-images.githubusercontent.com/8880943/197167100-5ce42e39-f1f2-4100-ac2c-c1d69fe874ee.png">
<img width="420" alt="image" src="https://user-images.githubusercontent.com/8880943/197167305-0909fe06-271c-463a-aed4-5818aa5159cd.png">

**Expected behavior**
Keep my manifest.json file for the PWA

**Comment by simonjj** [comment]
We're closing this issue due to its age. If this is still impacting you please open a new issue and simply link back to this one.
