### ISSUE TITLE
[docs] Typo; missing link to https://github.com/dotnet/dotnet-docker image

### ISSUE THREAD

**Issue by nathanv** [microsoft/Oryx#1637]
### Bug Report
There is a typo in docs: https://github.com/microsoft/Oryx/blob/main/doc/base_images.md#run
Where the link to the .net docker image is missing: 

> Oryx's run images build on Docker's runtime-specific images for [Node.js](https://github.com/nodejs/docker-node) , [Python](https://github.com/docker-library/python), [Php](https://github.com/docker-library/php) and [Dotnet][].

**Comment by pauld-msft** [comment]
Thanks for opening the related PR! As this has been merged in, I'm going to close this
