### ISSUE TITLE
Python Azure Functions deployment issue through Visual studio code

### ISSUE THREAD

**Issue by chandrabisen** [microsoft/Oryx#1668]
### Bug Report

- At what date and time did you most recently experience the problem?
- 08/11/2022

- Where did you experience the problem? 
- Azure Functions

- If your repo is publicly available please share its URL:
- NA

- What happened?
- Pip error
-  Running pip install...
 Done in 390 sec(s).
 WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb1489fa90>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
 WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb1489fb20>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb148b0310>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb148b01f0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb148a9940>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
 ERROR: Could not find a version that satisfies the requirement azure-functions==1.13.0b1 (from -r requirements.txt (line 5)) (from versions: none)
 ERROR: No matching distribution found for azure-functions==1.13.0b1 (from -r requirements.txt (line 5))

- What did you expect or want to happen?
- Should have been successfully deployed to azure portal

- How can we reproduce it?

- Do you have log output? Please include between the backticks:

Starting deployment...
 Creating zip package...
 Zip package size: 196 MB
 Fetching changes.
 Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/f7e6d1bf-9b2c-4adb-b3df-220fc6322f86.zip (189.59 MB) to /tmp/zipdeploy/extracted
 Updating submodules.
 Preparing deployment for commit id '66ab1448-5'.
 PreDeployment: context.CleanOutputPath False
 PreDeployment: context.OutputPath /home/site/wwwroot
 Repository path is /tmp/zipdeploy/extracted
 Running oryx build...
 Command: oryx build /tmp/zipdeploy/extracted -o /tmp/build/expressbuild --platform python --platform-version 3.9.7 -i /tmp/8dac1c2eb121410 -p packagedir=.python_packages/lib/site-packages
 Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
 You can report issues at https://github.com/Microsoft/Oryx/issues
 Oryx Version: 0.2.20220812.1, Commit: cdf6b1bef165d05b94830e963646495967d938f4, ReleaseTagName: 20220812.1
 Build Operation ID: |vidk4Szndak=.b679a800_
 Repository Commit : 66ab1448-5123-48eb-ae7b-e8c0fffc534e
 Detecting platforms...
 Detected following platforms:
   python: 3.9.7
 Using intermediate directory '/tmp/8dac1c2eb121410'.
 Copying files to the intermediate directory...
 Done in 37 sec(s).
 Source directory     : /tmp/8dac1c2eb121410
 Destination directory: /tmp/build/expressbuild
 Python Version: /tmp/oryx/platforms/python/3.9.7/bin/python3.9
 Creating directory for command manifest file if it does not exist
 Removing existing manifest file
 Running pip install...
 Done in 390 sec(s).
 WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb1489fa90>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
 WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb1489fb20>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb148b0310>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb148b01f0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb148a9940>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
 ERROR: Could not find a version that satisfies the requirement azure-functions==1.13.0b1 (from -r requirements.txt (line 5)) (from versions: none)
 ERROR: No matching distribution found for azure-functions==1.13.0b1 (from -r requirements.txt (line 5))
 "2022-11-08 20:00:48"|ERROR|WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb1489fa90>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
 WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb1489fb20>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb148b0310>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb148b01f0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb148a9940>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
 ERROR: Could not find a version that satisfies the requirement azure-functions==1.13.0b1 (from -r requirements.txt (line 5)) (from versions: none)
 ERROR: No matching distribution found for azure-functions==1.13.0b1 (from -r requirements.txt (line 5)) | Exit code: 1 | Please review your requirements.txt | More information: https://aka.ms/troubleshoot-python
 /opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /tmp/build/expressbuild --platform python --platform-version 3.9.7 -i /tmp/8dac1c2eb121410 -p packagedir=.python_packages/lib/site-packages
 Generating summary of Oryx build
 Deployment Log file does not exist in /tmp/oryx-build.log
 The logfile at /tmp/oryx-build.log is empty. Unable to fetch the summary of build
 Deployment Failed. deployer = Push-Deployer deploymentPath = Functions App ZipDeploy. Extract zip. Remote build.
 Deployment failed.

Thanks again!
CK

**Comment by chandrabisen** [comment]
This looks the similar issue.
https://github.com/microsoft/Oryx/issues/849

**Comment by pauld-msft** [comment]
Hi @chandrabisen, would you be able to share some more details with us regarding this issue? Specifically:
- are you running this behind a corporate proxy?
- if so, have you attempted to set an environment variable that points to a pip config file for the python installation to use, as recommended in the linked issue? (e.g. PIP_CONFIG_FILE=~/.config/pip/pip.conf)
- Do you have a way that we would be able to reproduce this issue to further investigate?

**Comment by pauld-msft** [comment]
Hi @CSLAFan, would you be able to share the answers to my above questions, as well as a full log sample? Since it seems as though this issue was caused for the original poster by their function app being unable to pull a package, which we commonly see when customers have not opened up traffic to the package source, in this case, `pypi.org`:
`
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb1489fa90>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
`

**Comment by CSLAFan** [comment]
Hi @pauld-msft, I was able to deploy my function using azure cli which was failing with vs code

**Comment by pauld-msft** [comment]
Ok, thanks for the information. Sounds like this issue would be better solved by posting in the azure functions for vscode repo here: https://github.com/microsoft/vscode-azurefunctions

If the Oryx build itself is failing, feel free to re-open this issue with a full log output so we can better assist. Thanks!
