### ISSUE TITLE
Python Flask application could use environment variables to detect.

### ISSUE THREAD

**Issue by kjaymiller** [microsoft/Oryx#1669]
There is a mention that Flask only looks for `wsgi.py` or `app.py`.

https://github.com/microsoft/Oryx/blob/21ef7ce9cd1b58b68a8e5da304c9ed0ff6bf1d7d/src/startupscriptgenerator/src/python/frameworks.go#L106-L109

According to the [documentation](https://flask.palletsprojects.com/en/2.2.x/cli/?highlight=environment#environment-variables-from-virtualenv), your can pass in environment variables that can point to the application path. 

> The variables are named like `FLASK_OPTION` or `FLASK_COMMAND_OPTION`, for example `FLASK_APP` or `FLASK_RUN_PORT`.

If `FLASK_APP=<YOUR APP PATH/NAME>` is provided then `python/frameworks.go` would also have access to them and can check for that file, specifically.

**Comment by simonjj** [comment]
@kjaymiller if this is still relevant please explicitly share with us how we can help or improve what's happening today. I am not sure I am following your issue fully.
