### ISSUE TITLE
Azure WebApp - Virtual environment activation fails

### ISSUE THREAD

**Issue by PaulinAubert** [microsoft/Oryx#1676]
Hi,

My problem seems to be related to the following issues : https://github.com/microsoft/Oryx/issues/804 and https://github.com/microsoft/Oryx/issues/922.

We deploy a Django application on an Azure WebApp and after establishing a connection via SSH, the virtual environment is not automatically activated: 

![image](https://user-images.githubusercontent.com/93337605/201078080-d939b396-6d78-4b46-9b7b-1ca5d6b8256b.png)

If we take a closer look, we can see that "/" is missing from the command "source /antenv/bin/activate". And if I write this command manually, it works: 

![image](https://user-images.githubusercontent.com/93337605/201078280-7f796bbd-f1a1-472d-a8f9-799d6a2a54b9.png)

We discovered that in the last line of the /root/.bashrc file, the "/" is missing: 

![image](https://user-images.githubusercontent.com/93337605/201078465-babd9bde-6f91-49d9-afa6-ba3f7bb722b2.png)

If we add it and save the file, the activation of the virtual environment is automatic. So we are able to fix the bug up to this point.

Our problem is that when we deploy our application again, the .bashrc file is overwritten and the last line is again ". antenv/bin/activate".

We don't know how to solve this problem. Thank you very much for your help!

**Comment by simonjj** [comment]
We're closing this issue due to its age. If this is still impacting you please open a new issue and simply link back to this one.
