### ISSUE TITLE
Devops pipeline oryx, deploy to Static Web App , @azure/core-rest-pipeline need node >=14

### ISSUE THREAD

**Issue by myread02** [microsoft/Oryx#1684]
### Bug Report

- At what date and time did you most recently experience the problem?
today

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Devops pipeline job

- If your repo is publicly available please share its URL:
private 

- What happened?
error @azure/core-rest-pipeline@1.10.0: The engine "node" is incompatible with this module. Expected version ">=14.0.0". Got "12.22.11"
error Found incompatible module.

- What did you expect or want to happen?
node version are >=14 and build pass

- How can we reproduce it?
please check log under

- Do you have log output? Please include between the backticks:

```
Verifying checksum...
Extracting contents...
performing sha512 checksum for: nodejs...
Done in 2 sec(s).

Removing existing manifest file
Creating directory for command manifest file if it does not exist
Creating a manifest file...
Node Build Command Manifest file created.

Using Node version:
v12.22.11

Using Yarn version:
1.22.15

Installing production dependencies in '/working_dir/api/.oryx_prod_node_modules'...

Running 'yarn install --prefer-offline --production'...

yarn install v1.22.15
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
error @azure/core-rest-pipeline@1.10.0: The engine "node" is incompatible with this module. Expected version ">=14.0.0". Got "12.22.11"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.


---End of Oryx build logs---
Oryx has failed to build the solution.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting
##[error]Error: The process '/usr/bin/bash' failed with exit code 1
Finishing: Build (UAT)

```

**Comment by cormacpayne** [comment]
@myread02 -- Hey there, sorry about the inconvenience here; when you are able to, would you mind providing the following pieces of information:

- Do you have logs from recent successful runs of this Azure DevOps task? If so, are you able to provide the logs in a follow-up comment? This will help us to validate the version of node that was installed on the machine and the version that was expected by your application when building
- Just to confirm: does your `package.json` have an `engines` field defined with a `node` property? It appears that this value may be `"node": ">=14.0.0"` but I just want to double-check.

**Comment by myread02** [comment]
just got pass but not sure what happen here. describe my testing:

1. when I comment out  `api_location: 'api'`, deploy will not fail. so I can sure errors in swa api building process.
2. I found an way say need specify nodejs version by add in package.json, tried but build Iog still show using node v12.
3. remove `package.lock` and `yarn.lock` in api folder may help.

```
---End of Oryx build logs---
Function Runtime Information. OS: linux, Functions Runtime: ~3, node version: 12
node version: 12 will be deprecated soon. Please upgrade to a supported version. For more details about this update and next steps, please visit https://aka.ms/staticwebapps-node12-deprecation
For list of supported API languages, versions and their end of support date, please visit https://aka.ms/staticwebapps-apiruntimes
Finished building function app with Oryx
```

for specify nodejs version: 
https://edi.wang/post/2022/1/27/how-to-specify-nodejs-version-when-building-azure-static-web-app

```
"engines": {
    "node": ">=16.0.0"
  },
```
