### ISSUE TITLE
Prisma client not generated

### ISSUE THREAD

**Issue by Sealjay** [microsoft/Oryx#1696]
### Bug Report
- What happened?

When I generate a prisma client based off a prisma.schema file, it appears to be generated successfully.

According to application insights, the client isn't being loaded based on node_modules.

```
Exception while executing function: Functions.contentItems Result: Failure
Exception: Worker was unable to load function contentItems: '@prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues'
Stack: Error: Worker was unable to load function contentItems: '@prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
```

I have also encountered EACCES errors, which I tried to resolve with this command - https://github.com/microsoft/Oryx/issues/1615 - based off an issue in the Oryx repo.
`api_build_command: "chown -R root:root . && npm install --unsafe-perm && npm run build && npx prisma generate` based off

**Comment by Sealjay** [comment]
Will do! I tried the environmental variable route too, but that also failed. Let me get the logs for each attempt, and I'll attach the contents of the GitHub action file

**Comment by Sealjay** [comment]
Right, getting logs over to you are on my todo (there are about 62 revs to check through where I saw an EACCES error) - in the interim, I had to resort to a messy hack to get this working.

For others:

1. Rewrite typescript functions to js
2. Change a `/api/prisma/schema.prisma` file to include `binaryTargets = ["debian-openssl-1.1.x"]` and generate to `./client`. This is so that your Azure functions can access generated library files, as Oryx doesn't appear to run the npm postinstall command of `npx prisma generate`. I also added `watchDirectories": ["prisma"],` to my `api/host.json` file.
```
generator client {
  provider      = "prisma-client-js"
  output        = "./client"
  binaryTargets = ["native", "darwin", "debian-openssl-1.1.x"]
}
```
3. Add library files except those needed for a swa environment to your .gitignore, .e.g;
```
api/prisma/client/libquery_engine-darwin-arm64.dylib.node
api/prisma/client/libquery_engine-darwin.dylib.node
```
4. Run `npx prisma generate` manually inside your `api` folder.
4. Require prisma from your checked in client, e.g.
```
const { PrismaClient } = require('../prisma/client')
const prisma = new PrismaClient()
```

**Comment by pauld-msft** [comment]
So sorry for the lapse in communication here. We recently had a deployment freeze, but have now been able to get a fix out for the EACCES issue we saw in the linked ticket. See https://github.com/microsoft/Oryx/pull/1759 for the pull request that should resolve that problem. 

Please let us know if this change combined with the suggestions from @glaucia86 are not successful for you.
