### ISSUE TITLE
Support the Java runtime image in Oryx

### ISSUE THREAD

**Issue by showpune** [microsoft/Oryx#1701]
### Feature Request

Check the doc (https://github.com/microsoft/Oryx/blob/main/doc/base_images.md), it seems the java runtime image is not supported, do we have a plan to support java runtime image? Or if java is supported, how can I run a Java image?

**Comment by simonjj** [comment]
This issue should be resolved with the latest release of Buildpacks on ACA. Will be closing this issue. If this is still relevant and impacting you please open a new issue and link back to this issue for reference.
