### ISSUE TITLE
npm ERR! code ERESOLVE

### ISSUE THREAD

**Issue by calloncampbell** [microsoft/Oryx#1703]
### Bug Report

Starting November 15, 2022, my Azure Static Web Apps actions are failing in Github Action. Using Azure/static-web-apps-deploy@v1. I see a similar issue was logged in #1683

`Our workflow file:

name: STG Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - staging
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - staging

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_SEA_08CA7FD0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_build_command: "npm run build:prod"
          app_location: "/" # App source code path
          api_location: "https://shp-stg-cc-shipcarteapi-web.azurewebsites.net/shipcarte" # Api source code path - optional
          output_location: "dist/authorize" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_SEA_08CA7FD0F }}
          action: "close"
`

Here is the build output and error:

`
10s
Run Azure/static-web-apps-deploy@v[1](https://github.com/ShipCarte/shipcarte-web-new/actions/runs/3468121385/jobs/5793622755#step:4:1)
  with:
    azure_static_web_apps_api_token: ***
    repo_token: ***
    action: upload
    app_build_command: npm run build:prod
    app_location: /
    api_location: https://shp-stg-cc-shipcarteapi-web.azurewebsites.net/shipcarte
    output_location: dist/authorize
/usr/bin/docker run --name b9c5bb1b40f84acda5548fcadee4844b_7[2](https://github.com/ShipCarte/shipcarte-web-new/actions/runs/3468121385/jobs/5793622755#step:4:2)0d[3](https://github.com/ShipCarte/shipcarte-web-new/actions/runs/3468121385/jobs/5793622755#step:4:3)5 --label 290506 --workdir /github/workspace --rm -e "INPUT_AZURE_STATIC_WEB_APPS_API_TOKEN" -e "INPUT_REPO_TOKEN" -e "INPUT_ACTION" -e "INPUT_APP_BUILD_COMMAND" -e "INPUT_APP_LOCATION" -e "INPUT_API_LOCATION" -e "INPUT_OUTPUT_LOCATION" -e "INPUT_API_BUILD_COMMAND" -e "INPUT_APP_ARTIFACT_LOCATION" -e "INPUT_ROUTES_LOCATION" -e "INPUT_SKIP_APP_BUILD" -e "INPUT_CONFIG_FILE_LOCATION" -e "INPUT_SKIP_API_BUILD" -e "INPUT_PRODUCTION_BRANCH" -e "INPUT_DEPLOYMENT_ENVIRONMENT" -e "INPUT_IS_STATIC_EXPORT" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/shipcarte-web-new/shipcarte-web-new":"/github/workspace" 290506:b9c5bb1b[4](https://github.com/ShipCarte/shipcarte-web-new/actions/runs/3468121385/jobs/5793622755#step:4:4)0f84acda[5](https://github.com/ShipCarte/shipcarte-web-new/actions/runs/3468121385/jobs/5793622755#step:4:5)548fcadee4844b
DeploymentId: [6](https://github.com/ShipCarte/shipcarte-web-new/actions/runs/3468121385/jobs/5793622755#step:4:6)5ab3dcf-ff[7](https://github.com/ShipCarte/shipcarte-web-new/actions/runs/3468121385/jobs/5793622755#step:4:7)4-4747-a[8](https://github.com/ShipCarte/shipcarte-web-new/actions/runs/3468121385/jobs/5793622755#step:4:8)e[9](https://github.com/ShipCarte/shipcarte-web-new/actions/runs/3468121385/jobs/5793622755#step:4:9)-9a6ee6ebe0a0

App Directory Location: '/' was found.
Looking for event info
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
Oryx will build app with the following custom override command: npm run build:prod
---Oryx build logs---

Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20221[10](https://github.com/ShipCarte/shipcarte-web-new/actions/runs/3468121385/jobs/5793622755#step:4:11)3.1, Commit: a2c65dde152b749fea395f4d1242ea9350942258, ReleaseTagName: 2022[11](https://github.com/ShipCarte/shipcarte-web-new/actions/runs/3468121385/jobs/5793622755#step:4:12)03.1

Build Operation ID: |Nm5ZQvW96B4=.931d[12](https://github.com/ShipCarte/shipcarte-web-new/actions/runs/3468121385/jobs/5793622755#step:4:13)9c_
Repository Commit : 86c584af4fb7dc471f69df00a240b2b4f5920477

Detecting platforms...
Detected following platforms:
  nodejs: 16.18.0
Version '16.18.0' of platform 'nodejs' is not installed. Generating script to install it...
Detected the following frameworks: Angular,Typescript,jQuery

Source directory     : /github/workspace
Destination directory: /bin/staticsites/ss-oryx/app

Downloading and extracting 'nodejs' version '16.18.0' to '/opt/nodejs/16.18.0'...
Detected image debian flavor: bullseye.
Downloaded in 0 sec(s).
Verifying checksum...
Extracting contents...
performing sha512 checksum for: nodejs...
Done in 1 sec(s).

Removing existing manifest file
Creating directory for command manifest file if it does not exist
Creating a manifest file...
Node Build Command Manifest file created.

Using Node version:
v16.18.0

Using Npm version:
8.19.2

Running 'npm install --unsafe-perm'...

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @angular-devkit/build-angular@0.1002.3
npm ERR! Found: @angular/localize@12.1.4
npm ERR! node_modules/@angular/localize
npm ERR!   @angular/localize@"^12.1.4" from the root project
npm ERR!   peer @angular/localize@"^12.0.0" from @ng-bootstrap/ng-bootstrap@10.0.0
npm ERR!   node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!     @ng-bootstrap/ng-bootstrap@"^10.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @angular/localize@"^10.0.0" from @angular-devkit/build-angular@0.1002.3
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"~0.1002.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/localize@10.2.5
npm ERR! node_modules/@angular/localize
npm ERR!   peerOptional @angular/localize@"^10.0.0" from @angular-devkit/build-angular@0.1002.3
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~0.1002.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /github/home/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2022-11-[15](https://github.com/ShipCarte/shipcarte-web-new/actions/runs/3468121385/jobs/5793622755#step:4:16)T06_49_[20](https://github.com/ShipCarte/shipcarte-web-new/actions/runs/3468121385/jobs/5793622755#step:4:21)_[60](https://github.com/ShipCarte/shipcarte-web-new/actions/runs/3468121385/jobs/5793622755#step:4:61)2Z-debug-0.log

---End of Oryx build logs---
Oryx has failed to build the solution.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting
`

**Comment by pauld-msft** [comment]
Hi @calloncampbell , SWA recently updated the default node version to 16 (the previous default was 14). You can manually configure your application default to 14, as mentioned in the [issue ](https://github.com/microsoft/Oryx/issues/1683)that you linked, by adding the following to your `package.json`

`"engines": { "node": "14.x" },`

**Comment by pauld-msft** [comment]
Hi @calloncampbell, we merged in a fix for this issue (https://github.com/microsoft/Oryx/pull/1759) a few weeks ago, and it is currently rolling out to our various partners such as Azure App Service. As there is a workaround currently, and the real fix is going through deployment, I am going to go ahead and close this issue. Thanks for reporting it.
