### ISSUE TITLE
Oryx Python Pip Install Fails for package on Azure Artifact Feed

### ISSUE THREAD

**Issue by sizzles** [microsoft/Oryx#1705]
Hi,

I am using the Azure App Service deploy task in an Azure classic release pipeline.

I have a .whl package (MY_PKG) to a private Azure artifact feed.  I can use the Pip Authenticate task to successfully pip install this as part of the build pipeline.

However, when doing a release (the deploy task uses Oryx under the hood) the pip install seems to ignore the PIP_INDEX_URL environment variable and still try to use the public PyPi repo. Consequently MY_PKG can't be found and the release process fails.

Is there a way:
1)To specify which index_url Oryx should use during the build process?
2)or force it to recognise environment variable?

Or failing that any pointers on how to use this with an Azure artifact feed? Fully appreciate that I might have missed something here.

Thanks!

**Comment by simonjj** [comment]
This issue seems resolved. Will be closing this issue. If this is still relevant and impacting you please open a new issue and link back to this issue for reference.
