### ISSUE TITLE
Support newer versions of Ruby

### ISSUE THREAD

**Issue by olbrich** [microsoft/Oryx#1708]
### Feature Request

Please update runtime support to include the latest versions of Ruby.

The most current versions are 2.7.7, 3.0.5, and 3.1.3 which all have important security updates.

**Comment by pauld-msft** [comment]
We are currently [in the process of](https://github.com/microsoft/Oryx/pull/1690) releasing 2.7.6. I've also created a ticket to take a look into investigating upgrading the mentioned versions. Thanks for bringing this to our attention.

**Comment by william-msft** [comment]
Hi @olbrich, the new versions of Ruby have been released:
ruby 2.7.7
ruby 3.0.5
ruby 3.1.3

Happy new year!

**Comment by olbrich** [comment]
Thanks! Also note that Ruby 3.2 came out over the holidays... see #1779
