### ISSUE TITLE
Ruby version detection fails

### ISSUE THREAD

**Issue by olbrich** [microsoft/Oryx#1709]
### Bug Report

- At what date and time did you most recently experience the problem?
2022-11-30 at 8:25am EST

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Running Github action to deploy static site

- What happened?
Ruby version detection failed.
The ruby version in the Gemfile was specified as '~> 3.1' which resulted in a Gemfile.lock containing a ruby version of `ruby 3.1.1p18`.

Oryx attempted to run and returned with this error:
```
Detecting platforms...
Error: Platform 'ruby' version '3.1.1p18' is unsupported. Supported versions: 2.5.8, 2.6.6, 2.7.1, 2.7.2, 2.7.6, 3.0.0, 3.0.3, 3.1.1, 2.5.8, 2.6.6, 2.7.1, 2.7.2, 2.7.6, 3.0.0, 3.0.3, 3.1.1
```

Also, note that it is conventional to indicate which version of ruby is used in a project by including a `.ruby-version` file in the root of the project containing the ruby version or a string like `ruby-3.1.1`. This mechanism of specifying the version appears to be ignored by Oryx.

A reasonable approach to detecting ruby versions would be to:
1. Properly parse the `Gemfile.lock` entry
2. Fall back to the contents of `.ruby-version`
3. Also look for a `.tool-versions` file (from asdf)
4. Use the `Gemfile` specification last

- What did you expect or want to happen?
It should have detected `3.1.1` as the requested ruby version.

- How can we reproduce it?
- Create a ruby app and generate a gemfile specifying a ruby version of `~> 3.1`.
- `bundle update --ruby`
- attempt to deploy the site

**Comment by olbrich** [comment]
So yes, it did attempt to detect the version from the Gemfile.lock that was generated on my local machine. The problem is that the version put there by bundler always has the patch version applied and Oryx does not appear to know how to interpret that part of the version string so you will never get a correct match. I expect that Oryx should have interpreted `3.1.1p18` to map to `3.1.1`.

**Comment by pauld-msft** [comment]
Hi @olbrich, would you happen to have any documentation that confirms that the `bundler always has the patch version applied`? I was looking around and was unable to find any. If I can get that, it should be a relatively quick fix to just have the version detection just use the first capturing group of something like `(.*?)(?:p[0-9]+)?` so that it can still support any preview versions that come down the pipeline in the future (so something like `3.2.0-preview1` is unchanged, but `3.1.1p18` is shortened to `3.1.1`).

**Comment by olbrich** [comment]
Based on this file... https://github.com/rubygems/rubygems/blob/master/bundler/lib/bundler/ruby_version.rb

It looks like bundler will usually add the patch version (with a format like `p<patch_version>`), but may not in some cases (like for `ruby-head` or a pre-release version). 

I have locally gotten a bundler to generate a lock file set to `3.2.0.rc1` which generates a line in the lockfile that looks like..

    RUBY VERSION
   		ruby 3.2.0.rc1

So you may want to tweak your regex a bit.

**Comment by pauld-msft** [comment]
sorry, but in the case that we have an RC or preview version, wouldn't we like the regex to capture the full `3.2.0.rc1` since `3.2.0.rc1 != 3.2.0`, whereas `3.2.0p123 == 3.2.0` so we can safely shorten to `3.2.0`?

**Comment by olbrich** [comment]
@pauld-msft That is probably true.

**Comment by pauld-msft** [comment]
Merged in a fix on the Oryx side (https://github.com/microsoft/Oryx/pull/1801). Deployment to our partners such as Azure App Service will take some time, but I am going to close this issue on our end. Thanks for reporting it.
