### ISSUE TITLE
Support golang build command other than `go build`

### ISSUE THREAD

**Issue by tchcto** [microsoft/Oryx#1715]
### Feature Request

We build APIs using golang, and use mage (magefile.org) to run the build. Ideally using the command `mage`
But this should work if we can run `go run mage.go` (see https://magefile.org/zeroinstall/)

This would enable us to easily have our build of the api include vet & test before build.

`api_build_command` is set up for node projects, can this not also be used for other platforms?

**Comment by simonjj** [comment]
We're closing this issue due to its age. If this is still impacting you please open a new issue and simply link back to this one.

**Comment by simonjj** [comment]
We're closing this issue due to its age. If this is still impacting you please open a new issue and simply link back to this one.
