### ISSUE TITLE
Update Python patch versions

### ISSUE THREAD

**Issue by tonybaloney** [microsoft/Oryx#1725]
### Feature Request

Please patch the minor Python versions with today's set of releases

https://discuss.python.org/t/python-3-11-1-3-10-9-3-9-16-3-8-16-3-7-16-and-3-12-0-alpha-3-are-now-available/21724

**Comment by simonjj** [comment]
This issue seems resolved. Will be closing this issue. If this is still relevant and impacting you please open a new issue and link back to this issue for reference.
