### ISSUE TITLE
[Question] Hugo build command

### ISSUE THREAD

**Issue by RiazChen** [microsoft/Oryx#1737]
### Bug Report

Under https://github.com/microsoft/Oryx/blob/main/doc/runtimes/hugo.md#build to build a Hugo App, 
![image](https://user-images.githubusercontent.com/120349662/206947384-c031ac43-b3fd-4eff-b30c-fc8c7d17de96.png)
Without command “hugo –minify” a building will not work, is that a mandatory one or included in the "custom script" in the picture above?

**Comment by william-msft** [comment]
Hi @RiazChen, this is not a requirement.

**Comment by simonjj** [comment]
This issue seems resolved. Will be closing this issue. If this is still relevant and impacting you please open a new issue and link back to this issue for reference.
