### ISSUE TITLE
Deploy Symfony PHP 8 on Azure App Service 

### ISSUE THREAD

**Issue by KawemeKowa** [microsoft/Oryx#1749]
I am writing to follow up on a previous issue that I raised [#1747](https://github.com/microsoft/Oryx/issues/1747). I followed your instructions, deleted all the empty .yaml files and deployed the Symfony application using PHP 8.0 to Azure App Service using the deployment centre. My repository is visible in the /wwwroot Kudu file. I however still get  "Your web app is running and waiting for your content" when I ran the web application. The url is https://tsinventory.azurewebsites.net/

I followed this blog that advised that I have to create a custom start up script /home/site/startup.sh and that modifies the /etc/nginx/sites-available/default file via SSH due to PHP 8.0 using NGINX instead of Apache. This still didn't fix my issue.
This is the log that I get when I do a "Availability and Performance" check.
![image](https://user-images.githubusercontent.com/68535259/208153247-9e2d90c3-3387-4db2-bd41-4850d5473340.png)

"Your app started but did not respond to health checks. This means that our App Service infrastructure has tried pinging the container every second until it responds, indicating that the HTTP server is up."

Please advice on what other steps I can take to have my PHP 8.0 Symfony application running on Azure.

**Comment by KawemeKowa** [comment]
anyone with an update on this issue?

**Comment by simonjj** [comment]
We're closing this issue due to its age. If this is still impacting you please open a new issue and simply link back to this one.
