### ISSUE TITLE
VS Code App Service Django deploy to Azure hangs on collectstatic then fails

### ISSUE THREAD

**Issue by dawnwages** [microsoft/Oryx#1750]
### Bug Report

- At what date and time did you most recently experience the problem?

Today, Dec 16th 2022

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.

Azure App Service via VS Code

- If your repo is publicly available please share its URL:

https://github.com/dawnwages/dw-django/tree/new-deploy

- What happened?

Oryx goes great until it gets to collectstatic and then fails.

- What did you expect or want to happen?

Keep moving forward by checking all my `static` dirs and outputting it to my `staticfiles` directory at the root of my project. 

Here's the django documentation on how collect static works: https://docs.djangoproject.com/en/4.1/ref/contrib/staticfiles/#:~:text=django-admin%20collectstatic%20Collects%20the%20static%20files%20into%20STATIC_ROOT.,one%20of%20the%20specified%20locations%20will%20be%20used.

how to staticfiles pattern that I like comes from the Django docs: https://docs.djangoproject.com/en/4.1/howto/static-files/

- How can we reproduce it?

You can use my app above, but I think it would also work with running collectstatic on any django app (even if you don't have your static dirs in other applications, it will still register the css/js for admin) and then attempt to deploy. 

What I believe is happening is that it's waiting for the user to reply yes or no to overwrite existing files in that directory and then times out. When I deleted my `staticfiles` directory it worked. What I think could be the solution is provide a way for the dev to confirm if they want files over written or by default use the `--no-input` flag that django has. I think allowing the user to confirm is the best option.

- Do you have log output? Please include between the backticks:

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/20374042/208176889-3f72018a-f54c-4d0a-b179-f7abc557695c.png">

```
1:33:07 PM dw-website: Content in source directory is a Django app
1:33:08 PM dw-website: Running collectstatic...
1:54:02 PM dw-website: An unknown error has occurred. Check the diagnostic log for details.
1:54:04 PM dw-website: Deployment failed.
```

**Comment by ethan-kisiel** [comment]
Having the same issue

**Comment by simonjj** [comment]
This issue seems resolved. Will be closing this issue. If this is still relevant and impacting you please open a new issue and link back to this issue for reference.
