### ISSUE TITLE
"Missing Django module" warning doesn't take into account recursive requirements files

### ISSUE THREAD

**Issue by pamelafox** [microsoft/Oryx#1778]
### Bug Report

- At what date and time did you most recently experience the problem?

Tuesday January 3rd 11:30 AM PT

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.

Azure App Service

- If your repo is publicly available please share its URL:

https://github.com/pamelafox/cookiecutter-django-output/tree/44240a985bce6eeb92c46b0c6cf07eae66316752

- What happened?

I deploy with the environment variable CUSTOM_REQUIREMENTSTXT_PATH: 'requirements/production.txt'

You can see that production.txt file here:
https://github.com/pamelafox/cookiecutter-django-output/blob/44240a985bce6eeb92c46b0c6cf07eae66316752/requirements/production.txt

It references base.txt, which is where Django is actually included:
https://github.com/pamelafox/cookiecutter-django-output/blob/44240a985bce6eeb92c46b0c6cf07eae66316752/requirements/base.txt

That is fine for pip, as pip knows how to install requirements from referenced files.
However, Oryx produces a warning:

  11:39:39 AM  Warnings (1)
  11:39:39 AM  1. Missing Django modile in Missing Django module in /tmp/8daedc21f7ce6ba/requirements.txt
  11:39:39 AM  - Next Steps: Add Django to your requirements.txt file.
  11:39:39 AM  - For more details you can browse to https://aka.ms/troubleshoot-python

- What did you expect or want to happen?

I do not expect a warning.

Or, I expect it to say something like "If your Django module is in a referenced sub-requirements file, then you can ignore this warning."

The warning also has typos - it says "modile" instead of "module" and repeats the phrase "Missing Django modu(i)le" twice.

This isn't a big deal, I assume I can just ignore the warning, I just wanted to document it for completeness.

- How can we reproduce it?

After installing the Azure Dev CLI, run `azd up` on my repo.

**Comment by pauld-msft** [comment]
Hi @pamelafox, thanks for reporting. The typo and repeated phrase was fixed in https://github.com/microsoft/Oryx/pull/1616.

As for the referenced file issue, it seems as though this will also keep Oryx from running `python manage.py collectstatic`. That being said, I am surprised that you are seeing this issue at all, as you have modules in your `production.txt` file that begin with `django`, and therefore Oryx should detect your project as including django. Are you sure that the production.txt configuration is being respected?

**Comment by pauld-msft** [comment]
I think that if it were, we would see something like `Missing Django module in /tmp/8daedc21f7ce6ba/requirements/production.txt`. Would you mind double checking that configuration, and if all looks good, sharing the full build logs with me?

**Comment by pamelafox** [comment]
Ah, I was wondering why I couldn't find the typo in the repo. You're right, I realized Oryx wasn't finding my requirements.txt correctly. It doesn't seem to be obeying CUSTOM_REQUIREMENTSTXT_PATH in the App Settings, so I'm trying other approaches now (but running into the psycopg2 error from other issue). Anyways I'll keep trying things and report back.

**Comment by pamelafox** [comment]
Ah, you are right! It is *not* running collectstatic, so this is more than just a cosmetic issue.

You can replicate with this version of the repo:
https://github.com/pamelafox/cookiecutter-django-output/tree/a9df9e843995c1e8b6f06429be9a4d7238fc1fd3

It has a "successful" deploy which includes the "Missing Django module" warning and shows no evidence of running collectstatic.

This version used this requirements.txt file:
https://github.com/pamelafox/cookiecutter-django-output/blob/a9df9e843995c1e8b6f06429be9a4d7238fc1fd3/requirements.txt

Which references requirements/production.txt which references requirements/base.txt (which has django in it).

**Comment by pamelafox** [comment]
To workaround this, I've written "Django" in a comment in requirements.txt, as that satisfies this: https://github.com/microsoft/Oryx/blob/df89ea1db9625a86ba583272ce002847c18f94fe/src/BuildScriptGenerator/Python/PythonBashBuildSnippet.sh.tpl#L237

I deployed that and confirmed it's now running collectstatic and my site is fully running.

**Comment by pauld-msft** [comment]
Well, I'm glad you were able to find a workaround. I'll see if I can figure out why `CUSTOM_REQUIREMENTSTXT_PATH` doesn't seem to be respected. Thanks for sharing the repo and detailed steps!

**Comment by pauld-msft** [comment]
Aha, I believe that we have fixed this issue with https://github.com/microsoft/Oryx/pull/1582, but the change is just in the process of rolling out to Azure App Service. If you check the version of Oryx being used for the AAS deployment, I imagine that you will see that the version is prior to [20220929.1](https://github.com/microsoft/Oryx/releases/tag/20220929.1) aka our `2022/09/29` release.
