### ISSUE TITLE
Python 3.11 Django and Flask apps being launched with Gunicorn on Python 3.9

### ISSUE THREAD

**Issue by tonybaloney** [microsoft/Oryx#1831]
When deploying the following Flask Web App to Azure Web Apps with Python 3.11, the runtime is actually being launched with Python 3.9.

This is a very basic `app.py` to demonstrate the problem:

```python
from flask import Flask, make_response
import sys

app = Flask(__name__)

@app.route('/')
def index():
    version = sys.version_info
    response = make_response(f"Hello, I am Python {version}", 200)
    response.mimetype = "text/plain"
    return response

if __name__ == '__main__':
    app.run(debug=True)
```

The response when deploying is:

```
Hello, I am Python sys.version_info(major=3, minor=9, micro=2, releaselevel='final', serial=0)
```

You can see how this is happening by SSH'ing to the container. `Gunicorn` has been installed as root in the image so it will launch the version of python that installed it (the Python 3.9.2 that comes installed in Debian containers, not the Python 3.11)

```
   _____                               
  /  _  \ __________ _________   ____  
 /  /_\  \\___   /  |  \_  __ \_/ __ \ 
/    |    \/    /|  |  /|  | \/\  ___/ 
\____|__  /_____ \____/ |__|    \___  >
        \/      \/                  \/ 
A P P   S E R V I C E   O N   L I N U X

Documentation: http://aka.ms/webapp-linux
Python 3.11.0
Note: Any data outside '/home' is not persisted
(antenv) root@40b1f8da82f9:/tmp/8daf9c0651c4ff6# which gunicorn
/usr/local/bin/gunicorn
(antenv) root@40b1f8da82f9:/tmp/8daf9c0651c4ff6# head /usr/local/bin/gunicorn
#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from gunicorn.app.wsgiapp import run
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(run())
(antenv) root@40b1f8da82f9:/tmp/8daf9c0651c4ff6# /usr/bin/python3 -V
Python 3.9.2
```

You can see the `pip install` command here: https://github.com/microsoft/Oryx/blob/a7ad8cea5e5b08e06537af15371315f112b5b6f8/images/runtime/python/3.11/base.bullseye.Dockerfile#L76

When Oryx auto-discovers Django or Flask applications it will create a startup command using `gunicorn`. This is launching Python 3.9 but with the virtual environment of Python 3.11. 

The consequences of this bug are two-fold:

1. Applications are running under the older, slower Python 3.9 instead of 3.11
2. Some apps will fail to run because they either require Python 3.11 only syntax or C-extensions

I've noted that this affects Django and Flask since Oryx will create the startup command automatically, but any app that starts by running `gunicorn` at the command will be impacted.

## Fix

Do not install Gunicorn using the root Python interpreter. Only install as a dependency for the target runtime

**Comment by tonybaloney** [comment]
Just tested and confirmed this bug does not affect Python 3.10. Just deploying the same app:

```
   _____                               
  /  _  \ __________ _________   ____  
 /  /_\  \\___   /  |  \_  __ \_/ __ \ 
/    |    \/    /|  |  /|  | \/\  ___/ 
\____|__  /_____ \____/ |__|    \___  >
        \/      \/                  \/ 
A P P   S E R V I C E   O N   L I N U X

Documentation: http://aka.ms/webapp-linux
Python 3.10.4
Note: Any data outside '/home' is not persisted
(antenv) root@64a00ec49cde:/tmp/8daf9c92b54eaaa# which gunicorn
/opt/python/3/bin/gunicorn
(antenv) root@64a00ec49cde:/tmp/8daf9c92b54eaaa# head /opt/python/3/bin/gunicorn
#!/opt/python/3.10.4/bin/python3.10
# -*- coding: utf-8 -*-
import re
import sys
from gunicorn.app.wsgiapp import run
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(run())
```

The web server returns

```
Hello, I am Python sys.version_info(major=3, minor=10, micro=4, releaselevel='final', serial=0)
```

**Comment by waliMSFT** [comment]
@tonybalcony 
 I have tested our github-actions-debian-bullseye image on a Flash app in Python 3.11. I have found on the runtime image the version of python is still 3.11. I could not replicate the issue you showed here.
 I believe only the bullseye images support python 3.11. Did you try on the same bullseye image? 
 or do you have any other supporting info that may help us to investigate more?

**Comment by tonybaloney** [comment]
Did you deploy the flask app I showed? The issue is that whilst 3.11 is installed, 3.9 is the one being launched by the default Oryx  startup script for flask and Django.

**Comment by tonybaloney** [comment]
This is no longer an issue with the latest version (3.11.1)

**Comment by Kyyza** [comment]
@tonybaloney can you run 3.11.1 in azure web app though?
