### ISSUE TITLE
PRE_BUILD_COMMAND 

### ISSUE THREAD

**Issue by e-hermoso** [microsoft/Oryx#1837]
I am trying to install these packages  shown below before I deploy to azure app services.

apt-get install libkrb5-dev
apt-get install gcc

Every time I deploy the application i recive this error below.
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)

When i ssh into my azure app service I am able to install the packages manually but it dos not persist throughout the azure app service.
I need these packages in order to use arcgis api python libraries on azure app services.

**Comment by daniv-msft** [comment]
Thanks @e-hermoso for opening this issue. Unfortunately installing dynamically packages from apt-get is not something we support, as our Oryx images are usually hosted in unprivileged hosts in App Service. I imagine that when you SSH you get better permissions that allow you to install these.

I don't have a great alternative to offer on App Service, but if you're willing to create a Dockerfile then Azure Container Apps would be a solid alternative: https://learn.microsoft.com/azure/container-apps/overview

Hope this helps!
