### ISSUE TITLE
[Feature Request] Add Deno support

### ISSUE THREAD

**Issue by snobu** [microsoft/Oryx#1846]
### Feature Request

Please consider adding [Deno](https://deno.land/) support. Sample Dockerfile: https://github.com/denoland/deno_docker#as-a-dockerfile

**Comment by cormacpayne** [comment]
@snobu Hey Adrian, thanks for the feature request -- we'll put this on the backlog and take a look at what work would be involved with integrating this in the future.

What would your expectations be for using this runtime in the Oryx images? From the looks of the links you've provided, this would be a _substitute_ for the `node` and `npm` commands that we use during our build and run images, not something that could be used side-by-side with it. Please correct me if I'm wrong with that previous statement.

**Comment by snobu** [comment]
Right. Deno is a TypeScript runtime. I believe the Node logic can be simplified and adjusted for Deno, however, in my view, the difficult problem here seems to be how to detect if a project is a Deno project or not.

Take this sample -
https://github.com/bricxcarasco/deno-rest-api

Not very easy to tell what type of project that is.

If someone uses `deno init`, it will generate a `deno.jsonc` file that gives us high confidence it's a Deno project, but it does not present a strong guarantee, since `deno init` is not a must, also the JSONC file is a rather new addition to the runtime.

To make things worse, Deno now supports a `package.json` file in the project root, identical to Node.

We could look at the `.ts` files and check for stdlib imports, however not sure if this is a good indication or not as we can only match by domain name.
```
// main.ts
import { copy } from "https://deno.land/std@0.178.0/fs/copy.ts";
...
```
Quite naive i would say, there must be a better way.

I opened an issue here,  https://github.com/denoland/deno/issues/17988 to learn more from the community.

**Comment by simonjj** [comment]
This has not been prioritized yet. We're open to pull requests on this issue. Closing due to age for now. If you have a PR please reference this issue in the PR.
