### ISSUE TITLE
Language not detected for Node/Typescript/React app

### ISSUE THREAD

**Issue by jakobpn** [microsoft/Oryx#1877]
### Bug Report
Trying to set up Github Actions to deploy a Node/React/Typescript project to an Azure Static Web app. Unfortunately, I get a "cannot detect language from repo" in the Detecting Platforms step in the Azure/static-web-apps-deploy@v1 script.

The APP_LOCATION environment variable is set to "/content-addin/src". The package.json file is in the "/content-addin" folder.  

This the output from Github actions:
Run Azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ***
    repo_token: ***
    action: upload
    app_location: /content-addin/src
    api_location: api
    app_artifact_location: dist
  env:
    APP_LOCATION: /content-addin/src
    API_LOCATION: api
    APP_ARTIFACT_LOCATION: dist
    AZURE_STATIC_WEB_APPS_API_TOKEN: ***
/usr/bin/docker run --name cffde5cf4b09c495c808471aa348a4f62_727e70 --label 49859c --workdir /github/workspace --rm -e "APP_LOCATION" -e "API_LOCATION" -e "APP_ARTIFACT_LOCATION" -e "AZURE_STATIC_WEB_APPS_API_TOKEN" -e "INPUT_AZURE_STATIC_WEB_APPS_API_TOKEN" -e "INPUT_REPO_TOKEN" -e "INPUT_ACTION" -e "INPUT_APP_LOCATION" -e "INPUT_API_LOCATION" -e "INPUT_APP_ARTIFACT_LOCATION" -e "INPUT_API_BUILD_COMMAND" -e "INPUT_OUTPUT_LOCATION" -e "INPUT_APP_BUILD_COMMAND" -e "INPUT_ROUTES_LOCATION" -e "INPUT_SKIP_APP_BUILD" -e "INPUT_CONFIG_FILE_LOCATION" -e "INPUT_SKIP_API_BUILD" -e "INPUT_PRODUCTION_BRANCH" -e "INPUT_DEPLOYMENT_ENVIRONMENT" -e "INPUT_IS_STATIC_EXPORT" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/[REDACTED]/[REDACTED]":"/github/workspace" 49859c:ffde5cf4b09c495c808471aa348a4f62
DeploymentId: 57acdd3e-6aa7-4948-8da9-91d5eee48050

App Directory Location: '/content-addin/src' was found.
Looking for event info
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
---Oryx build logs---

Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20221103.1, Commit: a2c65dde152b749fea395f4d1242ea9350942258, ReleaseTagName: 20221103.1

Build Operation ID: |u+b7ZDMA5uU=.20f8079f_
Repository Commit : 93b838c50cf4b3120cfcfce2139658d8c8826dd8

Detecting platforms...
Could not detect any platform in the source directory.
Error: Could not detect the language from repo.

---End of Oryx build logs---
Oryx was unable to determine the build steps. Continuing assuming the assets in this folder are already built. If this is an unexpected behavior please contact support.
Finished building app with Oryx
[WARNING] Api Directory Location: 'api' could not be found. Azure Functions will not be created.
Either no Api directory was specified, or the specified directory was not found. Azure Functions will not be created.
Zipping App Artifacts
Done Zipping App Artifacts
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.7915604(s)
Status: Succeeded. Time: 15.8969847(s)
Deployment Complete :)
Visit your site at: https://witty-desert-09ff99603.2.azurestaticapps.net
Thanks for using Azure Static Web Apps!
Exiting

**Comment by pauld-msft** [comment]
Hi @jakobpn, have you tried to set the APP_LOCATION var to `/content-addin`, since that is the location of your `package.json` file?

If you have already tried that, is there any chance that you would be able to provide a link to your repo (or contents of package.json file and the static web apps task from your github actions job)?

**Comment by BaggioFilipe** [comment]
How can I set APP_LOCATION inside my pipeline.yaml ?

**Comment by jakobpn** [comment]
@pauld-msft, thank you for your prompt response and help. Setting APP_LOCATION to /content-addin as you suggested solved the issue and the project started building.
