### ISSUE TITLE
Ruby 2.7 base images missing in Microsoft Artifact Registry

### ISSUE THREAD

**Issue by roberto-mardeni** [microsoft/Oryx#1887]
### Bug Report
- At what date and time did you most recently experience the problem?
2023/02/15 6:26 PM EST

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Container Registry, using az containerapp up command to build an app into container without Dockerfile

- If your repo is publicly available please share its URL:
https://github.com/roberto-mardeni/ruby-docs-hello-world

- What happened?
Using the command below fails:
`az containerapp up -n sample-ruby-app --source https://github.com/roberto-mardeni/ruby-docs-hello-world -g aca --environment myacaenv --ingress external > az_containerapp_up.log`
Error message is: 
Step 6/10 : FROM mcr.microsoft.com/oryx/${RUNTIME}
manifest for mcr.microsoft.com/oryx/ruby:2.7 not found: manifest unknown: manifest tagged by "2.7" is not found

- What did you expect or want to happen?
Container image to build and deploy to Azure Container Apps service

- How can we reproduce it?

1. Clone repo
2. Create Azure Resource Group
3. Create Azure Container Apps Environment
4. Run az containerapps up command below
`az containerapp up -n sample-ruby-app --source https://github.com/roberto-mardeni/ruby-docs-hello-world -g aca --environment myacaenv --ingress external > az_containerapp_up.log`

- Do you have log output? Please include between the backticks:
```
[az_containerapp_up.log](https://github.com/microsoft/Oryx/files/10750296/az_containerapp_up.log)
```

**Comment by william-msft** [comment]
Hi @roberto-mardeni by any chance have you tried bumping up to Ruby 3.0? Since 2.7 will EOL in about a month.

**Comment by william-msft** [comment]
Closing. Once additional information can be provided we can re-open. Thanks!
