### ISSUE TITLE
Fastapi

### ISSUE THREAD

**Issue by bstuddard** [microsoft/Oryx#1952]
### Feature Request

Add fastapi sample app in test, with custom run script.

**Comment by william-msft** [comment]
Hi @bstuddard, could you provide more context on the feature request? 

- Could you provide more context behind the request? Was there an un-caught Oryx issue for this?
- Do you have a sample fastapi that you would like us to test?
- What are you requesting the custom run script to be?

**Comment by bstuddard** [comment]
> Hi @bstuddard, could you provide more context on the feature request? 
> 
> - Could you provide more context behind the request? Was there an un-caught Oryx issue for this?
> - Do you have a sample fastapi that you would like us to test?
> - What are you requesting the custom run script to be?

Hi, thanks for reaching out. No urgent issue, just a potential addition for both example and testing purposes. There wasn't an error raised, essentially was thinking something like this for the startup script:

`
gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:80
`

And something like this for the sample app to test with
[Sample App](https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker/blob/master/docker-images/app/main.py)

**Comment by william-msft** [comment]
We have filed an [item](https://devdiv.visualstudio.com/DevDiv/_boards/board/t/Oryx/Stories/?workitem=1785553) on our board for someone on our team to pickup. Thank you.

**Comment by tonybaloney** [comment]
Hi @bstuddard I've got an example repo for FastAPI on App Service here https://github.com/tonybaloney/ants-azure-demos/tree/master/fastapi-web-app 

The important part is setting the custom startup script using the Azure CLI or the portal

```
az webapp config set --startup-file "startup.sh" -g fastapi-demo -n fastapi-web
```

**Comment by bstuddard** [comment]
> Hi @bstuddard I've got an example repo for FastAPI on App Service here https://github.com/tonybaloney/ants-azure-demos/tree/master/fastapi-web-app 
> 
> The important part is setting the custom startup script using the Azure CLI or the portal
> 
> ```
> az webapp config set --startup-file "startup.sh" -g fastapi-demo -n fastapi-web
> ```

This is great, thanks for sharing!

**Comment by simonjj** [comment]
This issue seems resolved. Will be closing this issue. If this is still relevant and impacting you please open a new issue and link back to this issue for reference.
