### ISSUE TITLE
Local git deployment does not synchronously delete files (Linux webapp)

### ISSUE THREAD

**Issue by lc-lc0304** [microsoft/Oryx#1966]
Hi Team:

We have encountered a difficulty, please assist.

We are using the Linux app service and the development language is php. After deleting a file locally and deploying it to the cloud, it will not be deleted in real time. We are very confused.

At present, we have tested and found that the Linux PHP and node.js stack did not synchronize in real time after deleting a file, but Java Linux is sufficient. We are very puzzled.

Please tell us the reason.This issue has caused a delay in our work. Please assist,Thank you very much.

**Comment by harryli0108** [comment]
Hi @lc-lc0304! This sounds like a configuration issue either from your local settings/git settings or possibly your function app config. I would suggest creating a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) if this is urgent matter. If you run into any remote code building issues related to Oryx, please feel free to share more!
