### ISSUE TITLE
We found this

### ISSUE THREAD

**Issue by pacharanero** [microsoft/Oryx#1995]
https://github.com/microsoft/Oryx/blob/77c05e54a175d52b4359b616bec11abe2deeb367/tests/SampleApps/StaticWebAppsSamples/ReactClientNodeServer/app/public/randomhidden.txt#L1

**Comment by pauld-msft** [comment]
😨

**Comment by william-msft** [comment]
Wow, I'm curious how you ended up there! Fortunately, this is a non-issue since Oryx does not deploy of the `tests/SampleApps/`

**Comment by pacharanero** [comment]
Non-issue? Makes one wonder what else is in there, hidden in unaudited source code upon which our Azure deployments depend?

**Comment by pauld-msft** [comment]
If i were to guess, we pulled this sample app for testing purposes from [this repo](https://github.com/miwebst/ReactSite/blob/master/app/public/randomhidden.txt), which was forked from [here](https://github.com/JarodAerts-Microsoft/ReactSite).
