### ISSUE TITLE
Hugo (Golang SSG) does not get detected due to new hugo.toml that replaces config.toml

### ISSUE THREAD

**Issue by thomasgauvin** [microsoft/Oryx#2007]
### Bug Report

As stated in your docs https://github.com/microsoft/Oryx/blob/403870bcc7b67bb9b6f8daa4f58b5dfb5a73f84c/doc/runtimes/hugo.md?plain=1#L15 and in your code https://github.com/microsoft/Oryx/blob/403870bcc7b67bb9b6f8daa4f58b5dfb5a73f84c/build/__hugoConstants.sh#L8, Oryx searches for config.toml (or config.json, config.yaml) to determine if the project is Hugo based. Hugo has since moved to a naming convention of hugo.toml (or hugo.json, hugo.yaml) since version 0.110.0 https://gohugo.io/getting-started/configuration/#hugotoml-vs-configtoml. Creating a new Hugo project without the config.toml results in the project not being detected, not properly built, and therefore not properly deployed to SWA. 

We need to support the new versions of Hugo as well. As stated in Hugo docs, Hugo will honor both config.toml and hugo.toml, and as such we should support & detect both as well.

Please keep me updated with this issue so I can update our SWA docs 👍

**Comment by harryli0108** [comment]
Hi @thomasgauvin!
Thank you for bringing this to our attention. We'll address this issue and keep you updated!

**Comment by harryli0108** [comment]
@thomasgauvin The PR is now merged. Closing this issue now

**Comment by thomasgauvin** [comment]
Corresponding PR https://github.com/microsoft/Oryx/pull/2009
