### ISSUE TITLE
Java version detection is broken and also breaks devcontainers

### ISSUE THREAD

**Issue by dsyer** [microsoft/Oryx#2025]
Oryx runs in codespaces (unconditionally?) and if it thinks it finds a Java project it installs Java 11 (it seems) and makes it the default Java runtime. This isn't very helpful if you project requires Java 17 (or something else entirely). The only way to avoid it is to use the fairly obscure trick of switching off the Java build completely `DISABLE_JAVA_BUILD=true` in the container.

See also https://github.com/devcontainers/features/issues/580

**Comment by simonjj** [comment]
This issue seems resolved. Will be closing this issue. If this is still relevant and impacting you please open a new issue and link back to this issue for reference.
