### ISSUE TITLE
Azure Static Web App fails to build Angular 16 app

### ISSUE THREAD

**Issue by nikneem** [microsoft/Oryx#2026]
### Bug Report

On creation of a new static web app I selected an Angular preset with `src` as the source folder of my app, I left the api/functions box empty as I don't use it and `dist/url-shortner-app` for the output location.

The creation of the static web app successfully added a GH Actions workflow to my repo (a public repo found here: https://github.com/nikneem/url-shortner-app) and it ran successfully, however nothing was deployed.
The first deployment I tries was 2023-06-23 01:30 PM CEST

Reviewing the log shows the following:
```
App Directory Location: 'src' was found.
Looking for event info
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
---Oryx build logs---


Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20230501.1, Commit: 58513374525ab2977af68fc5b3c344d32858d8af, ReleaseTagName: 20230501.1

Build Operation ID: 50953f83b3ae0ef3
OS Type           : bullseye
Image Type        : jamstack

Detecting platforms...
Could not detect any platform in the source directory.
Error: Could not detect the language from repo.
```

I expected the Angular app to build and deploy, but instead an empty web page is published (https://app.tinylnk.nl/). I can clone and build the app on my dev box and then the build succeeds.

**Comment by simonjj** [comment]
We're closing this issue due to its age. If this is still impacting you please open a new issue and simply link back to this one.
