### ISSUE TITLE
Getting error on build

### ISSUE THREAD

**Issue by gregowahoo** [microsoft/Oryx#2049]
Workload installation failed: Workload manifest dependency 'Microsoft.NET.Workload.Emscripten' version '6.0.19' is lower than version '6.0.20' required by manifest 'microsoft.net.workload.mono.toolchain' [/opt/dotnet/6.0.411/sdk-manifests/6.0.400/microsoft.net.workload.mono.toolchain/WorkloadManifest.json]

**Comment by Jacko1394** [comment]
I'm getting:
Downloading and extracting 'dotnet' version '7.0.305' to '/opt/dotnet/7.0.305'...
But my global.json specifies:
"version": "7.0.306"

**Comment by simonjj** [comment]
We're closing this issue due to its age. If this is still impacting you please open a new issue and simply link back to this one.
