### ISSUE TITLE
[Request] Support for Python v3.10.12 and v3.9.17

### ISSUE THREAD

**Issue by alexander-smolyakov** [microsoft/Oryx#2095]
### System Package Request

As I can see, some recent versions of Pythons were added to the support list but reverted for some reason. Could you please provide info regarding when we could expect support for the latest versions of Python?

Related links:
- #1994;
- #1996;
- #2037;
- #2041;

- Why do you need this package? For example, are you using a language-level package which depends on this system package?

The latest Python releases contain security patches.

- Which Oryx language runtime and version are you using? For example, "Node.js v10.14" or "Python v3.7".

> N/A

- What is the name of the package in the latest stable Debian release?For examples, see <https://packages.debian.org/stable/>.

> N/A

- Do you need a specific version? If so, which and why?

> N/A

**Comment by daniv-msft** [comment]
Thanks @alexander-smolyakov for opening this issue. This dance of updates/reverts is because of an issue we discovered a couple of months back with newer Python versions where, long story short, some dependencies were missing for building while running the applications worked as expected.
We proceeded to update the runtime images with newer versions (so that they include the newer security patches), but couldn't update the build SDKs because this would have broken customers relying on older versions.

The good news however is that we should soon be able to get back the SDKs to their newer versions (i.e. for the next Python release).

**Comment by alexander-smolyakov** [comment]
Hey @daniv-msft, thanks for the info!

> The good news however is that we should soon be able to get back the SDKs to their newer versions (i.e. for the next Python release).

Greate news! Will look forward to it.

**Comment by waliMSFT** [comment]
Hi [alexander-smolyakov](https://github.com/alexander-smolyakov),

we are working on the release of the Python v3.10.12 and v3.9.17 versions. https://github.com/microsoft/Oryx/pull/2100
Hopefully, we can release them within next week if everything goes according to the plan. 
Please let us know if you have any concerns. Thanks

**Comment by waliMSFT** [comment]
Hi @alexander-smolyakov,
we have released the newer versions of python images. Please get the updated image and let us know if you face any issue. Thanks.

**Comment by alexander-smolyakov** [comment]
Hey @waliMSFT, I'm not sure about images, but when I try to build a Python app with Python v3.10.12, I get the following error:

```console
codespace ➜ / $ oryx build --property python_version="${pythonVersion}" --property packagedir="${pythonSite}" home/codespace/python
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.0.0, Commit: , ReleaseTagName: 

Build Operation ID: f9d2f08f18717390
OS Type           : focal-scm

Detecting platforms...
Error: Platform 'python' version '3.10.12' is unsupported. Supported versions: 3.10.0, 3.10.0a2, 3.10.4, 3.10.8, 3.6.12, 3.6.15, 3.7.12, 3.7.15, 3.7.9, 3.8.12, 3.8.15, 3.8.16, 3.8.6, 3.9.0, 3.9.15, 3.9.1rc1, 3.9.7, 3.10.0, 3.10.0a2, 3.10.4, 3.10.8, 3.6.12, 3.6.15, 3.7.12, 3.7.15, 3.7.9, 3.8.12, 3.8.15, 3.8.16, 3.8.6, 3.9.0, 3.9.15, 3.9.1rc1, 3.9.7
```

**Comment by alexander-smolyakov** [comment]
Hey @waliMSFT, I just wanted to ping you regarding this issue. Do you have any ETA for enabling support for the new Python SDKs?

**Comment by waliMSFT** [comment]
Hi [alexander-smolyakov](https://github.com/alexander-smolyakov),
I believe we released the sdks of the python v3.10.12 and v3.9.17 versions. After that, I closed this discussion as we did not face any issue. 
As you are facing an issue, I will investigaste it and come back to you asap. Thanks for the patience.

**Comment by alexander-smolyakov** [comment]
Hey @waliMSFT, thanks for looking into this issue once again! As I can see from the source code, the error comes from this exception:

https://github.com/microsoft/Oryx/blob/2add94bc0000042e27ce7c1959b8444cf1ea5c93/src/BuildScriptGenerator/Exceptions/UnsupportedVersionException.cs#L20-L28

It seems the following list should be updated to allow the use of new versions of Python SDK:

https://github.com/microsoft/Oryx/blob/2add94bc0000042e27ce7c1959b8444cf1ea5c93/src/BuildScriptGenerator/PythonVersions.cs#L5-L20

**Comment by waliMSFT** [comment]
Hi [alexander-smolyakov](https://github.com/alexander-smolyakov),
There was a bug related to the release of new python versions. To avoid this Oryx temporarily stopped releasing the new versions of Python.
I am working on now to resume the python release again. I will update you as soon we release the versions. Thanks for the patience.

**Comment by waliMSFT** [comment]
> Hey @waliMSFT, thanks for looking into this issue once again! As I can see from the source code, the error comes from this exception:
> 
> https://github.com/microsoft/Oryx/blob/2add94bc0000042e27ce7c1959b8444cf1ea5c93/src/BuildScriptGenerator/Exceptions/UnsupportedVersionException.cs#L20-L28
> 
> It seems the following list should be updated to allow the use of new versions of Python SDK:
> 
> https://github.com/microsoft/Oryx/blob/2add94bc0000042e27ce7c1959b8444cf1ea5c93/src/BuildScriptGenerator/PythonVersions.cs#L5-L20

Thanks for providing more info to find the cause of your issue. Appreciate it.
