### ISSUE TITLE
npm ERR! Tracker "idealTree" already exists

### ISSUE THREAD

**Issue by SamuelJanoska** [microsoft/Oryx#2101]
### Bug Report

- At what date and time did you most recently experience the problem?
Since today 17th August 2023, 7:42 CET

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Web Apps

- If your repo is publicly available please share its URL:

- What happened?
When deploying from VS Code, after "Running 'npm install'...", "npm ERR! Tracker "idealTree" already exists" appears.

- What did you expect or want to happen?
- Expected deployment to continue as usual after 'npm install'

- How can we reproduce it?

- Do you have log output? Please include between the backticks:

```

```

**Comment by simonjj** [comment]
This issue seems resolved. Will be closing this issue. If this is still relevant and impacting you please open a new issue and link back to this issue for reference.
