### ISSUE TITLE
Error deploying App to Azure container

### ISSUE THREAD

**Issue by antori82** [microsoft/Oryx#2104]
### Bug Report

- At what date and time did you most recently experience the problem?
21/08/2023

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Github Actions for Azure App container

- If your repo is publicly available please share its URL:
The repo is private

- What happened?
I connected a continuous development setup from Azure Portal and it runs as soon as a commit arrives (correct). During deployment, however, I get an error and the build fails. I do not have any empty json files in my solution.

- What did you expect or want to happen?

App deployed in the container

- How can we reproduce it?

- Do you have log output? Please include between the backticks:

```
===> BUILDING
[builder] ---> Oryx Buildpack
[builder] Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
[builder] You can report issues at https://github.com/Microsoft/Oryx/issues
[builder] 
[builder] Oryx Version: 0.2.0.0, Commit: f1d8475da4afdcc6fe71f372ee6649217814dff7, ReleaseTagName: 
[builder] 
[builder] Build Operation ID: 98f765efd7de2937
[builder] Repository Commit : 9d9447ea7fbf76707b8c40201ed7c394ee905cc0
[builder] OS Type           : buster
[builder] Image Type        : cli
[builder] 
[builder] Detecting platforms...
[builder] Detected following platforms:
[builder]   nodejs: 16.20.1
[builder]   dotnet: 7.0.9
[builder] Version '16.20.1' of platform 'nodejs' is not installed. Generating script to install it...
[builder] Version '7.0.9' of platform 'dotnet' is not installed. Generating script to install it...
[builder] Error: Oops... An unexpected error has occurred.
[builder] Error: Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path 'dependencies['@azure/abort-controller']'.
[builder]    at Newtonsoft.Json.JsonReader.ReadAsString()
[builder]    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
[builder]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
[builder]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
[builder]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
[builder]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
[builder]    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
[builder]    at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
[builder]    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
[builder]    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
[builder]    at Newtonsoft.Json.Linq.JToken.ToObject[T]()
[builder]    at Microsoft.Oryx.BuildScriptGenerator.Node.NodePlatform.GenerateBashBuildScriptSnippet(BuildScriptGeneratorContext ctx, PlatformDetectorResult detectorResult) in /usr/oryx/src/BuildScriptGenerator/Node/NodePlatform.cs:line 308
[builder]    at Microsoft.Oryx.BuildScriptGenerator.DefaultBuildScriptGenerator.GetBuildSnippets(BuildScriptGeneratorContext context, IEnumerable`1 detectionResults, Boolean runDetection, List`1 directoriesToExcludeFromCopyToIntermediateDir, List`1 directoriesToExcludeFromCopyToBuildOutputDir) in /usr/oryx/src/BuildScriptGenerator/DefaultBuildScriptGenerator.cs:line 240
[builder]    at Microsoft.Oryx.BuildScriptGenerator.DefaultBuildScriptGenerator.GenerateBashScript(BuildScriptGeneratorContext context, String& script, List`1 checkerMessageSink) in /usr/oryx/src/BuildScriptGenerator/DefaultBuildScriptGenerator.cs:line 99
[builder]    at Microsoft.Oryx.BuildScriptGeneratorCli.BuildScriptGenerator.TryGenerateScript(String& generatedScript, Exception& exception) in /usr/oryx/src/BuildScriptGeneratorCli/BuildScriptGenerator.cs:line 65
[builder]    at Microsoft.Oryx.BuildScriptGeneratorCli.BuildCommand.Execute(IServiceProvider serviceProvider, IConsole console) in /usr/oryx/src/BuildScriptGeneratorCli/Commands/BuildCommand.cs:line 182
[builder]    at Microsoft.Oryx.BuildScriptGeneratorCli.CommandBase.OnExecute(CommandLineApplication app, IConsole console) in /usr/oryx/src/BuildScriptGeneratorCli/Commands/CommandBase.cs:line 88
[builder] ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle. This may be the result of using an untrusted builder: failed with status code: 51
Error: Process completed with exit code 1.
```

**Comment by pauld-msft** [comment]
Sorry or the delay here. Looks to me like Oryx is having trouble reading your `package.json`. Could you please verify for me that your `package.json` is formatted correctly, and potentially share it here so i can investigate more? Thanks

**Comment by antori82** [comment]
Hello. I have switched to another solution but I think this is worth investigating. Here's the package.json file

{
  "name": "PragmaticQuestions",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "@azure/abort-controller": {
      "version": "1.1.0",
      "resolved": "https://registry.npmjs.org/@azure/abort-controller/-/abort-controller-1.1.0.tgz",
      "integrity": "sha512-TrRLIoSQVzfAJX9H1JeFjzAoDGcoK1IYX1UImfceTZpsyYfWr09Ss1aHW1y5TrrR3iq6RZLBwJ3E24uwPhwahw==",
      "requires": {
        "tslib": "^2.2.0"
      }
    },
    "@azure/core-auth": {
      "version": "1.5.0",
      "resolved": "https://registry.npmjs.org/@azure/core-auth/-/core-auth-1.5.0.tgz",
      "integrity": "sha512-udzoBuYG1VBoHVohDTrvKjyzel34zt77Bhp7dQntVGGD0ehVq48owENbBG8fIgkHRNUBQH5k1r0hpoMu5L8+kw==",
      "requires": {
        "@azure/abort-controller": "^1.0.0",
        "@azure/core-util": "^1.1.0",
        "tslib": "^2.2.0"
      }
    },
    "@azure/core-http": {
      "version": "3.0.2",
      "resolved": "https://registry.npmjs.org/@azure/core-http/-/core-http-3.0.2.tgz",
      "integrity": "sha512-o1wR9JrmoM0xEAa0Ue7Sp8j+uJvmqYaGoHOCT5qaVYmvgmnZDC0OvQimPA/JR3u77Sz6D1y3Xmk1y69cDU9q9A==",
      "requires": {
        "@azure/abort-controller": "^1.0.0",
        "@azure/core-auth": "^1.3.0",
        "@azure/core-tracing": "1.0.0-preview.13",
        "@azure/core-util": "^1.1.1",
        "@azure/logger": "^1.0.0",
        "@types/node-fetch": "^2.5.0",
        "@types/tunnel": "^0.0.3",
        "form-data": "^4.0.0",
        "node-fetch": "^2.6.7",
        "process": "^0.11.10",
        "tslib": "^2.2.0",
        "tunnel": "^0.0.6",
        "uuid": "^8.3.0",
        "xml2js": "^0.5.0"
      }
    },
    "@azure/core-lro": {
      "version": "2.5.4",
      "resolved": "https://registry.npmjs.org/@azure/core-lro/-/core-lro-2.5.4.tgz",
      "integrity": "sha512-3GJiMVH7/10bulzOKGrrLeG/uCBH/9VtxqaMcB9lIqAeamI/xYQSHJL/KcsLDuH+yTjYpro/u6D/MuRe4dN70Q==",
      "requires": {
        "@azure/abort-controller": "^1.0.0",
        "@azure/core-util": "^1.2.0",
        "@azure/logger": "^1.0.0",
        "tslib": "^2.2.0"
      }
    },
    "@azure/core-paging": {
      "version": "1.5.0",
      "resolved": "https://registry.npmjs.org/@azure/core-paging/-/core-paging-1.5.0.tgz",
      "integrity": "sha512-zqWdVIt+2Z+3wqxEOGzR5hXFZ8MGKK52x4vFLw8n58pR6ZfKRx3EXYTxTaYxYHc/PexPUTyimcTWFJbji9Z6Iw==",
      "requires": {
        "tslib": "^2.2.0"
      }
    },
    "@azure/core-tracing": {
      "version": "1.0.0-preview.13",
      "resolved": "https://registry.npmjs.org/@azure/core-tracing/-/core-tracing-1.0.0-preview.13.tgz",
      "integrity": "sha512-KxDlhXyMlh2Jhj2ykX6vNEU0Vou4nHr025KoSEiz7cS3BNiHNaZcdECk/DmLkEB0as5T7b/TpRcehJ5yV6NeXQ==",
      "requires": {
        "@opentelemetry/api": "^1.0.1",
        "tslib": "^2.2.0"
      }
    },
    "@azure/core-util": {
      "version": "1.4.0",
      "resolved": "https://registry.npmjs.org/@azure/core-util/-/core-util-1.4.0.tgz",
      "integrity": "sha512-eGAyJpm3skVQoLiRqm/xPa+SXi/NPDdSHMxbRAz2lSprd+Zs+qrpQGQQ2VQ3Nttu+nSZR4XoYQC71LbEI7jsig==",
      "requires": {
        "@azure/abort-controller": "^1.0.0",
        "tslib": "^2.2.0"
      }
    },
    "@azure/logger": {
      "version": "1.0.4",
      "resolved": "https://registry.npmjs.org/@azure/logger/-/logger-1.0.4.tgz",
      "integrity": "sha512-ustrPY8MryhloQj7OWGe+HrYx+aoiOxzbXTtgblbV3xwCqpzUK36phH3XNHQKj3EPonyFUuDTfR3qFhTEAuZEg==",
      "requires": {
        "tslib": "^2.2.0"
      }
    },
    "@azure/storage-blob": {
      "version": "12.15.0",
      "resolved": "https://registry.npmjs.org/@azure/storage-blob/-/storage-blob-12.15.0.tgz",
      "integrity": "sha512-e7JBKLOFi0QVJqqLzrjx1eL3je3/Ug2IQj24cTM9b85CsnnFjLGeGjJVIjbGGZaytewiCEG7r3lRwQX7fKj0/w==",
      "requires": {
        "@azure/abort-controller": "^1.0.0",
        "@azure/core-http": "^3.0.0",
        "@azure/core-lro": "^2.2.0",
        "@azure/core-paging": "^1.1.1",
        "@azure/core-tracing": "1.0.0-preview.13",
        "@azure/logger": "^1.0.0",
        "events": "^3.0.0",
        "tslib": "^2.2.0"
      }
    },
    "@opentelemetry/api": {
      "version": "1.4.1",
      "resolved": "https://registry.npmjs.org/@opentelemetry/api/-/api-1.4.1.tgz",
      "integrity": "sha512-O2yRJce1GOc6PAy3QxFM4NzFiWzvScDC1/5ihYBL6BUEVdq0XMWN01sppE+H6bBXbaFYipjwFLEWLg5PaSOThA=="
    },
    "@types/node": {
      "version": "20.5.1",
      "resolved": "https://registry.npmjs.org/@types/node/-/node-20.5.1.tgz",
      "integrity": "sha512-4tT2UrL5LBqDwoed9wZ6N3umC4Yhz3W3FloMmiiG4JwmUJWpie0c7lcnUNd4gtMKuDEO4wRVS8B6Xa0uMRsMKg=="
    },
    "@types/node-fetch": {
      "version": "2.6.4",
      "resolved": "https://registry.npmjs.org/@types/node-fetch/-/node-fetch-2.6.4.tgz",
      "integrity": "sha512-1ZX9fcN4Rvkvgv4E6PAY5WXUFWFcRWxZa3EW83UjycOB9ljJCedb2CupIP4RZMEwF/M3eTcCihbBRgwtGbg5Rg==",
      "requires": {
        "@types/node": "*",
        "form-data": "^3.0.0"
      },
      "dependencies": {
        "form-data": {
          "version": "3.0.1",
          "resolved": "https://registry.npmjs.org/form-data/-/form-data-3.0.1.tgz",
          "integrity": "sha512-RHkBKtLWUVwd7SqRIvCZMEvAMoGUp0XU+seQiZejj0COz3RI3hWP4sCv3gZWWLjJTd7rGwcsF5eKZGii0r/hbg==",
          "requires": {
            "asynckit": "^0.4.0",
            "combined-stream": "^1.0.8",
            "mime-types": "^2.1.12"
          }
        }
      }
    },
    "@types/tunnel": {
      "version": "0.0.3",
      "resolved": "https://registry.npmjs.org/@types/tunnel/-/tunnel-0.0.3.tgz",
      "integrity": "sha512-sOUTGn6h1SfQ+gbgqC364jLFBw2lnFqkgF3q0WovEHRLMrVD1sd5aufqi/aJObLekJO+Aq5z646U4Oxy6shXMA==",
      "requires": {
        "@types/node": "*"
      }
    },
    "asynckit": {
      "version": "0.4.0",
      "resolved": "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz",
      "integrity": "sha512-Oei9OH4tRh0YqU3GxhX79dM/mwVgvbZJaSNaRk+bshkj0S5cfHcgYakreBjrHwatXKbz+IoIdYLxrKim2MjW0Q=="
    },
    "combined-stream": {
      "version": "1.0.8",
      "resolved": "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.8.tgz",
      "integrity": "sha512-FQN4MRfuJeHf7cBbBMJFXhKSDq+2kAArBlmRBvcvFE5BB1HZKXtSFASDhdlz9zOYwxh8lDdnvmMOe/+5cdoEdg==",
      "requires": {
        "delayed-stream": "~1.0.0"
      }
    },
    "delayed-stream": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz",
      "integrity": "sha512-ZySD7Nf91aLB0RxL4KGrKHBXl7Eds1DAmEdcoVawXnLD7SDhpNgtuII2aAkg7a7QS41jxPSZ17p4VdGnMHk3MQ=="
    },
    "events": {
      "version": "3.3.0",
      "resolved": "https://registry.npmjs.org/events/-/events-3.3.0.tgz",
      "integrity": "sha512-mQw+2fkQbALzQ7V0MY0IqdnXNOeTtP4r0lN9z7AAawCXgqea7bDii20AYrIBrFd/Hx0M2Ocz6S111CaFkUcb0Q=="
    },
    "form-data": {
      "version": "4.0.0",
      "resolved": "https://registry.npmjs.org/form-data/-/form-data-4.0.0.tgz",
      "integrity": "sha512-ETEklSGi5t0QMZuiXoA/Q6vcnxcLQP5vdugSpuAyi6SVGi2clPPp+xgEhuMaHC+zGgn31Kd235W35f7Hykkaww==",
      "requires": {
        "asynckit": "^0.4.0",
        "combined-stream": "^1.0.8",
        "mime-types": "^2.1.12"
      }
    },
    "mime-db": {
      "version": "1.52.0",
      "resolved": "https://registry.npmjs.org/mime-db/-/mime-db-1.52.0.tgz",
      "integrity": "sha512-sPU4uV7dYlvtWJxwwxHD0PuihVNiE7TyAbQ5SWxDCB9mUYvOgroQOwYQQOKPJ8CIbE+1ETVlOoK1UC2nU3gYvg=="
    },
    "mime-types": {
      "version": "2.1.35",
      "resolved": "https://registry.npmjs.org/mime-types/-/mime-types-2.1.35.tgz",
      "integrity": "sha512-ZDY+bPm5zTTF+YpCrAU9nK0UgICYPT0QtT1NZWFv4s++TNkcgVaT0g6+4R2uI4MjQjzysHB1zxuWL50hzaeXiw==",
      "requires": {
        "mime-db": "1.52.0"
      }
    },
    "node-fetch": {
      "version": "2.6.13",
      "resolved": "https://registry.npmjs.org/node-fetch/-/node-fetch-2.6.13.tgz",
      "integrity": "sha512-StxNAxh15zr77QvvkmveSQ8uCQ4+v5FkvNTj0OESmiHu+VRi/gXArXtkWMElOsOUNLtUEvI4yS+rdtOHZTwlQA==",
      "requires": {
        "whatwg-url": "^5.0.0"
      }
    },
    "process": {
      "version": "0.11.10",
      "resolved": "https://registry.npmjs.org/process/-/process-0.11.10.tgz",
      "integrity": "sha512-cdGef/drWFoydD1JsMzuFf8100nZl+GT+yacc2bEced5f9Rjk4z+WtFUTBu9PhOi9j/jfmBPu0mMEY4wIdAF8A=="
    },
    "sax": {
      "version": "1.2.4",
      "resolved": "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz",
      "integrity": "sha512-NqVDv9TpANUjFm0N8uM5GxL36UgKi9/atZw+x7YFnQ8ckwFGKrl4xX4yWtrey3UJm5nP1kUbnYgLopqWNSRhWw=="
    },
    "tr46": {
      "version": "0.0.3",
      "resolved": "https://registry.npmjs.org/tr46/-/tr46-0.0.3.tgz",
      "integrity": "sha512-N3WMsuqV66lT30CrXNbEjx4GEwlow3v6rr4mCcv6prnfwhS01rkgyFdjPNBYd9br7LpXV1+Emh01fHnq2Gdgrw=="
    },
    "tslib": {
      "version": "2.6.2",
      "resolved": "https://registry.npmjs.org/tslib/-/tslib-2.6.2.tgz",
      "integrity": "sha512-AEYxH93jGFPn/a2iVAwW87VuUIkR1FVUKB77NwMF7nBTDkDrrT/Hpt/IrCJ0QXhW27jTBDcf5ZY7w6RiqTMw2Q=="
    },
    "tunnel": {
      "version": "0.0.6",
      "resolved": "https://registry.npmjs.org/tunnel/-/tunnel-0.0.6.tgz",
      "integrity": "sha512-1h/Lnq9yajKY2PEbBadPXj3VxsDDu844OnaAo52UVmIzIvwwtBPIuNvkjuzBlTWpfJyUbG3ez0KSBibQkj4ojg=="
    },
    "uuid": {
      "version": "8.3.2",
      "resolved": "https://registry.npmjs.org/uuid/-/uuid-8.3.2.tgz",
      "integrity": "sha512-+NYs2QeMWy+GWFOEm9xnn6HCDp0l7QBD7ml8zLUmJ+93Q5NF0NocErnwkTkXVFNiX3/fpC6afS8Dhb/gz7R7eg=="
    },
    "webidl-conversions": {
      "version": "3.0.1",
      "resolved": "https://registry.npmjs.org/webidl-conversions/-/webidl-conversions-3.0.1.tgz",
      "integrity": "sha512-2JAn3z8AR6rjK8Sm8orRC0h/bcl/DqL7tRPdGZ4I1CjdF+EaMLmYxBHyXuKL849eucPFhvBoxMsflfOb8kxaeQ=="
    },
    "whatwg-url": {
      "version": "5.0.0",
      "resolved": "https://registry.npmjs.org/whatwg-url/-/whatwg-url-5.0.0.tgz",
      "integrity": "sha512-saE57nupxk6v3HY35+jzBwYa0rKSy0XR8JSxZPwgLr7ys0IBzhGviA1/TUGJLmSVqs8pb9AnvICXEuOHLprYTw==",
      "requires": {
        "tr46": "~0.0.3",
        "webidl-conversions": "^3.0.0"
      }
    },
    "xml2js": {
      "version": "0.5.0",
      "resolved": "https://registry.npmjs.org/xml2js/-/xml2js-0.5.0.tgz",
      "integrity": "sha512-drPFnkQJik/O+uPKpqSgr22mpuFHqKdbS835iAQrUC73L2F5WkboIRd63ai/2Yg6I1jzifPFKH2NTK+cfglkIA==",
      "requires": {
        "sax": ">=0.6.0",
        "xmlbuilder": "~11.0.0"
      }
    },
    "xmlbuilder": {
      "version": "11.0.1",
      "resolved": "https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-11.0.1.tgz",
      "integrity": "sha512-fDlsI/kFEx7gLvbecc0/ohLG50fugQp8ryHzMTuW9vSa1GJ0XYWKnhsUx7oie3G98+r56aTQIUB4kht42R3JvA=="
    }
  }
}

**Comment by simonjj** [comment]
git@github.com:microsoft/Oryx.git
