### ISSUE TITLE
It's not possible to use latest dotnet version to build Oryx due to `global.json`

### ISSUE THREAD

**Issue by alexander-smolyakov** [microsoft/Oryx#2211]
### Bug Report

- At what date and time did you most recently experience the problem?

After this PR was merged - #2056 

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.

Offline use, during building Oryx from sources.

- If your repo is publicly available please share its URL:

N/A

- What happened?

During building Oryx via dotnet v7.0.402, the following error occurs: 

```Console
16.52 Requested SDK version: 7.0.306
16.52 global.json file: /opt/tmp/oryx-repo/global.json
16.52
16.52 Installed SDKs:
16.52
16.52 Install the [7.0.306] .NET SDK or update [/opt/tmp/oryx-repo/global.json] to match an installed SDK.
16.52
16.52 Learn about SDK resolution:
16.52 https://aka.ms/dotnet/sdk-not-found
```

- What did you expect or want to happen?

Previously, there was no such limitation. Could you please clarify why this file was added? And could we expect the target dotnet version in the `global.json` file to be bumped periodically?

- How can we reproduce it?

Try to build Oryx using a dotnet version higher than `7.0.306`

- Do you have log output? Please include between the backticks:

```
16.52 Requested SDK version: 7.0.306
16.52 global.json file: /opt/tmp/oryx-repo/global.json
16.52
16.52 Installed SDKs:
16.52
16.52 Install the [7.0.306] .NET SDK or update [/opt/tmp/oryx-repo/global.json] to match an installed SDK.
16.52
16.52 Learn about SDK resolution:
16.52 https://aka.ms/dotnet/sdk-not-found
```

**Comment by alexander-smolyakov** [comment]
@pauld-msft, could you please provide any update regarding this issue?

**Comment by pauld-msft** [comment]
@alexander-smolyakov - sorry for delay here, I believe this was mistakenly added

**Comment by simonjj** [comment]
This issue seems resolved. Will be closing this issue. If this is still relevant and impacting you please open a new issue and link back to this issue for reference.
