### ISSUE TITLE
Azure static web app using node 16 when node 18 was specified

### ISSUE THREAD

**Issue by DarraghOFlaherty** [microsoft/Oryx#2299]
### Bug Report

- At what date and time did you most recently experience the problem?
Currently experiencing this problem

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure static web app

- If your repo is publicly available please share its URL:
No

- What happened?
Trying to use Node 18 in Azure static web app managed functions. 

Specified node 18 in staticwebapp.config.json
![image](https://github.com/microsoft/Oryx/assets/10475290/f14b4e88-2059-40c6-840a-6b27afc54c9f)

Specified node 18 in package.json
![image](https://github.com/microsoft/Oryx/assets/10475290/936f526d-92d9-411a-b164-49ed404706bc)

Specified node 18 in ci.yaml
![image](https://github.com/microsoft/Oryx/assets/10475290/5c11c9cc-5fb7-4987-8359-2616fc2a2bfc)

Oryx is using node 16
![image](https://github.com/microsoft/Oryx/assets/10475290/7cba0ef7-6ca2-44c7-a551-7b5c0c982065)

- What did you expect or want to happen?
I want to use node 18 and expect Oryx to use node 18 if specified in config 

- How can we reproduce it?
Create free azure static web app and use the config above.

- Do you have log output? Please include between the backticks:

```

```

**Comment by noppadol78** [comment]
Please change the  **package.json**.   I used value ">=18.7.0"  instead of "^18.0.0", and it worked for me.

![image](https://github.com/microsoft/Oryx/assets/22000000/74b58a96-53a2-42ef-8200-f2edc621480d)

**Comment by DarraghOFlaherty** [comment]
@noppadol78 same issue 
![image](https://github.com/microsoft/Oryx/assets/10475290/f8ed1c2d-93c7-483c-895c-8e457712d720)

**Comment by DarraghOFlaherty** [comment]
@snehapar9 any update on this issue?

**Comment by simonjj** [comment]
This issue seems resolved. Will be closing this issue. If this is still relevant and impacting you please open a new issue and link back to this issue for reference.
