### ISSUE TITLE
Deploying an app through github actions workflow, Oryx issu.

### ISSUE THREAD

**Issue by russmann2000** [microsoft/Oryx#2391]
### Bug Report

- At what date and time did you most recently experience the problem? 3/174/2024 SEVERAL TIMES A DAY

- Where did you experience the problem? Deploying my app through github actions workflow

- If your repo is publicly available please share its URL: No

- What happened? My web app did not deploy

- What did you expect or want to happen? I expected it to deploy

- How can we reproduce it? I have no idea

- Do you have log output? Log Details

Commit ID: ab04b6f1-6cf1-4fd0-9f07-29162d59af24
5:12:22 PM
Updating submodules.
5:12:23 PM
Preparing deployment for commit id 'ab04b6f1-6'.
5:12:23 PM
PreDeployment: context.CleanOutputPath False
5:12:24 PM
PreDeployment: context.OutputPath /home/site/wwwroot
5:12:24 PM
Repository path is /tmp/zipdeploy/extracted
5:12:24 PM

Running oryx build...
[Show Logs...](https://functions.azure.com/feature/subscriptions/d5d45033-23ad-4934-8326-c1ccc3a20d74/resourcegroups/appsvc_linux_centralus_basic/providers/microsoft.web/sites/terralloading/deploymentcenter?correlationid=62095c12-b4f7&sessionid=ddce05cc5a794e52a89382f747c24b8e&frameid=9f6931ea-bba5&appsvc.react=true&elasticscaleout=true&newoverviewblades=true&appsvc.bladetype=frameblade&clientOptimizations=undefined&l=en.en-us&trustedAuthority=https%3A%2F%2Fportal.azure.com&shellVersion=undefined#5df6fa40-3792-4bc2-9665-a5bf476ddc50)
5:12:34 PM
5:12:34 PM
Generating summary of Oryx build
5:12:34 PM
Parsing the build logs
5:12:34 PM
Found 0 issue(s)
5:12:34 PM
5:12:35 PM
Build Summary :
5:12:35 PM
===============
5:12:35 PM
Errors (0)
5:12:35 PM
Warnings (0)
5:12:35 PM
5:12:35 PM
Deployment Failed. deployer = GITHUB_ZIP_DEPLOY deploymentPath = ZipDeploy. Extract zip. Remote build.

Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 20 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8dc4473d36a35f4 -p compress_node_modules=tar-gz | tee /tmp/oryx-build.log

Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx

You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20230829.1, Commit: 5bd3088141516cdbd815d62ada052654e91f0429, ReleaseTagName: 20230829.1

Build Operation ID: 161d372baf3c7ded

Repository Commit : ab04b6f1-6cf1-4fd0-9f07-29162d59af24

OS Type           : bookworm

Image Type        : githubactions

Detecting platforms...

Error: Platform 'php' version '8.0' is unsupported. Supported versions: 8.1.22, 8.2.16, 8.2.9, 8.1.22, 8.2.16, 8.2.9

Error: Platform 'php' version '8.0' is unsupported. Supported versions: 8.1.22, 8.2.16, 8.2.9, 8.1.22, 8.2.16, 8.2.9\n/bin/bash -c "oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 20 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8dc4473d36a35f4 -p compress_node_modules=tar-gz | tee /tmp/oryx-build.log ; exit $PIPESTATUS "

```

```

**Comment by apeters0n** [comment]
hey, having this issue too. what was the solution for you? i tried switching from node 20 to node 18...currently deploying again.
