### ISSUE TITLE
Non-descript error message on Python/Django build

### ISSUE THREAD

**Issue by tiloc** [Microsoft/Oryx#24]
### Bug Report

- At what date and time did you most recently experience the problem?
27-Mar-2019 13:38 Europe/Berlin

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Linux based app service

- If your repo is publicly available please share its URL:

- What happened?
I deployed through local git and the build failed with the logged message below. As it contains no useful detail, I cannot troubleshoot.

- What did you expect or want to happen?
A successful deployment of my Django app, or an error message with enough detail to troubleshoot.

- How can we reproduce it?

- Do you have log output? Please include between the backticks:

```
...
remote: Copying file: 'djangohealth/settings/databases/postgres.py'        
remote: Omitting next output lines...        
remote: Running oryx build...        
remote: Build Operation ID: |/qwnM3RiVsc=.1f8b683d_        
remote: Oops... An unexpected error has occurred.        
remote: App container will begin restart within 10 seconds.        
To https://shs-cm-demo.scm.azurewebsites.net/shs-cm-demo.git
```

**Comment by tiloc** [comment]
Turns out the issue was a missing requirements.txt file. I think that would be a candidate for a much more descriptive error message.

**Comment by gpcastro** [comment]
Hi @tiloc, thanks for taking the time and giving us feedback. I agree this is not a very good user experience for this scenario. 

The good news is that this has already been [addressed](https://github.com/Microsoft/Oryx/commit/4af8a9fa69fa11b804cc940f6e4b2d5d874fb086), and we'll output the message 

> Could not find requirements.txt; Not running pip install.

This is not in production yet though, but should be available in the next roll out for app service in the coming weeks.
