### ISSUE TITLE
Consider removing/masking account keys from logs when deploying Azure Functions for the first time

### ISSUE THREAD

**Issue by ericthomas1** [microsoft/Oryx#2476]
Hello,

When deploying an Azure Function from local to the cloud, the internally-used Storage Account Key is showed multiple times on the screen in plaintext.

Please consider masking these secrets in the deployment logs and terminal output.

Thank you

![image](https://github.com/microsoft/Oryx/assets/42788729/1aef9e56-f079-491f-ae01-19272c9e05ef)

**Comment by sarsharma** [comment]
Hi @ericthomas1 
Can you please open an issue for this here: https://github.com/Azure/azure-functions-core-tools
This deployment is being done via the func core tools
Thanks for sharing this suggestion!

**Comment by ericthomas1** [comment]
https://github.com/Azure/azure-functions-core-tools/issues/3781
