### ISSUE TITLE
Oryx fails to spot compatible dotnet runtime versions even when installed.

### ISSUE THREAD

**Issue by Mathiyarasy** [microsoft/Oryx#2541]
### Bug Report

- At what date and time did you most recently experience the problem?
- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.

   In building Devcontainer Features and Images

- If your repo is publicly available please share its URL:
https://github.com/devcontainers/features/blob/2951f0481a488ea43a6f2ea6f18a47f0a0bf744d/src/oryx/install.sh#L195

- What happened?
In Dev containers we are using Oryx as a feature to be installed in images. 
For image: ubuntu:focal installed Dotnet SDK: 8.0.101 and runtime version is 8.0.1
Then when we build and publish project  from oryx repo: BuildScriptGeneratorCli.csproj 
could not run the Published dll GenerateBuildScript.dll . Landing in runtime issue stating 
"**You must install or update .net to run the application. Frameworks are not found**"
Despite having .net sdks and runtimes installed. Dotnet is installed using install.sh script
using **8.0.101 dotnet sdk** as mentioned in document: https://github.com/microsoft/Oryx/blob/main/doc/supportedPlatformVersions.md#focal-scm 
 
    **Options Checked**:
    .
     dotnet --list-sdks : 

          Gathering SDK locations in [/usr/share/dotnet]
          Found SDK version [7.0.410]
          Found SDK version [8.0.101]
          7.0.410 [/usr/share/dotnet/sdk]
          8.0.101 [/usr/share/dotnet/sdk]

     dotnet --list-runtimes: 

        Microsoft.AspNetCore.App 7.0.20 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
        Microsoft.AspNetCore.App 8.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
        Microsoft.NETCore.App 7.0.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
        Microsoft.NETCore.App 8.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
      
      DOTNET_ROOT environment variable is set correctly
      PATH also have reference to installed dotnet location
      
     Tried higher versions of sdk ex:8.0.202 landed in same issue
    
    Could you please help us in figuring out the compatible version of .net sdk for GenerateBuildScript.dll?
    

- What did you expect or want to happen?
    **Published  GenerateBuildScript without any issues** .
    
- How can we reproduce it?
   Build and Publish the project when installed .net SDK is 8.0.101.

- Do you have log output? Please include between the backticks:

```oryx --version
You must install or update .NET to run this application.

App: /usr/local/buildscriptgen/GenerateBuildScript
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0' (x64)
.NET location: /usr/local/buildscriptgen/

No frameworks were found.

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0&arch=x64&rid=linux-x64&os=ubuntu.20.04
```

**Comment by Mathiyarasy** [comment]
It is working when publishing the dotnet project with runtime. using --self-contained true tag

**Comment by pato22santiago22-ctrl** [comment]
#2596 

> e6890d3a3afe7380d3c6b4fcdeb02ba2 Versiones del SDK compatibles: 149.0 , 150.0, 151.0, 152.0, 153.0, 154.0, 155.0, 156.0, 157.0, 158.0, 159.0, 160.0, 161.0, 162.0, 163.0, 164.0, 165.0, 166.0, 167.0, 168.0, 169.0, 170.0, 171.0, 172.0, 173.0, 174.0, 175.0 ,176.0,177.0,178.0,179.0,180.0,181.0,182.0,183.0,184.0,185.0,186.0,187.0,188.0,189.0,190.0,191.0,192.0,193.0,194.0,195.0,196.0,197.0,198.0,199.0,200.0,201.0,202.0
