### ISSUE TITLE
yarn: Cannot add package body-parser

### ISSUE THREAD

**Issue by markwolff** [microsoft/Oryx#283]
### Bug Report

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.

During deployment

- If your repo is publicly available please share its URL:

I'm using a *Linux* App Service instance with a runtime of **Node LTS**
```
mkdir test && cd test
npm init
yarn add body-parser
```

`npm install body-parser` works fine, so I can use npm as a workaround
- What happened?

`$ yarn add body-parser`

```
yarn add v1.12.3
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
error An unexpected error occurred: "EBADF: bad file descriptor, copyfile '/usr/local/share/.cache/yarn/v4/npm-body-parser-1.19.0-96b2709e57c9c4e09a6fd66a8fd979844f69f08a/node_modules/body-parser/
HISTORY.md' -> '/home/demo/node_modules/body-parser/HISTORY.md'".
info If you think this is a bug, please open a bug report with the information provided in "/home/demo/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by gpcastro** [comment]
We do have a cache for yarn packages in our image; looks like it might be corrupted. We'll take a look

**Comment by arroyc** [comment]
As discussed, instead of running those commands `mkdir test && cd test
npm init
yarn add body-parser` in runtime container (ssh-ing takes you to runtime container), try running those commands as preinstall script in package.json. make sure for npm init or yarn init you use -y :)
