### ISSUE TITLE
Node.js: App Insights is not injected with "Node LTS" framework

### ISSUE THREAD

**Issue by markwolff** [microsoft/Oryx#287]
### Bug Report

- At what date and time did you most recently experience the problem?
7/17/2019

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Web Apps

- If your repo is publicly available please share its URL:
Any app will do, I tested with a basic hello world app.
https://github.com/Azure-Samples/nodejs-docs-hello-world

- What happened?
App Insights is not automatically injected when setting `APPINSIGHTS_INSTRUMENTATIONKEY` application setting via App Services Portal UI and runtime stack is selected as "Node LTS". Selecting a numbered version, "Node 10.14", "Node 8.12", etc will inject it properly.

- What did you expect or want to happen?
App Insight should be injected if Node LTS is selected

- How can we reproduce it?
1. Create new App Service Web App with runtime stack Node LTS, region West Central US
2. Set app config setting env var `APPINSIGHTS_INSTRUMENTATIONKEY` to be any non empty string
3. `git clone https://github.com/Azure-Samples/nodejs-docs-hello-world`
4. Deploy app

See #79

**Comment by gpcastro** [comment]
Thanks for reaching out, we'll investigate.

**Comment by arroyc** [comment]
this seems to be an issue/bug with appservice's kudulite implementation, we will track it till it gets solved by appservice team.

**Comment by markwolff** [comment]
I believe this is resolved now since we moved to runtime image and always set `NODE_OPTIONS`? Closing the issue, but reopen if it wasn't actually resolved.
