### ISSUE TITLE
npm run build failing with permission error

### ISSUE THREAD

**Issue by praveendath92** [microsoft/Oryx#309]
### Bug Report

- At what date and time did you most recently experience the problem?
It started this noon and can't deploy new builds since. 

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Web Apps

- If your repo is publicly available please share its URL:
https://github.com/praveendath92/whos-in-bot

- What happened?
I'm getting a permission in the `npm run build` step. Complaining about permission issue when copying a file from src to dist. That has always been the setup for the codebase.  

- What did you expect or want to happen?
I had the master branch set to auto deploy. I would expect the deploy to just work fine like it did for the commits before it. 

- How can we reproduce it?
Strangely enough, there were no code changes in the commits where it stopped working.
Auto deployed for commit - https://github.com/praveendath92/whos-in-bot/commit/f7d6a22dc2fb7a053ce2d4abdae39c899a6b495f
Stopped working from this commit - https://github.com/praveendath92/whos-in-bot/commit/42f998e9e54e04b3f5920f751787b8b978173dc6

- Do you have log output? Please include between the backticks:

```
Command: oryx build /home/site/wwwroot -o /home/site/wwwroot -l nodejs --language-version 10.10 -i /tmp/8d719d2efb0f68d -p compress_node_modules=tar-gz
Build orchestrated by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version       : 0.2.20190521.9, Commit: c2ee5d8bcba3b398c8390fbe2939d888dbf94352
Build Operation ID : |O168x+goWrs=.985aad5f_
Repository Commit  : c3ccac738855209b77c8f20701c0099ea3a51af8

Using intermediate directory '/tmp/8d719d2efb0f68d'.

Copying files to the intermediate directory...
Done in 1 sec(s).

Source directory     : /tmp/8d719d2efb0f68d
Destination directory: /home/site/wwwroot


Running 'npm install'...


> core-js@2.6.9 postinstall /tmp/8d719d2efb0f68d/node_modules/core-js
> node scripts/postinstall || echo "ignore"

[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m

[96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
[96m>[94m https://opencollective.com/core-js [0m
[96m>[94m https://www.patreon.com/zloirock [0m

[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m

npm WARN whos-in-bot@1.1.0 license should be a valid SPDX license expression
added 254 packages from 367 contributors and audited 890311 packages in 23.605s

found 0 vulnerabilities


Running 'npm run build'...


> whos-in-bot@1.1.0 build /tmp/8d719d2efb0f68d
> npm run build-sass && npm run build-ts && npm run lint && npm run copy-static-assets


> whos-in-bot@1.1.0 build-sass /tmp/8d719d2efb0f68d
sh: 1: node-sass: Permission denied
> node-sass src/public/css/main.scss dist/public/css/main.css
npm ERR! file sh

npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! whos-in-bot@1.1.0 build-sass: `node-sass src/public/css/main.scss dist/public/css/main.css`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the whos-in-bot@1.1.0 build-sass script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2019-08-05T18_30_39_001Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whos-in-bot@1.1.0 build: `npm run build-sass && npm run build-ts && npm run lint && npm run copy-static-assets`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the whos-in-bot@1.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2019-08-05T18_30_39_130Z-debug.log
npm WARN whos-in-bot@1.1.0 license should be a valid SPDX license expression\n\nsh: 1: node-sass: Permission denied\nnpm ERR! file sh\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno ENOENT\nnpm ERR! syscall spawn\nnpm ERR! whos-in-bot@1.1.0 build-sass: `node-sass src/public/css/main.scss dist/public/css/main.css`\nnpm ERR! spawn ENOENT\nnpm ERR! \nnpm ERR! Failed at the whos-in-bot@1.1.0 build-sass script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/.npm/_logs/2019-08-05T18_30_39_001Z-debug.log\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! whos-in-bot@1.1.0 build: `npm run build-sass && npm run build-ts && npm run lint && npm run copy-static-assets`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the whos-in-bot@1.1.0 build script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/.npm/_logs/2019-08-05T18_30_39_130Z-debug.log\n/opt/Kudu/Scripts/starter.sh oryx build /home/site/wwwroot -o /home/site/wwwroot -l nodejs --language-version 10.10 -i /tmp/8d719d2efb0f68d -p compress_node_modules=tar-gz
```

**Comment by praveendath92** [comment]
I just created a new Web app to see if the same commit deploys fine, and it did! Just to be clear, the issue still persists on my main Web app.

```
Command: oryx build /home/site/wwwroot -o /home/site/wwwroot -l nodejs --language-version 10.10 -i /tmp/8d719f75a2087f6 -p compress_node_modules=tar-gz
Build orchestrated by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version       : 0.2.20190521.9, Commit: c2ee5d8bcba3b398c8390fbe2939d888dbf94352
Build Operation ID : |kU5VlHg9wZ8=.a62d6955_
Repository Commit  : c3ccac738855209b77c8f20701c0099ea3a51af8

Using intermediate directory '/tmp/8d719f75a2087f6'.

Copying files to the intermediate directory...
Done in 1 sec(s).

Source directory     : /tmp/8d719f75a2087f6
Destination directory: /home/site/wwwroot


Running 'npm install'...


> node-sass@4.12.0 install /tmp/8d719f75a2087f6/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/linux-x64-64_binding.node
Download complete
Binary saved to /tmp/8d719f75a2087f6/node_modules/node-sass/vendor/linux-x64-64/binding.node
Caching binary to /home/.npm/node-sass/4.12.0/linux-x64-64_binding.node

> core-js@2.6.9 postinstall /tmp/8d719f75a2087f6/node_modules/core-js
> node scripts/postinstall || echo "ignore"

[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m

[96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
[96m>[94m https://opencollective.com/core-js [0m
[96m>[94m https://www.patreon.com/zloirock [0m

[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m


> mongodb-memory-server@5.1.10 postinstall /tmp/8d719f75a2087f6/node_modules/mongodb-memory-server
> node ./postinstall.js

mongodb-memory-server: checking MongoDB binaries cache...
Downloading MongoDB 4.0.3: 0 % (0mb / 79.4mb)
Downloading MongoDB 4.0.3: 66.4 % (52.7mb / 79.4mb)
mongodb-memory-server: binary path is /tmp/8d719f75a2087f6/node_modules/.cache/mongodb-memory-server/mongodb-binaries/4.0.3/mongod
> node-sass@4.12.0 postinstall /tmp/8d719f75a2087f6/node_modules/node-sass
> node scripts/build.js

Binary found at /tmp/8d719f75a2087f6/node_modules/node-sass/vendor/linux-x64-64/binding.node
Testing binary
Binary is fine

> nodemon@1.19.1 postinstall /tmp/8d719f75a2087f6/node_modules/nodemon
> node bin/postinstall || exit 0

[32mLove nodemon? You can now support the project via the open collective:[22m[39m
 > [96m[1mhttps://opencollective.com/nodemon/donate[0m

npm WARN whos-in-bot@1.1.0 license should be a valid SPDX license expression
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
added 1467 packages from 1826 contributors and audited 890311 packages in 123.05s

found 0 vulnerabilities


Running 'npm run build'...


> whos-in-bot@1.1.0 build /tmp/8d719f75a2087f6
> npm run build-sass && npm run build-ts && npm run lint && npm run copy-static-assets


> whos-in-bot@1.1.0 build-sass /tmp/8d719f75a2087f6
> node-sass src/public/css/main.scss dist/public/css/main.css

Rendering Complete, saving .css file...
Wrote CSS to /tmp/8d719f75a2087f6/dist/public/css/main.css

> whos-in-bot@1.1.0 build-ts /tmp/8d719f75a2087f6
> tsc


> whos-in-bot@1.1.0 lint /tmp/8d719f75a2087f6
> tsc --noEmit && eslint "*/**/*.{js,ts}" --quiet --fix


> whos-in-bot@1.1.0 copy-static-assets /tmp/8d719f75a2087f6
> ts-node copyStaticAssets.ts


Zipping existing node_modules folder ...
Done in 40 sec(s).

Copying files to destination directory '/home/site/wwwroot'...
Done in 4 sec(s).

Removing existing manifest file
Creating a manifest file...
Manifest file created.

Done in 233 sec(s).
```

**Comment by kichalla** [comment]
Thanks for trying out again and giving us the details. Feels hard to guess what could be the cause behind the 'Permission denied' error. Wondering if any other process is still holding onto the file('dist/public/css/main.css') being updated but that feels unlikely.
BTW the commits of the build and the one you say it stopped working do not match:

![image](https://user-images.githubusercontent.com/6559784/62500489-8cb50c00-b79b-11e9-83c3-7da4c2fe58e4.png)

**Comment by praveendath92** [comment]
Appreciate a quick response. Yes, they do not match. The commit in the logs is the current HEAD. The commit I reported as stopped working is when it stopped working. There were a couple of commits to master since then

**Comment by praveendath92** [comment]
@kichalla  Is there a way for me to do a fresh redeploy on the current web app? I'm guessing that would work again

**Comment by kichalla** [comment]
> @kichalla Is there a way for me to do a fresh redeploy on the current web app? I'm guessing that would work again

@sanchitmehta or @patricklee2  can probably answer that question

**Comment by praveendath92** [comment]
> @kichalla Is there a way for me to do a fresh redeploy on the current web app? I'm guessing that would work again

I deleted the app and created a new one with the same name (in a different region). Recreating with the same name in the same region gave the same error - I think it reused the container

Probably not the best way to go about it but works for my minimal config setup

**Comment by arroyc** [comment]
@praveendath92 are you still seeing this error or shall this considered to be resolved?

**Comment by praveendath92** [comment]
I would say worked around for now but yes, closing it since there's no reliable repro

**Comment by praveendath92** [comment]
I'm getting this again 😞 

I may have a repro this time. I had make the repo private and deployment center could't get the repo anymore. To fixed that I used "disconnect" in the deployment center and added the repo again. Now the error is back 😢

**Comment by praveendath92** [comment]
My repo is based on https://github.com/microsoft/TypeScript-Node-Starter I will try and make a public fork with minimal setup and see if I can get a reliable repro.

I love how easy it is to setup auto deployment using Oryx, will do my best to help in anyway I can

**Comment by arroyc** [comment]
@praveendath92 .. I am looking at your logs and have some questions for you ... are you doing local git push to deploy the webapp? the microsoft repo for typescript-node-starter seems to have a mongo db portion, how are you setting it up in cloud? because locally it will work but when you deploy in cloud(appservice) you need to set up a cloud mongo db (mongo lab?) and you will get authentication details (username-password) which you need to use in your project as env variables? So there are couple of extra steps needed. Can you bullet point all your deployment steps? And also it will be really helpful if ou can make your repo public or  something very similar to your current app with which we can dig deeper. Once again thanks for using Oryx and valuable feedbacks, it will help us to be a better product.

**Comment by praveendath92** [comment]
No, I set up a connection to the Github repo using Azure Deployment center. I was hoping that way any changes to master will be auto deployed. It was working fine - except it ran into this issue after a few successful deployments.

@arroyc thanks for help so far. I'm waiting for approvals to make the repo public. However, I can add you as a collaborator since you are already a member of Microsoft org. 

Just to be clear, the deployment did work a few times. Even without those config values, the deployment should work fine. We should also be able to see the home page without those configs set (in case of my app, not for the typescript-node-starter repo though)

**Comment by arroyc** [comment]
@praveendath92 , please let me know once it's ready

**Comment by praveendath92** [comment]
My bad, you already have access to the repo. I assumed you would have got an email about it. About 4 days ago

**Comment by praveendath92** [comment]
It looks a deployment is being built in a temporary folder without sufficient permissions

Log when deployment was successful
```
> whos-in-bot@1.1.0 build-sass /tmp/8d71f825cc27e37
> node-sass src/public/css/main.scss dist/public/css/main.css

Rendering Complete, saving .css file...
Wrote CSS to /tmp/8d71f825cc27e37/dist/public/css/main.css
```

Log when failure
```
> whos-in-bot@1.1.0 build-sass /tmp/8d71f7d2252dcb6
> node-sass src/public/css/main.scss dist/public/css/main.css
sh: 1: node-sass: Permission denied
```

**Comment by arroyc** [comment]
was able to access https://github.com/microsoft/whos-in-bot.git … will work on to see if I can repro

**Comment by praveendath92** [comment]
Thanks to a lot of patience from @arroyc, we found out that this is being caused by the app setting, `NODE_ENV` set to `production`

**Comment by praveendath92** [comment]
Specific to my project setup. Turns out, my `npm build` is configured to run `build-sass` and other tasks that require devDependencies. However, as I'm setting `NODE_ENV` to `production`, those aren't available!
