### ISSUE TITLE
php missing mcrypt in php 5.6

### ISSUE THREAD

**Issue by patricklee2** [microsoft/Oryx#336]
### Bug Report
see https://icm.ad.msft.net/imp/v3/incidents/details/142218082/home

- At what date and time did you most recently experience the problem?

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.

- If your repo is publicly available please share its URL:

- What happened?

- What did you expect or want to happen?

- How can we reproduce it?

- Do you have log output? Please include between the backticks:

```

```

**Comment by arroyc** [comment]
thanks for reporting this, it should be a problem for PHP 7.0 as well. Also we need to know what to be done from PHP 7.2 onward

**Comment by arroyc** [comment]
Necessary changes have been checked in  .... #345
