### ISSUE TITLE
Oryx Won't Deploy Dotnet Core Website When Deploying With Bin Files

### ISSUE THREAD

**Issue by capraynor** [microsoft/Oryx#367]
### Bug Report

- At what date and time did you most recently experience the problem?
Sept. 26th, 2019 - Sept. 27th, 2019

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.

Azure Web Apps. On Linux. 

- If your repo is publicly available please share its URL:

Deploy source: 
https://github.com/capraynor/oryx-bug-dotnet-core-2.1-cannot-deploy

- What happened?
When deploying dotnet core 2.1 web application, Oryx won't generate start script, and shows an error: 

**Could not detect the language from repo.**

- What did you expect or want to happen?
Dotnet core 2.1 should be deployed. 

- How can we reproduce it?
I have provided the binary repo, please directly deploy that repo, and you will find that problem.

- Do you have log output? Please include between the backticks:

```
C:\repositories\Test Core Application\Test Core Application\bin\Release\netcoreapp2.1\publish\testdeploy>git push
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 12 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 294 bytes | 294.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Deploy Async
remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id 'd26afee490'.
remote: Running oryx build...
remote: Build orchestrated by Microsoft Oryx, https://github.com/Microsoft/Oryx
remote: You can report issues at https://github.com/Microsoft/Oryx/issues
remote:
remote: Oryx Version      : 0.2.20190820.2, Commit: 450179ca187b5b9080175bb25f5b22466c63614b
remote: Build Operation ID: |ubqgvgMlEAs=.26fe5cc5_
remote: Repository Commit : d26afee490726150920c99365b031ba85b5e7486
remote:
remote: Error: Could not detect the language from repo.
remote: App container will begin restart within 10 seconds.
```

**Comment by capraynor** [comment]
More information provide in here. 
I found a line of code https://github.com/microsoft/Oryx/blob/87aa7bdb10168c735f8a214b2b8a19665e605ec7/src/BuildScriptGenerator/DotNetCore/DotnetCoreLanguageDetector.cs#L49

The code is basically like this: 
```
If cannot find the framework name from *csproj* file, It will throw an error. 
```

What if I just upload the binary files? Binary files don't have a csproj file, and this method will return null.

**Comment by capraynor** [comment]
More information provide in here

https://github.com/microsoft/Oryx/blob/697269ef7f8e5821b8d6a1b42f40b120ba3877f0/src/BuildScriptGenerator/DefaultBuildScriptGenerator.cs#L111

Obviously when fixing this bug, we need to consider investigate this todo.

**Comment by capraynor** [comment]
Looking forward for your reply!

**Comment by kichalla** [comment]
@capraynor Thanks for the information!

> What if I just upload the binary files? Binary files don't have a csproj file, and this method will return null.

Since you are just deploying the binary files basically you should not be going through the 'build' process as you can imagine we do not have information to do the build (i.e .csproj etc.)

How are you deploying your app? if you are zip deploying your app, then you need to set `SCM_DO_BUILD_DURING_DEPLOYMENT=false` to disable running the 'build' step.

**Comment by capraynor** [comment]
> @capraynor Thanks for the information!
> 
> > What if I just upload the binary files? Binary files don't have a csproj file, and this method will return null.
> 
> Since you are just deploying the binary files basically you should not be going through the 'build' process as you can imagine we do not have information to do the build (i.e .csproj etc.)
> 
> How are you deploying your app? if you are zip deploying your app, then you need to set `SCM_DO_BUILD_DURING_DEPLOYMENT=false` to disable running the 'build' step.

AMAZING!!!!!!!!


I think that this is your spec / manual
https://github.com/projectkudu/kudu/wiki/Configurable-settings
I'm I correct?

**Comment by kichalla** [comment]
> I think that this is your spec / manual
https://github.com/projectkudu/kudu/wiki/Configurable-settings
I'm I correct?

It is not exactly my team's but my partner team's but yeah you would get additional information about Azure App Service from the above link that you shared.

**Comment by kichalla** [comment]
Hopefully what I mentioned above resolved your issue, so closing it.
