### ISSUE TITLE
zip deployment fails with rsync error: some files/attrs were not transferred

### ISSUE THREAD

**Issue by mchudinov** [microsoft/Oryx#373]
### Bug Report

- We experience problem 03th of October 2019 (03.10.2019) at 10.16 CET

- We experience the problem at Azure Application Service Environment, Linux, Node.js 10.14

- Zip deployment fails 
with the following 
```
- rsync: rename "/home/site/wwwroot/.error1.log.W6GtMz" -> "error1.log": Permission denied (13)
- rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
```
application does not start after this error.

Our application uses error.log file for logging. It looks like the error.log file is somehow locked and that's the reason deployment fails. We have the following code in our Node.js application.
```
loggers.add('mainLog', {
    transports: [
        new transports.File({
            level: 'info',
            filename: './error.log',
            handleExceptions: true,
            maxsize: 524880,
            maxFiles: 5
        }),
        new transports.Console({
            level: 'debug'
        })
    ],
    exitOnError: false
});
```

- zip deployment should work as expected no matter files are in use by the previous deployed application.

Here is the deployemnt log.
some lines about coping files are skipped in log for brevity.
```
 - Updating submodules.
 - Preparing deployment for commit id '3d28831339'.
 - Oryx-Build: Running kudu sync...
 - Command: kudusync -v 50 -f /tmp/zipdeploy/extracted -t /home/site/wwwroot -n /home/site/deployments/3d288313391f44dd8b61e2be2935d86a/manifest -p /opt/Kudu/Scripts/firstDeploymentManifest -i ".git;.hg;.deployment;.deploy.sh"
 - Kudu sync from: '/tmp/zipdeploy/extracted' to: '/home/site/wwwroot'
 - Copying file: 'build.txt'
...
  - Copying file: 'lib/util/azureKeyVault.config.js'
  - Omitting next output lines...
 - Running oryx build...
 - Command: oryx build /home/site/wwwroot -o /home/site/wwwroot --platform nodejs --platform-version 10.14 -i /tmp/8d7428bfdffa780 -p compress_node_modules=tar-gz
 - Build orchestrated by Microsoft Oryx, https://github.com/Microsoft/Oryx
 - You can report issues at https://github.com/Microsoft/Oryx/issues
 - Oryx Version      : 0.2.20190820.2, Commit: 450179ca187b5b9080175bb25f5b22466c63614b
 - Build Operation ID: |Mfx6TBBAdkE=.70b50578_
 - Repository Commit : 3d288313391f44dd8b61e2be2935d86a
 - Warning: An outdated version of node was detected (10.14.2). Consider updating.\nVersions supported by Oryx: https://github.com/microsoft/Oryx
 - Using intermediate directory '/tmp/8d7428bfdffa780'.
 - Copying files to the intermediate directory...
 - Done in 4 sec(s).
 - Source directory     : /tmp/8d7428bfdffa780
 - Destination directory: /home/site/wwwroot
 - Running 'npm install'...
 - > nodemon@1.18.2 postinstall /tmp/8d7428bfdffa780/node_modules/nodemon
 - > node bin/postinstall || exit 0
 - [32mLove nodemon? You can now support the project via the open collective:[22m[39m
 -  > [96m[1mhttps://opencollective.com/nodemon/donate[0m
 - added 882 packages from 708 contributors and audited 20474 packages in 57.752s
 - found 422 vulnerabilities (62 low, 14 moderate, 345 high, 1 critical)
 - npm WARN fmd-client@1.2.0 No description
 -   run `npm audit fix` to fix them, or `npm audit` for details
 - npm WARN fmd-client@1.2.0 No repository field.
2019-09-26T14:16:41.339Z - npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
2019-09-26T14:16:41.351Z - npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
- Running 'npm run build'...
- > fmd-client@1.2.0 build /tmp/8d7428bfdffa780
- > tsc
- Zipping existing node_modules folder ...
- Done in 7 sec(s).
- Copying files to destination directory '/home/site/wwwroot'...
 - rsync: rename "/home/site/wwwroot/.error1.log.W6GtMz" -> "error1.log": Permission denied (13)
 - rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
 - npm WARN fmd-client@1.2.0 No description\nnpm WARN fmd-client@1.2.0 No repository field.\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})\n\nrsync: rename "/home/site/wwwroot/.error1.log.W6GtMz" -> "error1.log": Permission denied (13)\nrsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]\n/opt/Kudu/Scripts/starter.sh oryx build /home/site/wwwroot -o /home/site/wwwroot --platform nodejs --platform-version 10.14 -i /tmp/8d7428bfdffa780 -p compress_node_modules=tar-gz
 - App container will begin restart within 10 seconds.

```

**Comment by kichalla** [comment]
Thanks for reporting @mchudinov . We will investigate this issue.

**Comment by kichalla** [comment]
@mchudinov How many instances of your app is running in App? and also curious why the file name is `error1.log` instead of `error.log` as in your settings?

**Comment by mchudinov** [comment]
We are running 5 slots and at least 2 instances. Inside ASE.
I'm not sure why error1.log instead of error.log. I will ask developers about it.

**Comment by kichalla** [comment]
Thanks @mchudinov . Given your scenario, we recommend you to use a different directory under `/home` for writing out log files(or any files which you would like to persist) to prevent from files being locked during deployment. You can try this out and let us know if you still face any issues.

**Comment by mchudinov** [comment]
Thank you! We are going to try this.

**Comment by charlbury** [comment]
I am seeing a similar problem deploying code via github to an Azure Python Linux Web App.

I was originally storing the log files in a subdirectory when I first received this error. I have now moved them to the app root and still see the error. The deployment fails and restarts the previous deployment of the web app.

This is a flask app using python logging that is configured to create the log files. It uses the rotating file handler to rotate log files.

Python Flask Logging Initialisation:

    file_handler = RotatingFileHandler('flaskapp.log', maxBytes=10240,backupCount=10)
    file_handler.setFormatter(logging.Formatter('%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'))
    file_handler.setLevel(logging.INFO)
    app.logger.addHandler(file_handler)
    app.logger.setLevel(logging.INFO)

Deployment log file errors:

    2019-11-06T19:27:17.081Z - Copying files to destination directory '/home/site/wwwroot'...
    2019-11-06T19:27:21.462Z - rsync: rename "/home/site/wwwroot/.flaskapp.log.Tp419X" -> "flaskapp.log": Permission denied (13)
    2019-11-06T19:27:21.486Z - rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
    2019-11-06T19:27:23.316Z - ERROR: astroid 2.3.0 has requirement typed-ast>=1.3.0; implementation_name == "cpython" and python_version >= "3.7" and python_version < "3.8", but you'll have typed-ast 1.2.0 which is incompatible.\nrsync: rename "/home/site/wwwroot/.flaskapp.log.Tp419X" -> "flaskapp.log": Permission denied (13)\nrsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]\n/opt/Kudu/Scripts/starter.sh oryx build /home/site/wwwroot -o /home/site/wwwroot --platform python --platform-version 3.7 -i /tmp/8d762ef163af84c -p compress_virtualenv=tar-gz -p virtualenv_name=antenv --log-file /tmp/test.log

**Comment by kichalla** [comment]
@charlbury Thanks for the details. As a workaround can you see if you would still see the issue if you the logs files were written outside the `/home/site/wwwroot` folder?

**Comment by charlbury** [comment]
@kichalla I was able to modify the log file location to be outside the `/home/site/wwwroot` folder.

    if not os.path.exists('/home/applogs'):
        os.mkdir('/home/applogs')
    file_handler = RotatingFileHandler('/home/applogs/flaskapp.log', maxBytes=10240,backupCount=10)

This does now allow me to deploy without errors. Is this expected behaviour? Is this how I should have had it setup from the start?

**Comment by kichalla** [comment]
> This does now allow me to deploy without errors. Is this expected behaviour? Is this how I should have had it setup from the start?

@charlbury  What error are you seeing? 

@sanchitmehta Is there a written guidance for users regarding where to put the logs files to so that they are persistent? if yes, could you please share the link to it.

**Comment by charlbury** [comment]
@kichalla 

> This does now allow me to deploy without errors

I no longer see any errors now that my log files are located outside of the `wwwroot` folder.

**Comment by kichalla** [comment]
Great, thanks for confirming!

**Comment by HayHiTee** [comment]
I am getting the same errors even though I had removed the file and ignored from local repo

**Comment by charlbury** [comment]
@kichalla is the answer here that log files cannot reside within the `/home/site/wwwroot` folder?

**Comment by Ryan-McPartlan** [comment]
This issue also affected me today and was resolved by the solution mentioned by @charlbury on November 7th

**Comment by davjfish** [comment]
We are running into a similar issue when trying to deploy a python linux web app (django) to a web app service through a release pipeline, i.e. zip deployment.

When starting with a clean sandbox / deployment slot, the zip deployment is successful. Upon any subsequent release, deployment fails with the following output:

```
Copying files to destination directory '/home/site/wwwroot'...
rsync: rename "/home/site/wwwroot/.azure_oauth_settings.yml.t9QlcB" -> "azure_oauth_settings.yml": No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
rsync: rename "/home/site/wwwroot/.azure_oauth_settings.yml.t9QlcB" -> "azure_oauth_settings.yml": No such file or directory (2)\nrsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.7 -i /tmp/8d7b47b2c4d1ee1 -p compress_virtualenv=tar-gz -p virtualenv_name=antenv --log-file /tmp/build-debug.log 
##[error]Failed to deploy web package to App Service.
##[error]Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
##[warning]Error: Failed to update deployment history. Error: Bad Request (CODE: 400)
``` 

The file that it is complaining about `azure_oauth_settings.yml` is not a part of the git repo. It is being build as a part of the CI pipeline and sent to the release pipeline as an artifact. 

Here are some things that I find confusing: 
1) this is not the only file that is in the artifact but that is not part of the git repo. 
2) after the first deployment, if I SSH to the web app sandbox, I am able to interact with the above-mentioned file, e.g., `cat /home/site/wwwroot/azure_oauth_settings.yml`. After a failed release, if I try to repeat the above command, I get the same error that we are getting above in the rsync operation, even though the file seems to be present in the directory:

![image](https://user-images.githubusercontent.com/34521117/74746801-583b0600-523c-11ea-9db5-d78beec6a42b.png)


I also noticed a warning about a failure to update deployment history. I am not sure if this would be related to the problem or not.

**Comment by arroyc** [comment]
@kichalla  can this issue be solved? is it still a bug?

**Comment by arroyc** [comment]
Please feel free to create a new issue and link this old one there if you are still having some problems with rsync. Otherwise I'm closing this item here. Thank you al l!

**Comment by phdowling** [comment]
I got this issue out of the blue yesterday on a python web app, with no apparently build-relevant code changes made. One of the python libraries .so files are not successfully being copied (rename error). Anything I can try?
