### ISSUE TITLE
Directory did not sync caps change.

### ISSUE THREAD

**Issue by Callius** [microsoft/Oryx#378]
### Bug Report

- At what date and time did you most recently experience the problem?
03/10/2019 (d/m/y)

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Web Apps

- If your repo is publicly available please share its URL:
*x*

- What happened?
A directory from the previous project "Api" was not renamed to the directory from the new project "api". This is important in my case (Python/Django).

- What did you expect or want to happen?
Expected directory "Api" to be renamed to "api".

- How can we reproduce it?
Assuming it can be reproduced by deploying a directory, renaming the directory, and re-deploying the directory.

- Do you have log output? Please include between the backticks:
*Unsure where it find this*

**Comment by kichalla** [comment]
@Callius Thanks for the details. Can you please confirm if you indeed see the renamed folder when you visit `/home/site/repository`? I say this because renaming folders or files and git does not work as you usually expect to.

For example, `git status` does not show that the file has actually been renamed:

```
my@mydesktop MINGW64 /c/temp/investigations/foo (master)
$ ls -l
total 1
-rw-r--r-- 1 my 1049089 3 Oct  4 13:18 hi.txt

my@mydesktop MINGW64 /c/temp/investigations/foo (master)
$ mv hi.txt Hi.txt

my@mydesktop MINGW64 /c/temp/investigations/foo (master)
$ git status
On branch master
nothing to commit, working tree clean

my@mydesktop MINGW64 /c/temp/investigations/foo (master)
$ ls -l
total 1
-rw-r--r-- 1 my 1049089 3 Oct  4 13:18 Hi.txt

```

**Comment by Callius** [comment]
The "/home/site/repository" appears to be empty ("ls" command reveals nothing).

This could be my bad. I rebuild my api from scratch using a fresh repo. The old repo had a folder named "Api", and the new repo has a folder named "api". I assumed since it was a new repo, it would perform a clean build.

I will clear the App Service before changing repos next time :)

Thanks for looking at this. If it is a bug or unintended behavior, let me know.

**Comment by kichalla** [comment]
Closing this issue as it is not related to Oryx. Feel free to re-open this issue with more details.
