### ISSUE TITLE
pip install not installing in virtualenv

### ISSUE THREAD

**Issue by sdementen** [microsoft/Oryx#392]
### Bug Report

- issue observed in the last days (~ 1 week max)

- issue when deploying a django app on an Azure Webapp on Linux ASE 

- repo not publicly avail

- pip install is started
```
remote: Deploy Async        
remote: Updating branch 'master'.        
remote: ...        
remote: Updating submodules.        
remote: Preparing deployment for commit id '630fc6557b'.        
remote: Oryx-Build: Running kudu sync...        
remote: Kudu sync from: '/home/site/repository' to: '/home/site/wwwroot'        
remote: Copying file: 'requirements.txt'        
[...]
remote: Oryx Version      : 0.2.20191004.5, Commit: 95ca7f51b147da7b085922507f46106c664ae2a3        
remote: Build Operation ID: |spk7pv0hdiQ=.c8b03ef6_        
remote: Repository Commit : 630fc6557bbd1d3ac6030b5e490ddc8a8716c0b8        
remote: 
remote: Using intermediate directory '/tmp/8d7520f736f0b89'.        
remote: 
remote: Copying files to the intermediate directory...        
remote: .............................................................................................................................        
remote: Done in 130 sec(s).        
remote: 
remote: Source directory     : /tmp/8d7520f736f0b89        
remote: Destination directory: /home/site/wwwroot        
remote: 
remote: Python Version: /opt/python/3.7.4/bin/python3        
remote: Python Virtual Environment: antenv        
remote: Creating virtual environment ...        
remote: Activating virtual environment ...        
remote: 
remote: Upgrading pip...        
remote: Collecting pip        
remote:   Using cached https://files.pythonhosted.org/packages/4a/08/6ca123073af4ebc4c5488a5bc8a010ac57aa39ce4d3c8a931ad504de4185/pip-19.3-py2.py3-none-any.whl        
remote: Installing collected packages: pip        
remote:   Found existing installation: pip 19.0.3        
remote:     Uninstalling pip-19.0.3:        
remote:       Successfully uninstalled pip-19.0.3        
remote: Successfully installed pip-19.3        
remote: Done in 4 sec(s).        
remote: Running pip install...        
remote: [08:06:46+0000] Collecting adal==1.2.1        
remote: [08:06:46+0000]   Downloading https://files.pythonhosted.org/packages/00/72/53dce9e4f5d6c1aa57b8d408cb34dff1969ecbf10ab7e678f32c5e0e2397/adal-1.2.1-py2.py3-none-any.whl (52kB)        
[...]
remote: [08:08:01+0000] Successfully installed [...]
remote: Done running pip install.        
remote: 
remote: Compressing existing 'antenv' folder...        
remote: ........        
remote: Done in 13 sec(s).        
```
- when running `/home/site/wwwroot/antenv/bin/pip freeze`, I would expect to see new package from the requirements.txt to be installed yet they are not anymore installed (1 week ago it was OK) => I need to ssh and run `/home/site/wwwroot/antenv/bin/pip install -r ...` myself to have them installed (otherwise my django app that needs these packages fails miserably...)

- redeploy an app by changing the requirements.txt and check if the package has been really installed in the virtual env

**Comment by sdementen** [comment]
This bug is getting really painful.
Oryx is reinstalling the whole requirements.txt at every deploy not even in the virtual env (/home/site/wwwroot/antenv) ==> eating 5 minutes at each deploy!!!

**Comment by kichalla** [comment]
@sanchitmehta

**Comment by kichalla** [comment]
@sdementen The virtual environment `antenv` should be extracted to the root folder, for example: `/antenv`

**Comment by kichalla** [comment]
@sdementen Adding to my earlier comment, I did a deployment just now from VS Code and following is the content from the runtime container of my app.

```
root@dff5b9cb8db6:/home/site/wwwroot# ls -l
total 4522
drwxrwxrwx 2 nobody nogroup       0 Oct 18 18:13 __pycache__
-rwxrwxrwx 1 nobody nogroup 4624995 Oct 18 18:12 antenv.tar.gz
-rwxrwxrwx 1 nobody nogroup     166 Sep 26 20:20 app.py
-rwxrwxrwx 1 nobody nogroup     103 Oct 18 18:12 oryx-manifest.toml
-rwxrwxrwx 1 nobody nogroup      95 Apr  9  2019 requirements.txt
root@dff5b9cb8db6:/home/site/wwwroot#
root@dff5b9cb8db6:/home/site/wwwroot#
root@dff5b9cb8db6:/home/site/wwwroot# ls -l /antenv
total 16
drwxr-xr-x 2 1001 1005 4096 Oct 18 18:12 bin
drwxr-xr-x 2 1001 1005 4096 Oct 18 18:12 include
drwxr-xr-x 3 1001 1005 4096 Oct 18 18:12 lib
lrwxrwxrwx 1 1001 1005    3 Oct 18 18:12 lib64 -> lib
-rw-r--r-- 1 1001 1005   82 Oct 18 18:12 pyvenv.cfg
root@dff5b9cb8db6:/home/site/wwwroot#
root@dff5b9cb8db6:/home/site/wwwroot# cat /opt/startup/startup.sh
#!/bin/sh

# Enter the source directory to make sure the script runs where the user expects
cd /home/site/wwwroot

if [ -z "$HOST" ]; then
                export HOST=0.0.0.0
fi

export PORT=8000

echo Found virtual environment .tar.gz archive.
extractionCommand="tar -xzf antenv.tar.gz -C /antenv"
echo Removing existing virtual environment directory '/antenv'...
rm -fr /antenv
mkdir -p /antenv
echo Extracting to directory '/antenv'...
$extractionCommand
PYTHON_VERSION=$(python -c "import sys; print(str(sys.version_info.major) + '.' + str(sys.version_info.minor))")
echo Using packages from virtual environment 'antenv' located at '/antenv'.
export PYTHONPATH=$PYTHONPATH:"/antenv/lib/python$PYTHON_VERSION/site-packages"
echo "Updated PYTHONPATH to '$PYTHONPATH'"
GUNICORN_CMD_ARGS="--timeout 600 --access-logfile '-' --error-logfile '-' --bind=0.0.0.0:8000 --chdir=/home/site/wwwroot" gunicorn app:app
```

**Comment by sdementen** [comment]
When pushing via git on the webapp repo (local git deployment) the first time, it created the virtual env in the /home/site/wwwroot/antenv folder. At each deploy, it was pip installing the requirements in this folder too, installing only new packages.
Since a couple of days, it is not the case anymore. The pip install command is running and install all packages each time (before, only non previously installed packages were installed, now, much longer as all packages are installed) and moreover they are not installed in /home/site/wwwroot/antenv. Reading your post, I understand they are now installed in /antenv, correct? And is it normal all packages are reinstalled at each deploy (git push)?
When was this change done ?

**Comment by sdementen** [comment]
I just read issue https://github.com/microsoft/Oryx/issues/172 and settings BUILD_FLAGS to Off restore the old behavior.
Would you know if the default value of this flag could have changed recently ?

**Comment by kichalla** [comment]
Thanks @sdementen...my guess is this behavior is a recent regression. It would help if you could share the original behavior that you saw. I am specifically looking for build output that you see for 2 successive deployments. I think I know the issue but just want to confirm again.

**Comment by sdementen** [comment]
Original behavior was identical to the one I get now with BUILD_FLAGS=Off

**Comment by kichalla** [comment]
Thanks @sdementen We identified the issue and discussed with our partner team (Azure App Service). The fix would be from them and should roll out in next release. I will keep this issue open and will post any updates.

**Comment by gpcastro** [comment]
This should be fixed now. Let us know if you still see this issue.
