### ISSUE TITLE
Oryx base image prevents installation of OS tools that use python, can break apt

### ISSUE THREAD

**Issue by Chuxel** [microsoft/Oryx#404]
### Bug Report

Currently it looks like the base Oryx Docker image moves or removes the default Python installation that comes with Ubuntu.  This causes two problems:

1. Installing a package that adds a command like `apt-add-repository` breaks apt-get entirely since it relies on Python in this location.
2. A number of tools expect the OS python location to be present.

These two points make it difficult to install additional tools and runtimes in the container.

**Repros:**

1. Open a terminal and run

    `docker run -it --rm mcr.microsoft.com/oryx/build bash`

2. Now from inside the container, run:

   `apt-get update && apt-get install lsb-release`

3. Run `lsb_release` (with an _ this time). You will see:

    `bash: /usr/bin/lsb_release: /usr/bin/python3: bad interpreter: No such file or directory`

4. Now, break apt-get entirely by running:

     `apt-get install software-properties-common`

5. Run `apt-get install nano` to see it failing.

The problem is you'll see packages like these commonly listed in installation instructions for installing tools in external repository sources using Debian's package manager [including the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest) (lsb-release).  

There are workarounds to avoid these commands if you know what you are doing, but it makes it difficult to use the image for development.

Symbolic links could be used, but it would be better to leave the python install from the OS where it was initially placed if possible to avoid these issues.

//cc: @derekbekoe

**Comment by kichalla** [comment]
Thanks @Chuxel We removed the default installations of Python to make sure by default Oryx installed python versions are picked up (since they are later in the PATH environment variable) but did not anticipate the issue you mentioned above (even though we had a slight apprehension before making our change)...which version of Oryx build did you try this on?

**Comment by Chuxel** [comment]
@kichalla I am working with @derekbekoe on the VS Online team. The image that service uses as a base is `mcr.microsoft.com/oryx/build:20191028.3`

**Comment by Chuxel** [comment]
@kichalla Quick ping here - with Visual Studio Online now being live, we're starting to hear about this from customers.

**Comment by arroyc** [comment]
is this issue still something to be worked upon?

**Comment by arroyc** [comment]
please feel free to reopen this issue or create a new one.

**Comment by Chuxel** [comment]
We have worked around this issue by copying the content back as follows:

```Dockerfile
# Copy back python into the Oryx image from builddeps.
FROM buildpack-deps:stretch@sha256:d095aae2ecefdc786823e02b2cb0abc62b432202a49abd716c12cce37aee702b as builddeps
COPY --from=builddeps /usr/bin/py* /usr/bin/
```

https://github.com/microsoft/vscode-dev-containers/blob/master/containers/vsonline-linux/.devcontainer/Dockerfile

It's not ideal, but it gets the job done.
