### ISSUE TITLE
Deployment center build fails

### ISSUE THREAD

**Issue by MashB** [microsoft/Oryx#405]
I have configured Deployment center with Bitbucket repository, Whenever I checkin the build triggers and it successfully deploys, but on the Dashboard/UI, I see its failed. 

I'm deploying Nodejs application to App service. Selected Node stack environment.

Issue:
Successful builds are shown as failed build.

Expected:
Fix the status

**Comment by kichalla** [comment]
@MashB This is not the repo to file the issue that you are mentioning. 

@sanchitmehta is this something handled by your team?

**Comment by sanchitmehta** [comment]
@MashB did you also check the scm status <scm url>/newui -> status bar. Does it show it as failed, if yes could you share your deployment logs from the same place?

**Comment by MashB** [comment]
HI @sanchitmehta , yes scm URL shows failed status but logs look ok. 

Log:

[{
	"log_time": "2019-10-31T11:47:04.8464182Z",
	"id": "2731d776-b001-4d0d-9c48-74da96a78a85",
	"message": "Updating submodules.",
	"type": 0,
	"details_url": null
},
{
	"log_time": "2019-10-31T11:47:04.9130773Z",
	"id": "3cef64d7-e129-4207-9712-32aaee814b70",
	"message": "Preparing deployment for commit id 'ef8d2e4c72'.",
	"type": 0,
	"details_url": null
},
{
	"log_time": "2019-10-31T11:47:05.2777734Z",
	"id": "eed59ae7-8d0c-487b-b5fa-41d5cfe550c9",
	"message": "Oryx-Build: Running kudu sync...",
	"type": 0,
	"details_url": "https://dgcontentservice.scm.azurewebsites.net/api/deployments/ef8d2e4c721f8ccdee2917b9f51a7623f6de38d0/log/eed59ae7-8d0c-487b-b5fa-41d5cfe550c9"
},
{
	"log_time": "2019-10-31T11:47:10.6008646Z",
	"id": "8e3e30b0-d4e3-4ed6-99b4-76e4068d497d",
	"message": "Running oryx build...",
	"type": 2,
	"details_url": "https://dgcontentservice.scm.azurewebsites.net/api/deployments/ef8d2e4c721f8ccdee2917b9f51a7623f6de38d0/log/8e3e30b0-d4e3-4ed6-99b4-76e4068d497d"
},
{
	"log_time": "2019-10-31T11:47:53.3499553Z",
	"id": "c24c1245-c86e-4053-a319-5ff349033adc",
	"message": "App container will begin restart within 10 seconds.",
	"type": 0,
	"details_url": null
}]

**Comment by arroyc** [comment]
@MashB  is it still an issue?

**Comment by arroyc** [comment]
feel free to reopen this issue or create a new one
