### ISSUE TITLE
Flatten layout of dotnet versions to allow dotnet to pick versions.

### ISSUE THREAD

**Issue by srivatsn** [microsoft/Oryx#425]
I was looking at how the different versions are installed in the Oryx build image and it looks like this:

/opt/dotnet/sdks/1.1/dotnet
/opt/dotnet/sdks/1.1/sdks
/opt/dotnet/sdks/1.1/sdks/1.1.x
/opt/dotnet/sdks/1.1/2.1/dotnet
/opt/dotnet/sdks/1.1/sdks
/opt/dotnet/sdks/1.1/sdks/2.1.x

Is there a particular reason that there are two levels of versions? The dotnet executable is a multiplexer itself and it will look in the sdks folder underneath it and pick the latest version to use. However because all these different version first level versions have their own dotnet that dotnet is not aware of any of the other versions on the machine. So far example, if I run `dotnet –list-runtimes` it only outputs 2.1 instead of showing all the other installed runtimes.

Is it possible to switch to something like:

/opt/dotnet/dotnet
/opt/dotnet/sdks
/opt/dotnet/sdks/<all versions and let dotnet be the multiplexer instead of benv>? 

@kichalla

**Comment by arroyc** [comment]
currently we have defaulted to dotnet 2.1, but we can change it to any of the installed dotnet core versions. Can you please explain the scenario or user story behind this ask?

**Comment by srivatsn** [comment]
We use this image as the base for VS Online and so when someone creates an environment they think it only has 2.1 installed. The problem is not the default version but the fact that dotnet that's on the path doesnt know about all the other versions that are installed.
