### ISSUE TITLE
'project' setting in .deployment file ignored

### ISSUE THREAD

**Issue by JoakimFFCG** [microsoft/Oryx#428]
I use a Azure Linux Web App configured to deploy from a GitHub repository.
My repository contains a .deployment file with the following content:
```
[config]
project = htdocs
```

However, when I deploy using Oryx (as now is the default) the .deployment file, or at least the 'project' setting, seems to be ignored, since /home/site/wwwroot/ contains the htdocs directory (not its content).

If I set ENABLE_ORYX_BUILD to false, using the legacy Kudu build instead, everything works as expected. So this appears to be a problem with Oryx.

The issue is similar to #56. However, I am positive that my .deployment file has LF line endings. I even checked within the App Service using the SSH interface:
```
> file /home/site/repository/.deployment
/home/site/repository/.deployment: ASCII text
```

I tested this today (2019-11-11).

**Comment by arroyc** [comment]
hi @JoakimFFCG .. thanks for reporting .. can you please tell little more about your app? Also it will be nice if you can provide us a sample app to repro the issue. what's the content in .deployment file and what is the purpose to set the project = htdocs .. I may be able to give you workaround

**Comment by JoakimFFCG** [comment]
I made a [sample app](https://github.com/JoakimFFCG/azure-deployment-test) for you.

The .deployment file contains only what I told you it contains, nothing more. See the sample app.

The purpose is to separate the actual app files (those in htdocs) from those I don't want to deploy, but still would like to have in the repository. Like, for example, the readme file in the sample app.

My workaround for now is to set ENABLE_ORYX_BUILD to false.

**Comment by arroyc** [comment]
Thanks for explanation .. here are two things that I can say based on my understanding …

1. If you only want to deploy source code (actual app files) you can filter them via .gitignore. Now you may ask I still want to modify the readme (for example) time to time and upload that to actual git repo, but I don't want that updated readme to be the part of azure app service (hope I'm understanding your requirement correctly here). In that case you can maintain a structure like this ..

> Project public (remote github)
    - .git
    - .gitignore
    - Project folder (remote azure app service)
        - .git
        - .gitignore
        - (folders and files)
based on the above structure you should be able to filter subfolder's  .gitignore, .git files to be pushed to public git repo by modifying root .git and .gitignore.

2. If you don't like the first approach, you can upoad your own site config (for example xyz.conf) in azure app service and override apache's default configuration. You can look at this [article](https://medium.com/linode-cube/how-to-host-multiple-websites-with-apache-2-4-d648d23bcd6a)

Apache is installed at /etc/apache2.

Let me know if the above solutions works for you.

**Comment by kichalla** [comment]
@arroyc Regarding the approach no. 2, we would not be installing the PHP packages though  right, for example if the `composer.json` is present under a sub-folder 'oryx build' would not be able install the packages?

**Comment by arroyc** [comment]
@kichalla that is correct, we currently look for composer.json in the root and if it is in subfolder it won't be able to install the packages, they need to be manually installed in run image.

**Comment by JoakimFFCG** [comment]
1. 
I assume you mean a file structure like this?
> Project public (remote github)
> \- .git
> \- .gitignore
> \- Project folder (remote azure app service)
> -- .git
> -- .gitignore
> -- (folders and files)

From what I understood I will then need to use [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) and have two git repositories.
That should technically work since the deployed repo will only contain the app files and won't be located in a subfolder.
However, I don't think we want to have an extra repository. (This is an app for work, so I don't have the only say in this.)

2.
I tried this approach. The problem is that the apache config files are reset during every deploy.
I tried to solve that by adding a post deploy script, but when I deploy it fails with the following messages:
```
/home/site/wwwroot/deployment/postbuild.sh: line 3: /etc/apache2/sites-available/site.conf: No such file or directory
/home/site/wwwroot/deployment/postbuild.sh: line 27: /etc/apache2/ports.conf: No such file or directory
/home/site/wwwroot/deployment/postbuild.sh: line 40: a2ensite: command not found
apache2: unrecognized service
```
Running the script manually after a deploy works fine. But I obviously don't want to do that every deployment.
(If you want to see the script it's [here](https://github.com/JoakimFFCG/azure-deployment-test/blob/deployment-script/deployment/postbuild.sh).)

3. Yeah, that won't work for me.

---
You don't support / plan to support the 'project' setting in .deployment? The answer in #56 says you do, but maybe that has changed since then?

**Comment by arroyc** [comment]
@JoakimFFCG … oryx build currently supports project environment variable only for dotnetcore, we are planning to support it for all other platforms (e.g. php) in future, but for now if you want to use this variable I guess the right approach would be setting ENABLE_ORYX_BUILD to false which you are already doing. As per #56 azure app service do support it but not via oryx build rather via their legacy/old build

**Comment by JoakimFFCG** [comment]
@arroyc thanks for your help and suggestions for alternative approaches. I will use the ENABLE_ORYX_BUILD = false setting for now.

You might want to add some information about this in your documentation.

I currently don't use VS code and it sounds like that solution avoids the GitHub repo, which I don't want. I want to make sure that the deployed code is the same as in the repository.
Anyway, as I said, I'm going with ENABLE_ORYX_BUILD = false for now.

**Comment by arroyc** [comment]
@JoakimFFCG .. closing this issue for now .. as we have some workaround .. feel free to file a new one
