### ISSUE TITLE
Oryx Version

### ISSUE THREAD

**Issue by pooja-sketch** [microsoft/Oryx#441]
An outdated version of node was detected (10.1.0). Consider updating.\nVersions supported by Oryx: https://github.com/microsoft/Oryx

**Comment by pooja-sketch** [comment]
npm WARN tar ENOENT: no such file or directory, open '/tmp/8d77a4945a1b417/node_modules/.staging/readable-stream-c6b87ed5/package.json

**Comment by arroyc** [comment]
Can you elaborate what is the issue you are facing .. what is your scenario?
