### ISSUE TITLE
antenv is compressed

### ISSUE THREAD

**Issue by HayHiTee** [microsoft/Oryx#444]
I cannot use antenv to run some commands in the azure ssh anymore. I use python and django, sometimes i would want to run some manage.py commands on file. Is there any alternative?

**Comment by kichalla** [comment]
@HayHiTee Could you please give more details on your scenario? Can you use a custom startup file or command as described here? https://docs.microsoft.com/en-us/azure/python/tutorial-deploy-app-service-on-linux-04#create-a-startup-file

**Comment by arroyc** [comment]
@HayHiTee , following up here with the issue you reported earlier, any luck?

**Comment by HayHiTee** [comment]
@arroyc and @kichalla This issue is still persisting. I want to run some custom commands. Before I used kudu ssh home/wwwroot/site/antenv where the python environment and app packages were residing. Right now antenv is compressed to antenv.tar.gz such that I cannot run python from this environment to run app commands. Commands like migrations, custom managements command created for the apps itself.

**Comment by arroyc** [comment]
@kichalla  is that pre-run script feature solving this issue?

**Comment by arroyc** [comment]
@HayHiTee, did you try using post-build script?

**Comment by arroyc** [comment]
@HayHiTee  I'm assuming the issue is resolved, if not please create a new one and link this issue there. I'm closing this issue
