### ISSUE TITLE
Issue pulling image

### ISSUE THREAD

**Issue by garycr** [microsoft/Oryx#447]
W: Conflicting distribution: https://packages.microsoft.com/debian/9/prod stretch InRelease (expected stretch but got stable)
W: Conflicting distribution: https://packages.microsoft.com/debian/9/prod stretch InRelease (expected stretch but got stable)
E: Failed to fetch https://packages.microsoft.com/debian/9/prod/dists/stretch/main/binary-amd64/Packages.bz2  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:156065 [weak]
    - SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b
    - SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0
    - SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak]
    - MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak]
   Hashes of received file:
    - SHA512:a18b4df496d00477e52cf62e01c9f6c9534926ad0e3bf17f94fc28fc9bd91d5ee5e906b460477e2c1b280a5757a067937c9b2724bd6c72066e982a19306f28b8
    - SHA256:94e637dd6df186bbed5a19f2e7bdc2dcc8f7bb0feb2f1eaf93f05b45dd322cc4
    - SHA1:fb9e80e17952a577030e9266737b23269c8d878b [weak]
    - MD5Sum:4360374f4ec05159ef14908c0dbf4116 [weak]
    - Filesize:68668 [weak]
   Last modification reported: Fri, 13 Dec 2019 01:35:23 +0000
   Release file created at: Thu, 12 Dec 2019 19:59:19 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by kichalla** [comment]
@garycr It is unclear which image you are referring to?

**Comment by arroyc** [comment]
@garycr , if this for php, I am also seeing this same error since last night

**Comment by arroyc** [comment]
seems like many are affected .... https://github.com/dotnet/core/issues/3598

**Comment by arroyc** [comment]
@garycr  .. give it a try now .. looks like the  issue has been resolved
