### ISSUE TITLE
Oryx is using the wrong node.js version

### ISSUE THREAD

**Issue by rlataguerra** [microsoft/Oryx#452]
Oryx is using the wrong node.js version while it is properly set in the package.json under engines.

Oryx build output :
<img width="359" alt="Capture d’écran 2019-12-23 à 13 26 32" src="https://user-images.githubusercontent.com/2256150/71358039-e752d700-2587-11ea-96f5-01f5fb89eafd.png">

package.json file :
<img width="423" alt="Capture d’écran 2019-12-23 à 13 26 05" src="https://user-images.githubusercontent.com/2256150/71358040-e752d700-2587-11ea-83d6-0a823222922e.png">

**Comment by arroyc** [comment]
@rlataguerra  thanks for reporting .. we will look into this, in the mean time can you please also share the region where you faced this issue.

**Comment by rlataguerra** [comment]
no, problem, Im using western europe region 👍

**Comment by arroyc** [comment]
@rlataguerra .. I tried to repro .. worked for me … 
`remote: Running oryx build...
remote: Build orchestrated by Microsoft Oryx, https://github.com/Microsoft/Oryx
remote: You can report issues at https://github.com/Microsoft/Oryx/issues
remote:
remote: Oryx Version      : 0.2.20191105.2, Commit: 67e159d71419415435cb5d10c05a0f0758ee8809, ReleaseTagName: 20191105.2
remote: Build Operation ID: |nCDbhckxfQQ=.99cad3a0_
remote: Repository Commit : 5aef171604b5bf8e679c796b3132a525fe597d4d
remote:
remote: Using intermediate directory '/tmp/8d78e19b14d6361'.
remote:
remote: Copying files to the intermediate directory...
remote: Done in 0 sec(s).
remote:
remote: Source directory     : /tmp/8d78e19b14d6361
remote: Destination directory: /home/site/wwwroot
remote:
remote:
remote: Using Node version:
remote: v12.13.0
remote:
remote: Using Npm version:
remote: 6.12.0`
can you share the general settings of your app where it shows node version?
For example, 
<your resource group name> > <your app service> > Configuration > General Settings
![image](https://user-images.githubusercontent.com/16231002/71629577-264de180-2bb3-11ea-974e-327ad7b5ec28.png)

**Comment by rlataguerra** [comment]
here are my general settings :
<img width="501" alt="Capture d’écran 2020-01-01 à 13 14 21" src="https://user-images.githubusercontent.com/2256150/71641240-b6b22200-2c98-11ea-8ddc-b457a6a3f2e4.png">

**Comment by arroyc** [comment]
I was able to repro this issue … I will update you once the patch is there in prod, in the mean time I suggest you to use specific LTS as workaround

**Comment by arroyc** [comment]
update: As per node maintenance schedule this is what I see
@rlataguerra this is what I see in node's official page

Release | Status | Codename | Initial Release | Active LTS Start | Maintenance LTS Start | End-of-life
-- | -- | -- | -- | -- | -- | --
v10 | Active LTS | Dubnium | 2018-04-24 | 2018-10-30 | 2020-04-01 | 2021-04-30
v12 | Active LTS | Erbium | 2019-04-23 | 2019-10-21 | 2020-10-21 | 2022-04-30

Based on my discussion with app service team they are planning to move LTS to 12, but not sure if it will happen during end of lifetime of 10 or sometimes before. @sanchitmehta  can confirm the deadline. So as for now I am planning to close this issue unless you have something.

**Comment by arroyc** [comment]
@rlataguerra, this should have been fixed now, please reopen this bug if you still see this issue or create a new issue.
