### ISSUE TITLE
Add support for libgomp.so in linux image for Python

### ISSUE THREAD

**Issue by eafpres** [microsoft/Oryx#465]
### System Package Request

I'm building models in Python and some of them use xgboost, as in this example of a Flask app:
```
import xgboost as xgb
import pandas as pd
from flask import Flask
from flask import request, jsonify
import numpy as np
import pickle as p
#
app = Flask(name)
modelfile = 'prodmodelxgboost.pkl'
model = p.load(open(modelfile, 'rb'))
#
@app.route('/api/', methods=['POST'])
   def makecalc():
   data = request.get_json()
   data = pd.DataFrame.from_dict(data, orient = &#39;index&#39;).transpose()
   data = np.reshape(data, (1, -1))
   prediction = np.array2string(model.predict(data))
   return jsonify(prediction)
```

Model is trained using xgboost, and that is needed at runtime

Oryx language runtime and version "Python v3.7".

Name of the package in the latest stable Debian release?
There does not appear to be a Debian release, however the problem appears actually to be with a lower level library libgomp.so (see below)

In Python, the xgboost version is 0.90, but any recent should be OK

To further explain the situation, if the following is requirements.txt for the above code:

```
click==6.7
Flask==1.0.2
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.0
Werkzeug==0.14.1
pandas==0.25.1
numpy==1.16.5
pickleshare==0.7.5
xgboost==0.90
```
then the following errors occur on deploy during the build on Azure Web Apps Linux:

```
2020-01-14T22:17:00.663067008Z xgboost.core.XGBoostError: XGBoost Library (libxgboost.so) could not be loaded.
2020-01-14T22:17:00.663070609Z Likely causes:
2020-01-14T22:17:00.663074109Z * OpenMP runtime is not installed (vcomp140.dll or libgomp-1.dll for Windows, libgomp.so for UNIX-like OSes)
2020-01-14T22:17:00.663077709Z * You are running 32-bit Python on a 64-bit OS
```

Thus, the problem appears to be missing libgomp.so

Thanks for any support!

**Comment by kichalla** [comment]
@eafpres Were you able to resolve this issue? does this issue get resolved if you run the commands `apt-get update; apt-get install libgomp1` in the runtime container. I suppose you are seeing this issue when running the app and not when building the app, right?

**Comment by gpcastro** [comment]
@eafpres you can read more about custom commands [here](https://docs.microsoft.com/en-us/azure/app-service/containers/how-to-configure-python#customize-startup-command).
You should be able to run `apt install ... && <your app startup command>` using this feature.
Let us know if that doesn't work.

**Comment by eafpres** [comment]
Could one of you clarify how to do the sudo apt- on the container?  I'm using the standard Azure CLI deploy, so I'm not building the container.

**Comment by eafpres** [comment]
I suppose you are seeing this issue when running the app and not when building the app, right?

Actually what happens is on deploy, when it tries to build the container, it fails.  However, the linux instance is there, so it might be feasible to then do the install and try to start it, but I'm not familiar with how to do this.  I can experiment and try to get something to work, but at present I've restructured my models so I can convert them to pure python functions and deploy that.  Not the most elegant but it works for simple cases.

**Comment by nitin-barthwal** [comment]
I am still facing this issue. 

Any tips how to get past over it?
