### ISSUE TITLE
Best practice for customising Oryx/Python image

### ISSUE THREAD

**Issue by jahead** [microsoft/Oryx#470]
Hey guys, 

Just looking for extra information. 
Due to some constraints with an upstream vendor, we require some extra system packages and that Django is installed **before** pip install is ran. We all can agree that it is sub-optimal, but it's out of our control.

At first, I thought we could use the ``PRE_BUILD_SCRIPT_PATH`` and ``POST_BUILD_SCRIPT_PATH`` but it seems to lack the elevated system privileges required to do any ``apt-get`` commands. It also seems to be unable to install Django, because as I understand it, the virtual env is set up after the pre-build script.  

Can you guys, confirm that I'm correct in my understanding and that is no way we could see this working using the default Oryx python image?

If so, we would still like to stay as closely aligned to Oryx as possible, so when the vendor fixes their issues we can move back to a more standard approach. We are wondering what is the best possible way for customizing the deployment that is based on Oryx? 

We don't mind then launching it onto App Service Linux (container) for the short term.

**Comment by gpcastro** [comment]
Hi @jahead, the Oryx build doesn't run with elevated privileges, so if you need that during the build here's a few things that you can try:
- You can use our new GitHub action: https://github.com/marketplace/actions/app-service-web-app-build-action which allows you to specify the `PRE_BUILD_SCRIPT_PATH` and run with root privilege. 
- As you've mentioned, revert to App Service for Containers; you can still run Oryx that way, producing an image identical to the one you use today, but you deploy the final image instead of the code. We can add some documentation about how to do that if you're interested
- While you still depend on this vendor code, you can use a custom startup command (which _does_ run with elevated privileges) to build your vendor code. The downside of that is your app start up might be slower if this built process takes too long, and there might be concurrency issues if multiple instances of the app are starting at the same time.

**Comment by jahead** [comment]
Hey @gpcastro thanks for your information. 

> You can use our new GitHub action: https://github.com/marketplace/actions/app-service-web-app-build-action which allows you to specify the PRE_BUILD_SCRIPT_PATH and run with root privilege.

We use bitbucket, but maybe we could test this on Github. I'll look into seeing if this is a possibility

> As you've mentioned, revert to App Service for Containers; you can still run Oryx that way, producing an image identical to the one you use today, but you deploy the final image instead of the code. We can add some documentation about how to do that if you're interested

This is our current thinking, we plan to use the `--os-requirements` to include the missing system packages. We have an issue where Django needs to be bootstrapped into the venv before `pip install ` has run, we have the commitment from the vendor to fix this requirement, so it might be best we wait for them, instead of doing anything extreme in Oryx. 

We see another issue, is that some manual commands need to run before 'manage.py migrate' otherwise migrate will error. I see that there is `DISABLE_COLLECTSTATIC` but there isn't one to disable auto migrate. I would like to not have support our own startup script, is there any undocumented environment variable we could use?  

> While you still depend on this vendor code, you can use a custom startup command (which does run with elevated privileges) to build your vendor code. The downside of that is your app start up might be slower if this built process takes too long, and there might be concurrency issues if multiple instances of the app are starting at the same time.

Are you saying that we build the python code in the runtime image instead of the build image? I mean that could work. Maybe we use this as a last resort.

**Comment by arroyc** [comment]
@jahead  .. did you try using custom startup command .. did that solve your problem?

**Comment by jahead** [comment]
@arroyc 
Hey, We actually ended up using that route!
```
RUN cd /app && oryx -appPath /app -userStartupCommand scripts/entry.sh  create-script
ENTRYPOINT ["/app/run.sh"]
```
We actually got in touch with MS, and you guys have been helping us. And our vendor moved to wheels which solved our bootstrapping needs. 

We ended up leveraging pipelines, and are able to get something up and running! 
all this just for `libcairo2 libcrack2 libgdk-pixbuf2.0-0 libpango1.0-0 shared-mime-info libxslt1.1`

Currently, we are `collectstatic` and migrating on runtime, which can take longer than 30 mins. 

Otherwise, it all working, just takes two boots to get stable :/

Thanks for your help, we basically followed your advice

**Comment by arroyc** [comment]
Thank you @jahead  … in that case I'm closing this issue .. please feel free to open a new one for performance (longer startup time) if you want.

**Comment by jamwil** [comment]
> Hi @jahead, the Oryx build doesn't run with elevated privileges, so if you need that during the build here's a few things that you can try:
> 
> * You can use our new GitHub action: https://github.com/marketplace/actions/app-service-web-app-build-action which allows you to specify the `PRE_BUILD_SCRIPT_PATH` and run with root privilege.

Hi @gpcastro,

Where might one specify this variable within the workflow?
