### ISSUE TITLE
Logging the contents of the Requirements.txt

### ISSUE THREAD

**Issue by FinVamp1** [microsoft/Oryx#482]
### Feature Request

For Azure Functions app deployment sometimes the customers mention that they have a missing module after deployment.

E.G

Question: What deployment exception are you experiencing?
Answer: Exception: ModuleNotFoundError: No module named 'azure.cosmos'

It would help for these scenarios if we can log the output for Oryx of what it has found in the requirements.txt.

**Comment by arroyc** [comment]
@FinVamp1 we do log output of the build, can you please explain a bit more of your scenario?

**Comment by arroyc** [comment]
@FinVamp1  ..  please feel free to reach us back if you need help on this
