### ISSUE TITLE
Circular reference is generated in `/node_modules`

### ISSUE THREAD

**Issue by hihorika** [microsoft/Oryx#499]
### Bug Report

- At what date and time did you most recently experience the problem?
-> The time when App Service on Linux (Node.js blessed image) starts more than 3 times

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
-> I think that it happens on only App Service on Linux (Node.js blessed image), because the issue is caused by `/opt/startup/startup.sh` for Node.js application.

- If your repo is publicly available please share its URL:
-> This issue can be reproduced by simple node.js application.

- What happened?
-> A symlink which links to `/node_modules` is generated in the directory itself,
i.e. the symlink is circular reference, `/node_modules/node_modules` -> `/node_modules`

![image](https://user-images.githubusercontent.com/4566555/75098792-e7119f00-55fd-11ea-9ef8-b82bfff73773.png)

This causes unexpected behavior on applications which follow all symlink.
e.g. Angular application which is set `preserveSymlink` to `true`.

And this causes `Maximum call stack size exceeded` error on executing `npm ls`.
![image](https://user-images.githubusercontent.com/37284286/75099004-0c9fa800-5600-11ea-9945-a6c2374c4c3e.png)

- What did you expect or want to happen?
-> Any circular reference was never generated.

- How can we reproduce it?
-> It can be reproduced by repeating following steps 3 times at least.

  1. Start any Node.js application on App Service on Linux
  1. Access to the application by web browser for executing `/opt/start/startup.sh`
  1. Stop the application.

- Do you have log output? Please include between the backticks:
-> Though there is no log, a reproduce process is found.
This is caused by `mv` command in `/opt/startup/startup.sh` which is [generated by oryx](https://github.com/microsoft/Oryx/blob/master/src/startupscriptgenerator/src/node/scriptgenerator.go#L100).

  1. At first starting, symlink `/home/site/wwwroot/node_modules` is generated by `ln` at [this in the script](https://github.com/microsoft/Oryx/blob/master/src/startupscriptgenerator/src/node/scriptgenerator.go#L155).
    Then `/home/site/wwwroot/node_modules` links to `/node_modules`.
  2. At second starting, the symlink is moved to `/home/site/wwwroot/_del_node_modules` by `/home/site/wwwroot/node_modules` using `mv` at [this](https://github.com/microsoft/Oryx/blob/master/src/startupscriptgenerator/src/node/scriptgenerator.go#L150).
    Then it is succeeded and `/home/site/wwwroot/_del_node_modules` which links to `/node_modules` is generated.
  3. At third starting, the script tries to overwrite `/home/site/wwwroot/_del_node_modules` by `/home/site/wwwroot/node_modules` using the `mv` again.
    But the `mv` doesn't overwrite for symlink to directories, it **moves** `/home/site/wwwroot/node_modules` **into** `/home/site/wwwroot/_del_node_modules` (i.e. `/node_nodules`).

As a result, `/node_modules` includes the symlink which links to itself.

A current workaround is to execute following command in a script specified as startup command

```sh
unlink /node_modules/node_modules &>/dev/null
```

Could you please look into this?

Regards,

**Comment by arroyc** [comment]
Thank you for reporting in detail, we will try to repro it and if possible a fix at our earliest.

**Comment by hihorika** [comment]
Hi @arroyc 
Could you repro this behavior?
Please let me know if you cannot repro this.

**Comment by arroyc** [comment]
@hihorika can't repro this .. lets chat over teams and show me if you can still repro this

**Comment by hihorika** [comment]
We shared repro steps.
Thanks @arroyc

**Comment by arroyc** [comment]
@hihorika  just waiting for ant-88 deployments, once that completes hopefully this issue will be resolved. Tagging it as tracking for now.

**Comment by arroyc** [comment]
@hihorika , I'm closing this issue for now, feel free to create a new one if you are still seeing similar incidents after ant-88 is released which is  roughly 1.5 months from today

**Comment by arroyc** [comment]
should be available in the coming deployment of ant-88 ..
