### ISSUE TITLE
pip install should support --no-cache-dir option

### ISSUE THREAD

**Issue by Hazhzeng** [microsoft/Oryx#507]
### Feature Request
One of our Azure Functions Python app customer wants to install the PyTorch 1.4.0 on the Oryx build machine. The PyTorch package with CUDA has a size of 700MB and we're running out of memory on our machine.

We need a way to pass the pip --no-cache-dir flag from Oryx Build command.

**Comment by arroyc** [comment]
Thank you for using Oryx. We will try to get back to you once we decide when this feature can be released.

**Comment by arroyc** [comment]
please feel free to reach us back if you have any issues

**Comment by HoLengZai** [comment]
Hi @arroyc ,
Do you have an update on that issue, please? Wondering why it has been closed without an update.
I found the doc:
https://github.com/microsoft/Oryx/blob/main/doc/runtimes/python.md#build
On Conda environment, it's doing "--no-cache-dir" but no option for non conda env
Thanks

**Comment by KristianMischke** [comment]
Any updates on this?
