### ISSUE TITLE
Python version 3.7 or 3.8?

### ISSUE THREAD

**Issue by qing-bzi** [microsoft/Oryx#527]
I think the oryx build image (mcr.microsoft.com/oryx/build:latest) was updated to Python 3.8 recently.

That is greate except my Flask app is built using Python 3.7, and this template docker file won't work.

ARG RUNTIME=python:3.7

FROM mcr.microsoft.com/oryx/build:latest as build
WORKDIR /app
COPY . .
RUN oryx build /app

FROM mcr.microsoft.com/oryx/${RUNTIME}
COPY --from=build /app /app
RUN cd /app && oryx create-script -appPath /app
ENTRYPOINT ["/app/run.sh"]

Is there a way to specify the oryx build image to use Python 3.7? a tag or something?

**Comment by arroyc** [comment]
how about using 

> RUN oryx build /app --platform python --platform-version 3.7
instead of what you are using now

![image](https://user-images.githubusercontent.com/16231002/76603144-ab197d80-64c9-11ea-8b5a-4d1f05bdb28e.png)

**Comment by arroyc** [comment]
you can type 

> oryx platforms

 to see the supported platforms and corresponding versions in the build image

**Comment by qing-bzi** [comment]
Thank you both!
