### ISSUE TITLE
How do I set Oryx to build using Python 2.7 on Azure WebApp?

### ISSUE THREAD

**Issue by gkgaurav31** [microsoft/Oryx#549]
It seems that Oryx uses Python 3.x by default. Is there a way to set is to use Python 2.7?

**Comment by arroyc** [comment]
how are you using oryx build?

if you are experimenting locally you can use the command oryx build <source dir> --platform python --platform-version 2.7

**Comment by gkgaurav31** [comment]
I found that Oryx uses linuxFxVersion to determine the python version. Since 2.7 has been removed from the Azure portal, I wasn't able to use it. However, I could change the runtime using az cli. It works now.

**Comment by arroyc** [comment]
@gkgaurav31  can you please explain what are you trying to do .. I'm not sure how you are trying to build with oryx based on images available in azure portal.

**Comment by arroyc** [comment]
Hopefully this issue is reolved, please feel free to create a new one in future
