### ISSUE TITLE
Files deployed to local folder can't be deployed to Azure Application service Git.

### ISSUE THREAD

**Issue by vit100** [microsoft/Oryx#555]
### Bug Report

- Issue with Azure App Service local git deployment
- When you `git push` files deployed by dotnet or VS into Azure App Service Oryx tries to compile project and fails:

> 
> git push 
> Enumerating objects: 305, done.
> Counting objects: 100% (305/305), done.
> Delta compression using up to 8 threads
> Compressing objects: 100% (171/171), done.
> Writing objects: 100% (305/305), 10.77 MiB | 1.45 MiB/s, done.
> Total 305 (delta 137), reused 297 (delta 133)
> remote: Resolving deltas: 100% (137/137), done.
> remote: Deploy Async
> remote: Updating branch 'master'.
> remote: Updating submodules.
> remote: Preparing deployment for commit id '71c5a6ed9e'.
> remote: Repository path is /home/site/repository
> remote: Running oryx build...
> remote: Build orchestrated by Microsoft Oryx, https://github.com/Microsoft/Oryx
> remote: You can report issues at https://github.com/Microsoft/Oryx/issues
> remote:
> remote: Oryx Version      : 0.2.20200114.13, Commit: 204922f30f8e8d41f5241b8c218425ef89106d1d, ReleaseTagName: 20200114.13
> remote: Build Operation ID: |6YUqeO3OO/w=.277f0498_
> remote: Repository Commit : 71c5a6ed9e13b067c3df53ac35829abd84722058
> remote:
> remote: Enumerating repo to find any files with extension 'csproj'...
> remote: Error: Could not detect the language from repo.
> remote: Deployment Logs : 'https://unix-test-depl.scm.azurewebsites.net/newui/jsonviewer?view_url=/api/deployments/71c5a6ed9e13b067c3df53ac35829abd84722058/log'
> To https://unix-test-depl.scm.azurewebsites.net:443/unix-test-depl.git
>  [new branch]      master -> master
> 

- What did you expect or want to happen?
If "deployed" files pushed, deployment should be just copy to target, something like this in prev version:

> git push
> Enumerating objects: 305, done.
> Counting objects: 100% (305/305), done.
> Delta compression using up to 8 threads
> Compressing objects: 100% (171/171), done.
> Writing objects: 100% (305/305), 10.77 MiB | 1.42 MiB/s, done.
> Total 305 (delta 137), reused 297 (delta 133)
> remote: Resolving deltas: 100% (137/137), done.
> remote: Updating branch 'master'.
> remote: .
> remote: Updating submodules.
> remote: Preparing deployment for commit id '71c5a6ed9e'.
> remote: Generating deployment script.
> remote: Generating deployment script for Web Site
> remote: Running deployment command...
> remote: Handling Basic Web Site deployment.
> remote: Creating app_offline.htm
> remote: KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
> remote: Deleting file: 'hostingstart.html'
> remote: Copying file: 'appsettings.Development.json'
> remote: Copying file: 'appsettings.json'
> remote: Copying file: 'dotnet-aspnet-codegenerator-design.dll'
> .....skipped output of deployment-.....
> remote: Copying file: 'de\Microsoft.CodeAnalysis.resources.dll'
> remote: Omitting next output lines...
> remote: Finished successfully.
> remote: Running post deployment command(s)...
> remote: Triggering recycle (preview mode disabled).
> remote: Deployment successful.

- How can we reproduce it?
Create Asp.Net core project. Deploy it to local folder and push it to Azure local Git deployment.

**Comment by kichalla** [comment]
@vit100 I am suspecting if you enabled the environment setting which kicks off a build on publishing the files? Could you please check and let us know? Thanks.

**Comment by vit100** [comment]
Here is env from Azure service:

> A P P   S E R V I C E   O N   L I N U X
> 
> Documentation: http://aka.ms/webapp-linux
> Dotnet quickstart: https://aka.ms/dotnet-qs
> ASP .NETCore Version: 3.1.0
> Note: Any data outside '/home' is not persisted
> 
> root@2f8d5a6b715f:~/site/wwwroot# env
> SHELL=/bin/bash
> APPSETTING_ScmType=LocalGit
> WEBSITE_SITE_NAME=kiosk-test
> WEBSITE_AUTH_ENCRYPTION_KEY=<Somelong string here removed>
> WEBSITE_AUTH_LOGOUT_PATH=/.auth/logout
> HOSTNAME=2f8d<Somelong string here removed>15f
> APPSETTING_WEBSITE_AUTH_AUTO_AAD=False
> ASPNETCORE_ENVIRONMENT=Development
> WEBSITE_INSTANCE_ID=bb6f79fc7be76<Somelong string here removed>3b879340e03d1dd0e0
> DIAGNOSTIC_LOGS_MOUNT_PATH=/var/log/diagnosticLogs
> DOTNET_VERSION=3.1.0
> ASPNETCORE_URLS=
> WEBSITE_AUTH_SIGNING_KEY=BF23BAB<Somelong string here removed>4538A182F48BD621
> PWD=/home/site/wwwroot
> APPSVC_RUN_ZIP=FALSE
> LOGNAME=root
> PORT=8080
> COMPlus_DbgEnableMiniDump=1
> ORYX_AI_INSTRUMENTATION_KEY=4aa<Somelong string here removed>2b887
> APPSETTING_WEBSITE_SITE_NAME=k-test
> APPSETTING_WEBSITE_AUTH_LOGOUT_PATH=/.auth/logout
> WEBSITE_OWNER_NAME=11c<Somelong string here removed>44f5f8+dev-EastUSwebspace
> HOME=/home
> APPSETTING_FUNCTIONS_RUNTIME_SCALE_MONITORING_ENABLED=0
> FUNCTIONS_RUNTIME_SCALE_MONITORING_ENABLED=0
> ORYX_ENV_TYPE=AppService
> SSH_CONNECTION=172.16.1.2 56910 172.16.1.3 2222
> WEBSITE_RESOURCE_GROUP=dev
> COMPUTERNAME=RD00155D96F144
> WEBSITE_ROLE_INSTANCE_ID=0
> TERM=vt100
> APPSETTING_ASPNETCORE_ENVIRONMENT=Development
> USER=root
> REMOTEDEBUGGINGVERSION=16.0.28729.10
> ScmType=LocalGit
> PLATFORM_VERSION=87.0.7.83
> SHLVL=0
> DOTNET_RUNNING_IN_CONTAINER=true
> ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
> APPSETTING_WEBSITE_AUTH_ENABLED=False
> SSH_CLIENT=172.16.1.2 56910 2222
> WEBSITE_HOSTNAME=<Somelong string here removed>.azurewebsites.net
> DUMP_DIR=/home/logs/dumps
> APPSETTING_REMOTEDEBUGGINGVERSION=16.0.28729.10
> SSH_PORT=2222
> PATH=/opt/dotnetcore-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/site/wwwroot
> WEBSITE_AUTH_ENABLED=False
> WEBSITE_AUTH_AUTO_AAD=False
> MAIL=/var/mail/root
> SSH_TTY=/dev/pts/0
> ORYX_ENV_NAME=k-test
> ASPNETCORE_VERSION=3.1.0
> _=/usr/bin/env
>

**Comment by kichalla** [comment]
@vit100 Thanks for the details but seems like those settings are from the `runtime` container. I am looking for settings from the `build` container. Could you share that too?

**Comment by vit100** [comment]
@kichalla , Yes, of course I can, if you tell me how -))

**Comment by kichalla** [comment]
@vit100 When you go to the SCM website, you should see a link which says 'bash'. Clicking this link will give you a console in a browser window. This console is for the build container whereas the 'ssh' link is to the 'runtime' container

**Comment by vit100** [comment]
ah.. Kudu.. got it.
Btw, I created site from wizard, didn't select any specific different setting compared to .NetCore 3.0 in Windows.


here it is:

> Kudu Remote Execution Console
> Type 'exit' to reset this console.
> /home>set
> APPDATA=/opt/Kudu/local
> APPSETTING_ASPNETCORE_ENVIRONMENT=Development
> APPSETTING_FUNCTIONS_RUNTIME_SCALE_MONITORING_ENABLED=0
> APPSETTING_REMOTEDEBUGGINGVERSION=16.0.28729.10
> APPSETTING_SCM_USE_LIBGIT2SHARP_REPOSITORY=0
> APPSETTING_ScmType=LocalGit
> APPSETTING_WEBSITE_AUTH_AUTO_AAD=False
> APPSETTING_WEBSITE_AUTH_ENABLED=False
> APPSETTING_WEBSITE_AUTH_LOGOUT_PATH=/.auth/logout
> APPSETTING_WEBSITE_SITE_NAME=k-test<Somelong string here removed>
> APPSVC_RUN_ZIP=FALSE
> ASPNETCORE_ENVIRONMENT=Development
> ASPNETCORE_URLS=http://0.0.0.0:8181
> BASH=/bin/bash
> BASHOPTS=cmdhist:complete_fullquote:extquote:force_fignore:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
> BASH_ALIASES=()
> BASH_ARGC=()
> BASH_ARGV=()
> BASH_CMDS=()
> BASH_EXECUTION_STRING='set && echo '\'''\'' && pwd'
> BASH_LINENO=()
> BASH_SOURCE=()
> BASH_VERSINFO=([0]="4" [1]="4" [2]="12" [3]="1" [4]="release" [5]="x86_64-pc-linux-gnu")
> BASH_VERSION='4.4.12(1)-release'
> COMPUTERNAME=RD00155D96F144
> DEBIAN_FRONTEND=noninteractive
> DEPLOYMENT_SOURCE=/home
> DEPLOYMENT_TARGET=/home/site/wwwroot
> DIRSTACK=()
> DOTNET_CLI_TELEMETRY_PROFILE=AzureKudu
> DOTNET_RUNNING_IN_CONTAINER=true
> DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
> DOTNET_USE_POLLING_FILE_WATCHER=true
> ENABLE_ORYX_BUILD=true
> EUID=1002
> EnableNuGetPackageRestore=true
> FRAMEWORK=DOTNETCORE
> FRAMEWORK_VERSION=3.1
> FUNCTIONS_RUNTIME_SCALE_MONITORING_ENABLED=0
> GO_WEB_CONFIG_TEMPLATE=/opt/Kudu/Scripts/go.web.config.template
> GROUPS=()
> GYP_MSVS_VERSION=2015
> HOME=/home
> HOMEDRIVE=
> HOMEPATH=/home
> HOSTNAME=6d82e4ecff2f
> HOSTTYPE=x86_64
> HTTP_AUTHORITY=k-test<Somelong string here removed>.scm.azurewebsites.net
> HTTP_HOST=k-test<Somelong string here removed>.scm.azurewebsites.net
> IFS=$' \t\n'
> KUDU_APPPATH=/opt/Kudu
> KUDU_RUN_USER=4335596308923efa00349fbe
> KUDU_SELECT_NODE_VERSION_CMD='node "/opt/Kudu/Scripts/selectNodeVersion"'
> KUDU_SELECT_PYTHON_VERSION_CMD='python "/opt/Kudu/Scripts/select_python_version.py"'
> KUDU_SYNC_CMD=kudusync
> KUDU_WEBSSH_PORT=3000
> LANG=C.UTF-8
> MACHTYPE=x86_64-pc-linux-gnu
> MSBUILD_15_DIR=
> MSBUILD_PATH=
> NOKOGIRI_USE_SYSTEM_LIBRARIES=true
> NPM_JS_PATH=/usr/bin/npm-cli.js
> NUGET_EXE=/opt/Kudu/Scripts/nuget.exe
> NUGET_PACKAGES=/var/nuget
> NUGET_XMLDOC_MODE=skip
> OLDPWD=/
> OPTERR=1
> OPTIND=1
> ORYX_AI_INSTRUMENTATION_KEY=4aadb<Somelong string here removed>c62b887
> ORYX_ENV_NAME='~1kiosk-test'
> ORYX_ENV_TYPE=AppService
> OSTYPE=linux-gnu
> PATH=/home/site/deployments/tools:/opt/Kudu/Scripts:/usr/bin:/usr/bin:/usr/local/bin:/usr/local/bin:/usr/local/bin:/usr/local/bin:/usr/local/.rbenv/bin:/usr/local:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/dotnet/sdks/2.2.402:/opt/oryx:/opt/nodejs/lts/bin:/opt/dotnet/sdks/lts:/opt/python/latest/bin:/opt/yarn/stable/bin:/opt/php/lts/bin:/root/.dotnet/tools:/opt/nodejs/9/bin
> PLATFORM_VERSION=87.0.7.83
> PORT=8181
> PPID=95
> PS4='+ '
> PWD=/home
> PYTHONIOENCODING=UTF-8
> RBENV_ROOT=/usr/local/.rbenv
> REMOTEDEBUGGINGVERSION=16.0.28729.10
> RUBY_CFLAGS=-O3
> RUBY_CONFIGURE_OPTS=--disable-install-doc
> SCM_BUILD_ARGS=
> SCM_COMMAND_IDLE_TIMEOUT=60
> SCM_DNVM_PS_PATH=/opt/Kudu/Scripts/dnvm.ps1
> SCM_LOGSTREAM_TIMEOUT=7200
> SCM_TRACE_LEVEL=Verbose
> SCM_USE_LIBGIT2SHARP_REPOSITORY=0
> SELECT_LATEST_VERSION_CMD=/opt/Kudu/Scripts/selectLatestVersion.ps1
> SHELL=/bin/sh
> SHELLOPTS=braceexpand:hashall:interactive-comments
> SHLVL=2
> SITE_BITNESS=AMD64
> ScmType=LocalGit
> TERM=dumb
> UID=1002
> VCInstallDir_140=
> VCTargetsPath=
> WEBJOBS_DEPLOY_CMD=deploy_webjobs.cmd
> WEBROOT_PATH=/home/site/wwwroot
> WEBSITE_AUTH_AUTO_AAD=False
> WEBSITE_AUTH_ENABLED=False
> WEBSITE_AUTH_ENCRYPTION_KEY=F498B9<Somelong string here removed>D36BCBC526CF48885
> WEBSITE_AUTH_LOGOUT_PATH=/.auth/logout
> WEBSITE_AUTH_SIGNING_KEY=BF23BAB5788D646E047021790B82A6961B09F62C9BD595F14538A182F48BD621
> WEBSITE_HOSTNAME=kiosk-test.azurewebsites.net
> WEBSITE_INSTANCE_ID=bb6f79fc7be7675fdae1<Somelong string here removed>3d1dd0e0
> WEBSITE_OWNER_NAME=11c83f8<Somelong string here removed>f5f8+dev-EastUSwebspace
> WEBSITE_RESOURCE_GROUP=dev
> WEBSITE_ROLE_INSTANCE_ID=0
> WEBSITE_SITE_NAME=kiosk-test
> _=bash
> deployment_branch=master
> dotnet=/opt/dotnet/sdks/2.2.402/dotnet
> /home>

**Comment by kichalla** [comment]
@sanchitmehta any ideas why @vit100 is seeing his already built and deployed bits being tried to be built again?

**Comment by kichalla** [comment]
@vit100 Are you still seeing this issue? if yes, you can try the setting `SCM_DO_BUILD_DURING_DEPLOYMENT=false`
This will prevent from the app being built on AppService.

**Comment by vit100** [comment]
Looks like  it is working now, probably it was fixed.

**Comment by bgawale** [comment]
Can you confirm how did you manage to solve this?
