### ISSUE TITLE
deploy azure web apps (from local git) failed during Oryx Build step 

### ISSUE THREAD

**Issue by andyzhu** [microsoft/Oryx#560]
### Bug Report

- At what date and time did you most recently experience the problem?
April 11th, 2020 7:58PM EST

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Web Apps

- If your repo is publicly available please share its URL:
No

- What happened?
When try to follow instruction on this learning course (https://docs.microsoft.com/en-us/learn/modules/stage-deploy-app-service-deployment-slots/3-exercise-create-deployment-slots) and use local git deployment method to push a ASP.Net sore web app to Azure Web App service, the deployment failed

$ git push Staging
Enumerating objects: 128, done.
Counting objects: 100% (128/128), done.
Delta compression using up to 4 threads
Compressing objects: 100% (93/93), done.
Writing objects: 100% (128/128), 397.79 KiB | 13.72 MiB/s, done.
Total 128 (delta 35), reused 119 (delta 31)
remote: Resolving deltas: 100% (35/35), done.
remote: Deploy Async
remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id '09a1b2b2d0'.
remote: Repository path is /home/site/repository
remote: Running oryx build...
remote: Build orchestrated by Microsoft Oryx, https://github.com/Microsoft/Oryx
remote: You can report issues at https://github.com/Microsoft/Oryx/issues
remote:
remote: Oryx Version      : 0.2.20200114.13, Commit: 204922f30f8e8d41f5241b8c218425ef89106d1d, ReleaseTagName: 20200114.13
remote: Build Operation ID: |XTo1MpJQ7M4=.61e0194f_
remote: Repository Commit : 09a1b2b2d0137a97195eae15519df17e1bf5fdba
remote:
remote: **Enumerating repo to find any files with extension 'csproj'..**.
remote: **Error: Could not detect the language from repo.**
remote: Deployment Logs : 'https://az-slot-deploy-0001-staging.scm.azurewebsites.net/newui/jsonviewer?view_url=/api/deployments/09a1b2b2d0137a97195eae15519df17e1bf5fdba/log'
To https://az-slot-deploy-0001-staging.scm.azurewebsites.net:443/az-slot-deploy-0001.git
 * [new branch]      master -> master

- What did you expect or want to happen?

- How can we reproduce it?

- Do you have log output? Please include between the backticks:

```
Command: oryx build /home/site/repository -o /home/site/wwwroot --platform dotnet --platform-version 3.1 -i /tmp/8d7de707316a4ce --log-file /tmp/build-debug.log 
Build orchestrated by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version      : 0.2.20200114.13, Commit: 204922f30f8e8d41f5241b8c218425ef89106d1d, ReleaseTagName: 20200114.13
Build Operation ID: |+nOI5k+STf4=.c03fecf0_
Repository Commit : 2d119a720d3b534d47f418c3b1d092fb2d1245ea

Enumerating repo to find any files with extension 'csproj'...
Error: Could not detect the language from repo.
Error: Could not detect the language from repo.\n/opt/Kudu/KuduConsole/Scripts/starter.sh oryx build /home/site/repository -o /home/site/wwwroot --platform dotnet --platform-version 3.1 -i /tmp/8d7de707316a4ce --log-file /tmp/build-debug.log
```

**Comment by kichalla** [comment]
@andyzhu do you still see this issue? If yes, could you share a simple repro for it?

**Comment by kichalla** [comment]
Closing this issue as we have not heard back from you in a long time. Feel free to re-open it with additional details.
