### ISSUE TITLE
node_modules.tar.gz is not uncompressed properly

### ISSUE THREAD

**Issue by lovettchris** [microsoft/Oryx#567]
### Bug Report

Sunday, April 19, 2020, 8:56:38 PM GMT-7 I tried to deploy my react node.js website to https://f99teleprompter.azurewebsites.net/ and the logs said everything worked, but the site returns ":( Application Error" because the node_modules did not uncompress properly.

- Where did you experience the problem? **Azure Web Apps**

- If your repo is publicly available please share its URL:
https://github.com/lovettchris/TeleprompterBuild

- What happened?
[build.log](https://github.com/microsoft/Oryx/files/4501162/build.log)

- What did you expect or want to happen?
Notice that node_modules is a 2kb file instead of a folder:

![image](https://user-images.githubusercontent.com/18707114/79713206-fd487e00-8281-11ea-8b5b-ca4a1c7652b0.png)

- How can we reproduce it?
Just re-run the deployment, or email me clovett at microsoft.com and I'll show you.

- Do you have log output? Please include between the backticks:
oryx build log is attached above.

**Comment by lovettchris** [comment]
I have been able to reproduce this again with the following steps:
1. Create new Azure Web App, node.js version 12, on Linux
2. Deploy git repo https://github.com/lovettchris/TeleprompterBuild using kudu
3. Wait for deploy to succeed
4. Navigate to your new web app url
5. ":( Application Error"
6. Now open the kudu BASH prompt and run this:
7. cd site/wwwroot
8. tar -xvf node_modules.tar.gz --directory node_modules
9. restart your web app using restart button on Overview portal.
10. now app is running...

**Comment by arroyc** [comment]
@lovettchris  thanks for following up .. can you still repro this? I couldn't repro this when I tried those steps.

**Comment by lovettchris** [comment]
You couldn't repro because the github repo is gone right?

**Comment by lovettchris** [comment]
Here's the new repro steps:
1. Create new Azure Web App, node.js version 12, on Linux:
![image](https://user-images.githubusercontent.com/18707114/97630301-a1a73c00-19ec-11eb-93cb-3540bedb0290.png)
2. Create "local git" with Kudu and clone that repo locally
3. Copy the bits from https://github.com/lovettchris/Teleprompter and "push" these bits up to the Azure local git repo.
4. Wait for "remote: Deployment successful." and navigate to the public website URL and you will see this:
![image](https://user-images.githubusercontent.com/18707114/97630265-93592000-19ec-11eb-9f08-34c86faba025.png)

5. Try and open SSH to the site using
![image](https://user-images.githubusercontent.com/18707114/97630511-f480f380-19ec-11eb-9bd9-e597e66ac0b8.png)

and you will see another problem:
on.error - Error: connect ECONNREFUSED 172.16.1.2:2222Error: connect ECONNREFUSED 172.16.1.2:2222

See attached log file. 
[log.txt](https://github.com/microsoft/Oryx/files/5461234/log.txt)

Interestingly it fails Chrome with a different error:
SSH CONNECTION CLOSE - Error: Timed out while waiting for handshakeError: connect EHOSTUNREACH 172.16.1.2:2222Error: connect EHOSTUNREACH 172.16.1.2:2222Error: connect EHOSTUNREACH 172.16.1.2:2222

**Comment by arroyc** [comment]
thanks @lovettchris  .. I will try again !

**Comment by wasuaje** [comment]
Same error here!

**Comment by qianz2** [comment]
Closing it as it's been long time, feel free to reopen if you have other questions.
