### ISSUE TITLE
Add Rust toolchain

### ISSUE THREAD

**Issue by manekinekko** [microsoft/Oryx#583]
### System Package Request

- **Why do you need this package? For example, are you using a language-level package which depends on this system package?**

More and more developers use Rust to compile their apps to WASM, and eventually deploy them to Azure Functions, on a Node.js runtime. It'd be great if Oryx adds support for Rust toolchain e.g. `rustup `, `rustc` and `cargo`.

- **Which Oryx language runtime and version are you using? For example, "Node.js v10.14" or "Python v3.7".**

Node.js v12+

- **What is the name of the package in the latest stable Debian release?For examples, see <https://packages.debian.org/stable/>.**

The Rust documentation recommends installing the toolchain as follows: 
```bash
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

- **Do you need a specific version? If so, which and why?**

No specific version.

**Comment by arroyc** [comment]
thanks for reporting .. we will keep you updated ...

**Comment by arroyc** [comment]
@manekinekko  .. we have this added in our story board .. but we have other priorities now ... Please subscribe to our repo for future releases .. you will get notified when this feature will be published .. closing this for now .. feel free to file new issues
