### ISSUE TITLE
Add Ruby / RubyGem Support

### ISSUE THREAD

**Issue by CalvinAllen** [microsoft/Oryx#586]
### Feature Request

I would love to have the Ruby / RubyGems / CMake toolchain available for Oryx auto-detection/build.

I.e., automatically detect a Gemfile, perform an installation of those gems (via bundler?).

It may also be needed to detect a `.ruby-version` file to lock in a specific version of Ruby for `rbenv` before hand.

**Comment by eloekset** [comment]
Agree. Strange that Ruby isn't one of the first platforms to be supported, since Jekyll is **the** static web app of GitHub.

**Comment by qianz2** [comment]
@CalvinAllen @eloekset We recently added Ruby apps detect/build support, thanks for your attention. Feel free to try it and get back to use if you have any feedbacks. I'll close this issue for now.
