### ISSUE TITLE
pip3 and python3 resolve to different versions of python

### ISSUE THREAD

**Issue by jkeech** [microsoft/Oryx#588]
### Bug Report

- At what date and time did you most recently experience the problem? **5/13/20**

- Where did you experience the problem? **Codespaces**

- If your repo is publicly available please share its URL: **N/A**

- What happened?

1) Fired up a repo with no `devcontainer.json`
2) Codespaces seemed to realize it was a python repo, and created a `pythonenv37` folder
3) If I execute the `python3` and `pip3` under that folder, all is well. But the default `python3` maps to a different (python 3.5) binary under `/usr/bin`. And the default `pip3` maps to a python 3.6!
So a naïve user trying to run their usual `pip3 install` and `python3` in terminal will have a real bad time: packages will be installed to python 3.8, but scripts will execute under python 3.5, so it’ll look to them like packages aren’t being installed

- What did you expect or want to happen? **The same version of python is used in both cases**

- How can we reproduce it? **Create an empty Codespace in GitHub or https://online.visualstudio.com and run the commands below**

- Do you have log output? Please include between the backticks:

```bash
vsonline:~/workspace/gocamp$ which python3
/usr/bin/python3
vsonline:~/workspace/gocamp$ python3 --version
Python 3.5.3
vsonline:~/workspace/gocamp$ which pip3
/opt/python/latest/bin/pip3
vsonline:~/workspace/gocamp$ pip3 --version
pip 19.3.1 from /opt/python/3.8.0/lib/python3.8/site-packages/pip (python 3.8)
```

**Comment by kichalla** [comment]
This has been fixed in https://github.com/microsoft/Oryx/commit/66c22929a8024f9686315dd519f53c4a6f3cdb12
