### ISSUE TITLE
Azure WebApps NodeJS version deployment error message

### ISSUE THREAD

**Issue by guy-shahine** [microsoft/Oryx#593]
Every time we deploy our app, we get an error message that the Node.JS version is outdated and that we should check this repo for supported versions.  Azure portal is not up to date on these versions and the readme.md on this repo is still at 10.15.0. so where's the best place to check for the supported versions?

remote: Build orchestrated by Microsoft Oryx, https://github.com/Microsoft/Oryx
remote: You can report issues at https://github.com/Microsoft/Oryx/issues
remote:
remote: Oryx Version      : 0.2.20200114.13, Commit: 204922f30f8e8d41f5241b8c218425ef89106d1d, ReleaseTagName: 20200114.13
remote: Build Operation ID: |nsRmnAmdImA=.c6a4a99e_
remote: Repository Commit : 0cd31cbc139f0645f44db91e2dd7e402efd9a867
remote:
**remote: Warning: An outdated version of node was detected (10.18.0). Consider updating.\nVersions supported by Oryx: https://github.com/microsoft/Oryx**
remote:
remote: Using intermediate directory '/tmp/8d7f90f160427f5'.
remote:
remote: Copying files to the intermediate directory...
remote: Done in 1 sec(s).
remote:

**Comment by danieljaguiar** [comment]
Same here... but mine is 10.10
