### ISSUE TITLE
F# Azure Function project is not found and fails the build/deployment from App Service Static Apps

### ISSUE THREAD

**Issue by panesofglass** [microsoft/Oryx#603]
### Bug Report

Oryx appears to only work with C# projects (i.e., .csproj). I created an F# (.fsproj) dotnet Azure Functions Project which failed to build through App Service Static Apps. The error logs (below) noted that it could not find a `.csproj` file, though I should think any supported `.**proj` file should work just fine.

- At what date and time did you most recently experience the problem?
2020-05-20 8:00 AM

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure App Service Static Apps

- If your repo is publicly available please share its URL:
https://github.com/panesofglass/oryx-fsharp-repro

- What happened?
Oryx failed to build the Azure Function because it was looking only for `.csproj`, not `.fsproj`

- What did you expect or want to happen?
Expected the F# Azure Function to build and deploy successfully. Steps should be the same regardless of `.**proj`

- How can we reproduce it?
  * Generate a new Azure Functions App with `dotnet new func --lang f# -o api -n api`
  * Add an F# function, e.g. `cd api && dotnet new http --lang f# -n HttpTrigger
  * Create a new Azure Static Web App (preview) to generate the GitHub Actions workflow and trigger a build and deploy

- Do you have log output? Please include between the backticks:

```
App Directory Location: 'src' was found.
Api Directory Location: 'api' was found.
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
---Oryx build logs---


Build orchestrated by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version      : 0.2.20200514.4, Commit: 33f337f79d0218ca33b308eee9124d3713d5da95, ReleaseTagName: 20200514.4
Build Operation ID: |JEjG3TaeHgY=.b5146de6_

Enumerating repo to find any files with extension 'csproj'...
Error: Could not detect the language from repo.


---End of Oryx build logs---
Oryx was unable to determine the build steps. Continuing assuming the assets in this folder are already built. If this is an unexpected behavior please contact support.
Finished building app with Oryx
Starting to build function app with Oryx
Function Runtime Information. OS: Linux, Functions Runtime: V3, NodeJS version: 12.X
---Oryx build logs---
```

**Comment by kichalla** [comment]
Hi @panesofglass , the message printed out to stdout is misleading and we do support F# projects. That said we do not C#/F# projects in App Service **Static Apps** yet and are actively working on to add support for it.

**Comment by kichalla** [comment]
.NET Core 3.1 support has been added to Azure Static Web Apps recently. Please try again and let us know if you still see the issue:
https://devblogs.microsoft.com/aspnet/azure-static-web-apps-with-blazor/

**Comment by panesofglass** [comment]
Looks like the project built and deployed, but I don't see the function listed in the portal, and I cannot hit the API.

**Comment by kichalla** [comment]
Thanks for the update @panesofglass 

cc @Hazhzeng @miwebst

**Comment by kichalla** [comment]
Closing this issue as Oryx supports F# projects. Seems like this issue is at the Static WebApps end.
