### ISSUE TITLE
Azure Static Site (Preview) Build And Deploy: ERR! code ELIFECYCLE 

### ISSUE THREAD

**Issue by EdSF** [microsoft/Oryx#605]
### Bug Report

- At what date and time did you most recently experience the problem?

5/20/2020 2:00 PM Pacific

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.

Azure Static Sites (Preview)

- If your repo is publicly available please share its URL:

It's private...nothing special, just trying out Azure Static Sites (preview) with Github

- What happened?

Running Github Action scripted and created by Azure Static Sites (I did not write/create) runs and fails at `Build And Deploy` section with error output provided below. It points to a log file, but I'm not really clear on how to get to it for further tinkering...

- What did you expect or want to happen?

Build successfully (just like in local environment)

- How can we reproduce it?

Unsure...I'm a n00b at all this

- Do you have log output? Please include between the backticks:

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project-name@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-project-name@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2020-05-20T21_15_15_651Z-debug.log
```

**Comment by EdSF** [comment]
Comparing `package.json` taken from [Quickstart: Building your first static web app](https://github.com/staticwebdev/react-basic/), _specific_ to `react` since it seems to be failing on `react-scripts-build`:

<table>
<tr>
<td>Quickstart</td>
<td>Mine</td>
</tr>
<tr>
<td>

```

"react": "^16.12.0",
"react-dom": "^16.12.0",
"react-scripts": "3.4.0"

```

</td>
<td>

```

"react": "^16.13.1",
"react-dom": "^16.13.1",
"react-router-dom": "^5.1.2",
"react-scripts": "3.4.1"

```

</td>
</tr>
</table>

**Comment by kichalla** [comment]
Thanks @EdSF . It could be a temporary issue. I did try to repro now with content as you mentioned above and the build went through fine. Here it is: https://github.com/kichalla/react-basic/runs/697716404?check_suite_focus=true

**Comment by EdSF** [comment]
> Thanks @EdSF . It could be a temporary issue. I did try to repro now with content as you mentioned above and the build went through fine. Here it is: https://github.com/kichalla/react-basic/runs/697716404?check_suite_focus=true

Thank you for that! My repo is still failing. **BUT**, I went through the logs again and did find this log msg:

`Treating warnings as errors because process.env.CI = true` 

and I do have *warnings* .

 _Assuming_ that is the reason for the failed `build`, I'm looking at the workflow script and can't seem to find that setting. This is more of an education process for me as to learning how this new Azure offering goes as I can resolve the code level warnings as well.

Thank you again!

**Comment by EdSF** [comment]
Solved
---

For n00bs to all this like myself:

This discussion, [Treating warnings as errors because process.env.CI = true](https://github.community/t5/GitHub-Actions/Treating-warnings-as-errors-because-process-env-CI-true/m-p/52593/highlight/true#M8570) is the answer.

If you have code level _warnings_ the build process will **fail** unless you add the setting to your Github actions `Workflow Script` - or if you refactor your code and resolve the _warnings_ (not errors). 

This differs from your experience with running `npm run build` in your dev box.

`Workflow Script` is 
- the script created for you by the Azure Static Sites (Preview) process
- you will find it in your Github repo `branch`  
`./github/workflows` folder

To fix:
- modify the script (and enjoy the Github code completion 👍 ) 
- add the `env` setting `CI: false` , like so  

```
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env:
      CI: false
    steps:
    - uses: actions/checkout@v1

    ...removed for brevity..
```

Hth...

**Comment by Dibendu-Saha** [comment]
Yes, thank you. Prior to setting the **CI** property, my component names were all capitalized in GitHub though it was in small in my local environment. Finally a green tick aside the **Build and Deploy Job**.

**Comment by duro721** [comment]
Thanks, was driving me nuts why my app was deploying fine on Render and Heroku but not to Azure through the Github Actions.
