### ISSUE TITLE
Add support for dotnet core 3.1 in Azure Static Web Apps (preview)

### ISSUE THREAD

**Issue by lalitadithya** [microsoft/Oryx#614]
### Add support for dotnet core 3.1 in Azure Static Web Apps (preview)

I tried deploying a dotnet core 3.1 Azure functions app along with a React front end (https://github.com/lalitadithya/PlanetScaleTodoApp) and I noticed that dotnet core 3.1 is not supported. Moreover it doesn't tell me what versions are supported, so I'm assuming that dotnet is not supported at all. 

Build logs:
```
Function Runtime Information. OS: Linux, Functions Runtime: V3, NodeJS version: 12.X
---Oryx build logs---


Build orchestrated by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version      : 0.2.20200514.4, Commit: 33f337f79d0218ca33b308eee9124d3713d5da95, ReleaseTagName: 20200514.4
Build Operation ID: |39UxGjFwAHU=.e8023f22_

Error: Platform 'dotnet' version '3.1' is unsupported. Supported versions: 


---End of Oryx build logs---
Oryx has found build steps, but identified unsupported platform versions. Failing build.
```

**Comment by christiannagel** [comment]
Not supported yet, but actively working on to add support - see #603:  https://github.com/microsoft/Oryx/issues/603#issuecomment-631498275

@timheuer has a sample using ASP.NET Blazor with the preview of Azure Static Web Apps - this might help in the meantime: https://timheuer.com/blog/hosting-blazor-in-azure-static-web-apps

**Comment by lalitadithya** [comment]
Thank you @christiannagel 
I will have a look at the link you shared and see if that is something I can use for my app.

**Comment by kichalla** [comment]
Closing this issue as the support is currently available: https://devblogs.microsoft.com/aspnet/azure-static-web-apps-with-blazor/
