### ISSUE TITLE
Deployment Failure Reason: Failure during content distribution

### ISSUE THREAD

**Issue by sytone** [microsoft/Oryx#616]
### Bug Report

- At what date and time did you most recently experience the problem?
5/25 8:00 PM PDT

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Static Web App

- If your repo is publicly available please share its URL:
Private, but can share offline the details. 

- What happened?
First run when fine, action built project and then it was deployed. Every deployment post that has failed. Snippet below from log, no other details and no way I could see to get more debug information so no idea what it was actually polling.

```
---End of Oryx build logs---
Finished building function app with Oryx
Zipping App Artifacts
Done Zipping App Artifacts
Zipping Api Artifacts
Done Zipping Api Artifacts
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.3001619(s)
Status: Failed. Time: 16.074828(s)
Deployment Failed :(
Deployment Failure Reason: Failure during content distribution
Exiting
```

- What did you expect or want to happen?
Site to be deployed. 

- How can we reproduce it?
Can provide source offline. 

- Do you have log output? Please include between the backticks:

```
---End of Oryx build logs---
Finished building function app with Oryx
Zipping App Artifacts
Done Zipping App Artifacts
Zipping Api Artifacts
Done Zipping Api Artifacts
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.3001619(s)
Status: Failed. Time: 16.074828(s)
Deployment Failed :(
Deployment Failure Reason: Failure during content distribution
Exiting
```

**Comment by SandeepShah89** [comment]
Having the same issue. 3 of the last 5 deploys have failed for the same reason...

**Comment by sytone** [comment]
I managed to resolve it out, there is a issue where files have the same name but different case. So if you have `fileName.html` and `filename.html` in the same directory the deployment will fail.

**Comment by kichalla** [comment]
cc @miwebst

**Comment by kichalla** [comment]
Closing this issue as it is not related to Oryx. Please feel free to re-open it with additional details.

**Comment by arvinhubert** [comment]
Hi @sytone , are you talking about the build folder?

**Comment by appasaheb4** [comment]
<img width="1055" alt="Screenshot 2021-10-04 at 10 52 54 AM" src="https://user-images.githubusercontent.com/24726539/135798283-448ccfc7-5782-4aa7-a119-0dc51eebc0ed.png">
facing azure static web on deploy time

**Comment by miwebst** [comment]
This is due to an underlying Azure issue, we are tracking mitigation process here: https://github.com/Azure/static-web-apps/issues/596
