### ISSUE TITLE
PRE_BUILD_COMMAND for apt-get installation: permission denied

### ISSUE THREAD

**Issue by mmcux** [microsoft/Oryx#643]
I am relatively new to programming and Azure App Service and don't know if I am right here.

My Python web app is running without a problem, but now I want want to add a feature which requires the installation of `libhunspell-dev` with apt-get.
It must be installed before the `pip install` commands, so I tried to use oryx's `PRE_BUILD_COMMAND`.
But I get the error message: 
```
remote: E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
remote: E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
```

Is it even possible to install that package with apt-get? Using sudo doesn't work as I get the same error message if I want to install it (which kind of makes sense without the rights). I would be glad if I don't have to set up a complete new linux image in a new container as this is the advantage of using App Service/Oryx.
Commands I used for prebuild.sh :
```
apt-get -y install libhunspell-dev
```
or
```
apt-get update && apt-get -y install sudo dialog apt-utils
sudo apt-get -y install python-dev libhunspell-dev
```

Maybe it is related with #404 . I would be very happy if you could give me a hint what I could try out! Thanks!

**Comment by kichalla** [comment]
Hi @mmcux App Service's build runs in a container which is a constrained environment and so you will not be able to install system packages using `apt-get` commands.

cc @sanchitmehta

**Comment by mmcux** [comment]
Hi @kichalla 
Thanks for your response. The deployment process was easy to handle until this point and I guess I have to dive deeper now into different Azure services.

**Comment by thomassajot** [comment]
Hi @mmcux, I am having the same issue. Did you find a work around ?

**Comment by albian786** [comment]
Please use PRE_BUILD_COMMAND or PRE_BUILD_SCRIPT_PATH to execute custom scripts before deployment
