### ISSUE TITLE
Deployment failed with  Error: Platform 'nodejs' version '14' is unsupported.

### ISSUE THREAD

**Issue by prernarp** [microsoft/Oryx#650]
1:25:39 PM preTestWindows: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 14 -i /tmp/8d8174ad21a2dc0 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
1:25:43 PM preTestWindows: Build orchestrated by Microsoft Oryx, https://github.com/Microsoft/Oryx
1:25:43 PM preTestWindows: You can report issues at https://github.com/Microsoft/Oryx/issues
1:25:43 PM preTestWindows: Oryx Version      : 0.2.20200312.1, Commit: 8fe90af07018bd4454a39b0edea6ecc5119642da, ReleaseTagName: 20200312.1
1:25:43 PM preTestWindows: Build Operation ID: |wUELx8Re/Zc=.65b56869_
1:25:43 PM preTestWindows: Repository Commit : 3ee5057adbfb41cdb4b520d43310a028
1:25:43 PM preTestWindows: Error: Platform 'nodejs' version '14' is unsupported. Supported versions: 4.4.7, 4.5.0, 4.8.0, 6.2.2, 6.6.0, 6.9.3, 6.10.3, 6.11.0, 6.17.1, 8.0.0, 8.1.4, 8.2.1, 8.8.1, 8.9.4, 8.11.2, 8.12.0, 8.15.1, 8.17.0, 9.4.0, 10.1.0, 10.10.0, 10.14.2, 10.16.3, 10.19.0, 12.16.1
1:25:46 PM preTestWindows: Error: Platform 'nodejs' version '14' is unsupported. Supported versions: 4.4.7, 4.5.0, 4.8.0, 6.2.2, 6.6.0, 6.9.3, 6.10.3, 6.11.0, 6.17.1, 8.0.0, 8.1.4, 8.2.1, 8.8.1, 8.9.4, 8.11.2, 8.12.0, 8.15.1, 8.17.0, 9.4.0, 10.1.0, 10.10.0, 10.14.2, 10.16.3, 10.19.0, 12.16.1\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 14 -i /tmp/8d8174ad21a2dc0 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
1:25:47 PM preTestWindows: Deployment failed.

**Comment by arroyc** [comment]
@prenarp did you select node lts as runtime stack?

**Comment by qianz2** [comment]
Hi @prernarp, do you still have the issue? I think Oryx current releases have supported Node 14 version. If it's no longer an error, we'll close this.

**Comment by kichalla** [comment]
@prernarp We believe this issue should already have been fixed. Feel free to re-open it if you still see it.
