### ISSUE TITLE
deploy web app with vs code

### ISSUE THREAD

**Issue by jessicanevesmachado-zz** [microsoft/Oryx#662]
hello, has anyone had this error when deploying a react application?
how can i solve?

<img width="980" alt="erro" src="https://user-images.githubusercontent.com/12597532/86059592-69412280-ba39-11ea-8329-2482f0311641.png">

**Comment by gnmaxim** [comment]
Yes, same issue when trying to deploy the build directory with vs-code.

**Comment by arroyc** [comment]
@gnmaxim , @jessicanevesmachado-zz  Couldn't repro this ... please feel free to reopen this issue or create a new one
