### ISSUE TITLE
Azure Linux Web App, "it" culture not working

### ISSUE THREAD

**Issue by tarekgh** [microsoft/Oryx#68]
_From @Eilon on Friday, 05 April 2019 16:49:46_

_From @valeriob on Friday, 05 April 2019 08:05:46_

### Describe the bug
Create a new aspnetcore 2.2 web app, enable it and en cultures as the documentation instructs, and make a page that prints the current date in short date format "d".
Run it locally with an italian browser, it correctly use the dd/MM/yyyy pattern, then deploy it to azure linux web app (code and framework dependent, not container) navigate to that page with the same browser with italian language : the displayed date has the english M/d/yyyy pattern.
Printing the output of this code in a page confirms that the database of culture information has problems : 

new System.Globalization.CultureInfo("it").DateTimeFormat.ShortDatePattern)
new System.Globalization.CultureInfo("en").DateTimeFormat.ShortDatePattern)

_Copied from original issue: aspnet/AspNetCore#9106_

_Copied from original issue: dotnet/corefx#36631_

**Comment by tarekgh** [comment]
_From @Eilon on Friday, 05 April 2019 16:49:48_

_From @blowdart on Friday, 05 April 2019 16:38:23_

@Eilon can you move this to CoreFx?

**Comment by tarekgh** [comment]
_From @joshfree on Friday, 05 April 2019 21:07:31_

@tarekgh @krwq PTAL

**Comment by tarekgh** [comment]
_From @tarekgh on Friday, 05 April 2019 22:05:29_

@Eilon could you please help explain why you think this is corefx issue? I believe this is about setting the current culture correctly in the web app and not really how the culture behave.

**Comment by tarekgh** [comment]
_From @tarekgh on Friday, 05 April 2019 22:14:42_

CC @blowdart as it looks he is the one asked to move this issue to corefx.  @blowdart please explain why you think this is corefx issue?

**Comment by tarekgh** [comment]
_From @tarekgh on Friday, 05 April 2019 22:45:20_

I have confirmed on Linux (I used Ubuntu 18.04) we are producing the dd/MM/yy pattern for Italian culture. 

@valeriob what Linux distro and version you were running on Azure? and what is the output you are seeing from 

```C#
   new System.Globalization.CultureInfo("it").DateTimeFormat.ShortDatePattern)
   new System.Globalization.CultureInfo("en").DateTimeFormat.ShortDatePattern)
```

Also, would be nice if you can get the output of 
```C#
   new System.Globalization.CultureInfo("it").EnglishName
```

Just to ensure you have the full globalization support there.

**Comment by tarekgh** [comment]
_From @blowdart on Friday, 05 April 2019 22:57:26_

Culture and ageing formatting which isn’t us

________________________________

**Comment by tarekgh** [comment]
_From @tarekgh on Friday, 05 April 2019 23:15:17_

@valeriob I have confirmed on Ubuntu 14.04 we return expected short date pattern for Italian too. Please send the information I requested in https://github.com/dotnet/corefx/issues/36631#issuecomment-480444935

**Comment by tarekgh** [comment]
_From @valeriob on Saturday, 06 April 2019 06:30:15_

Hi,
i'm not using any distribution directly, i'm deploying code in an Azure Linux Web App, it builds a container under the hood automatically as i recon. I've chosen netcore 2.2, and i think it's using an old aspnetcore version 2.2.0.

Both commands output the same value : dd/MM/yyyy

new System.Globalization.CultureInfo("it").DateTimeFormat.ShortDatePattern
new System.Globalization.CultureInfo("en").DateTimeFormat.ShortDatePattern

i will check on monday for this output  new System.Globalization.CultureInfo("it").EnglishName

**Comment by tarekgh** [comment]
_From @tarekgh on Sunday, 07 April 2019 18:01:16_

Thanks @valeriob 

Could you please get the values of the following properties too?

```C#
System.Runtime.InteropServices.RuntimeInformation.OSDescription  
System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription
```

> Both commands output the same value : dd/MM/yyyy

did you mean ```M/d/yyyy```?

**Comment by tarekgh** [comment]
_From @valeriob on Monday, 08 April 2019 07:38:51_

Hi @tarekgh,
yes i meant MM/dd/yyy.

Those are the values :
OSDescription : Linux 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 
FrameworkDescription : .NET Core 4.6.27317.07 
CultureInfo_it_EnglishName : Invariant Language (Invariant Country) 
Cultura Request : it-IT
CulturaUI Request : it-IT
Cultura Thread : it-IT
CulturaUI Thread : it-IT
ShortDatePattern it : MM/dd/yyyy
ShortDatePattern en : MM/dd/yyyy

I'm not deploying any container, i'm using Azure Linux Werb App with code deployment and i selected .netcore 2.2 runtime, using the startup file to run "dotnet /site/wwwroot/mywebsite.dll"

Thanks

**Comment by tarekgh** [comment]
_From @tarekgh on Monday, 08 April 2019 15:38:06_

Looks this has been deployed on a container with turning on the Invariant Globalization mode https://github.com/dotnet/corefx/blob/master/Documentation/architecture/globalization-invariant-mode.md which basically no complete globalization support on such container. I am not sure if there is option to choose the container when deploying? 

@Eilon any idea how the container is chosen in the @valeriob scenario? or do you know who can help in that.

**Comment by tarekgh** [comment]
_From @valeriob on Monday, 08 April 2019 16:05:04_

Those are the app settings taken from kudu

webpages:Enabled = true
deployment_branch = master
SCM_TRACE_LEVEL = Verbose
SCM_COMMAND_IDLE_TIMEOUT = 60
SCM_LOGSTREAM_TIMEOUT = 1800
SCM_BUILD_ARGS =
REMOTEDEBUGGINGVERSION = 15.0.28010.00
WEBSITE_HTTPLOGGING_RETENTION_DAYS = 7
ASPNETCORE_HOSTINGSTARTUPASSEMBLIES = Microsoft.ApplicationInsights.Profiler.AspNetCore
WEBSITE_SITE_NAME = yyyyyyyy
APPINSIGHTS_INSTRUMENTATIONKEY = xxxxxxx
WEBSITE_AUTH_LOGOUT_PATH = /.auth/logout
ASPNETCORE_ENVIRONMENT = Development
WEBSITE_AUTH_ENABLED = False
SCM_USE_LIBGIT2SHARP_REPOSITORY = 0
WEBSITE_WEBDEPLOY_USE_SCM = false
WEBSITE_AUTH_AUTO_AAD = False
ScmType = None

**Comment by tarekgh** [comment]
_From @tarekgh on Monday, 08 April 2019 16:26:26_

I am not seeing any interesting setting 
```
ASPNETCORE_ENVIRONMENT = Development
```
@valeriob could you try other settings than ```Development``` value and figure out if this will make any difference? 

@Eilon any idea if there is any specific settings affect enabling/disabling the [globalization environment mode](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/globalization-invariant-mode.md)?

**Comment by tarekgh** [comment]
_From @Eilon on Monday, 08 April 2019 17:58:20_

> @Eilon any idea how the container is chosen in the @valeriob scenario? or do you know who can help in that.

Sorry no idea.

> @Eilon any idea if there is any specific settings affect enabling/disabling the globalization environment mode?

By default, ASP.NET Core uses whatever culture the host process is using. The developer has to explicitly use loc/glob features of .NET Core or ASP.NET Core to use something else.

**Comment by tarekgh** [comment]
_From @tarekgh on Monday, 08 April 2019 18:16:16_

> By default, ASP.NET Core uses whatever culture the host process is using. The developer has to explicitly use loc/glob features of .NET Core or ASP.NET Core to use something else.

my question was regarding the configuration setting when deploying to Azure. anyway, do you have any contact we can ask how the containers get configured when deploying? Thanks.

**Comment by tarekgh** [comment]
_From @Eilon on Monday, 08 April 2019 20:01:19_

I'm not aware of any config settings that directly affect loc in ASP.NET Core. It would be an app-specific thing, or a general .NET / .NET Core thing.

There's an internal email 'ancant' that you could try contacting to see if there's an Azure App Service specific thing.

**Comment by tarekgh** [comment]
_From @tarekgh on Monday, 08 April 2019 20:49:01_

@valeriob could you please send more details about how you did the deployments? did you choose a container during the deployment? more info here can help.

**Comment by tarekgh** [comment]
_From @valeriob on Tuesday, 09 April 2019 08:12:56_

Hi,
i just created the web app like this : 
![image](https://user-images.githubusercontent.com/1522516/55783676-3d8df180-5aaf-11e9-8e0e-27eb86cb1059.png)
i added the app config WEBSITE_WEBDEPLOY_USE_SCM= false because octopus deploy does not work with it and add startup file = "dotnet /home/site/wwwroot/mywebapp.dll

I do not think the code copy itself is the problem, i've the same result if i ftp into it and copy the output of dotnet publish command into /home/site/wwwroot. I do not know what container it uses to run the code, up to last week it was using an old dotnet 2.2 build, a few days ago has been updated to 2.2.2.

this is the log i get when i restart it :

2019-04-09 08:13:28.822 INFO  - Starting container for site
2019-04-09 08:13:28.849 INFO  - docker run -d -p 5158:8080 --name mywebsiteName_1 -e WEBSITE_SITE_NAME=mywebsiteName -e WEBSITE_AUTH_ENABLED=False -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_INSTANCE_ID=63a6649b66ce55a87e63eef954b71797662516db5aa6ffb28edfb5720b9c7533 -e HTTP_LOGGING_ENABLED=1 appsvc/dotnetcore:2.2.2_1903041701 dotnet /home/site/wwwroot/mywebsite.dll

Thanks

**Comment by tarekgh** [comment]
_From @davidfowl on Thursday, 11 April 2019 07:16:06_

@valeriob we confirmed this is an issue with the base image used on Azure App Service. We're looking into it.

cc @glennc @bradygaster

**Comment by tarekgh** [comment]
_From @valeriob on Thursday, 11 April 2019 08:38:48_

cheers !
For sake of learning, how do i see what image is being used ?

**Comment by tarekgh** [comment]
To summarize, the azure image is enabling the globalization invariant mode by setting the environment variable 

```
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
```

Also, if you are going to remove this environment variable, ensure the libicu is installed on the machine.

**Comment by valeriob** [comment]
So basically just add apk add icu-libs to the apline docker file and remove the environment variable ?
https://github.com/dotnet/dotnet-docker/blob/master/2.2/runtime-deps/alpine3.8/amd64/Dockerfile#L22

It's very strange that the default behavior is without globalization support.

**Comment by tarekgh** [comment]
> So basically just add apk add icu-libs to the apline docker file and remove the environment variable ?

Yes.

> It's very strange that the default behavior is without globalization support.

This is done for specific containers (like Alpine) for the scenarios of the apps that don't care about the globalization. It was an error to have APSNET 2.2 used this container by default. They are working to fix that.

**Comment by valeriob** [comment]
Thanks for clarifying that.
Be aware that this setting is on 2.1 and 3.0 too.
It's very strange nobody noticed it before.

**Comment by tarekgh** [comment]
> Be aware that this setting is on 2.1 and 3.0 too.

How did you confirm that? 

@kichalla, could you please look if the issue is spanning 2.1 and 3.0 too?

**Comment by valeriob** [comment]
I have not tested it, but the docker file has the same commands

**Comment by tarekgh** [comment]
Thanks @valeriob, if this is the case, then @kichalla will take care fixing this for all versions.

Are you ok to close the issue on corefx repo as we are tracking it here?

**Comment by valeriob** [comment]
Sure, thanks

https://github.com/dotnet/dotnet-docker/search?q=DOTNET_SYSTEM_GLOBALIZATION_INVARIANT%3Dtrue&unscoped_q=DOTNET_SYSTEM_GLOBALIZATION_INVARIANT%3Dtrue

**Comment by kichalla** [comment]
@valeriob In AppService, only the 2.2 version of AspNetCore is based on Alpine while the rest of the earlier versions are based on `stretch-slim` which does not have this issue. Just to give some context, AppService depends on the docker images built by Oryx team. We fixed the issue by basing this 2.2 version also on `stretch-slim`, so it is only a matter of time before this new image is applied into AppService.

**Comment by valeriob** [comment]
Thanks @kichalla for explaining it, can you also explain how do i check which image the service is currently using ?

**Comment by tarekgh** [comment]
> can you also explain how do i check which image the service is currently using ?

@kichalla may know better her, but I think one way is to dump the contents of the file ```/etc/os-release``` which can tell.

**Comment by valeriob** [comment]
Hi,
do you have an eta on when the dotnet core 2.2 image on azure Linux web app will be updated ?
Thanks

**Comment by kichalla** [comment]
@valeriob Could you check again? The fix should be available now.

**Comment by valeriob** [comment]
Hi,
i restarted the web app and i do not see any changes : 
ShortDatePattern it : MM/dd/yyyy
ShortDatePattern en : MM/dd/yyyy
Do i need to deploy the code again to use the new base container image ? If so, i'll be able to do it tomorrow.

**Comment by valeriob** [comment]
I made a new deployment, it's still running on alpine 3.8 and the "it" culture is still invariant.

**Comment by kichalla** [comment]
Sorry for the delay in replying @valeriob. I just now checked with my partner team about this and was told that the fix is still getting rolled out (they do region by region) and it seems it would probably take one more week for the change to propagate to your region (Its France region?..could you share the region you chose on the Azure portal?)

**Comment by valeriob** [comment]
Thanks @kichalla,
yes i'm deployed in France Central, i'll  check again next week !

**Comment by valeriob** [comment]
Hi, i can confirm it's fixed, thanks !

**Comment by valeriob** [comment]
Hi, i can confirm it's fixed, thanks !

**Comment by kichalla** [comment]
Great, thanks for letting us know. Closing this issue.
