### ISSUE TITLE
Conflicting apt sources in vso Oryx image

### ISSUE THREAD

**Issue by dmgardiner25** [microsoft/Oryx#703]
### Bug Report

- At what date and time did you most recently experience the problem?
7/30 at 9:15am PDT.

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Visual Studio Codespaces and directly in the Oryx image version `vso-20200719.1` through `docker run`.

- If your repo is publicly available please share its URL:

- What happened?
We had a [user report](https://github.com/MicrosoftDocs/vscodespaces/issues/644) that they were unable to install `ca-certificates` from `apt` because it was trying to pull dependencies from `buster`.

- What did you expect or want to happen?
`ca-certificates` should be able to be installed without issue and `/etc/apt/sources.list.d/buster.list` shouldn't exist while still on `stretch`.

- How can we reproduce it?
1. Create a blank Codespace (by not specifying a repository)
2. Run `sudo apt-get update`
3. Run `sudo apt-get install ca-certificates`

- Do you have log output? Please include between the backticks:

```
root@8833bc8e008c:/# apt-get update
Ign:1 http://deb.debian.org/debian stretch InRelease
Hit:2 http://security.debian.org/debian-security stretch/updates InRelease
Hit:3 http://deb.debian.org/debian stretch-updates InRelease
Hit:4 http://security.debian.org/debian-security buster/updates InRelease
Hit:5 http://deb.debian.org/debian buster InRelease
Hit:6 http://deb.debian.org/debian buster-updates InRelease
Hit:7 http://deb.debian.org/debian stretch Release
Reading package lists... Done
root@8833bc8e008c:/# apt-get install ca-certificates
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ca-certificates : Depends: openssl (>= 1.1.1) but 1.1.0l-1~deb9u1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by kichalla** [comment]
@dmgardiner25 Sorry for the delay in getting back to you on this. We will get out a fix for this.

**Comment by arroyc** [comment]
@dmgardiner25  ... did you check if ca-certificate is already installed? I think it is already there

**Comment by kichalla** [comment]
@dmgardiner25 Thanks for reporting this issue. This was fixed and will be available in our next release

**Comment by kichalla** [comment]
This issue is fixed in our recent images. You can try them and remove any workaround that you might have added at your end to verify. Thanks.
