### ISSUE TITLE
Deploy failed on "oryx build" (rsync error, code 23)

### ISSUE THREAD

**Issue by wyrmling** [microsoft/Oryx#724]
Problem occurs regularly on B2 Web App Service with react app during one of the last `oryx build` operations:

```
Command: oryx build /home/site/repository -o /home/site/wwwroot --platform nodejs --platform-version 12 -i /tmp/8d83ef5595f132c -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
Build orchestrated by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version      : 0.2.20200522.2, Commit: bf724c0e83f3da74487f55cd304c63331dab7067, ReleaseTagName: 20200522.2
Build Operation ID: |A7NJJQQ0IEE=.636bfe8f_
Repository Commit : 13c67d86a59f58204121df2e340ec8a73be6d25a

Using intermediate directory '/tmp/8d83ef5595f132c'.

Copying files to the intermediate directory...
Done in 4 sec(s).

Source directory     : /tmp/8d83ef5595f132c
Destination directory: /home/site/wwwroot


Using Node version:
v12.16.3

Using Npm version:
6.14.4

Running 'npm install --unsafe-perm'...


> node-sass@4.14.1 install /tmp/8d83ef5595f132c/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/.npm/node-sass/4.14.1/linux-x64-72_binding.node

> pre-commit@1.2.2 install /tmp/8d83ef5595f132c/node_modules/pre-commit
> node install.js


> core-js@2.6.11 postinstall /tmp/8d83ef5595f132c/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m

[96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
[96m>[94m https://opencollective.com/core-js [0m
[96m>[94m https://www.patreon.com/zloirock [0m

[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m


> core-js@3.6.5 postinstall /tmp/8d83ef5595f132c/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js-pure@3.6.5 postinstall /tmp/8d83ef5595f132c/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"


> spawn-sync@1.0.15 postinstall /tmp/8d83ef5595f132c/node_modules/spawn-sync
> node postinstall


> node-sass@4.14.1 postinstall /tmp/8d83ef5595f132c/node_modules/node-sass
> node scripts/build.js

Binary found at /tmp/8d83ef5595f132c/node_modules/node-sass/vendor/linux-x64-72/binding.node
Testing binary
Binary is fine
added 2014 packages from 1269 contributors and audited 2022 packages in 162.632s
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})


89 packages are looking for funding
  run `npm fund` for details

found 2 vulnerabilities (1 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

Running 'npm run build'...


> star-web@0.1.0 build /tmp/8d83ef5595f132c
> react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  242.26 KB  build/static/js/2.518899f0.chunk.js
  37.68 KB   build/static/js/main.9ebd8a13.chunk.js
  8.52 KB    build/static/css/main.1681826c.chunk.css
  3.24 KB    build/static/css/2.469057ea.chunk.css
  779 B      build/static/js/runtime-main.cf23afb2.js

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  bit.ly/CRA-deploy


Zipping existing node_modules folder...
Done in 114 sec(s).

Copying files to destination directory '/home/site/wwwroot'...
rsync: rename "/home/site/wwwroot/build/.index.html.2NYVaQ" -> "build/index.html": No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/jest-haste-map/node_modules/fsevents):\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})\n\nrsync: rename "/home/site/wwwroot/build/.index.html.2NYVaQ" -> "build/index.html": No such file or directory (2)\nrsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]\n/opt/Kudu/KuduConsole/Scripts/starter.sh oryx build /home/site/repository -o /home/site/wwwroot --platform nodejs --platform-version 12 -i /tmp/8d83ef5595f132c -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
```

**Comment by poornagollakoti** [comment]
Same problem here for App Service
Command: oryx build /home/site/repository -o /home/site/wwwroot --platform nodejs --platform-version 12 -i /tmp/8d84445e51e40de -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
Build orchestrated by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version      : 0.2.20200522.2, Commit: bf724c0e83f3da74487f55cd304c63331dab7067, ReleaseTagName: 20200522.2
Build Operation ID: |sA1JUmeQK50=.983f3c01_
Repository Commit : 3c03dbc0b861459da4e7e0748aba3b324c189022

Using intermediate directory '/tmp/8d84445e51e40de'.

Copying files to the intermediate directory...
Done in 4 sec(s).

Source directory     : /tmp/8d84445e51e40de
Destination directory: /home/site/wwwroot


Using Node version:
v12.16.3

Using Npm version:
6.14.4

Running 'npm install --unsafe-perm'...

npm WARN clousassessor@1.0.0 No repository field.
added 124 packages from 146 contributors and audited 124 packages in 15.463s


2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


Zipping existing node_modules folder...
Done in 4 sec(s).

Copying files to destination directory '/home/site/wwwroot'...
rsync: close failed on "/home/site/wwwroot/.node_modules.tar.gz.U7z5hL": Input/output error (5)
rsync error: error in file IO (code 11) at receiver.c(859) [receiver=3.1.2]
npm WARN clousassessor@1.0.0 No repository field.\n\nrsync: close failed on "/home/site/wwwroot/.node_modules.tar.gz.U7z5hL": Input/output error (5)\nrsync error: error in file IO (code 11) at receiver.c(859) [receiver=3.1.2]\n/opt/Kudu/Scripts/starter.sh oryx build /home/site/repository -o /home/site/wwwroot --platform nodejs --platform-version 12 -i /tmp/8d84445e51e40de -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log

**Comment by kichalla** [comment]
cc @sanchitmehta

**Comment by esttenorio** [comment]
Same here but instead it cannot find the zipped node_modules and the index.html:

Zipping existing node_modules folder...
Done in 175 sec(s).

Copying files to destination directory '/home/site/wwwroot'...
rsync: rename "/home/site/wwwroot/.node_modules.tar.gz.h6cjoB" -> "node_modules.tar.gz": No such file or directory (2)
rsync: rename "/home/site/wwwroot/build/.index.html.3Vt8n2" -> "build/index.html": No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/chokidar/node_modules/fsevents):\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})\n\nrsync: rename "/home/site/wwwroot/.node_modules.tar.gz.h6cjoB" -> "node_modules.tar.gz": No such file or directory (2)\nrsync: rename "/home/site/wwwroot/build/.index.html.3Vt8n2" -> "build/index.html": No such file or directory (2)\nrsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]\n/opt/Kudu/KuduConsole/Scripts/starter.sh oryx build /home/site/repository -o /home/site/wwwroot --platform nodejs --platform-version 10.14 -i /tmp/8d86f18ab243cee -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log

**Comment by arroyc** [comment]
@wyrmling @esttenorio   still facing this issue?

**Comment by arroyc** [comment]
please feel free to open a new one if you see this issue again
