### ISSUE TITLE
Could not detect any platform in the source directory.

### ISSUE THREAD

**Issue by TataKim** [microsoft/Oryx#753]
## Development Environment
Node / React latest version / Windows 10
IDE: Visual Code (with Azure App Service Extension)

## Outline
When deploying React App by Visual Code Azure App Service Extension, I have faced the below issues during progress. I had success several times almost the same code yesterday. suddenly it makes an error from today. I could not find any root cause of this. 

## Attempt: (Unfortunately, All makes fail.)
1. Clear All Visual Code Cache. 
2. Trying to deploy another azure app service that is in the same resource group. 
3. Trying to deploy another azure app service of the different resource group 
4. Clear Yarn cache, Reinstalling, and Rebuild several times.
5. Rollback source code and Rebuild, Deploy.

Please support. 👋

## Terminal Log
5:12:40 AM xxxxxxx: Repository path is /tmp/zipdeploy/extracted
5:12:40 AM xxxxxxx: Running oryx build...
5:12:40 AM xxxxxxx: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 12 -i /tmp/8d84efed0ced745 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
5:12:43 AM xxxxxxx: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
5:12:43 AM xxxxxxx: You can report issues at https://github.com/Microsoft/Oryx/issues
5:12:43 AM xxxxxxx: Oryx Version: 0.2.20200805.1, Commit: e7c39ede513143e9d80fd553f106f04268d770d4, ReleaseTagName: 20200805.1
5:12:43 AM xxxxxxx: Build Operation ID: |utUR36dG4bg=.708f20fd_
5:12:43 AM xxxxxxx: Repository Commit : 6b64177a73544924939e1f4cd4e4c2f2
5:12:43 AM xxxxxxx: Detecting platforms...
5:12:43 AM xxxxxxx: Could not detect any platform in the source directory.
5:12:43 AM xxxxxxx: Error: Couldn't detect a version for the platform 'nodejs' in the repo.
5:12:46 AM xxxxxxx: Error: Couldn't detect a version for the platform 'nodejs' in the repo.\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 12 -i /tmp/8d84efed0ced745 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
5:12:49 AM xxxxxxx: Deployment failed.

**Comment by TataKim** [comment]
it seems one of an azure issue. I resolved this issue by changing Region of Azure app service.

**Comment by Tredence-GitHub** [comment]
@TataKim atter changing Region did it worked for you? i am also facing same issue while deploying React JS application and currently we are usign WEST-US region. Can you be little more specific with the answer?

**Comment by kimtth** [comment]
> @TataKim atter changing Region did it worked for you? i am also facing same issue while deploying React JS application and currently we are usign WEST-US region. Can you be little more specific with the answer?

I could not find root cause of this issues. but it seems a problem of azure. when this case happened, I change the region of app service to little far place, not same continent or country of current region. e.g . I changed it from japan east to central us or others. It has made always a success. sometimes the region of same continent and country makes a failure.

**Comment by TataKim** [comment]
> @TataKim atter changing Region did it worked for you? i am also facing same issue while deploying React JS application and currently we are usign WEST-US region. Can you be little more specific with the answer?

I could not find a root cause of this issues. but it seems a problem of azure. when this case happened, I change the region of app service to little far place, not same continent or country of current region. e.g . I changed it from japan east to central us or others. It has made always a success. sometimes the region of same continent and country makes a failure.
