### ISSUE TITLE
Oryx deployment ERROR on "detecting platforms..." 

### ISSUE THREAD

**Issue by connyho** [microsoft/Oryx#755]
### Bug Report

- At what date and time did you most recently experience the problem?

Repeatedly since Wednesday, September 2 2020

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.

Deployment of Azure Linux Web App, Python 3.6 (Django app)

- If your repo is publicly available please share its URL:

- What happened?

Local GIT deployment fails with unspecific ERROR:

```
Counting objects: 144, done.
Delta compression using up to 12 threads.
Compressing objects: 100% (135/135), done.
Writing objects: 100% (144/144), 17.94 KiB | 1.05 MiB/s, done.
Total 144 (delta 60), reused 0 (delta 0)
remote: Resolving deltas: 100% (60/60), done.
remote: Deploy Async
remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id 'ed0b35314f'.
remote: Repository path is /home/site/repository
remote: Running oryx build...
remote: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
remote: You can report issues at https://github.com/Microsoft/Oryx/issues
remote:
remote: Oryx Version: 0.2.20200805.1, Commit: e7c39ede513143e9d80fd553f106f04268d770d4, ReleaseTagName: 20200805.1
remote:
remote: Build Operation ID: |O1AJT5OD03E=.e1aba31d_
remote: Repository Commit : ed0b35314f9f162830d26bf1ed3a739ed47a845e
remote:
remote: Detecting platforms...
remote: Error: Oops... An unexpected error has occurred.
```

- What did you expect or want to happen?

Successful deployment. We even reverted our GIT repository to a commit version that was successfully deployed before -> does not work any more! Restarting the web application did also not help.

- How can we reproduce it?

Error is reproducible since yesterday, local git deployment does not work any more. 

- Do you have log output? Please include between the backticks:

Checked serveral log files (kudu, deplyoment...):

```
2020-09-03T12:16:29  Updating branch 'master'.
2020-09-03T12:16:30  Updating submodules.
2020-09-03T12:16:30  Preparing deployment for commit id 'ed0b35314f'.
2020-09-03T12:16:30  Repository path is /home/site/repository
2020-09-03T12:16:30  Running oryx build...
2020-09-03T12:16:30    Command: oryx build /home/site/repository -o /home/site/wwwroot --platform python --platform-version 3.6 -i /tmp/8d8500330c68acd -p compress_virtualenv=tar-gz -p virtualenv_name=antenv3.6 --log-file /tmp/build-debug.log 
2020-09-03T12:16:34    Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
2020-09-03T12:16:34    You can report issues at https://github.com/Microsoft/Oryx/issues
2020-09-03T12:16:34    
2020-09-03T12:16:34    Oryx Version: 0.2.20200805.1, Commit: e7c39ede513143e9d80fd553f106f04268d770d4, ReleaseTagName: 20200805.1
2020-09-03T12:16:34    
2020-09-03T12:16:34    Build Operation ID: |O1AJT5OD03E=.e1aba31d_
2020-09-03T12:16:34    Repository Commit : ed0b35314f9f162830d26bf1ed3a739ed47a845e
2020-09-03T12:16:34    
2020-09-03T12:16:34    Detecting platforms...
2020-09-03T12:16:34    Error: Oops... An unexpected error has occurred.
2020-09-03T12:16:37    Error: Oops... An unexpected error has occurred.
/opt/Kudu/KuduConsole/Scripts/starter.sh oryx build /home/site/repository -o /home/site/wwwroot --platform python --platform-version 3.6 -i /tmp/8d8500330c68acd -p compress_virtualenv=tar-gz -p virtualenv_name=antenv3.6 --log-file /tmp/build-debug.log 
2020-09-03T12:16:37  

```

From kudu trace logs:

```
<step title="Executing external process" date="2020-09-03T12:16:29.108" instance="67b0e6" type="process" path="kudu.exe" arguments="/home/site /opt/Kudu/msbuild" >
  <step title="Cleanup Xml Logs" date="2020-09-03T12:16:29.124" >
    <step title="Cleanup Infos" date="2020-09-03T12:16:29.149" totalFiles="526" totalCleanup="366" /><!-- duration: 8ms -->
  </step><!-- duration: 40ms -->
  <step title="Executing external process" date="2020-09-03T12:16:29.278" type="process" path="git" arguments="log -n 1 master --" /><!-- duration: 147ms -->
  <step title="DeploymentManager.Deploy(id:ed0b35314f9f162830d26bf1ed3a739ed47a845e)" date="2020-09-03T12:16:29.436" >
    <step title="Collecting changeset information" date="2020-09-03T12:16:29.465" /><!-- duration: 440ms -->
    <step title="Updating to specific changeset" date="2020-09-03T12:16:29.912" >
      <step title="Executing external process" date="2020-09-03T12:16:30.299" type="process" path="git" arguments="checkout master --force" /><!-- duration: 157ms -->
    </step><!-- duration: 559ms -->
    <step title="Updating submodules" date="2020-09-03T12:16:30.484" /><!-- duration: 52ms -->
    <step title="Determining deployment builder" date="2020-09-03T12:16:30.613" >
      <step title="Builder is OryxBuilder" date="2020-09-03T12:16:30.625" /><!-- duration: 4ms -->
    </step><!-- duration: 19ms -->
    <step title="Building" date="2020-09-03T12:16:30.659" >
      <step title="Executing external process" date="2020-09-03T12:16:30.759" type="process" path="starter.sh" arguments="oryx build /home/site/repository -o /home/site/wwwroot --platform python --platform-version 3.6 -i /tmp/8d8500330c68acd -p compress_virtualenv=tar-gz -p virtualenv_name=antenv3.6 --log-file /tmp/build-debug.log " >
        <step title="Process dump" date="2020-09-03T12:16:37.391" exitCode="1" type="processOutput" /><!-- duration: 7ms -->
      </step><!-- duration: 6643ms -->
      <step title="Error occurred" date="2020-09-03T12:16:37.425" type="error" text="Error: Oops... An unexpected error has occurred.
/opt/Kudu/KuduConsole/Scripts/starter.sh oryx build /home/site/repository -o /home/site/wwwroot --platform python --platform-version 3.6 -i /tmp/8d8500330c68acd -p compress_virtualenv=tar-gz -p virtualenv_name=antenv3.6 --log-file /tmp/build-debug.log " stackTrace="   at Kudu.Core.Infrastructure.Executable.ExecuteInternal(ITracer tracer, Func`2 onWriteOutput, Func`2 onWriteError, Encoding encoding, String arguments, Object[] args) in /tmp/KuduLite/Kudu.Core/Infrastructure/Executable.cs:line 243
   at Kudu.Core.Infrastructure.Executable.ExecuteWithProgressWriter(ILogger logger, ITracer tracer, String arguments, Object[] args) in /tmp/KuduLite/Kudu.Core/Infrastructure/Executable.cs:line 115
   at Kudu.Core.Deployment.Generator.ExternalCommandBuilder.RunCommand(DeploymentContext context, String command, Boolean ignoreManifest, String message) in /tmp/KuduLite/Kudu.Core/Deployment/Generator/ExternalCommandBuilder.cs:line 111" /><!-- duration: 4ms -->
      <step title="Purge deployment items" date="2020-09-03T12:16:37.651" >
        <step title="Remove temp-8d8a, Pending, received at 9/3/20 12:16:24 PM" date="2020-09-03T12:16:37.678" /><!-- duration: 4ms -->
        <step title="Remove temp-5887, Pending, received at 9/3/20 11:29:06 AM" date="2020-09-03T12:16:37.700" /><!-- duration: 3ms -->
      </step><!-- duration: 56ms -->
    </step><!-- duration: 7066ms -->
    <step title="Error occurred" date="2020-09-03T12:16:37.728" type="error" text="Error: Oops... An unexpected error has occurred.
/opt/Kudu/KuduConsole/Scripts/starter.sh oryx build /home/site/repository -o /home/site/wwwroot --platform python --platform-version 3.6 -i /tmp/8d8500330c68acd -p compress_virtualenv=tar-gz -p virtualenv_name=antenv3.6 --log-file /tmp/build-debug.log " stackTrace="   at Kudu.Core.Infrastructure.Executable.ExecuteInternal(ITracer tracer, Func`2 onWriteOutput, Func`2 onWriteError, Encoding encoding, String arguments, Object[] args) in /tmp/KuduLite/Kudu.Core/Infrastructure/Executable.cs:line 243
   at Kudu.Core.Infrastructure.Executable.ExecuteWithProgressWriter(ILogger logger, ITracer tracer, String arguments, Object[] args) in /tmp/KuduLite/Kudu.Core/Infrastructure/Executable.cs:line 115
   at Kudu.Core.Deployment.Generator.ExternalCommandBuilder.RunCommand(DeploymentContext context, String command, Boolean ignoreManifest, String message) in /tmp/KuduLite/Kudu.Core/Deployment/Generator/ExternalCommandBuilder.cs:line 111
   at Kudu.Core.Deployment.Generator.OryxBuilder.Build(DeploymentContext context) in /tmp/KuduLite/Kudu.Core/Deployment/Generator/OryxBuilder.cs:line 65
   at Kudu.Core.Deployment.DeploymentManager.Build(ChangeSet changeSet, ITracer tracer, IDisposable deployStep, IRepository repository, DeploymentInfoBase deploymentInfo, DeploymentAnalytics deploymentAnalytics, Boolean fullBuildByDefault) in /tmp/KuduLite/Kudu.Core/Deployment/DeploymentManager.cs:line 704" /><!-- duration: 4ms -->
  </step><!-- duration: 8304ms -->
  <step title="Cleaning up temp files" date="2020-09-03T12:16:37.744" /><!-- duration: 4ms -->
  <step title="Reloading status file with latest updates" date="2020-09-03T12:16:37.758" >
    <step title="WebHooksManager.PublishEventAsync: PostDeployment" date="2020-09-03T12:16:37.762" /><!-- duration: 74ms -->
  </step><!-- duration: 85ms -->
  <step title="Executing external process" date="2020-09-03T12:16:37.855" type="process" path="git" arguments="log -n 1 master --" /><!-- duration: 85ms -->
</step><!-- duration: 8836ms -->
```

We don't have a clue what goes wrong - how can we get more detailed information on the error occuring during the oryx build process?

**Comment by kichalla** [comment]
@connyho Thanks for the detailed report. I looked up logs at our end and found the reason behind the error. 

Short answer: As a workaround, create an app setting called `DISABLE_HUGO_BUILD` with value `true` to disable detection for Hugo platform style apps.

Long answer: Oryx tries to detect for different platforms used in a repo. In this process we try to detect for Hugo style apps too. As part of this platform's detection we try to parse files with name `config.json` for example and from our logs seems like deserialization of this file is failing probably due to invalid content. You can check to see if the json file content is valid and if not fix it or you can disable the Hugo platform detection by creating an app setting called `DISABLE_HUGO_BUILD` and set it's value to `true`.

**Comment by connyho** [comment]
We don't have a file named "config.json" in our repository, but the deployment process is successful again with the additional app setting DISABLE_HUGO_BUILD, thanks a lot for the solution!

**Comment by rkrakesh2690** [comment]
Am also experiencing the same issue with an angular application deployed on the Linux App service.
The DevOps pipeline was working till last week but we see the same issue as mentioned by @connyho.

I followed the DISABLE_HUGO_BUILD solution mentioned but it doesn't seem to work for me. However, it does say its skipping detection in the logs but still goes on to detect and fails the deployment.

------------------------------------------------------

Package deployment using ZIP Deploy initiated.
Updating submodules.
Preparing deployment for commit id '6a27f240c2'.
Repository path is /tmp/zipdeploy/extracted
Running oryx build...
Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 10.10 -i /tmp/8d855842babeefe -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20200805.1, Commit: e7c39ede513143e9d80fd553f106f04268d770d4, ReleaseTagName: 20200805.1

Build Operation ID: |bFm2WRn44vA=.d298846f_
Repository Commit : 6a27f240c25e49b4a91b5536e84ed297

Detecting platforms...
Platform 'hugo' has been disabled, so skipping detection for it.
Could not detect any platform in the source directory.
Error: Couldn't detect a version for the platform 'nodejs' in the repo.
Error: Couldn't detect a version for the platform 'nodejs' in the repo.\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 10.10 -i /tmp/8d855842babeefe -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
##[error]Failed to deploy web package to App Service.
##[error]Error: Package deployment using ZIP Deploy failed. Refer logs for more details.

-----------------------------------------------------------------------------------------

**Comment by kichalla** [comment]
@rkrakesh2690 If possible could you share a repro for this issue?

**Comment by rkrakesh2690** [comment]
@kichalla It won't be possible to share the code base, but if you want to look at the structure of the repo to check for some files. Here it is.

![image](https://user-images.githubusercontent.com/46018474/92848558-f9bbbc00-f407-11ea-9f0f-e84c0283defa.png)

If you are looking for any specific configuration file, then please let me know.

**Comment by bhanutej-pr** [comment]
@rkrakesh2690 I am also facing the same issue , have you got any workaround.

**Comment by kichalla** [comment]
@rkrakesh2690 Oryx looks for `package.json` in the root directory to determine if it is a node app. From the app snapshot I do not see a package.json. What kind of app is this? are you trying to deploy a static files webiste?

@bhanutej-pr Is this the case in your scenario too? are you trying to deploy a static files webiste?

cc @sanchitmehta

**Comment by kichalla** [comment]
@rkrakesh2690 Are you trying to deploy to Azure Static Web Apps? If yes, for the app folder you need to specify "app" folder present in the repo. I suppose that is the folder which has package.json in it.

**Comment by surajsoni5** [comment]
I'm also facing a similar problem starting recently. Though setting `DISABLE_HUGO_BUILD`  to `true` worked for me, but not sure what exactly happening here. I don't have any `config.json` files in my repo.

**Comment by kichalla** [comment]
FYI: we made changes at our end to ignore parsing exceptions when trying to detect for Hugo based files. We are just waiting for App Service to deploy this fix.

**Comment by arroyc** [comment]
This has been deployed to appservice .. please feel free to open an issue if you get one ...

**Comment by arroyc** [comment]
@cod2017  can you please share the repo structure here and some more info about your repo? Where are you trying to deploy this? Azure web app or somewhere else?

**Comment by cod2017** [comment]
![20210303_151928](https://user-images.githubusercontent.com/26476946/109787143-ef021700-7c33-11eb-9f43-664ca904ccff.jpg)
This is a nodejs app which is deployed to Azure app service. It was working fine few days back but suddenly throwing this error.

**Comment by arroyc** [comment]
@cod2017 can you please also attach the build log the failures?

**Comment by cod2017** [comment]
@arroyc it is the same error mentioned above by @connyho

**Comment by arroyc** [comment]
@cod2017 .. are you in some special app service environment (ASE) or have special network/dns settings?

**Comment by shahedurrahman** [comment]
Having similar issues :( Trying to deploy on Linux App Service. Project does contain project.json file.

Here is the log:

>2021-03-25T13:43:07.9796683Z Package deployment using ZIP Deploy initiated.
2021-03-25T13:44:11.8511094Z Updating submodules.
2021-03-25T13:44:11.8512722Z Preparing deployment for commit id '0c0732dc-f'.
2021-03-25T13:44:11.8513380Z Repository path is /tmp/zipdeploy/extracted
2021-03-25T13:44:11.8513904Z Running oryx build...
2021-03-25T13:44:12.2106425Z Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 10.14 -i /tmp/8d8ef940898e124 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
2021-03-25T13:44:12.2107810Z Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
2021-03-25T13:44:12.2108416Z You can report issues at https://github.com/Microsoft/Oryx/issues
2021-03-25T13:44:12.2108764Z 
2021-03-25T13:44:12.2109310Z Oryx Version: 0.2.20210120.1, Commit: 66c7820d7df527aaffabd2563a49ad57930999c9, ReleaseTagName: 20210120.1
2021-03-25T13:44:12.2109939Z 
2021-03-25T13:44:12.2110309Z Build Operation ID: |xLJVBJPUGZg=.2795aadd_
2021-03-25T13:44:12.2111462Z Repository Commit : 0c0732dc-fc1f-41aa-998c-af6dddd64b77
2021-03-25T13:44:12.2111748Z 
2021-03-25T13:44:12.2112091Z Detecting platforms...
2021-03-25T13:44:12.2112737Z Platform 'hugo' has been disabled, so skipping detection for it.
2021-03-25T13:44:12.2113257Z Could not detect any platform in the source directory.
2021-03-25T13:44:12.2113948Z Error: Couldn't detect a version for the platform 'nodejs' in the repo.
2021-03-25T13:44:12.2115285Z Error: Couldn't detect a version for the platform 'nodejs' in the repo.\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 10.14 -i /tmp/8d8ef940898e124 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
2021-03-25T13:44:12.2146355Z ##[error]Failed to deploy web package to App Service.
2021-03-25T13:44:12.2157418Z ##[error]Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
2021-03-25T13:44:13.9865206Z Successfully updated deployment History at https://shop2shipapi-dev.scm.azurewebsites.net/api/deployments/71616679852473
2021-03-25T13:44:14.3129761Z App Service Application URL: http://shop2shipapi-dev.azurewebsites.net
2021-03-25T13:44:14.3267265Z ##[section]Finishing: Deploy Azure App Service

**Comment by CuriousUser513** [comment]
> @cod2017 .. are you in some special app service environment (ASE) or have special network/dns settings?

I have a similar problem and we have a special network configuration that prevents traffic going out from our private network.
It's a python project and we have all our dependencies in the deployed package, but seems oryx still tries to reach out to some external site and fails with "Error: Oops... An unexpected error has occurred." We have Hugo build disabled.
Can this be related to the problems in this thread or should I create a new issue?

**Comment by kankomi** [comment]
I set the `DISABLE_HUGO_BUILD` to `true` in the app settings and in the logs it does say its skipping detection. It detects correctly that I'm using nodejs, but still fails trying to detect a php version. I also don't have a `config.json` file anywhere in my repo.

```
Command: oryx build /home/site/repository -o /home/site/wwwroot --platform php --platform-version 7.0 -i /tmp/8d8f2825ba30713 --log-file /tmp/build-debug.log 

Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20210120.1, Commit: 66c7820d7df527aaffabd2563a49ad57930999c9, ReleaseTagName: 20210120.1
Build Operation ID: |ICn+UUHf+t4=.32571102_
Repository Commit : 924115962cddc7256e23c187740acdc85ed19343

Detecting platforms...
Platform 'hugo' has been disabled, so skipping detection for it.
Detected following platforms:

  nodejs: 14.15.1

Error: Couldn't detect a version for the platform 'php' in the repo.

Error: Couldn't detect a version for the platform 'php' in the repo.\n/opt/Kudu/Scripts/starter.sh oryx build /home/site/repository -o /home/site/wwwroot --platform php --platform-version 7.0 -i /tmp/8d8f2825ba30713 --log-file /tmp/build-debug.log 
```

**Comment by shahedurrahman** [comment]
> Having similar issues :( Trying to deploy on Linux App Service. Project does contain project.json file.
> 
> Here is the log:
> 
> > 2021-03-25T13:43:07.9796683Z Package deployment using ZIP Deploy initiated.
> > 2021-03-25T13:44:11.8511094Z Updating submodules.
> > 2021-03-25T13:44:11.8512722Z Preparing deployment for commit id '0c0732dc-f'.
> > 2021-03-25T13:44:11.8513380Z Repository path is /tmp/zipdeploy/extracted
> > 2021-03-25T13:44:11.8513904Z Running oryx build...
> > 2021-03-25T13:44:12.2106425Z Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 10.14 -i /tmp/8d8ef940898e124 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log
> > 2021-03-25T13:44:12.2107810Z Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
> > 2021-03-25T13:44:12.2108416Z You can report issues at https://github.com/Microsoft/Oryx/issues
> > 2021-03-25T13:44:12.2108764Z
> > 2021-03-25T13:44:12.2109310Z Oryx Version: 0.2.20210120.1, Commit: [66c7820](https://github.com/microsoft/Oryx/commit/66c7820d7df527aaffabd2563a49ad57930999c9), ReleaseTagName: 20210120.1
> > 2021-03-25T13:44:12.2109939Z
> > 2021-03-25T13:44:12.2110309Z Build Operation ID: |xLJVBJPUGZg=.2795aadd_
> > 2021-03-25T13:44:12.2111462Z Repository Commit : 0c0732dc-fc1f-41aa-998c-af6dddd64b77
> > 2021-03-25T13:44:12.2111748Z
> > 2021-03-25T13:44:12.2112091Z Detecting platforms...
> > 2021-03-25T13:44:12.2112737Z Platform 'hugo' has been disabled, so skipping detection for it.
> > 2021-03-25T13:44:12.2113257Z Could not detect any platform in the source directory.
> > 2021-03-25T13:44:12.2113948Z Error: Couldn't detect a version for the platform 'nodejs' in the repo.
> > 2021-03-25T13:44:12.2115285Z Error: Couldn't detect a version for the platform 'nodejs' in the repo.\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 10.14 -i /tmp/8d8ef940898e124 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log
> > 2021-03-25T13:44:12.2146355Z ##[error]Failed to deploy web package to App Service.
> > 2021-03-25T13:44:12.2157418Z ##[error]Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
> > 2021-03-25T13:44:13.9865206Z Successfully updated deployment History at https://shop2shipapi-dev.scm.azurewebsites.net/api/deployments/71616679852473
> > 2021-03-25T13:44:14.3129761Z App Service Application URL: http://shop2shipapi-dev.azurewebsites.net
> > 2021-03-25T13:44:14.3267265Z ##[section]Finishing: Deploy Azure App Service

Working now!

In my case, the artifact was coming from Azure DevOps where inside the zip file, all the project files were within another folder. That's why Oryx couldn't detect the project type because it couldn't find the project.json in root directory. To change that, I had to set following in the pipeline configuration (Archive files task).

`includeRootFolder: false`

**Comment by kankomi** [comment]
I found a workaround for my case, you have to set the stack manually.
Go to the AppService under `Configuration` -> `General Settings` and set your stack there, in my case `node`.
If you deploy via terraform you can set the stack under the `site_config` like this: 
```hcl
resource "azurerm_app_service" "server_app" {
...
  site_config {
    always_on = true
    linux_fx_version = "NODE|12-lts"
  }

...
```

After this at least the zip deployment is working.

**Comment by arroyc** [comment]
This issue is getting lot of traction here it seems, but because this issue was created long back, so I guess it's not the original bug  for which the issue has been created earlier ... Can someone please create a new issue and we can follow up there @kankomi @shahedurrahman  @cod2017 .. if you are still facing the same issue please create a new issue. It will be easier to track. Once I get the new issue I will close this one
