### ISSUE TITLE
Oryx build failing for linux web app in Azure Deployment Center - Bitbucket repos

### ISSUE THREAD

**Issue by praneshshzl** [microsoft/Oryx#770]
Hello all,

I'm using a azure web app (linux\php) and using deployment center to connect to a bitbucket repos.
after files copy over to **site/repository** , the deployment to **site/wwwroot** fails with below error
```
Command: oryx build /home/site/repository -o /home/site/wwwroot --platform php --platform-version 7.3 -i /tmp/8d857c177ada0b0 --log-file /tmp/build-debug.log 
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20200805.1, Commit: e7c39ede513143e9d80fd553f106f04268d770d4, ReleaseTagName: 20200805.1

Build Operation ID: |v/gkZ5Er4A4=.ced0cf00_
Repository Commit : 246d978f335acec04dfbd17fc61dd02060ca8e83

Detecting platforms...
Could not detect any platform in the source directory.
Error: Couldn't detect a version for the platform 'php' in the repo.
Error: Couldn't detect a version for the platform 'php' in the repo.\n/opt/Kudu/Scripts/starter.sh oryx build /home/site/repository -o /home/site/wwwroot --platform php --platform-version 7.3 -i /tmp/8d857c177ada0b0 --log-file /tmp/build-debug.log 
```

This is a new linux web app, should i be adding something in the repos to fix this?
The same repos builds fine in a asp.net web app (windows) w\o any issues and uses deploy.cmd from the /deployment/tools directory.

**Comment by praneshshzl** [comment]
I used a composer.json file in my repo to fix this: copy the below code and create a composer.json and commit it to repo.
```
{
    "name": "devops/ms",
    "require": {
        "php": "7.3.0"
    }
}

```
Now my build is successful.
```
Command: oryx build /home/site/repository -o /home/site/wwwroot --platform php --platform-version 7.3 -i /tmp/8d857c62ceddffa --log-file /tmp/build-debug.log 
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20200805.1, Commit: e7c39ede513143e9d80fd553f106f04268d770d4, ReleaseTagName: 20200805.1

Build Operation ID: |4MhxvbqMtyo=.4918f70c_
Repository Commit : 673d3af1552949d83a449bff7625992fffd6abc2

Detecting platforms...
Detected following platforms:
  php: 7.3.15

Using intermediate directory '/tmp/8d857c62ceddffa'.

Copying files to the intermediate directory...
Done in 0 sec(s).

Source directory     : /tmp/8d857c62ceddffa
Destination directory: /home/site/wwwroot

PHP executable: /opt/php/7.3.15/bin/php
Composer archive: /opt/php-composer/composer.phar
Running 'composer install --ignore-platform-reqs --no-interaction'...

Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files

Copying files to destination directory '/home/site/wwwroot'...
Done in 0 sec(s).

Removing existing manifest file
Creating a manifest file...
Manifest file created.

Done in 17 sec(s).
```

**Comment by PaulDash** [comment]
> {
>     "name": "devops/ms",
>     "require": {
>         "php": "7.3.0"
>     }
> }

Thanks, praneshshzl, this also worked for me.

Except that my Azure DevOps repo is a static HTML website. Why do I need a file like this if Oryx says platform parameter is not mandatory? There is nothing in its documentation that I found about HOW it detects the platform.

So yes, the composer.json file solved it, but... how about writing out all the values the detection could be looking for? What if I want to deploy a .NET Core website? What would be the "require" part???

**Comment by praneshshzl** [comment]
@PaulDash You will have to check the Oryx configuration at https://github.com/Microsoft/Oryx/blob/master/doc/configuration.md#oryx-configuration.
And see which app setting in azure web app enables you to ignore platform parameters and such.
My guess is that its forcing the --platform php --platform-version 7.3 in the build command based on how the azure web app was setup initially, and looks like azure webapp cannot be setup (during creation) with just static html code in mind. Backend technology stack is enforced.
If somehow the --platform php --platform-version 7.3 is no longer forced when azure automates the build command, then composer.json is no longer required.
