### ISSUE TITLE
Not able to deploy Angular App to Linux NodeJs Web App Server from VS Code.

### ISSUE THREAD

**Issue by bhanutej-pr** [microsoft/Oryx#780]
### Bug Report

- At what date and time did you most recently experience the problem?
18-09-2020

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
 Azure Web App Service Deployment

- If your repo is publicly available please share its URL:

- What happened?
 Using Vs Code to deploy angular build code to respective Web App Server(Linux with Node), but it is failing.

- What did you expect or want to happen?
Application should have deployed

- How can we reproduce it?
1. Build the angular code using **ng build --prod**
2. Now from VS Code using Azure App Service Extension deploy the build code(dist folder) to web app server.

- Do you have log output? Please include between the backticks:
![image](https://user-images.githubusercontent.com/57625605/93581078-454d0780-f9be-11ea-8609-352725943525.png)

```

```

**Comment by bhanutej-pr** [comment]
Hi I tried the **DISABLE_HUGO_BUILD** solution , but it is not working. Do we have any other solution for this?

**Comment by jacckjacck** [comment]
Hi, same error here!

**Comment by kichalla** [comment]
@bhanutej-pr and @jacckjacck : are you trying to deploy locally built app to AppService? In that case you can use the following setting to fix it: `SCM_DO_BUILD_DURING_DEPLOYMENT=false`
More info here: https://github.com/projectkudu/kudu/wiki/Configurable-settings#enabledisable-build-actions

**Comment by kichalla** [comment]
gentle ping

**Comment by jacckjacck** [comment]
Hi @kichalla, today I tried to publish again from VSCode and it worked without problem but I did not change any configuration.

**Comment by kichalla** [comment]
Thanks for the update @jacckjacck .

I am closing this issue now. If you are still facing this issue, please open a new one with more details so that we can reproduce on our side.
