### ISSUE TITLE
NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.1

### ISSUE THREAD

**Issue by phil000** [microsoft/Oryx#787]
I've seen many differing posts on whether .NET 3.1 is supported via oryx build yet.
What's the story in **Australia East**

-----------------------------------------------------------------
Command: oryx build /home/site/repository -o /tmp/build/expressbuild --platform dotnet --platform-version 2.2 -i /tmp/8d85eb479913e8d
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20200805.1, Commit: e7c39ede513143e9d80fd553f106f04268d770d4, ReleaseTagName: 20200805.1

Detecting platforms...
Detected following platforms:
  dotnet: 2.2.7

Using .NET Core SDK Version: 2.2.402
/opt/dotnet/sdks/2.2.402/sdk/2.2.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.1.

**Comment by niklevinsky** [comment]
Similar problem here, wondering if it has anything to do with the fact that I am trying to deploy to a function app that is tied to an older app service plan.  The .NET Core 3.1 function deployed from VSCode and runs great on the same plan, only getting the failed status in Deployment Center when trying to setup continuous deployment from GitHub.

```
Command: oryx build /home/site/repository -o /tmp/build/expressbuild --platform dotnet --platform-version 2.2 -i /tmp/8d85f6f04546e51
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20200805.1, Commit: e7c39ede513143e9d80fd553f106f04268d770d4, ReleaseTagName: 20200805.1

Build Operation ID: |5XMKNQccV/8=.2d39c64f_
Repository Commit : 65a15d76859a31e4797dabb0f14f2fd5c5dc0325

Detecting platforms...
Detected following platforms:
  dotnet: 2.2.7

Using intermediate directory '/tmp/8d85f6f04546e51'.

Copying files to the intermediate directory...
Done in 0 sec(s).

Source directory     : /tmp/8d85f6f04546e51
Destination directory: /tmp/build/expressbuild


Using .NET Core SDK Version: 2.2.402
/opt/dotnet/sdks/2.2.402/sdk/2.2.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.1. [/tmp/8d85f6f04546e51/somdomainredirect.csproj]
\n/opt/Kudu/Scripts/starter.sh oryx build /home/site/repository -o /tmp/build/expressbuild --platform dotnet --platform-version 2.2 -i /tmp/8d85f6f04546e51
```

**Comment by kichalla** [comment]
@phil000 and @niklevinsky From the logs I see that `--platform-version 2.2` is being used but I suppose you are using `3.1` .NET Core app. Why are you choosing `2.2` version in AppService though?

cc @sanchitmehta

**Comment by niklevinsky** [comment]
Likely my misunderstanding, I don't see a way to update the .NET version in AppService plans, but will do some additional research.  As I mentioned it is an older app service plan, but because the 3.1 function runs I assume it was present.

**Comment by phil000** [comment]
@kichalla 
I didn't choose anything. As far as i can see thee is no way to choose or specify the -platform-version.
 All i did was setup CI in the Function App and the tool\SDK version (2.2) was chosen for me.

**Comment by kichalla** [comment]
cc @Hazhzeng Do you know why this is happening?

**Comment by Hazhzeng** [comment]
@phil000, This seems like the issue when your local project is targeting netcoreapp3.1, while your function app in Azure is targeting ~2. Try changing the appsetting in your function app **FUNCTIONS_EXTENSION_VERSION** to **~3** should solve this issue.

**Comment by phil000** [comment]
Hello.
I've just had a look and the runtime version is ~3 already.

It is running on Linux also.

![image](https://user-images.githubusercontent.com/9067236/95244630-b6ba0080-086e-11eb-8081-eeb0de2215a6.png)

**Comment by kichalla** [comment]
Thanks @Hazhzeng and @phil000 . I will consider this as fixed and closing the issue.

**Comment by phil000** [comment]
How is this fixed? The suggestion is not relevant as the function is already ion Runtime v3 as shown.

**Comment by Hazhzeng** [comment]
Sorry @phil000, I misunderstood your question. Could you check if the LinuxFxVersion is properly set to DOTNET|3 in https://resources.azure.com/subscriptions/<subscription_id>/resourceGroups/<resource_group_name>/providers/Microsoft.Web/sites/<function_app_name>/config/web.

If not, please use "Read/Write" mode, edit the LinuxFxVersion field, and do a PUT request. This will ensure your function app is running on DOTNET|3. The Oryx Build requires this field to derive which SDK to use when building your dotnet app.

**Comment by phil000** [comment]
linuxFxVersion
DOTNET|3.1

**Comment by wonsil** [comment]
I'm seeing the exact same behavior. 

    "netFrameworkVersion": "v4.0",
    "phpVersion": "",
    "pythonVersion": "",
    "nodeVersion": "",
    "powerShellVersion": "",
    "linuxFxVersion": "dotnet|3.1",

but the Oryx build log starts this way:

Command: oryx build /home/site/repository -o /tmp/build/expressbuild --platform dotnet --platform-version 2.2 -i /tmp/8......

I've searched all of the nodes in the tree and don't see the string 2.2 anywhere. Where is Oryx getting it? Could it be hard-coded and not be pulling it from linexFxVersion?

Maybe this fix? https://github.com/microsoft/Oryx/pull/806
