### ISSUE TITLE
Zip deployment failed for Python.

### ISSUE THREAD

**Issue by Yorihito** [microsoft/Oryx#788]
### Bug Report
When I tried following the command line, deployment failed.
>az webapp up --sku B1 -n flightlogvv -l koreasouth

Here is the log.
[
    {
        "log_time": "2020-09-23T01:41:33.5354297Z",
        "id": "",
        "message": "Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.7 -i /tmp/8d85f61cd49a938 -p compress_virtualenv=tar-gz -p virtualenv_name=antenv --log-file /tmp/build-debug.log ",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2020-09-23T01:41:36.7296675Z",
        "id": "",
        "message": "Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2020-09-23T01:41:36.7656573Z",
        "id": "",
        "message": "You can report issues at https://github.com/Microsoft/Oryx/issues",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2020-09-23T01:41:36.7829442Z",
        "id": "",
        "message": "",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2020-09-23T01:41:36.8146914Z",
        "id": "",
        "message": "Oryx Version: 0.2.20200805.1, Commit: e7c39ede513143e9d80fd553f106f04268d770d4, ReleaseTagName: 20200805.1",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2020-09-23T01:41:36.8323392Z",
        "id": "",
        "message": "",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2020-09-23T01:41:36.8380583Z",
        "id": "",
        "message": "Build Operation ID: |VAjJMAGlrgI=.2a7b4d0_",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2020-09-23T01:41:36.8449923Z",
        "id": "",
        "message": "Repository Commit : 99fdc2921bb84a08b15f35476ccc08fc",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2020-09-23T01:41:36.8544126Z",
        "id": "",
        "message": "",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2020-09-23T01:41:36.861191Z",
        "id": "",
        "message": "Detecting platforms...",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2020-09-23T01:41:37.0172878Z",
        "id": "",
        "message": "Detected following platforms:",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2020-09-23T01:41:37.1143744Z",
        "id": "",
        "message": "  python: 3.7.7",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2020-09-23T01:41:37.4877702Z",
        "id": "",
        "message": "",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2020-09-23T01:41:37.6065826Z",
        "id": "",
        "message": "Using intermediate directory '/tmp/8d85f61cd49a938'.",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2020-09-23T01:41:37.6271674Z",
        "id": "",
        "message": "",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2020-09-23T01:41:37.638472Z",
        "id": "",
        "message": "Copying files to the intermediate directory...",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2020-09-23T01:41:37.666296Z",
        "id": "",
        "message": "Done in 0 sec(s).",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2020-09-23T01:41:37.6859534Z",
        "id": "",
        "message": "",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2020-09-23T01:41:37.712356Z",
        "id": "",
        "message": "Source directory     : /tmp/8d85f61cd49a938",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2020-09-23T01:41:37.7422285Z",
        "id": "",
        "message": "Destination directory: /home/site/wwwroot",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2020-09-23T01:41:37.7615891Z",
        "id": "",
        "message": "",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2020-09-23T01:41:37.9809282Z",
        "id": "",
        "message": "/tmp/BuildScriptGenerator/0d55b0ac98614213ad21ecaaa33dbb1f/build.sh: line 97: source: filename argument required",
        "type": 1,
        "details_url": null
    },
    {
        "log_time": "2020-09-23T01:41:37.9998479Z",
        "id": "",
        "message": "source: usage: source filename [arguments]",
        "type": 1,
        "details_url": null
    },
    {
        "log_time": "2020-09-23T01:41:41.2148005Z",
        "id": "",
        "message": "/tmp/BuildScriptGenerator/0d55b0ac98614213ad21ecaaa33dbb1f/build.sh: line 97: source: filename argument required\\nsource: usage: source filename [arguments]\\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.7 -i /tmp/8d85f61cd49a938 -p compress_virtualenv=tar-gz -p virtualenv_name=antenv --log-file /tmp/build-debug.log ",
        "type": 2,
        "details_url": null
    }
]

**Comment by claitonbecoco** [comment]
We are also having this problem for the past 2 weeks.

**Comment by Yorihito** [comment]
I saw the same issue today several times. But currently no more repro. Closing this.

**Comment by claitonbecoco** [comment]
This is not our experience, we are still getting the same error as stated here, this has been happening for the past 3 weeks, an Azure function that used to deploy just fine started to get this error, and even new function plans are also doing the same.

**Comment by Yorihito** [comment]
When I got the same error after I posted above, what I did was clean up the folder which has app.py. Actually, I had jupyter notebook in the same folder, and I moved that to a subfolder. After doing this I never saw the error. HTH.

**Comment by claitonbecoco** [comment]
Thanks for the recommendation! I can give that a try.
When you mean clean up the folder, did you remove the Python cache? we havent added any new files to our folder.

**Comment by Yorihito** [comment]
In my case, I didn't clear that. Folders as is, made files are app.py and requiremets.txt only.
