### ISSUE TITLE
Remote build fails for Azure Python Function app deployment using func azure functionapp publish <myapp>

### ISSUE THREAD

**Issue by EdFarrell** [microsoft/Oryx#791]
### Bug Report

- At what date and time did you most recently experience the problem?
9/25/2020 1pm EST

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Functions

- If your repo is publicly available please share its URL:
No

- What happened?
Attempted to redeploy a function app using cli 

`func azure functionapp publish <myapp> `

This triggers a remote build.

- What did you expect or want to happen?
I expected the remote build to be successful and to deploy to the function app. 

- How can we reproduce it?
Create a consumption python function app on python 3.7. Deploy some code, try to redeploy. 

- Do you have log output? Please include between the backticks:

```
PS C:\Users\Ed\Documents\azure-devops-repos\peco-function-backup> func azure functionapp publish peco-fun-py
Getting site publishing info...
Creating archive for current directory...
Performing remote build for functions project.
Deleting the old .python_packages directory
Uploading 67.33 KB [##############################################################################]
Remote build in progress, please wait...
Updating submodules.
Preparing deployment for commit id 'dc8438fa74'.
Repository path is /tmp/zipdeploy/extracted
Running oryx build...
Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.7 -p packagedir=.python_packages/lib/site-packages
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20200813.1, Commit: 16c4841161ae3c639fd26b0212be4f55e515ef7d, ReleaseTagName: 20200813.1

Build Operation ID: |hibj+A1xHn4=.66aa299f_
Repository Commit : dc8438fa749240299bcb3907e5f6972c

Detecting platforms...
Detected following platforms:
  python: 3.7.9


Source directory     : /tmp/zipdeploy/extracted
Destination directory: /home/site/wwwroot

/tmp/BuildScriptGenerator/d46a450f27a24437a612ade16acc0cc0/build.sh: line 91: source: filename argument required
source: usage: source filename [arguments]
/tmp/BuildScriptGenerator/d46a450f27a24437a612ade16acc0cc0/build.sh: line 91: source: filename argument required\nsource: usage: source filename [arguments]\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.7 -p packagedir=.python_packages/lib/site-packages
Remote build failed!
```

**Comment by kichalla** [comment]
@EdFarrell Could you please let me know if your repo has any Conda based environment.yaml file or .ipynb files? My suspicion is these files are being detected and Oryx is trying to create a conda envirnoment which is failing. Could you try removing these files and try again? We are currently working on a fix related to this.

**Comment by kichalla** [comment]
Based on your comments in the following issue, I am assuming your issue got resolved, so I am closing this issue and keeping the following one open.
https://github.com/microsoft/Oryx/issues/795
