### ISSUE TITLE
Oryx error for Hugo with valid config.toml

### ISSUE THREAD

**Issue by joshdcar** [microsoft/Oryx#801]
### Bug Report

NOTE: This issue was originally reported at https://github.com/Azure/static-web-apps/issues/160 but was advised it should be moved here. 

- At what date and time did you most recently experience the problem?

9/29/2020

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.

Azure Static Web Apps

- If your repo is publicly available please share its URL:

https://github.com/joshdcar/azure-static-web-app-hugo-build-fail

- What happened?

I recently changed the theme and the corresponding config.toml on an Azure Static Web App configured for Hugo. The build had previously worked. The build started throwing an "Oops.. An unexpected error has occurred" following the update.  The Hugo site built and ran fine locally and the config.toml was valid. 

- What did you expect or want to happen?

If the config.toml is valid Oryx build should not fail.  Worse case the build should provide a more useful error details to help diagnose the issue. 

- How can we reproduce it?

I discovered the root cause of this issue to be "section" ordering in the config.toml. The configuration itself is valid for Hugo (runs\builds fine locally) and the toml is of course valid but will fail in Oryx.

Oryx throw an error after "Detecting platforms..." when a "sub-section" is defined before the "root" section.  

    [params.search]
     enable = true

    [params]
     author = "my name"

However the following works successfully:

    [params]
     author = "my name" 

    [params.search]
     enable = true

After playing with around a dozen themes I found this pattern to be fairly prevalent.  I agree that logically [params] should appear before [params.search] but in general, if the configuration is valid for Hugo it should IMO work in Oryx \ Azure Static Web Apps as well.  I couldn't figure out how to get some more diagnostic details from Oryx. 

I set up a repo that you can use to reproduce this issue at https://github.com/joshdcar/azure-static-web-app-hugo-build-fail . The repo has the same details in the readme and it's also wired up to an azure static web app where I've "broken" the build on purpose.  If you need additional permissions to the repo or details on the static web app instance please let me know. 

- Do you have log output? Please include between the backticks:

![image](https://user-images.githubusercontent.com/24570240/94476867-12b1c480-019f-11eb-8343-826b9b4d373f.png)

**Comment by qianz2** [comment]
Hi @joshdcar ,
Thanks for reporting the issue. When Oryx detect if it's a Hugo app, it checks if a` .toml` file exists and parse the file to check if it's valid. If the parser failed to parse, Oryx will catch a `FailedToParseException `and so it will not be detected as a hugo app. In this case, the parser failed. Here is what it looks like when directly use Oryx to build. 
When Azure static web app utilizes Oryx to build, it didn't bring the error messages up to you. 

```
root@0e3fb7367558:/# oryx build /apps/azure-static-web-app-hugo-build-fail-master/ --debug
Debug mode enabled
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.0.0, Commit: 5c115e90ee51f03c048e3a0898f721969ab13c14, ReleaseTagName:

Build Operation ID: |0hmAzdVOaR4=.db0cf46f_

Detecting platforms...
Could not detect any platform in the source directory.
Error: Could not detect the language from repo.
```

**Comment by kichalla** [comment]
As discussed let us see if we have options to make the order of items less stricter.

**Comment by kichalla** [comment]
Similar to issue: https://github.com/microsoft/Oryx/issues/752

**Comment by qianz2** [comment]
We've updated toml file parser, so this issue is resolved and will be updated in the latest release. Thanks for reporting the issue. We'll close this.
