### ISSUE TITLE
Virtual environment activation fails for python antenv3.6

### ISSUE THREAD

**Issue by connyho** [microsoft/Oryx#804]
### Bug Report

- At what date and time did you most recently experience the problem?
always

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Linux Web App (Django), python 3.6
Deployment Method: Local GIT

- If your repo is publicly available please share its URL:

- What happened?

Tried to activate virtual environment via ssh, but pip freeze does not list site-packages although they are in the according directory. According to startup.sh the compressed virtual environment is extracted to /antenv3.6.
Tried `source /antenv3.6/bin/activate` , but `pip freeze` does not list packages in /antenv3.6/lib/python3.6/site-packages.
Activation script contains reference to temporary directory, which does not exist any more:
```
#/antenv3.6/bin/activate
VIRTUAL_ENV="/tmp/8d865343e1e1833/antenv3.6"
export VIRTUAL_ENV
```

- What did you expect or want to happen?

Correct virtual environment activation, listing of our installed packages and being able to execute management commands. 

- How can we reproduce it?

- Do you have log output? Please include between the backticks:

From /opt/startup/startup.sh:
```
#!/bin/sh


# Enter the source directory to make sure the script runs where the user expects
cd /home/site/wwwroot

if [ -z "$HOST" ]; then
                export HOST=0.0.0.0
fi

export PORT=8000

export PATH="/opt/python/3.6.10/bin:${PATH}"
echo Found virtual environment .tar.gz archive.
extractionCommand="tar -xzf antenv3.6.tar.gz -C /antenv3.6"
echo Removing existing virtual environment directory '/antenv3.6'...
rm -fr /antenv3.6
mkdir -p /antenv3.6
echo Extracting to directory '/antenv3.6'...
$extractionCommand
PYTHON_VERSION=$(python -c "import sys; print(str(sys.version_info.major) + '.'
+ str(sys.version_info.minor))")
echo Using packages from virtual environment 'antenv3.6' located at '/antenv3.6'
.
export PYTHONPATH=$PYTHONPATH:"/antenv3.6/lib/python$PYTHON_VERSION/site-package
s"
echo "Updated PYTHONPATH to '$PYTHONPATH'"
GUNICORN_CMD_ARGS="--timeout 600 --access-logfile '-' --error-logfile '-' --bind
=0.0.0.0:8000 --chdir=/home/site/wwwroot" gunicorn instance.wsgi
```

**Comment by kichalla** [comment]
@connyho Thanks for the detailed information. We recently fixed this issue in Oryx and it will be available in the next deployment of AppService.

cc @sanchitmehta @JennyLawrance

**Comment by arroyc** [comment]
this fix is available .. so closing this issue .. feel free to open an issue for any problems
