### ISSUE TITLE
Deployment failing with unknown error

### ISSUE THREAD

**Issue by dexajit** [microsoft/Oryx#808]
### Bug Report

- At what date and time did you most recently experience the problem?
2020-10-02 1140hours

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Functions

- If your repo is publicly available please share its URL:
Repo is private

- What happened?
Deployment failed. Error is unknown

- What did you expect or want to happen?
Deployment to go through. No major changes in repo 

- How can we reproduce it?
Function app was created with python 3.8.
Using Durable functions for this activity
Run  func azure functionapp publish <function-appname>

- Do you have log output? Please include between the backticks:

```
Getting site publishing info...
Creating archive for current directory...
Performing remote build for functions project.
Deleting the old .python_packages directory
Uploading 16.83 KB [##############################################################################]
Remote build in progress, please wait...
Updating submodules.
Preparing deployment for commit id '8d194d3d12'.
Repository path is /tmp/zipdeploy/extracted
Running oryx build...
Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.8 -p packagedir=.python_packages/lib/site-packages
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20200813.1, Commit: 16c4841161ae3c639fd26b0212be4f55e515ef7d, ReleaseTagName: 20200813.1

Build Operation ID: |AqiMtu/LAfU=.ac34c615_
Repository Commit : 8d194d3d12cc4c6bae6f9dd8ff771f70

Detecting platforms...
Error: Oops... An unexpected error has occurred.
Error: Oops... An unexpected error has occurred.\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.8 -p packagedir=.python_packages/lib/site-packages
Remote build failed!
```

**Comment by dexajit** [comment]
Our last deployment was successful on 2020-09-22 with below versions of oryx.

  Oryx Version      : 0.2.20200310.1, Commit: f4b40f6ea0763678611b86b0ff9a48c922edcc46, ReleaseTagName: 20200310.1
  Build Operation ID: |CzM176naVGU=.8b87f836_
  Repository Commit : c9e4bbc06ccd427b8c007ba65726f217
  Source directory     : /tmp/zipdeploy/extracted
  Destination directory: /home/site/wwwroot
  Python Version: /opt/python/3.8.2/bin/python3

**Comment by qianz2** [comment]
@dexajit Could you please share more details about the app you build. Does your repo has any Conda environment.yaml file or .ipynb files? Oryx added support for Conda and it's probably detecting these files as Conda environment. If you have these files, please clean these files and try again. We're working on fixing it, thanks!

**Comment by dexajit** [comment]
@qianz2 I am not using environment.yaml file or .ipynb files in my app. function app is python 3.8 based Durable functions. There is a python package in activity function to call HTTP endpoint In activity function for maintenance activities for Azure accounts.

**Comment by kichalla** [comment]
@dexajit I checked our logs and found that the reason your build is failing is because Oryx is trying to parse a .yaml file in your repo to determine if it is a Hugo type app(Oryx tries to detect different kind of apps as part of the build process). We fixed this issue in later builds where we no longer throw an exception when we are unable to parse an yaml file. For now, as a workaround you can apply the setting `DISABLE_HUGO_BUILD=true` and try again.

**Comment by itahirov** [comment]
Hello @kichalla ,   Did you fixed the issue only for function applications or for linux web apps as well ? 
We faced the same behavior on web application which had been mitigated by setting  DISABLE_HUGO_BUILD=true
