### ISSUE TITLE
Deployment failure of App Service  python webapp from vscode using AZURE:APP Service

### ISSUE THREAD

**Issue by sindexdev** [microsoft/Oryx#810]
2020-10-07  11:05 EST

Issue : Azure Web App Service Deployment failure

Deploy failure with build.sh 

11:05:26 AM sindexhello: /tmp/BuildScriptGenerator/742b4894c11a4ea49232d4f96490c044/build.sh: line 97: source: filename argument required
11:05:26 AM sindexhello: source: usage: source filename [arguments]
11:05:30 AM sindexhello: /tmp/BuildScriptGenerator/742b4894c11a4ea49232d4f96490c044/build.sh: line 97: source: filename argument required\nsource: usage: source filename [arguments]\n/opt/Kudu/Scripts/starter.sh oryx build 

This is the output from the output console

11:05:16 AM sindexhello: Starting deployment...
11:05:17 AM sindexhello: Creating zip package...
11:05:17 AM sindexhello: Zip package size: 385 kB
11:05:19 AM sindexhello: Fetching changes.
11:05:19 AM sindexhello: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/89056073-8f69-448f-ae3a-82ee763e7101.zip (0.37 MB) to /tmp/zipdeploy/extracted
11:05:22 AM sindexhello: Updating submodules.
11:05:22 AM sindexhello: Preparing deployment for commit id '7e69fa4a55'.
11:05:22 AM sindexhello: Repository path is /tmp/zipdeploy/extracted
11:05:22 AM sindexhello: Running oryx build...
11:05:22 AM sindexhello: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.6 -i /tmp/8d86ad269b9003c -p compress_virtualenv=tar-gz -p virtualenv_name=antenv3.6 --log-file /tmp/build-debug.log 
11:05:24 AM sindexhello: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
11:05:24 AM sindexhello: You can report issues at https://github.com/Microsoft/Oryx/issues
11:05:25 AM sindexhello: Oryx Version: 0.2.20200805.1, Commit: e7c39ede513143e9d80fd553f106f04268d770d4, ReleaseTagName: 20200805.1
11:05:25 AM sindexhello: Build Operation ID: |vYan5YE/Hks=.9da3f5ca_
11:05:25 AM sindexhello: Repository Commit : 7e69fa4a553a49b5b9b285482beea2f7
11:05:25 AM sindexhello: Detecting platforms...
11:05:25 AM sindexhello: Detected following platforms:
11:05:25 AM sindexhello:   python: 3.6.10
11:05:25 AM sindexhello: Using intermediate directory '/tmp/8d86ad269b9003c'.
11:05:26 AM sindexhello: Copying files to the intermediate directory...
11:05:26 AM sindexhello: Done in 1 sec(s).
11:05:26 AM sindexhello: Source directory     : /tmp/8d86ad269b9003c
11:05:26 AM sindexhello: Destination directory: /home/site/wwwroot
11:05:26 AM sindexhello: /tmp/BuildScriptGenerator/742b4894c11a4ea49232d4f96490c044/build.sh: line 97: source: filename argument required
11:05:26 AM sindexhello: source: usage: source filename [arguments]
11:05:30 AM sindexhello: /tmp/BuildScriptGenerator/742b4894c11a4ea49232d4f96490c044/build.sh: line 97: source: filename argument required\nsource: usage: source filename [arguments]\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.6 -i /tmp/8d86ad269b9003c -p compress_virtualenv=tar-gz -p virtualenv_name=antenv3.6 --log-file /tmp/build-debug.log 
11:05:39 AM sindexhello: Deployment failed.

**Comment by kichalla** [comment]
@sindexdev Thanks for reporting the issue. Could you please check if the workaround mentioned here would fix your issue? https://github.com/microsoft/Oryx/issues/795#issuecomment-700162458
We fixed it at our end and are waiting for AppService to deploy it.

**Comment by sindexdev** [comment]
The workaround of removing the .ipynb file worked. App was successfully deployed. Thanks for quick turnaround on this issue.
