### ISSUE TITLE
Oryx/Build official Python 3.9.0 support

### ISSUE THREAD

**Issue by Hazhzeng** [microsoft/Oryx#811]
### Feature Request

Getting the 202009291 oryx/build image and the Python 3.9 is still using 3.9.0b1 (released on 05/19/2020). Since the Azure Functions team is working on releasing Python 3.9 now, the remote build depends on the latest offical 3.9.0 (released on 10/06/2020).

![image](https://user-images.githubusercontent.com/48038149/95392026-ea1b8000-08ac-11eb-881c-1171677db36c.png)

Please update us when the oryx/build image supports the offical 3.9.0.

cc: @anirudhgarg @vrdmr @stefanushinardi

**Comment by kichalla** [comment]
This is fixed and available now.
