### ISSUE TITLE
I get this message: "Error: Platform 'java' version '11.0.8' is unsupported. Supported versions:"

### ISSUE THREAD

**Issue by dphizler** [microsoft/Oryx#822]
This started happening yesterday afternoon.

We have an azure app service which contains a PHP 5.6 app

We use local git to deploy to that app using git remotes.

The command we use is 
`git push remote-name HEAD:master`

This is the entire message that appears in the git bash dialog:
```
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 8 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 382 bytes | 127.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Checking connectivity: 4, done.
remote: Deploy Async
remote: Updating branch 'master'.
remote: ............
remote: Updating submodules.
remote: Preparing deployment for commit id '3731bff201'.
remote: Repository path is /home/site/repository
remote: Running oryx build...
remote: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
remote: You can report issues at https://github.com/Microsoft/Oryx/issues
remote:
remote: Oryx Version: 0.2.20200917.1, Commit: 59deb778658a124cb74ea8e2c8f39fa87abcc9d9, ReleaseTagName: 20200917.1
remote:
remote: Build Operation ID: |A+SucU1uce4=.5b60ab5f_
remote: Repository Commit : 3731bff20118d7747e4e6d99c795f058fc469a64
remote:
remote: Detecting platforms...
remote: .....................................................................
remote: Error: Platform 'java' version '11.0.8' is unsupported. Supported versions:
remote: Deployment Logs : 'xxxx'
To yyyy
   4595f2cc5..3731bff20  HEAD -> master
```
(I've replaced a few urls with xxxx and yyyy)

I believe the key here is: Platform 'java' version '11.0.8' is unsupported

I just don't know where that can be fixed. 

I've tried searching for answers but all I found was a suggestion to set this value to false:
`SCM_DO_BUILD_DURING_DEPLOYMENT= FALSE`

I've tried deploying with other apps and I get the same issue.

**Comment by grant-unwin** [comment]
Looking at the Oryx source, the java detector seems to be triggering as your project contains files with either `.java` or `.jsp` extensions.

This could potentially be because of a node module you are using that contains java files.

You can override this by configuring **Runtime Stack** property in your Azure App Service deploy step in Azure DevOps to the version of Node you require.

[![enter image description here][1]][1]


[Source][2]


  [1]: https://i.stack.imgur.com/5VKhv.png
  [2]: https://github.com/microsoft/Oryx/blob/a6b4b3d3a7e255432c33561f195be8776748f5b2/src/Detector/Java/JavaDetector.cs

**Comment by aspexi** [comment]
Any ideas for PHP applications? Just recently issue has started. We don't have any .java or .jsp files in the repository.

The only work around for this that works is to change PHP version from 7.3 to 7.4.

**Comment by MS-alsulli** [comment]
@aspexi @dphizler 

Just as a disclaimer - I do not support the Oryx repo or any issues that come with it, but I have been working with someone that has had this issue. If you add an application setting "DISABLE_JAVA_BUILD" = true then this should stop oryx from looking for java platforms in the first place. Could give this a try as another workaround.

**Comment by aspexi** [comment]
@MS-alsulli thank you.

Setting `DISABLE_JAVA_BUILD=true` did the trick for me.

**Comment by MS-alsulli** [comment]
@aspexi Are you deploying locally, through Azure DevOps, etc.?

**Comment by aspexi** [comment]
> @aspexi Are you deploying locally, through Azure DevOps, etc.?

Azure - App Service - Deployment Center (Kudu, Git, Bitbucket).

**Comment by kichalla** [comment]
@aspexi Would it be possible for you to share a repro app of this issue?

**Comment by aspexi** [comment]
@kichalla I'm afraid not at this time. I can only say it's WordPress installation that does not include any `.java` or `.jsp` files.

**Comment by kichalla** [comment]
Thanks @aspexi . Oryx does a recursive directory lookup of presence of those files. So you are sure that your repo does not any `.java` or `.jsp` files anywhere in the repo? (I ask this because in the past we have seen where apps have unexpected file extensions in installed modules/packages etc.)

**Comment by aspexi** [comment]
@kichalla I indeed found `.java` file in my project. It was in W3 Total Cache plugin (https://wordpress.org/support/topic/java-file-presence-causing-deployment-issues-with-azure-kudu-oryx/).

**Comment by qianz2** [comment]
Close it as it was resolved.
