### ISSUE TITLE
Use npm ci instead of npm install

### ISSUE THREAD

**Issue by jpoiron** [microsoft/Oryx#823]
### Feature Request

Hi, I was wondering if it's possible to use `npm ci` instead of `npm install` when building node.js apps. 

It looks like I could possibly use a [custom build command](https://docs.microsoft.com/en-us/azure/static-web-apps/github-actions-workflow#custom-build-commands) such as `npm ci && npm run build` but if I'm understanding correctly, `npm install` will still always be run automatically first and it might update my dependencies and package-lock.json on me. My goal is to have predictable builds and I'm worried that some sneaky issues could get into other environments if npm install is used.

Thanks!

**Comment by qianz2** [comment]
Hi @jpoiron, thanks for providing us feedbacks. Your understanding is correct, currently we always run `npm install` command before any custom build command. We'll analyze and discuss within team about this feature request, and get back to you. Thanks!

**Comment by HarryGifford** [comment]
@qianz2 I'm not the original person, but it would be useful for my use case to be able to override the `npm install` command. I'm using [PNPM](https://pnpm.js.org/) for a project instead of NPM due to some improved features such as workspaces and would like to be able to use it to build Azure static web apps. Running `npm install` causes the build to fail, since NPM doesn't know where to find the workspace packages (since they're not published.)

**Comment by qianz2** [comment]
Close this as we have added an environment variable `CUSTOM_BUILD_COMMAND`, which enables to override npm install commands. It's in the latest release. Please check it out.

**Comment by jpoiron** [comment]
That's great! I'll check it out soon. If there are any docs you can point me to that would be great. But it sounds like to accomplish what I want I just need to add `CUSTOM_BUILD_COMMAND` to the `env` section of the Azure/static-web-apps-deploy GitHub action and set it to `npm ci && npm run build`. Does that sound right? 

Also, do I need to bump the version of the GitHub action? Currently I have it set to`Azure/static-web-apps-deploy@v0.0.1-preview` and I don't see any other versions within the GitHub actions UI.
