### ISSUE TITLE
Pip fails to install the latest version of tensorflow | pip upgrade required 

### ISSUE THREAD

**Issue by neilmario70** [microsoft/Oryx#824]
I am trying to host a flask application that uses tensorflow 2.3.1 on azure web services with python 3.6 run time.

You can find screen shots and a detailed descriptions over here [here](https://stackoverflow.com/questions/64482622/azure-flask-web-app-with-python-3-6-runtime-unable-to-install-tensorflow-2-x-du)

Coming to my stack. 

My **requirements.txt**

```
Flask==1.1.2
tensorflow==2.3.1
Keras==2.4.3
scikit-learn==0.23.2
pdf2image==1.14.0
Pillow==8.0.0
python-resize-image==1.1.19
azure-storage-blob==12.5.0
azure-cosmosdb-table==1.0.6
```

Now when I push my application to the newly created service using git and kudu build services, I get the below error

**remote: No matching distribution found for tensorflow==2.3.1 (from -r requirements.txt (line 53))
remote: You are using pip version 18.1, however version 20.2.4 is available.**

When I login to my app service using scm and check the version of pip it shows the latest version. 

When I replace tensorflow==2.3.1 with just tensorflow in the **requirements.txt**, it deploys successfully with tensorflow version 1.14 but I do not want this version.

How do I get the pip version of the virtual environment that azure is creating to get upgraded to the latest version and install tensorflow 2.3? Tensorflow says that we need pip version greater than 19 to be able to install tensorflow 2.

**Comment by arroyc** [comment]
thanks @nerilmario for reporting .. will try to repro this issue by using the similar requirement.txt that you have provided in your stackoverflow thread
