### ISSUE TITLE
Error: Couldn't detect a version for the platform 'nodejs' in the repo.

### ISSUE THREAD

**Issue by sdev99** [microsoft/Oryx#826]
9:23:55 PM KellisprepWeb: Repository path is /tmp/zipdeploy/extracted
9:23:55 PM KellisprepWeb: Running oryx build...
9:23:55 PM KellisprepWeb: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 10 -i /tmp/8d87a9082204486 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
9:23:56 PM KellisprepWeb: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
9:23:56 PM KellisprepWeb: You can report issues at https://github.com/Microsoft/Oryx/issues
9:23:56 PM KellisprepWeb: Oryx Version: 0.2.20200917.1, Commit: 59deb778658a124cb74ea8e2c8f39fa87abcc9d9, ReleaseTagName: 20200917.1
9:23:56 PM KellisprepWeb: Build Operation ID: |74ubcv1jop8=.9fbdd4bd_
9:23:56 PM KellisprepWeb: Repository Commit : 62ed694699fe4e428ad01ef0ed7b88be
9:23:56 PM KellisprepWeb: Detecting platforms...
9:23:56 PM KellisprepWeb: Could not detect any platform in the source directory.
9:23:57 PM KellisprepWeb: Error: Couldn't detect a version for the platform 'nodejs' in the repo.
9:23:57 PM KellisprepWeb: Error: Couldn't detect a version for the platform 'nodejs' in the repo.\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 10 -i /tmp/8d87a9082204486 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
9:24:10 PM KellisprepWeb: Deployment failed.

**Comment by arroyc** [comment]
thanks for reporting .. would be able to provide a sample repo structure to me? like where is you package.json located in your repo? how are you trying to deploy? are you using azure app service kudu build service or something else?

**Comment by sdev99** [comment]
now i uploaded success it to azure via pipline but in url it showing default page

**Comment by robbie-li** [comment]
I got same issue, when I want to deploy my app static html/js/css under dist folder.
I think I don't need to run oryx build during my deployment, but I have no idea how to disable this step.

**Comment by rudymiked** [comment]
how did you fix this @robbie-li?
