### ISSUE TITLE
Azure Functions Powershell Support

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/Oryx#835]
### Feature Request

Powershell is a supported-in-production azure function backend. It should be very easy to support as it requires no compilation, just a zip deploy of the API folder. It can be detected from the host.json file easily.

**Comment by arroyc** [comment]
@JustinGrote  .. thanks for raising this .. we have similar task in our backlog .. we will be working on it and will update this thread once it's there

**Comment by arroyc** [comment]
I have listed it in our workitems ... you will be notified once it's released. Closing this issue for now. Feel free to reopen this or open a new one.
