### ISSUE TITLE
5.0rc2 builds broken now that 5.0RTM dotnet was released but 5.0RTM nuget packages not present yet

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/Oryx#838]
### Bug Report

- At what date and time did you most recently experience the problem?
2020-09-07

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Static Web Apps Github Action

- If your repo is publicly available please share its URL:
https://github.com/JustinGrote/AzurePrice/actions/runs/351398712

- What happened?
5.0rc2 builds failing because the system now detects 5.0 runtime but the 5.0 nuget packages are not released. I imagine this is a transient issue that will be cleaned up in a couple days but I also want to know how to work around it in the future if it happens (e.g. 6.0)

- What did you expect or want to happen?
Build 5.0 project. Is there a way to manually specify an RC version to the oryx downloader via the github action?

- How can we reproduce it?
Start an RC2 project and try to build it in Static Web Apps

- Do you have log output? Please include between the backticks:

```

Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20200929.1, Commit: 0266eb9f094e3f18e2d73c438dcbb2be70841922, ReleaseTagName: 20200929.1

Build Operation ID: |1vAzuMdQ59M=.5566b026_
Repository Commit : a939a28a66f02f486a57a4def38c31574bd8c5af

Detecting platforms...
Detected following platforms:
  dotnet: 5.0.0
Version '5.0.0' of platform 'dotnet' is not installed. Generating script to install it...


Source directory     : /github/workspace/Client
Destination directory: /bin/staticsites/ss-oryx/app


Downloading and extracting 'dotnet' version '5.0.100' to '/tmp/oryx/platforms/dotnet/5.0.100'...
Downloaded in 0 sec(s).
Verifying checksum...
Extracting contents...
Done in 5 sec(s).


Using .NET Core SDK Version: 5.0.100

Welcome to .NET 5.0!
---------------------
SDK Version: 5.0.100

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
  Determining projects to restore...
  Restored /github/workspace/Shared/Shared.csproj (in 1.78 sec).
/github/workspace/Client/Client.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.browser-wasm with version (= 5.0.0)
/github/workspace/Client/Client.csproj : error NU1102:   - Found 6 version(s) in nuget.org [ Nearest version: 5.0.0-rc.2.20475.5 ]
/github/workspace/Client/Client.csproj : error NU1213: The package Microsoft.NETCore.App.Runtime.browser-wasm 5.0.0-rc.2.20475.5 has a package type DotnetPlatform that is incompatible with this project. 
/github/workspace/Client/Client.csproj : error NU1213: The package Microsoft.NETCore.App.Runtime.browser-wasm 5.0.0-rc.2.20475.5 has a package type DotnetPlatform that is incompatible with this project. 
  Failed to restore /github/workspace/Client/Client.csproj (in 4.99 sec).


---End of Oryx build logs---
Oryx has failed to build the solution.

```

**Comment by dknittl** [comment]
Thank you for opening this issue! I'm having the same problem since yesterday with my RC2 project failing to build in Github Actions.

**Comment by Courra** [comment]
Same issue - RC2 project failing to build in Github Actions

**Comment by macekkrystof** [comment]
Hello, I've been facing same issue since yesterday. I hope it will be fixed with .NET 5 official release.

**Comment by kichalla** [comment]
Ah, sorry to know that your builds have broken. Yes these failures should go away once .NET 5 is released, but meanwhile you can try couple of workarounds to overcome this issue:

Add global.json to your repo with the following content which pins the SDK version
```
{
  "sdk": {
    "version": "5.0.100-rc.2.20479.15",
    "rollForward": "disable"
  }
}
```

OR

Add an environment variable in your github action workflow which sets the `runtime version` explicitly:  
`DOTNET_VERSION="5.0.0-rc.2.20475.5"`

**Comment by JustinGrote** [comment]
@kichalla doesn't work, even if you pin to 20475.5 it downloads 20479.15 anyways, and then it complains that 20479.15 isn't supported by oryx

**Comment by JustinGrote** [comment]
Now that .NET 5 is released, this works as expected when setting the project to net5.0, and a proper workaround was provided by @kitchalla
