### ISSUE TITLE
I got this message when deploying Azure Functions : 'Error: Platform 'java' version '11.0.8' is unsupported. Supported versions: '

### ISSUE THREAD

**Issue by imhfk** [microsoft/Oryx#839]
I got the following error message when deploying Azure Functions on Azure Environment
I changed the vscode setting that enables Java11 but it doesn't work well.
Would someone know hot to solve this problem?? I do wanna avoid this error...

### Bug Report

```
10:01:46 gx-zejappsfa001: Running oryx build...
10:01:46 gx-zejappsfa001: Command: oryx build /tmp/zipdeploy/extracted -o /tmp/build/expressbuild --platform python --platform-version 3.8 -i /tmp/8d8844b0834c358 -p packagedir=.python_packages/lib/site-packages
10:01:48 gx-zejappsfa001: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
10:01:48 gx-zejappsfa001: You can report issues at https://github.com/Microsoft/Oryx/issues
10:01:48 gx-zejappsfa001: Oryx Version: 0.2.20200917.1, Commit: 59deb778658a124cb74ea8e2c8f39fa87abcc9d9, ReleaseTagName: 20200917.1
10:01:48 gx-zejappsfa001: Build Operation ID: |97Ih+oNKEiM=.38673213_
10:01:48 gx-zejappsfa001: Repository Commit : 2ca49cc6b04c4ca4b58d74d38f5c54ff
10:01:48 gx-zejappsfa001: Detecting platforms...
10:01:50 gx-zejappsfa001: Error: Platform 'java' version '11.0.8' is unsupported. Supported versions: 
10:01:52 gx-zejappsfa001: Error: Platform 'java' version '11.0.8' is unsupported. Supported versions:\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /tmp/build/expressbuild --platform python --platform-version 3.8 -i /tmp/8d8844b0834c358 -p packagedir=.python_packages/lib/site-packages
10:02:00 gx-zejappsfa001: Deployment failed.
```

**Comment by imhfk** [comment]
Hi, I fixed this issue on my own.
My function app is made up of Python. So I don't need Java .

Hence,as the previous ticket shows, I go to the Azure App Service's Configuration Setting and set the new variable on the following.

「DISABLE_JAVA_BUILD=true」

After this setting, the deployment was successful.
That really did work to me!!!
Thanks.

**Comment by kichalla** [comment]
Hi @imhfk Can you please provide the repro app for this issue? We would like to investigate why Java is being detected for your repo.

**Comment by kichalla** [comment]
Closing this issue as we have not heard back from you.

**Comment by trstruth** [comment]
@kichalla I ran into this issue as well on a python only function app instance

setting `DISABLE_JAVA_BUILD=true` in the app configuration solved the issue.

I can provide repro information if you're still interested - what all do you need as identifiers?

**Comment by sshojiro** [comment]
Unlike the ticket, would you know if there's a way to install Java into Python runtime of Azure Functions? If so, please let me know. I achieved this on my local test env built on a Dockerfile (https://github.com/Azure/azure-functions-docker/issues/498#issuecomment-917325452), but I could not reproduce the environment on Oryx, the producion env of Azure Functions.

I'd happy to hear any advices. Thanks,
S
