### ISSUE TITLE
Add support for TimerTriggers

### ISSUE THREAD

**Issue by KelvinTegelaar** [microsoft/Oryx#840]
### Feature Request

Timer triggers for webapps can be super useful, triggering APIs based on time based events instead of just HTTP triggers opens up a lot of possibilities:

- Refreshing a client/server token before it expires
- Expiring sessions
- Connecting to a second API(or other middleware) based on a specific time/date
- time based edits on files/folders/Azure File Tables/etc.

Seeing as the Azure Functions host support time based triggers, why not allow those too? :)

(I am unsure if this issue should be here, or in the Azure/Static-web-apps github. If this is the wrong location, please notify me and I will close it here and open it there.)

**Comment by arroyc** [comment]
@KelvinTegelaar  this seems to be more like an feature request for Azure static web apps
