### ISSUE TITLE
Dotnet 5 SDK

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/Oryx#843]
### System Package Request

- Why do you need this package? For example, are you using a language-level package which depends on this system package?
Dotnet SDK 5.0.100

- Which Oryx language runtime and version are you using? For example, "Node.js v10.14" or "Python v3.7".
Dotnet SDK 5.0.100

- What is the name of the package in the latest stable Debian release?For examples, see <https://packages.debian.org/stable/>.

- Do you need a specific version? If so, which and why?
Speed up Oryx operations by not needing to download it separately

**Comment by qianz2** [comment]
Hi @JustinGrote, thanks for the request. We recently added .NET SDK 5.0.100, please check Oryx latest release.

**Comment by JustinGrote** [comment]
@qianz2 Thanks, not seeing it with Azure Static WebApps builds but they are still running `0.2.20200929.1` upon further inspection.

**Comment by JustinGrote** [comment]
@quianz2 per https://github.com/Azure/static-web-apps/issues/206, Azure Static Webapps has been updated but it's still not finding the local dotnet. Can you investigate with @kichalla and @miwebst?

**Comment by kichalla** [comment]
Hi @JustinGrote .NET 5 SDK is dynamically installed during build. Also Static Web Apps has been updated to a latest version of Oryx. Are you seeing builds fail?

**Comment by JustinGrote** [comment]
@kichalla no but both 2.0 and 3.0 are added into the base image, why not 5.0 now? If the goal is to minify the image, why not remove 2.0 and 3.0 at this point?

**Comment by kichalla** [comment]
> @kichalla no but both 2.0 and 3.0 are added into the base image, why not 5.0 now? If the goal is to minify the image, why not remove 2.0 and 3.0 at this point?

Yes that is our end goal but we are rolling this out in stages. In Azure Static Web Apps, no SDKs are pre-baked into the image but only in AppService we currently have 2.1, 2.2, 3.0 and 3.1 baked into the image. These too will move to dynamic install.

**Comment by JustinGrote** [comment]
@kichalla thanks for the update.
