### ISSUE TITLE
Python Azure Functions and proxy issue

### ISSUE THREAD

**Issue by davidfmatheson** [microsoft/Oryx#849]
### Bug Report

- At what date and time did you most recently experience the problem?
2020/11/12 1:00pm EST

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Deploying Python code to an Azure Function App

- What happened?
We cannot deploy Python code to a running Azure Function, either from VS Code or the command line. I believe this is because Oryx does not respect the environment variables for our corporate proxy.

- What did you expect or want to happen?
I expected that the code would be pushed to our Azure Function app successfully.

- How can we reproduce it?
From behind a proxy which is intended to route all traffic to the outside internet, try to deploy some boilerplate Python code to a function app running in Azure: `func azure functionapp publish function-app-linux-python`. Note that the code deploys fine if I invoke local building: `func azure functionapp publish function-app-linux-python --build local`.

- Do you have log output?

```
Getting site publishing info...
Updating Application Settings for Remote build...
Creating archive for current directory...
Performing remote build for functions project.
Deleting the old .python_packages directory
Uploading 2.43 KB [###############################################################################]
Remote build in progress, please wait...
Updating submodules.
Preparing deployment for commit id '09d0a5295b'.
Repository path is /tmp/zipdeploy/extracted
Running oryx build...
Command: oryx build /tmp/zipdeploy/extracted -o /tmp/build/expressbuild --platform python --platform-version 3.8 -i /tmp/8d887372fad37ca -p packagedir=.python_packages/lib/site-packages
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20200917.1, Commit: 59deb778658a124cb74ea8e2c8f39fa87abcc9d9, ReleaseTagName: 20200917.1

Build Operation ID: |KO+V1E+vyYk=.4bcef954_
Repository Commit : 09d0a5295bd1433e873974650f1d6e92

Detecting platforms...
Detected following platforms:
  python: 3.8.5

Using intermediate directory '/tmp/8d887372fad37ca'.

Copying files to the intermediate directory...
Done in 0 sec(s).

Source directory     : /tmp/8d887372fad37ca
Destination directory: /tmp/build/expressbuild

Python Version: /opt/python/3.8.5/bin/python3.8

Running pip install...
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4b9f2f9a90>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4ba158c5e0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4ba15be730>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4ba15be640>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4ba15be430>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
ERROR: Could not find a version that satisfies the requirement azure-functions (from -r requirements.txt (line 5)) (from versions: none)
ERROR: No matching distribution found for azure-functions (from -r requirements.txt (line 5))
Done in 390 sec(s).
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4b9f2f9a90>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/\nWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4ba158c5e0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/\nWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4ba15be730>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/\nWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4ba15be640>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/\nWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4ba15be430>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/\nERROR: Could not find a version that satisfies the requirement azure-functions (from -r requirements.txt (line 5)) (from versions: none)\nERROR: No matching distribution found for azure-functions (from -r requirements.txt (line 5))\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /tmp/build/expressbuild --platform python --platform-version 3.8 -i /tmp/8d887372fad37ca -p packagedir=.python_packages/lib/site-packages
Remote build failed!
```

**Comment by qianz2** [comment]
Hi @davidfmatheson, if you have a self configured pip.conf file, you may need to manually tell pip where your configuration file located by setting environment variable like this: `PIP_CONFIG_FILE=~/.config/pip/pip.conf`

**Comment by davidfmatheson** [comment]
Hi @qianz2! I tried `export PIP_CONFIG_FILE=~/.config/pip/pip.conf` and then `func azure functionapp publish function-app-linux-python`, and I still have the same problem.

**Comment by arroyc** [comment]
is it still an issue @davidfmatheson ?

**Comment by davidfmatheson** [comment]
Hi @arroyc! I have not tried this specific use case in some time, and we do not have plans to try this scenario anytime soon. Feel free to close the issue. If anyone else comes across this issue, they may have better luck configuring a private endpoint on their function app so that the proxy is not implicated.

**Comment by chandrabisen** [comment]
@davidfmatheson : I am facing the exact same issue while deploying Python azure function through Visual studio code. Can you suggest how we can resolve this issue?
8:00:48 PM azfn-eus2-tminor-mdm-001: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb1489fa90>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
8:00:48 PM azfn-eus2-tminor-mdm-001: WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb1489fb20>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
8:00:48 PM azfn-eus2-tminor-mdm-001: WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb148b0310>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
8:00:48 PM azfn-eus2-tminor-mdm-001: WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb148b01f0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
8:00:48 PM azfn-eus2-tminor-mdm-001: WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb148a9940>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
8:00:48 PM azfn-eus2-tminor-mdm-001: ERROR: Could not find a version that satisfies the requirement azure-functions==1.13.0b1 (from -r requirements.txt (line 5)) (from versions: none)
8:00:48 PM azfn-eus2-tminor-mdm-001: ERROR: No matching distribution found for azure-functions==1.13.0b1 (from -r requirements.txt (line 5))
8:00:48 PM azfn-eus2-tminor-mdm-001: "2022-11-08 20:00:48"|ERROR|WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb1489fa90>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
8:00:48 PM azfn-eus2-tminor-mdm-001: WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb1489fb20>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
8:00:48 PM azfn-eus2-tminor-mdm-001: WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb148b0310>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
8:00:48 PM azfn-eus2-tminor-mdm-001: WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb148b01f0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
8:00:48 PM azfn-eus2-tminor-mdm-001: WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbb148a9940>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure-functions/
8:00:48 PM azfn-eus2-tminor-mdm-001: ERROR: Could not find a version that satisfies the requirement azure-functions==1.13.0b1 (from -r requirements.txt (line 5)) (from versions: none)
8:00:48 PM azfn-eus2-tminor-mdm-001: ERROR: No matching distribution found for azure-functions==1.13.0b1 (from -r requirements.txt (line 5)) | Exit code: 1 | Please review your requirements.txt | More information: https://aka.ms/troubleshoot-python
8:00:49 PM azfn-eus2-tminor-mdm-001: /opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /tmp/build/expressbuild --platform python --platform-version 3.9.7 -i /tmp/8dac1c2eb121410 -p packagedir=.python_packages/lib/site-packages
8:00:49 PM azfn-eus2-tminor-mdm-001: Generating summary of Oryx build
8:00:49 PM azfn-eus2-tminor-mdm-001: Deployment Log file does not exist in /tmp/oryx-build.log
8:00:49 PM azfn-eus2-tminor-mdm-001: The logfile at /tmp/oryx-build.log is empty. Unable to fetch the summary of build
8:00:50 PM azfn-eus2-tminor-mdm-001: Deployment Failed. deployer = Push-Deployer deploymentPath = Functions App ZipDeploy. Extract zip. Remote build.
8:00:54 PM azfn-eus2-tminor-mdm-001: Deployment failed.
