### ISSUE TITLE
Oryx Readme Seems to be Out of Date

### ISSUE THREAD

**Issue by oscarhermoso** [microsoft/Oryx#854]
### Bug Report

- At what date and time did you most recently experience the problem?

Monday, 16th November, 11 AM UTC

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.

Oryx's [GitHub Readme](https://github.com/microsoft/Oryx#build-and-run-an-app),  [hub.docker.com](https://hub.docker.com/_/microsoft-oryx-images), Oryx Docker Container (*mcr.microsoft.com/oryx/build:latest*)

- If your repo is publicly available please share its URL:

N/A, Private Repo

- What happened?

I've been attempting to use the Oryx command line to create a Docker Image for a new Azure App service, running a Python 3.8 / Django 3.1 server instance.

The GitHub Readme and Docker pages both seem to be out of date.

The GitHub Readme includes a seemingly deprecated url the startup script:
```bash
   ...
    'docker.io/oryxprod/node-10.14:latest' \
    sh -c 'oryx create-script -appPath /app && /run.sh'
```
Docker has is missing the `create-script` command...
```bash
    ...
    'mcr.microsoft.com/oryx/node:10.14' \
    sh -c 'oryx -appPath /app && /run.sh'
```
...but when I run `oryx --help` in the latest provided docker image (*mcr.microsoft.com/oryx/build:latest*), `create-script` doesn't seem to be a valid command anyway?

If these documents could be updated, it would really help me out as someone new to both Docker containers and Azure services. Thanks!

**Comment by oscarhermoso** [comment]
*Edit:* I see now that the version of `oryx` running on the build image is totally different to the runtime image. The build image does not have the `create-script` command, but the runtime image does.

**Comment by qianz2** [comment]
Hi @oscarhermoso , I think the README file you're looking is specified for Oryx runtime images, `create-script` command is used in runtime images only. Thanks for reminding us, we'll update README as we found inconsistencies.

**Comment by oscarhermoso** [comment]
Thanks @qianz2 

You're correct, when I initially made this post, I didn't realise that the version of Oryx running on the build image was completely different to the run image. It makes sense now after spinning up a few containers and testing things out. Maybe that could be clarified in the README too? Or maybe it's already there and I read past it.

**Comment by qianz2** [comment]
#881 #877 we recently updated documents, so closed it as it's resolved. Thanks for reporting!
