### ISSUE TITLE
An expected error has occured

### ISSUE THREAD

**Issue by MCKLMT** [microsoft/Oryx#855]
### Bug Report

- At what date and time did you most recently experience the problem?

Monday, November 16th, 4:45PM CET

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.

Azure WebApps

- If your repo is publicly available please share its URL:

https://github.com/MCKLMT/demophpsymfony

- What happened?

Error: Oops... An unexpected error has occurred.

- What did you expect or want to happen?

- How can we reproduce it?

https://github.com/MCKLMT/demophpsymfony

- Do you have log output? Please include between the backticks:

```
Command: oryx build /home/site/repository -o /home/site/wwwroot --platform php --platform-version 7.4 -i /tmp/8d88a45a0e5fc03 --log-file /tmp/build-debug.log
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20200929.1, Commit: 0266eb9f094e3f18e2d73c438dcbb2be70841922, ReleaseTagName: 20200929.1

Build Operation ID: |jDTcZLv3PMk=.e3b538e1_
Repository Commit : 61cbe332d89aca3e788c249f5d0f82166aac8f4a

Detecting platforms...
Error: Oops... An unexpected error has occurred.
Error: Oops... An unexpected error has occurred.\n/opt/Kudu/Scripts/starter.sh oryx build /home/site/repository -o /home/site/wwwroot --platform php --platform-version 7.4 -i /tmp/8d88a45a0e5fc03 --log-file /tmp/build-debug.log
```

**Comment by kichalla** [comment]
Thanks for the details @MCKLMT. Seems like when Oryx is trying to detect it is trying to parse one of the `.yaml` files and fails. Actually we fixed this issue in later builds but for now as a workaround, you can set an environment or app setting `DISABLE_HUGO_BUILD=true`

**Comment by MCKLMT** [comment]
Any idea when the fix will be deployed?

**Comment by kichalla** [comment]
I am not really sure about the timeline since the deployment is done by other team.

**Comment by arroyc** [comment]
@MCKLMT  .. please let us know if you still see this issue, should have been deployed by now
