### ISSUE TITLE
[not support .NET 5.0] Azure Functions 3.0.11 with Oryx build error:Metadata generation failed

### ISSUE THREAD

**Issue by yangyx91** [microsoft/Oryx#857]
Bug Report:

- these days，i deploy a azure static web app with Blazor+Azure Function Api. before it is targed Net Core 3.1 and github action buld and deplyed well.

- now i  upgrade the app target .NET 5.0, as Blazore Client upgrade .Net 5.0， and Azure Function Api also upgrade .NET 5.0. than commit these code change, now the github action shows [Oryx has failed to build the solution]. 

- the log report as below three pictures, please help recheck this situation.

![azure-workflow-action](https://user-images.githubusercontent.com/11272259/99505871-56b19080-29bc-11eb-9f0c-7067232f7d26.jpg)
![azure-workflow-static-web-error](https://user-images.githubusercontent.com/11272259/99505859-531e0980-29bc-11eb-9db7-5992b6ce2904.jpg)
![azure-workflow-static-web](https://user-images.githubusercontent.com/11272259/99505869-5618fa00-29bc-11eb-9039-22ddc6e753bb.jpg)

i check Azure Functions 3.0.11 with Oryx may not support NET 5.0, so i degrade Azure Function Api target to net Core 3.1 ,Blazor Client still hold on Net 5.0，this time , the Oryx deploy worked.

**Comment by qianz2** [comment]
Hi @yangyx91 , we recently supported installing .NET core 5.0 dynamically during the build, it's probably because Azure Functions didn't use Oryx latest release during the deploy. Could you let us know which Oryx release was using here? I recommend you to file an issue at Azure Functions repository for updating Oryx release instead.

**Comment by yangyx91** [comment]
thanks @qianz2 reply, i review the oryx log and find this vesion number.
this version shows :
 Oryx Version: 0.2.20201112.1,
 Commit: a120bb248aa8d208ca5e02d7d9d075196e79cffd, 
ReleaseTagName: 20201112.1

now i file this issue at Azure Functions repository for updating Oryx release instead.

**Comment by arroyc** [comment]
@yangyx91 thank you .. as you already have a tracking issue on the azure function side, we are closing this issue here .. feel free to open a new one if you find problems

@qianz2
