### ISSUE TITLE
WEBSITE_RUN_FROM_PACKAGE does not work for NodeJS app on Windows plan

### ISSUE THREAD

**Issue by geraldnguyen** [microsoft/Oryx#861]
### Bug Report

I was trying out Run-from-package option for a nodejs app

**Creating the NodeJs codes and creating zip archive**
```
npx express-generator hellonode --view pug --git`

cd hellonode

npm install

zip -r hellonode.zip .
```

**Creating webapp**

```
az appservice plan create -g az-webapp -n node-hello -l eastus

az webapp create -g az-webapp -p node-hello -n az204helloapp --runtime "node|10.14"

az webapp config appsettings set --resource-group az-webapp --name az204helloapp --settings WEBSITE_RUN_FROM_PACKAGE="1"

az webapp deployment source config-zip -g az-webapp -n az204helloapp --src hellonode.zip

```

On a Windows appservice plan, the deployment was successful, but viewing the app (http://az204helloapp.azurewebsites.net/) always results in **You do not have permission to view this directory or page**

Creating webapp with custom startup `az webapp config set -g az-webapp -n az204helloapp --startup-file "npm start"` didn't work either

It *appears* to work fine under Linux-based plan (I haven't investigated whether it actually run-from-package or works like a normal zip deployment. Hence the word `appear`)

**Comment by arroyc** [comment]
@sanchitmehta who will be the best contact person on this? 

@geraldnguyen this is windows team .. not on us ... I have tagged someone who can direct you to the right team

**Comment by geraldnguyen** [comment]
@arroyc Thanks for replying! I got confused between Oryx and Kudu. Is Oryx responsible for Linux build and Kudu for Windows build?

@sanchitmehta Seeking your advise on who or which team should I contact regarding this issue? Thanks.
