### ISSUE TITLE
Unable to deploy multiple Python files in a function

### ISSUE THREAD

**Issue by peterskurt** [microsoft/Oryx#865]
### Bug Report

- At what date and time did you most recently experience the problem?
When deploying a python app to functions.

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Functions

- If your repo is publicly available please share its URL:
no

- What happened?
All imports fail. Python imports do not work. Additionally, changing the functions.json to the file that is imported by __init__.py doesn't work.  It said it could not find the module.

- What did you expect or want to happen?
I expected it to run the right file and import the modules as if run from the command line.

- How can we reproduce it?
Have __init__.py try to import a local module which then also tries to import a local module.

- Do you have log output? Please include between the backticks:

```
Result: Failure Exception: ModuleNotFoundError: No module named 'keytherm'. Troubleshooting Guide: https://aka.ms/functions-modulenotfound Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 271, in _handle__function_load_request func = loader.load_function( File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 34, in call raise extend_exception_message(e, message) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 32, in call return func(*args, **kwargs) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/loader.py", line 76, in load_function mod = importlib.import_module(fullmodname) File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "/home/site/wwwroot/TimerTriggerNest/__init__.py", line 5, in <module> import keytherm

```

**Comment by arroyc** [comment]
@peterskurt  thank you for reporting this issue ... I will look into this and get back to you as soon as I can .. in the mean time would you be able to provide more information of the oryx version it is running ..

you can get that by using command oryx --version

**Comment by arroyc** [comment]
I'm closing this issue assuming it was intermittent issue, please feel free to open a new one or activate this one if you still see the same problem
