### ISSUE TITLE
Pecl can't find php when called in PRE_BUILD script

### ISSUE THREAD

**Issue by meidlinga** [microsoft/Oryx#874]
### Bug Report

- At what date and time did you most recently experience the problem?

Various times at different times since 26. Nov 2020

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.

Azure Web Apps

- If your repo is publicly available please share its URL:

- What happened?

When trying to use pecl in a prebuild or postbuild script with Azure webapps, when the PHP version is set to 7.4, I get the following error:
```
/tmp/oryx/platforms/php/7.4.9/bin/pecl: 28: exec: /opt/php/7.4.9/bin/php: not found
```
The same script works in one of the following conditions:

    Calling it in a WebSSH shell with php version set to 7.4
    Calling it in a prebuild with php version set to 7.3

- What did you expect or want to happen?

I would expect the command `pecl config-show` to print the config.

- How can we reproduce it?

Saving the following script and calling as PRE_BUILD or POST_BUILD script. I used LocalGit for deployment. I assume it is the same with other methods.
```
#!/bin/bash

php --version
pecl config-show
```

- Do you have log output? Please include between the backticks:

```
[...] 
Oryx Version: 0.2.20200929.1, Commit: 0266eb9f094e3f18e2d73c438dcbb2be70841922, ReleaseTagName: 20200929.1
[...]
/tmp/oryx/platforms/php/7.4.9/bin/pecl: 28: exec: /opt/php/7.4.9/bin/php: not found
```

**Comment by meidlinga** [comment]
As additional note: I could work around this by setting environment cariables for pecl like this:
```
PHP_PEAR_PHP_BIN=php PHP_PEAR_INSTALL_DIR=/tmp/oryx/platforms/php/7.4.9/lib/php pecl config-show
```
phpize still fails, probably because of the same root cause.

**Comment by qianz2** [comment]
Hi @meidlinga , Looks like you have two paths of Php 7.4.9. _/opt/php_ is the path where we store all php platform versions on disk inside the image, and _/tmp/oryx/platforms/php_ is the path used when it did't find the version in the image and dynamically install it. In your case I assume the php 7.4.9 inside the image was removed and it's still pointing to the old path.

**Comment by qianz2** [comment]
Can you try `printenv` command inside the image and see which path it's using? If it's `php=/opt/php/7.4/bin/php`, you can try something like updating it to `php=/tmp/oryx/platforms/7.4/bin/php`

**Comment by meidlinga** [comment]
Hello @qianz2 ,
Thanks for the fast response. I have not knowingly removed it. I have switched running instances using the Web App configuration in the Azure web portal. But since then, I also completely removed and recreated the whole environment several times using terraform and manually in the web portal. So I assume I do not have any side effects of previous installations.

The image seems to be based on buster which only includes PHP 7.3 as system package.

At the time the pre_build script is executed, /opt/php does not exist. 
Setting the envirnonment variable did not help.

I tried running the following script:
```
echo env php: $php

echo tree /opt/php
tree -L 2 /opt/php

echo tree /tmp/oryx/platforms
tree -L 2 /tmp/oryx/platforms

echo executing pecl
export php=/tmp/oryx/platforms/7.4/bin/php
pecl config-show
```

Which produced the following output (it is a bit shuffled):
```
remote: Executing pre-build command...
remote: env php: /tmp/oryx/platforms/php/7.4.9/bin/php
remote: /tmp/oryx/platforms/php/7.4.9/bin/pecl: 28: exec: /opt/php/7.4.9/bin/php: not found
remote: tree /opt/php
remote: /opt/php [error opening dir]
remote: 
remote: 0 directories, 0 files
remote: tree /tmp/oryx/platforms
remote: /tmp/oryx/platforms
remote: ├── php
remote: │   └── 7.4.9
remote: └── php-composer
remote:     └── 1.9.3
remote: 
remote: 4 directories, 0 files
remote: executing pecl

```

I am currently working around this by setting `PHP_PEAR_PHP_BIN` and `PHP_PEAR_INSTALL_DIR`
Additionally the path seems to be hardcoded in phpize:
```
$  cat /tmp/oryx/platforms/php/7.4.9/bin/phpize                                                                                                                                                     
#!/bin/sh                                                                                                                                                                                           
                                                                                                                                                                                                    
# Variable declaration                                                                                                                                                                              
prefix='/opt/php/7.4.9'                                                                                                                                                                             
datarootdir='/opt/php/7.4.9/php'  
```

I currently work around this by replacing /opt/php with /tmp/oryx/platforms/php using:
```
sed -e 's#/opt/php/7.4.9#/tmp/oryx/platforms/php/7.4.9#g' /tmp/oryx/platforms/php/7.4.9/bin/phpize > phpize.fixed
```

I still think a better solution would be, if those fixes are done in Oryx, or /tmp/oryx/platforms/php/7.4.9 would be symlinked to /opt/php/7.4.9.

**Comment by meidlinga** [comment]
Until around 20. Dec 2020, only php 7.4 was affected by this bug.
Currently, also php7.3 is affected
```
remote: Running oryx build...
remote: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
remote: You can report issues at https://github.com/Microsoft/Oryx/issues
remote: 
remote: Oryx Version: 0.2.20201105.1, Commit: 127d6a3c61a6c0eb67bcfeee0600c3fe71251839, ReleaseTagName: 20201105.1
remote: 
remote: Build Operation ID: |v1sfNRou4RU=.cff149a0_
remote: Repository Commit : 7e840af1ec7cf492389fefaf7f84aa294a8b60f9
remote: 
remote: Detecting platforms...
remote: .......
remote: Detected following platforms:
remote:   php: 7.3.25
remote: 
remote: Using intermediate directory '/tmp/8d8a59901353da1'.
remote: 
remote: Copying files to the intermediate directory...
remote: ....
remote: Done in 8 sec(s).
remote: 
remote: Source directory     : /tmp/8d8a59901353da1
remote: Destination directory: /home/site/wwwroot
remote: 
remote: Executing pre-build command...
remote: 
remote: pear config-show
remote: /tmp/oryx/platforms/php/7.3.25/bin/pear: 28: exec: /opt/php/7.3.25/bin/php: not found
remote: pecl bundle redis
remote: /tmp/oryx/platforms/php/7.3.25/bin/pecl: 28: exec: /opt/php/7.3.25/bin/php: not found
remote: 

```

**Comment by arroyc** [comment]
@meidlinga sorry for late response, we will look into this and update you as soon as possible once the fix is available ... for the time being I guess the workaround would be use the path from tmp directory for pear?

**Comment by meidlinga** [comment]
Hi @arroyc ,

It works when setting the environment variables as stated in a previous comment. Additionally it is required to patch phpize, because it seems to contain the paths hardcoded.

**Comment by arroyc** [comment]
@meidlinga  .. thanks for confirming .. in that case I would think we can close this. if you have other thoughts, feel free to reopen this with your thoughts :) ... happy to help !
