### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by Woile** [microsoft/Oryx#878]
### Feature Request

Hello, I've been reading Azures docs + the issues in this repo, and I was not able to find anything like a configuration file.
A configuration file would make my life way simpler as a developer. At the moment I'm build a python app with [starlette](https://www.starlette.io/) and there's no straightforward or clear way to do it. 
I've only found the [python configurations](https://docs.microsoft.com/en-us/azure/app-service/configure-language-python#customize-startup-command) and now I understand what do I have to do, but at some point I was still confused :sweat_smile: 
My recommendation would be to have something like a `oryx.toml` or `webapp.toml` file, where I could specify the python version, settings like `WEBSITES_ENABLE_APP_SERVICE_STORAGE`, startup, pre and post build, some env variables, etc.
This would also go in-line with reproducibility.

Sorry again if this already exists, this system is already making my life way faster so thank you!

**Comment by qianz2** [comment]
Hi @Woile , please take a look at` doc/configuration.md` or` doc/runtimes/python.md` files, you may find how the build process works for python apps and the configuration information you needed. Thank you!

**Comment by Woile** [comment]
Hey @qianz2 I've read them and they do not seem to achieve the objective. It's hard to have a reproducible project with env variables. It would be much easier if a configuration file is present in the repository + github hook => life super easy. This would also be in-line with many other tools developers know, like vercel or netlify.

Anyway, I understand if there are no plans to implement something like that 👍🏻 

Regards and thanks for answering.
