### ISSUE TITLE
App Path set to /tmp/xxxxx folder in newer Oryx Version

### ISSUE THREAD

**Issue by michaelteo** [microsoft/Oryx#880]
### Bug Report

- At what date and time did you most recently experience the problem?
Dec 7

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Web Apps

- If your repo is publicly available please share its URL:

- What happened?
Our application is having an issue with the paths with the new Oryx version starting from : 
**_Oryx Version: 0.2.20201105.1, Commit: 127d6a3c61a6c0eb67bcfeee0600c3fe71251839, ReleaseTagName: 20201105.1_**

In the older version this was working fine **_Oryx Version: 0.2.20200917.1, Commit: 59deb778658a124cb74ea8e2c8f39fa87abcc9d9, ReleaseTagName: 20200917.1_**

This new setup is causing issues with our Django app and how it is reference files under home/site/wwwroot/media.

I also observed that normally on app service when you SSH into it, the default app_path in /home/site/wwwroot. With the new version it is pointing to a tmp folder _"/tmp/8d89b4af3d8b59f"_

- What did you expect or want to happen?
1. Is there a way to specific an older oryx version for build in app service?
2. if that is not possible - Is there way to turn off compression ? I believe the new oryx version is compressing into output.tar.gz and somehow in the log, it is marked as "[ERROR]  Output is compressed. Extracting it..."  and I suspect that could be the cause of issues for our app. 

- How can we reproduce it?

- Do you have log output? Please include between the backticks:

```
2020-12-08T07:31:28.143551042Z: [INFO]  
2020-12-08T07:31:28.143585142Z: [INFO]    _____                               
2020-12-08T07:31:28.143591342Z: [INFO]    /  _  \ __________ _________   ____  
2020-12-08T07:31:28.143595642Z: [INFO]   /  /_\  \___   /  |  \_  __ \_/ __ \ 
2020-12-08T07:31:28.143599642Z: [INFO]  /    |    \/    /|  |  /|  | \/\  ___/ 
2020-12-08T07:31:28.143603642Z: [INFO]  \____|__  /_____ \____/ |__|    \___  >
2020-12-08T07:31:28.143607542Z: [INFO]          \/      \/                  \/ 
2020-12-08T07:31:28.143611343Z: [INFO]  
2020-12-08T07:31:28.143614743Z: [INFO]  A P P   S E R V I C E   O N   L I N U X
2020-12-08T07:31:28.143618343Z: [INFO]  
2020-12-08T07:31:28.143621643Z: [INFO]  Documentation: http://aka.ms/webapp-linux
2020-12-08T07:31:28.143625243Z: [INFO]  Python 3.6.12
2020-12-08T07:31:28.143628743Z: [INFO]  Note: Any data outside '/home' is not persisted
2020-12-08T07:31:28.255811316Z: [INFO]  Starting OpenBSD Secure Shell server: sshd.
2020-12-08T07:31:28.279091198Z: [INFO]  Site's appCommandLine: /home/site/startup.sh
2020-12-08T07:31:28.279570701Z: [INFO]  Checking of /home/site/startup.sh is a file
2020-12-08T07:31:28.279714403Z: [INFO]  App command line is a file on disk
2020-12-08T07:31:28.287214361Z: [INFO]  App command line is a shell script, will execute this script as startup script
2020-12-08T07:31:28.290457086Z: [INFO]  Launching oryx with: create-script -appPath /home/site/wwwroot -output /opt/startup/startup.sh -virtualEnvName antenv3.6 -defaultApp /opt/defaultsite -bindPort 8000 -userStartupCommand /home/site/startup.sh
2020-12-08T07:31:28.344611808Z: [INFO]  Found build manifest file at '/home/site/wwwroot/oryx-manifest.toml'. Deserializing it...
2020-12-08T07:31:28.351244360Z: [INFO]  Build Operation ID: |Y61ngtynOUI=.d4eebf4_
2020-12-08T07:31:28.356932704Z: [INFO]  Oryx Version: 0.2.20201112.1, Commit: a120bb248aa8d208ca5e02d7d9d075196e79cffd, ReleaseTagName: 20201112.1
2020-12-08T07:31:28.357180106Z: [ERROR]  Output is compressed. Extracting it...
2020-12-08T07:31:28.360242930Z: [ERROR]  Extracting '/home/site/wwwroot/output.tar.gz' to directory '/tmp/8d89b4af3d8b59f'...

2020-12-08T07:31:36.464402898Z: [ERROR]  App path is set to '/tmp/8d89b4af3d8b59f'
```

**Comment by abhilashmk** [comment]
This change came with newer version of Platform on App Service : https://github.com/Azure-App-Service/KuduLite/wiki/Python-Build-Changes. 

Post this change all files in Project Root have to be relative or use $APP_PATH env to get the exact path.

**Comment by michaelteo** [comment]
Looks like there is no option for this. We had to change our code a bit to make sure we reference the right paths to make it work. So will close the issue for now

**Comment by getmarked** [comment]
I would like to offer a datapoint that this change broke my app.

It is same reason as @michaelteo where i used mount storage that points to `wwwroot` and i expected that django app to run from `wwwroot`.

**Comment by geciciserkan** [comment]
Hi. this problem is still available and our production has been effected from this issue. Why does this issue seems as closed ?

**Comment by michaelteo** [comment]
I closed the issue because our team did a workaround for the issue to just fix our code.

Looks like the Azure team is trying to fix this in https://github.com/Azure-App-Service/ImageBuilder/issues/87

I'll reopen for now for benefit of others. I will close once the other thread resolves it.

**Comment by divinedeveloper** [comment]
@michaelteo We too are facing this and I think we should keep the issue open here too.  Somehow it works for us by using azure devops for deployment but doesn't work when we use the deployment center from portal.

**Comment by michaelteo** [comment]
The issue is specific to Oryx Build which is the default build deploy system for Kudu Lite deployment for Azure app service. 
I believe Azure Devops is a different build system so it makes sense that it works there.

**Comment by divinedeveloper** [comment]
@michaelteo today we tried deployment using azure-cli and azure devops and we faced the same /tmp/xxxxxxx directory issue. I have commented on the other issue used by Azure team.

**Comment by geciciserkan** [comment]
Is there any quick alternative solution for this problem ? Our app is down for 1 week ?

**Comment by delzac** [comment]
@geciciserkan hard code the path to whatever thing that needs it.

**Comment by geciciserkan** [comment]
@delzac 
Template is already available at following directory but I am still getting this error ? (/tmp/8d8a9e074b17d1a/App/templates/App/Home/index.html)


Template-loader postmortem
Django tried loading these templates, in this order:

Using engine django:

django.template.loaders.filesystem.Loader: /tmp/8d8a9e074b17d1a/App/templates/App/Home/index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /tmp/8d8a9e074b17d1a/App/templates/App/Home/index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /tmp/8d8a9e074b17d1a/antenv/lib/python3.7/site-packages/django/contrib/admin/templates/App/Home/index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /tmp/8d8a9e074b17d1a/antenv/lib/python3.7/site-packages/django/contrib/auth/templates/App/Home/index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /tmp/8d8a9e074b17d1a/antenv/lib/python3.7/site-packages/crispy_forms/templates/App/Home/index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /tmp/8d8a9e074b17d1a/antenv/lib/python3.7/site-packages/rest_framework/templates/App/Home/index.html (Source does not exist)

**Comment by delzac** [comment]
@geciciserkan I don't think i understand enough of your problem to help you.

The issue i faced was from azure blob mount storage. Within django, the pathing should be with reference to `BASE_DIR` so it should still work.

**Comment by geciciserkan** [comment]
@delzac my exception is different.  I am getting TemplateDoesNotExist error as follows but template is available in directory annd the application is working well locally




Request Method: | GET
-- | --
http://edufinance.loan/
2.2.7
TemplateDoesNotExist
App/Home/index.html
/tmp/8d8a9e074b17d1a/antenv/lib/python3.7/site-packages/django/template/loader.py in get_template, line 19
/opt/python/3.7.9/bin/python3.7
3.7.9
['/opt/python/3.7.9/bin',  '/tmp/8d8a9e074b17d1a',  '/tmp/8d8a9e074b17d1a/antenv/lib/python3.7/site-packages',  '/opt/python/3.7.9/lib/python37.zip',  '/opt/python/3.7.9/lib/python3.7',  '/opt/python/3.7.9/lib/python3.7/lib-dynload',  '/opt/python/3.7.9/lib/python3.7/site-packages']

**Comment by delzac** [comment]
Did you use Azure portal and see whether the templates are really there?

![image](https://user-images.githubusercontent.com/19370780/103169063-a9ac1c80-4873-11eb-9100-1588871a8a5a.png)

Use advance tools >> go and then check if the templates are really there in the directory.

**Comment by geciciserkan** [comment]
@delzac  yes template is available as follows

antenv) root@f2b1b54166b8:/tmp/8d8aa43d29cac58/App/templates/App/home# ls
admin_dashboard.html  dashboard.html  index.html

**Comment by delzac** [comment]
@geciciserkan 

The errors says

```
TemplateDoesNotExist at /

/tmp/8d8a9e074b17d1a/App/templates/App/Home/index.html
```

But your path is `tmp/8d8aa43d29cac58/App/templates/App/home`

Django is looking for file at `tmp/8d8a9e074b17d1a/` but your files are at `tmp/8d8aa43d29cac58/`

**Comment by geciciserkan** [comment]
@delzac 

directory name under tmp folder is changing after every build. Sorry I shared logs from different builds. But problem is still available

**Comment by delzac** [comment]
Have you use Azure portal >> Advanced tools >> Go >> SSH and visually check with your eyes that the files are there?

**Comment by geciciserkan** [comment]
Yes I did it

**Comment by delzac** [comment]
In the debug log i saw
```

[{'APP_DIRS': True,
  'BACKEND': 'django.template.backends.django.DjangoTemplates',
  'DIRS': ['/tmp/8d8aa5a5bd0edcd/templates'],
  'OPTIONS': {'context_processors': ['django.template.context_processors.debug',
                                     'django.template.context_processors.request',
                                     'django.contrib.auth.context_processors.auth',
                                     'django.contrib.messages.context_processors.messages']}}]
```

You are not suppose to hard code`'DIRS': ['/tmp/8d8aa5a5bd0edcd/templates'],` it should reference `BASE_DIR`.

You have no idea what is the random directory oryx is going to put your files in. Always take reference from `BASE_DIR`.

In your case `os.join(BASE_DIR, 'templates')` will probably work.

**Comment by geciciserkan** [comment]
@delzac it is runime debug log, my setting file is as follows


# Template configuration
# https://docs.djangoproject.com/en/2.1/topics/templates/
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

**Comment by arroyc** [comment]
you should not have to do any sort of path hack i believe, you need to use $APP_PATH as suggested by the app service team .. this is a breaking change  and i agree there should have been better and more documentation on this. But using APP_PATH should solve your issue, if not please feel free to create a new issue or reopen this one
