### ISSUE TITLE
Node and Yarn 2 errors

### ISSUE THREAD

**Issue by ericis** [microsoft/Oryx#895]
### Bug Report

- At what date and time did you most recently experience the problem?

2020-12-22T15:22:17.052272Z

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.

Azure Web Apps

- If your repo is publicly available please share its URL:

https://github.com/ourchitecture/panda/tree/main/src/tutorials/node/azure

- What happened?

Deployment with `az webapp up` failed with the error `Usage Error: Couldn't find a configuration settings named "cache-folder"`.

- How can we reproduce it?

Clone the repo and follow the steps.

- Do you have log output? Please include between the backticks:

**az webapp up logs**

```
Webapp 'app-our-tutorials-node-hello' already exists. The command will deploy contents to the existing app.
Creating zip with contents of dir /app ...
Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
Deployment endpoint responded with status code 202
Configuring default logging for the app, if not already enabled
ValidationError: Zip deployment failed. {'id': '69d35dc5aad045a998647c8fc9af7021', 'status': 3, 'status_text': '', 'author_email': 'N/A', 'author': 'N/A', 'deployer': 'Push-Deployer', 'message': 'Created via a push deployment', 'progress': '', 'received_time': '2020-12-22T17:47:48.1521144Z', 'start_time': '2020-12-22T17:47:49.4054755Z', 'end_time': '2020-12-22T17:48:21.0986005Z', 'last_success_end_time': None, 'complete': True, 'active': False, 'is_temp': False, 'is_readonly': True, 'url': 'https://app-our-tutorials-node-hello.scm.azurewebsites.net/api/deployments/latest', 'log_url': 'https://app-our-tutorials-node-hello.scm.azurewebsites.net/api/deployments/latest/log', 'site_name': 'app-our-tutorials-node-hello'}. Please run the command az webapp log deployment show -n app-our-tutorials-node-hello -g rg-our-tutorials
```

**Deployment logs**

```
[
  {
    "log_time": "2020-12-22T15:22:17.052272Z",
    "id": "",
    "message": "Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 12 -i /tmp/8d8a68d5dd76127 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log ",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:19.8318635Z",
    "id": "",
    "message": "Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:19.8680591Z",
    "id": "",
    "message": "You can report issues at https://github.com/Microsoft/Oryx/issues",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:19.8916967Z",
    "id": "",
    "message": "",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:19.9041061Z",
    "id": "",
    "message": "Oryx Version: 0.2.20201105.1, Commit: 127d6a3c61a6c0eb67bcfeee0600c3fe71251839, ReleaseTagName: 20201105.1",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:19.9273543Z",
    "id": "",
    "message": "",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:19.9510794Z",
    "id": "",
    "message": "Build Operation ID: |zbLbT92K/9c=.fdbf1e1b_",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:19.96405Z",
    "id": "",
    "message": "Repository Commit : d1b4d372626b4a7cbac3b111c46bc210",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:19.9829995Z",
    "id": "",
    "message": "",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:19.9958992Z",
    "id": "",
    "message": "Detecting platforms...",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:22.6996718Z",
    "id": "",
    "message": "Platform 'hugo' has been disabled, so skipping detection for it.",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:22.7744226Z",
    "id": "",
    "message": "Detected following platforms:",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:22.7945082Z",
    "id": "",
    "message": "  nodejs: 12.19.0",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:23.4873617Z",
    "id": "",
    "message": "",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:23.5657292Z",
    "id": "",
    "message": "Using intermediate directory '/tmp/8d8a68d5dd76127'.",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:23.5788203Z",
    "id": "",
    "message": "",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:23.5869773Z",
    "id": "",
    "message": "Copying files to the intermediate directory...",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:24.0923394Z",
    "id": "",
    "message": "Done in 1 sec(s).",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:24.1253145Z",
    "id": "",
    "message": "",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:24.1452563Z",
    "id": "",
    "message": "Source directory     : /tmp/8d8a68d5dd76127",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:24.1705368Z",
    "id": "",
    "message": "Destination directory: /home/site/wwwroot",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:24.1898388Z",
    "id": "",
    "message": "",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:24.647978Z",
    "id": "",
    "message": "",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:24.6762706Z",
    "id": "",
    "message": "Using Node version:",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:24.9215174Z",
    "id": "",
    "message": "v12.19.0",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:24.9756746Z",
    "id": "",
    "message": "",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:25.0039729Z",
    "id": "",
    "message": "Using Yarn version:",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:27.5474371Z",
    "id": "",
    "message": "2.4.0",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:27.6585403Z",
    "id": "",
    "message": "",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:27.6714754Z",
    "id": "",
    "message": "Configuring Yarn cache folder...",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:29.6301484Z",
    "id": "",
    "message": "Usage Error: Couldn't find a configuration settings named \"cache-folder\"",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:29.6587039Z",
    "id": "",
    "message": "",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:29.6773342Z",
    "id": "",
    "message": "$ yarn config set [--json] [-H,--home] <name> <value>",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020-12-22T15:22:31.3643399Z",
    "id": "",
    "message": "\\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 12 -i /tmp/8d8a68d5dd76127 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log ",
    "type": 2,
    "details_url": null
  }
]
```

I've had a LOT of issues developing a ["hello world" Node.js app](https://github.com/ourchitecture/panda/tree/main/src/tutorials/node/azure) that **consistently** deploys with `az webapp up`. I'll list the most immediate issue below, but include others at the end for reference.

The most recent challenge seems to be that Oryx may not support Yarn 2 and fails while configuring Yarn with the error `Usage Error: Couldn't find a configuration settings named "cache-folder"`. It appears Yarn 2 has a config setting for "cacheFolder", but no such setting for "cache-folder".

As a result of the various and seeminly inconsistent issues along with the difficulty in triaging them, I'm probably going to abandon `az webapp up` and transition to ACI to deploy an immutable Node.js container to the AppService instance. This should improve consistency and also remove a dependency on the "magic".

#### Related issues

- https://github.com/microsoft/Oryx/issues/864

### Other Challenges

- Hugo build file check bug seems to impact regular Node.js applications. I had to set "app_settings.DISABLE_HUGO_BUILD = true" to get past the Hugu bug error and on to the new Yarn 2 error above.
- There was very little documentation on how to create the AppService with Node.js support using Terraform, specifically the `site_config.linux_fx_version` and `app_settings.SCM_DO_BUILD_DURING_DEPLOYMENT` settings as well as the nuances of `use_32_bit_worker_process = true` for Free and Shared plans. Ultimately, I found some success through reverse-engineering by creating the AppService in the web portal, importing that instance into Terraform and then reviewing the state code for settings.
- Node.js v10 deployment had failed with odd output. I didn't even attempt to triage the issue and upgraded to v12 LTS.
- `az webapp up` seems to want to reconfigure the AppService with some magic. It was difficult to figure out the "best" way to configure the Node version originally configured in Terraform, but then also configured in "package.json" `engines` setting.
- The syntax for `az webapp up` changed in recent Azure CLI versions, completely breaking the original code that passed `--runtime` and other settings.

It's been interesting to see just how hard it is for engineers to get a basic "Hello World" Node.js application working that doesn't follow the over-simplified online tutorials without DevOps automation.

I'll continue to try to work on building out the [end-to-end example](https://github.com/ourchitecture/panda/tree/main/src/tutorials/node/azure) and document the various lessons and work-arounds as I go. I'd welcome any contributions, including [submitting any new issues](https://github.com/ourchitecture/panda/issues) for ideas, questions, concerns, etc.

Once I can get a consistent, local build, I'll add a GitHub CD action to constantly test deployments. Future work will include simulating multiple environments (test/stage/prod) and multiple regions with fail-over.

**Comment by ericis** [comment]
Yes, this line is hard-coded to Yarn 1 syntax:
https://github.com/microsoft/Oryx/blob/66a1aee00346b8834546f3cdf432a5b200c47416/images/build/yarn-cache/cacheNodePackages.sh#L16

Yarn 2 was released in early 2020. It would be good to support both versions.

I wonder if it would be better to use the environment variable `YARN_CACHE_FOLDER` rather than calling the CLI?

**Comment by ericis** [comment]
I have now validated that this error occurs when the application settings include `SCM_DO_BUILD_DURING_DEPLOYMENT="1"`, but can be avoided by using a Zip deployment instead, since it skips the Oryx build steps by setting `WEBSITE_RUN_FROM_PACKAGE="1"` and `SCM_DO_BUILD_DURING_DEPLOYMENT="0"`.

Engineers can follow this tutorial for the basic steps using the CLI:
https://docs.microsoft.com/en-us/azure/app-service/deploy-run-package

As a result, I'll update the [Ourchitecture hello world example](https://github.com/ourchitecture/panda/tree/main/src/tutorials/node/azure) to include these settings in the Terraform infrastructure as code deployment and use the Zip deployment approach for CI/CD. I can also update the comments here when I have something working.

However, the above is still a bug with Oryx and Yarn2.

**Comment by ericis** [comment]
Yes, I was able to get a work-around working with yarn 2 that skips the Oryx build:

https://github.com/ourchitecture/panda/blob/0012c9641fa0a4641bd2f69eefc3b4c68b83bb39/src/scripts/azure/webapps/install.sh#L47-L51

- [Project code](https://github.com/ourchitecture/panda/tree/main/src/tutorials/node/azure/app#readme)
- [Continuous deployment workflow](https://github.com/ourchitecture/panda/blob/0012c9641fa0a4641bd2f69eefc3b4c68b83bb39/.github/workflows/tutorials_node-azure_app_cd.yml#L42) (will execute the script above)

This is now working for CI and CD and engineers can replicate the exact behavior locally without relying on a DevOps automation engine to debug.

👀  I'd be happy to re-test any Oryx build updates that support Yarn 2.

**Comment by arroyc** [comment]
Thanks for reporting, we will be working on supporting yarn 2 soon. Please let us know if you see other problems.

**Comment by anthonychu** [comment]
@arroyc Is there an issue tracking Yarn 2 that we can link to?

**Comment by qianz2** [comment]
Here is a temporary workaround that works for the above issue: use CUSTOM_BUILD_COMMAND flag, which can skip running package install command and run the custom build command provided, in this case `yarn add --cached`.

**Comment by qianz2** [comment]
> @arroyc Is there an issue tracking Yarn 2 that we can link to?

@anthonychu, above is the link to the PR that we're working on regarding the yarn 2 issue.
