### ISSUE TITLE
oryx run-script - Platform name is required

### ISSUE THREAD

**Issue by derekbekoe** [microsoft/Oryx#90]
### Bug Report

- At what date and time did you most recently experience the problem? =
**Apr 22 2019**

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
**Local**

- If your repo is publicly available please share its URL:
**https://github.com/vsls-contrib/guestbook**

- What happened?
Platform name is required while [the oryx README](https://github.com/Microsoft/Oryx/blob/master/README.md#build-and-run-an-app) suggests it's not required.

- What did you expect or want to happen?
It runs without `--platform nodejs` being required.

- How can we reproduce it?
```bash
$ docker run -it oryxprod/build:latest bash
# git clone https://github.com/vsls-contrib/guestbook
# cd guestbook/
# oryx build
# oryx run-script --appPath .
Platform name is required.
```

**Comment by gpcastro** [comment]
Thanks Derek, we will work on this.

**Comment by cormacpayne** [comment]
The fix for this has been merged and will be available in the next release of the Oryx build image.
