### ISSUE TITLE
"build/index.html": No such file or directory (2)

### ISSUE THREAD

**Issue by esttenorio** [microsoft/Oryx#909]
I have an Azure Web App which is linked to a local Git Repo. Almost every time I push so it can update and publish the changes, it fails due to this error:

> remote: Zipping existing node_modules folder...
remote: ...............................................................................................................................................
remote: Done in 149 sec(s).
remote: Preparing output...
remote:
remote: Copying files to destination directory '/home/site/wwwroot'...
remote: .....
remote: rsync: rename "/home/site/wwwroot/build/.index.html.vRnkg7" -> "build/index.html": No such file or directory (2)
remote: rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
remote: Deployment Logs : 'https://mywebsite.scm.azurewebsites.net/newui/jsonviewer?view_url=/api/deployments/8b2bbbd21007707676c32503d931b7e6d09927c5/log'
`

The commit gets pushed and master is updated but the latest changes are not deployed.

This is not the first time, since I started deploying on this Web App I have to do a manual clean up according to some comments and posts that I saw online:

> The workaround is to click Disconnect in Deployment center, go to Advanced tools -> Kudu -> Bash
cd site/wwwroot
rm -rf *
Return to Deployment center, connect it back and Redeploy.
NOTE: rm -rf starts working after 5 min after disconnection. Before that it says "Directory is not empty" :(

Source: https://social.msdn.microsoft.com/Forums/azure/en-US/084bc5e0-7fa4-4102-8141-57983a718d47/react-deployment-to-linux-app-service-keeps-failing-intermittently?forum=opensourcedevwithazure

After doing the workaround and building again the failed commit it works fine.

This workaround seems to work every time for me. It's really annoying to hit this error almost every time I deploy.

Azure Web App details:
- OS: Linux
- reactJS project using npm 
-   "engines": {
        "node": "10.14.x"
    },
- Using local Git Repo

**Comment by esttenorio** [comment]
It happened again:

```
Zipping existing node_modules folder...
Done in 150 sec(s).
Preparing output...

Copying files to destination directory '/home/site/wwwroot'...
rsync: rename "/home/site/wwwroot/build/.index.html.RCtZmg" -> "build/index.html": No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
```

**Comment by mfxuus** [comment]
Having similar issues with git deployments - please help!

```
remote:
remote: Copying files to destination directory '/home/site/wwwroot'...
remote: rsync: rename "/home/site/wwwroot/.<xxxxxx>.sh.pfbSqK" -> "<xxxxxx>.sh": No such file or directory (2)
remote: rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
```

**Comment by esttenorio** [comment]
are there any updates on this? still happening for me 2/3 times. It really slows down the development process since it's no longer a commit and deploy process.

**Comment by mfxuus** [comment]
The bigger issue for me is that it causes actual downtime to fix this..

**Comment by arroyc** [comment]
hey folks ... sorry for delayed response .. this rsync issue is something due to network share and we (oryx) do not control it .. with that bein said I will try to see if there are any  alternative routes of deployment that can ease the process for you !

**Comment by arroyc** [comment]
just heard from app service folks and they are recommending using slots for fresh deployment and change slots once deployment is successful. Another solution would be run from package, official docs talks about azure functions but it will be same for azure web apps too

https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package
https://github.com/Azure/app-service-announcements/issues/84#:~:text=Run%20From%20Package%20is%20an%20exciting%20new%20feature,zip%20(typically%20using%20a%20storage%20SAS%20URL),%20e.g.

**Comment by esttenorio** [comment]
I think that this still should be fixed given that you are not removing the use of "local git repo". In case you are not going to solve this and the solution is to use a deployment package instead of local git, then you should remove the local git option.

**Comment by ydarma** [comment]
Hi,
We had the same issue with our Vuejs application and managed to solve it in a way acceptable to us. I think that the problem was due to the application that was still running at deployment time, maybe preventing proper site cleanup (?).
In order to prevent the application from running during deployment, the server looks every 20s for the file `/home/touch` and stops if present.

```js
...

fs.stat(flagFile, err => {
  if (err) {
    start();
  }
});

function start() {
  server.listen(process.env.PORT || 8080, () => {
    const interval = setInterval(() => checkStop(interval), 20000);
  });
}

function checkStop(interval) {
  fs.stat(flagFile, err => {
    if (!err) {
      server.close();
      clearInterval(interval);
    }
  });
}
```

The npm build script creates the flag file and wait that the server stops before performing the actual build:
```json
  "build": "touch /home/stop ; sleep 30 ; rm -rf /home/site/wwwroot ; ..."
```
And the start script removes the flag file to allow the server to start:
```json
  "start": "rm -rf /home/stop ; ..."
```
The path of the flag file must be absolute and under `/home` because the build is done in a temporary directory that is not accessible by the application at runtime.

Since then, the deployments have been going well for us.

Hope this helps
