### ISSUE TITLE
Publishing Azure Linux Web App does not update the running application

### ISSUE THREAD

**Issue by valeriob** [microsoft/Oryx#91]
Hi,
i'm not sure this is the right repository to issue this, but here is how to reproduce the problem :

- Create an azure Linux web app, **code publishing**, i'm not actually publishing the code but the compiled application, via FTP or web deployment i think, whatever visual studio and Octopus Deploy use (https://octopus.com/docs/deployment-examples/azure-deployments/deploying-a-package-to-an-azure-web-app).
![image](https://user-images.githubusercontent.com/1522516/56568748-eeb87f80-65b7-11e9-9190-234feb0dfe7b.png)

- Configure the startup file with 'dotnet /home/site/wwwroot/WebApplication.dll'
- Create an aspnetcore WebApplication (framework dependant)
- Import the publish profile into visual studio
- Deploy the application the first time, it should work as expected
- Change something on the home page (like some text)
- Publish the application again
- Browsing to the same page, it should reflect the change, but it does not. Pressing restart on the portal has no effect, the only way is to STOP and Start the web application from the portal.

**Comment by gpcastro** [comment]
Thanks for reaching out. We're aware of this issue and we're working on a fix. In the meantime, have you tried using [slots](https://docs.microsoft.com/en-us/azure/app-service/deploy-staging-slots)?
They allow you to update your web app without conflicting with files being used by the version currently running.

**Comment by valeriob** [comment]
Hi,
glad to hear you are working on it, I've tried slots but they add a little bit of complexity to our deployment. I look forward for an updated.
Thanks !

**Comment by bharatdwarkani** [comment]
Any update on this when it going to be fixed?

**Comment by ClientIco** [comment]
Also would like to know ?

**Comment by kichalla** [comment]
Are you still able to reproduce this issue?

**Comment by valeriob** [comment]
Hi,
i just tested a few times, yes it still require a manual restart to work.

**Comment by shotyme** [comment]
This issue occurs in the Linux based Azure Functions as well. The workaround to stop and start the azure function does not work.
Can somebody help me please?

**Comment by paulbatum** [comment]
File locking issues are common on .NET Core because it does not have the shadow copying behavior that was present on .NET Framework. There are two common approaches to this problem:
1. Modifying the publish profile to take the app offline during deployment. The setting is called `EnableMSDeployAppOffline`. I know this setting works when deploying Azure Functions, but I haven't tried it for a linux web app.
2. Deploy using [Run From Package.](https://docs.microsoft.com/en-us/azure/app-service/deploy-run-package). This approach should work in all scenarios.

**Comment by arroyc** [comment]
please feel free to reopen this issue if you are experiencing it

**Comment by valeriob** [comment]
Pls do not close it, we still have this problem.
Thanks

**Comment by kichalla** [comment]
@valeriob AppService team now supports 'running from package' which is supposed to fix issues like this. Could you try with this and let us know if you are still seeing this issue?
https://docs.microsoft.com/bs-latn-ba/azure/app-service/deploy-run-package

**Comment by valeriob** [comment]
thanks @kichalla, i will try this feature, but it will drastically change our automated deployment pipeline, last time i tried az cli was a nightmare to script due to escape problems https://github.com/Azure/azure-cli/issues/7874

**Comment by kichalla** [comment]
> but it will drastically change our automated deployment pipeline, last time i tried az cli was a nightmare to script due to escape problems Azure/azure-cli#7874

How are you deploying your app to AppService? by zip deploying already built bits or zip deploying and making the build to happen on app serivce or pushing your repo? more details will help us narrow the problem.

This run from package feature is just an appsetting so not sure what you meant by `script`

**Comment by kichalla** [comment]
Gentle ping.

**Comment by valeriob** [comment]
Hi,
we are using octopus deploy at the moment.
https://octopus.com/docs/deployment-examples/azure-deployments/deploying-a-package-to-an-azure-web-app

**Comment by schauhan232** [comment]
> Hi,
> we are using octopus deploy at the moment.
> https://octopus.com/docs/deployment-examples/azure-deployments/deploying-a-package-to-an-azure-web-app

Did you find any solution, we are using same and I have been facing same issue.

**Comment by valeriob** [comment]
You can use deployment slots or just restart the WebAp with a script

$webAppName = '#{Octopus.Action.Azure.WebAppName}'
$rg =(Get-AzureRmWebApp -Name $webAppName).ResourceGroup
Restart-AzureRmWebApp -Name $webAppName -ResourceGroup $rg

**Comment by schauhan232** [comment]
> You can use deployment slots or just restart the WebAp with a script
> 
> $webAppName = '#{Octopus.Action.Azure.WebAppName}'
> $rg =(Get-AzureRmWebApp -Name $webAppName).ResourceGroup
> Restart-AzureRmWebApp -Name $webAppName -ResourceGroup $rg

I have been using slot and facing issue with that too.
