### ISSUE TITLE
How configure private NPM registry in Azure Devops?

### ISSUE THREAD

**Issue by persyl** [microsoft/Oryx#919]
### Bug Report

I'm building a Azure Static web app and it works fine but I want to use my private registry for NPM packages and can not get it to work or find documentation about how to do it.

My private registry is at: https://pkgs.dev.azure.com/MY-ORG-NAME/_packaging/MY-NPM-FEED-NAME/npm/registry/

- What happened?
Error 404 Not Found - GET https://registry.npmjs.org/MY-NPM-PACKAGE - Not found

- What did you expect or want to happen?
- To install MY-NPM-PACKAGE from https://pkgs.dev.azure.com/MY-ORG-NAME/_packaging/MY-NPM-FEED-NAME/npm/registry/ and NOT trying from https://registry.npmjs.org

I have a file .npmrc in the root

```
https://pkgs.dev.azure.com/MY-ORG-NAME/_packaging/MY-NPM-FEED-NAME/npm/registry/:username=foo
https://pkgs.dev.azure.com/MY-ORG-NAME/_packaging/MY-NPM-FEED-NAME/npm/registry/:_password=MY-SECRET-HERE
https://pkgs.dev.azure.com/MY-ORG-NAME/_packaging/MY-NPM-FEED-NAME/npm/registry/:email=foo@bar.com
```

**Comment by qianz2** [comment]
Hello @persyl, for nodejs apps, we have a `NPM_REGISTRY_URL` setting key which allows you to specify custom NPM registry URL. Will be written to .npmrc during the build. Could you give it a try and see if it can resolve your issue?

**Comment by persyl** [comment]
Well @qianz2 I have tried it and hopefully the correct way, as you can see in my posting here:

https://github.com/Azure/static-web-apps/issues/44#issuecomment-771666201

I put NPM_REGISTRY_URL (_and other variables_) under **env** as you can see.
Should I put them in another place?!

**Comment by qianz2** [comment]
Hello @persyl , Could you share what's the logs after you run this workflow? I want to know if the .npmrc file is being read or not. We'll add this issue to our backlogs.

**Comment by qianz2** [comment]
Let us know if you have other following up questions, closing the issue now.
