### ISSUE TITLE
Adding pyproject.toml to Python

### ISSUE THREAD

**Issue by daddycocoaman** [microsoft/Oryx#941]
### Feature Request

Hi. With the popular adoption of pyproject.toml configurations for managing Python build environments (https://www.python.org/dev/peps/pep-0517/), would it be possible to use it as a indicator of a Python project for Oryx. Since it is recognized by `pip`, it would just needed to be added to the detection logic using the same command line as `requirements.txt`.

**Comment by arroyc** [comment]
Thank you for using oryx and asking for this feature ... we would like to add it surely, at the same time it would be great if you can add some user cases for this feature so that we can plan this feature accordingly.

**Comment by daddycocoaman** [comment]
Sorry...I thought I responded to this already and I meant to post this under my MSFT work account. 😅

At any rate, the use case lies in the increased usage of pyproject.toml over requirements.txt for dependency manage. Popular managers like Poetry use pyproject, and  `pip` has ensured it supports the format over the last year or so.

It's really no different than the requirements.txt use cases, but it also allows for additional configuration where needed. It would also enable some of the Azure services that depend on Oryx to extend usability for Python detection.
