### ISSUE TITLE
Avoid node_modules install from scractch on each deploy

### ISSUE THREAD

**Issue by khelkun** [microsoft/Oryx#960]
### Feature Request
I use [vscode-azureappservice](https://github.com/microsoft/vscode-azureappservice) to deploy my Node web app as An App Service on Linux (Code hosting).

This [is a zip package deploy](https://github.com/microsoft/vscode-azureappservice/wiki/Configuring-Zip-Deployment), and it always run `npm install` from scratch on each deploy. Considering the dependencies of the project, this is a long operation on each deploy.

How can I please avoid to `npm install` all dependencies from scratch on each deploy from vscode ?

I may have missed it but I don't see anything to achieve this in the [Oryx Configuration](https://github.com/microsoft/Oryx/blob/master/doc/configuration.md) or in the [Oryx Nodejs runtime doc](https://github.com/microsoft/Oryx/blob/master/doc/runtimes/nodejs.md)

**Comment by khelkun** [comment]
I found out this:
`CUSTOM_BUILD_COMMAND` default value is `npm ci` which cleans the `node_modules` folder before `npm install`.

My way to gain time on the zip deployment so far with app service application settings:
1. `CUSTOM_BUILD_COMMAND="npm install --production"`, then I speed up my deployment (less dependencies to install).
2. `RUN_BUILD_COMMAND=""` and do the  `npm run build` on my local machine before deploying the zip package.

But this does not really achieve what I'm looking for.
In the deployment logs of the azure portal while it's running, there is a temporary log where I can see this:
```
Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/dbc6393f-35f5-45d5-b706-e82837bdd338.zip (5.45 MB) to /tmp/zipdeploy/extracted
```
And the first line of the "Running oryx build" log is:
```
Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 12 --log-file /tmp/build-debug.log
```
So if I trust this sentence:
> Cleaning up temp folders from previous zip deployments

Then I assume `/tmp/zipdeploy/extracted` is cleared before each deployment. So Oryx clearly does an `npm install --production` from scratch in a fresh new uploaded folder on each zip deployment.

Is that right? If yes then I assume there's nothing to avoid doing a full `npm install` (at least in this zip package deployment scenario)?

**Comment by qianz2** [comment]
Hello @khelkun , the `CUSTOM_BUILD_COMMAND` has empty default value, you'll need to set it up. It can be used to avoid original command ` npm install --production` to resolve cases like this. You can included this in the workflow. Could you try it out?

`env:
  CUSTOM_BUILD_COMMAND: 'npm ci && npm run build' `

**Comment by khelkun** [comment]
Hello @qianz2 
That's right `CUSTOM_BUILD_COMMAND` has empty default value, but in the azure [zip package deploy](https://github.com/microsoft/vscode-azureappservice/wiki/Configuring-Zip-Deployment) it has `npm ci` value.

You may want to read again my second upper post but I'll try to clarify my point:
- I did `CUSTOM_BUILD_COMMAND="npm install --production"` because it's a faster install than `npm ci` which also install dev dependencies.  
- `npm ci` cleans up `node_modules` before running, while `npm install --production` doesn't do that. Despite this fact it sounds to me that, whatever I do, Oryx always:
`Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/dbc6393f-35f5-45d5-b706-e82837bdd338.zip (5.45 MB) to /tmp/zipdeploy/extracted`
- So whatever is my `CUSTOM_BUILD_COMMAND` I always installing `node_modules` from scratch on each deploy.

**Comment by qianz2** [comment]
@khelkun , I think the app service uses zip deployment on their layer as the default method. There has nothing we could do to avoid this here.

**Comment by khelkun** [comment]
@qianz2, that was my hypothesis, thanks for the confirmation
