### ISSUE TITLE
Build fails for Node.js app with @sentry/cli

### ISSUE THREAD

**Issue by srigi** [microsoft/Oryx#963]
### Bug Report
> At what date and time did you most recently experience the problem?

March 19th 2021

> Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.

Deploying source to app-service via git deployment

> What happened?

If my node.js app list `@sentry/cli` NPM dependency, build fails (see log)

> How can we reproduce it?

Just try to deploy [next.js/examples/with-sentry](https://github.com/vercel/next.js/tree/canary/examples/with-sentry) into app-service

> Do you have log output? Please include between the backticks:

```
remote: Running oryx build...
remote: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
remote: You can report issues at https://github.com/Microsoft/Oryx/issues
remote: 
remote: Oryx Version: 0.2.20210225.2, Commit: f7b557f29a83aa078cc94c0056e7337c07f14271, ReleaseTagName: 20210225.2
remote: 
remote: Build Operation ID:
remote: Repository Commit :
remote: 
remote: Detecting platforms...
remote: ..
remote: Detected following platforms:
remote:   nodejs: 14.15.1
remote: Version '14.15.1' of platform 'nodejs' is not installed. Generating script to install it...
remote: 
remote: Using intermediate directory '/tmp/8d8eb05b12d03dd'.
remote: 
remote: Copying files to the intermediate directory...
remote: Done in 1 sec(s).
remote: 
remote: Source directory     : /tmp/8d8eb05b12d03dd
remote: Destination directory: /home/site/wwwroot
remote: 
remote: 
remote: Downloading and extracting 'nodejs' version '14.15.1' to '/tmp/oryx/platforms/nodejs/14.15.1'...
remote: Downloaded in 5 sec(s).
remote: Verifying checksum...
remote: Extracting contents...
remote: .......
remote: Done in 18 sec(s).
remote: 
remote: ...
remote: 
remote: Using Node version:
remote: ...
remote: v14.15.1
remote: 
remote: Using Yarn version:
remote: 1.22.10
remote: 
remote: Running 'yarn install --prefer-offline'...
remote: 
remote: yarn install v1.22.10
remote: [1/5] Validating package.json...
remote: [2/5] Resolving packages...
remote: [3/5] Fetching packages...
remote: ...............................................................................
remote: info There appears to be trouble with your network connection. Retrying...
remote: .................................
remote: info There appears to be trouble with your network connection. Retrying...
remote: .............................................................................................................
remote: info fsevents@2.3.2: The platform "linux" is incompatible with this module.
remote: info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
remote: [4/5] Linking dependencies...
remote: .............................................................................................................................................................................
remote: [5/5] Building fresh packages...
remote: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
remote: error /tmp/8d8eb05b12d03dd/node_modules/@sentry/cli: Command failed.
remote: Exit code: 1
remote: Command: node scripts/install.js
remote: Arguments: 
remote: Directory: /tmp/8d8eb05b12d03dd/node_modules/@sentry/cli
remote: Output:
remote: Error: EACCES: permission denied, mkdir '/opt/Kudu/local/npm-cache'```

**Comment by srigi** [comment]
More info on the bug - It appears only if I provide `yarn.lock` generated on my machine (macOS Catalina). If I deploy an app without a *lock* file, it deploys just fine.

However, it is not the best practice to remove the *lock* file from my Node.js project. This is clearly issue with native modules

**Comment by arroyc** [comment]
this looks like an issue with yarn's cross platform scenario. I'm guessing this may have to do something with optional dependencies. Can you try to create the yarn.lock locally (in your mac) with `yarn install --ignore-optional` and check if the generated lock file still cause problem during deployment? @srigi

**Comment by srigi** [comment]
@arroyc I've done some tests:

- `yarn` is not working at all (`--ignore-optional` didn't help)
- deploying without any *lock* file works
- deploying with NPM generated `package-lock.json` works as well!

In the example project I linked, there is a `@sentry/webpack-plugin` dependency which requires `@sentry/cli`. Sentry CLI looks like a native module - on Github repo you can see that majority of the source code is in Rust.

This is definitely a problem of the packager. Thank you for your input, I believe this issue can be closed (leave that on you).

**Comment by arroyc** [comment]
Thanks @srigi for confirming ... closing this issue here
