### ISSUE TITLE
Support for Shapely python package

### ISSUE THREAD

**Issue by FScaccheri** [microsoft/Oryx#97]
### System Package Request

- Why do you need this package? For example, are you using a language-level package which depends on this system package?

I would like to deploy an application on Azure which has [Shapely](https://pypi.org/project/Shapely/) as a requirement. Shapely, in turn, requires lib geos_c (or its variants, libgeos_c.so or libgeos_c.so.1). I'm currently getting this error after deploying:

**Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].**

- Which Oryx language runtime and version are you using? For example, "Node.js v10.14" or "Python v3.7".

I'm using Python 2.7.15+

- What is the name of the package in the latest stable Debian release?For examples, see <https://packages.debian.org/stable/>.

python-shapely

- Do you need a specific version? If so, which and why?

Since it's a Python 2.7 application, I need version [1.5.17](https://pypi.org/project/Shapely/1.5.17/) of Shapely

**Comment by JasonRShaver** [comment]
The team discussed this this morning and will work to add support for Shapely.  While I can't make a commitment right now, I'm hopeful for this being available in June.

**Comment by arroyc** [comment]
@FScaccheri Thanks for trying oryx … Can you tell us a little more about your scenario? Did you try to host/build a python app or node app? Based on above description when I tried shapely to build an circular patch, it worked for me. I used shapely as well as geos in my requirements.txt.

**Comment by FScaccheri** [comment]
@arroyc I tried to host an old python 2.7 app (with Django 1.11) and whenever I tried to deploy to Azure, Shapely installation would fail because it was missing the geos library. I have Shapely in my requirements.txt, but not geos, because it's an apt package. How did you manage to include its installation into the requirements file?

**Comment by arroyc** [comment]
@FScaccheri thanks for your  feed back, we will update you once we add these libraries to our image

**Comment by arroyc** [comment]
@FScaccheri, nevermind, i was debugging and in one of the steps I installed libgeos-dev manually which I forgot to mention earlier, so indeed we need this library to fix this issue

**Comment by arroyc** [comment]
@FScaccheri .. we have added the support for shapely, but it will take some time to roll out through out .. thanks … if you don't see it in next 2 weeks or so, please feel free to post here :)

**Comment by poligarcia** [comment]
@arroyc would you please point us on how this support was implemented? Which commit/pull request?

**Comment by arroyc** [comment]
@poligarcia https://github.com/microsoft/Oryx/pull/105

**Comment by arroyc** [comment]
@poligarcia ... I'm closing this issue. Please feel free to reach us or reopen this issue if you see any problem
