### ISSUE TITLE
Detecting platforms... Error: Oops... An unexpected error has occurred. 

### ISSUE THREAD

**Issue by mauriciojost** [microsoft/Oryx#971]
### Bug Report

- At what date and time did you most recently experience the problem?
Around 2021-04-01 17h00 UTC.

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Functions.

- If your repo is publicly available please share its URL:
Not public.

- What happened?
Same as #929, the only difference is that I have no other function app working. 

- What did you expect or want to happen?
Upon running: 
```
func  azure  functionapp publish func-mesh-from-xxx-datatransfer2
```
I'd expect the deployment to succeed, or at least there should be an easy way to find out what went wrong from the logs.

- Do you have log output? Please include between the backticks:

```
(venv) mjost@host:~/workspace/azure-function-from-scratch (master) $ func  azure  functionapp publish func-mesh-from-xxx-datatransfer2 --force
Getting site publishing info...
Creating archive for current directory...
Performing remote build for functions project.
Deleting the old .python_packages directory
Uploading 9.93 MB [###############################################################################]
Remote build in progress, please wait...
Updating submodules.
Preparing deployment for commit id '1d2d3fd1-e'.
Repository path is /tmp/zipdeploy/extracted
Running oryx build...
Command: oryx build /tmp/zipdeploy/extracted -o /tmp/build/expressbuild --platform python --platform-version 3.8 -i /tmp/8d8f5386e9b06e3 -p packagedir=.python_packages/lib/site-packages
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20210120.1, Commit: 66c7820d7df527aaffabd2563a49ad57930999c9, ReleaseTagName: 20210120.1

Build Operation ID: |K9ZrSSPWtrg=.1eb096d0_
Repository Commit : 1d2d3fd1-e1ef-47de-adc7-b7c87069fa0d

Detecting platforms...
Error: Oops... An unexpected error has occurred.
Error: Oops... An unexpected error has occurred.\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /tmp/build/expressbuild --platform python --platform-version 3.8 -i /tmp/8d8f5386e9b06e3 -p packagedir=.python_packages/lib/site-packages
Remote build failed!
```

**Comment by qianz2** [comment]
Hi @mauriciojost , could you share your app folder structure, what files you included in your app? Does it contain a setup.py file or requirement.txt file? These files are needed to be identified as a python app.

**Comment by mauriciojost** [comment]
The issue was caused by the Function App having a VNet integration. After disconnecting it I managed to publish the functions without problem.
The logged error was not useful at all though (even a timeout word mentioned would have been appreciated). Maybe this issue could be used to improve the error message in such scenarios?
Thanks for your help,
Mauricio

**Comment by drumph33** [comment]
I am having this same issue.  What seems to be happening is that the oryx build command needs access to the internet.  A common reason people are running function apps in vnet integrations is to restrict outbound traffic. 

 **If we know what IPs the oryx build command is hitting then we could allow it in the NSG which should fix the problem.**  

 I had a DenyAll rule as my only rule in the NSG.  I added a rule to allow internet from vnet on 443 and it deploys now.

**Does the oryx build command access a consistent set of IPs or is each build different?**

**Comment by arroyc** [comment]
@drumph33  oryx needs to get access to https://oryx-cdn.microsoft.io for a successful build

**Comment by denisrobert** [comment]
Why would this be closed? Makes no sense that this isn't considered a blocking issue. VNet integration is pretty fundamental to functions, and not being able to build with VNet Integration turned on is a tad ridiculous

**Comment by arroyc** [comment]
@denisrobert ... this is closed because this doesn't seem to be a build issue rather an issue with vnet configuration with function. Hope this makes sense now.

**Comment by Caramba77** [comment]
In fact, I had to open the following in order for the deployement to work, not just the oryx-cdn...
oryx-cdn.microsoft.io:443
pypi.org:443
files.pythonhosted.org:443
Then my deployment was able to finish correctly.
