### ISSUE TITLE
Regression: Yarn no longer works

### ISSUE THREAD

**Issue by phawxby** [microsoft/Oryx#972]
I have a Microsoft enterprise support ticket open to track this: 2103310050002615. Opening this ticket for public visibility of the issue. 

### Bug Report

Yarn no longer works during install on Node 14 with the error message 
`EACCES: permission denied, mkdir '/usr/local/share/yarn-cache'.`

#### At what date and time did you most recently experience the problem?
31/03/21

#### Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Web App

#### If your repo is publicly available please share its URL:
No

#### What happened?
It errored

#### What did you expect or want to happen?
I expected the Yarn install to complete.

#### How can we reproduce it?
Try and deploy any web application via yarn on Node 14.

#### Note from support

In the Node 12, where the deployment is successful we can see `success Set "cache-folder" to /usr/local/share/yarn-cache".,,0`
![image](https://user-images.githubusercontent.com/1090602/113346326-9ce40c80-932b-11eb-8f26-976db3542b9d.png)

While in the Node 14 this is missing:
![image](https://user-images.githubusercontent.com/1090602/113346342-a0779380-932b-11eb-8276-a9c74aaea9cc.png)

Support have identified this commit as bad.
https://github.com/microsoft/Oryx/commit/f064fe972fac84c4d924ba621a7e47af341751bf

PR #966

**Comment by qianz2** [comment]
Hi @phawxby , we recently removed yarn cache layer from full image for its large size and trying to improve our build image overall. The yarn-cache folder was removed and looks that Azure web app is still using it, we're working on a fix for it, it's expected to roll out in our next release.

**Comment by qianz2** [comment]
https://github.com/microsoft/Oryx/pull/976

**Comment by qianz2** [comment]
Hi @phawxby , this should be fixed in our latest release, your issue has been addressed and it will be working soon. So close it, feel free to open it again if you have more questions.

**Comment by chaaya** [comment]
I am facing the same issue now. It started all of the sudden two weeks ago.

https://github.com/microsoft/Oryx/issues/1615
