### ISSUE TITLE
Build apps with a custom Docker image

### ISSUE THREAD

**Issue by FScaccheri** [Microsoft/Oryx#98]
### Feature Request

I would like to be able to make Onyx build apps using a custom running Docker image, so that I'm able to install a system package (more specifically **build-essential**).

**Comment by JasonRShaver** [comment]
We've investigate this, but there are some security concerns that need to be solved before the scenario can be enabled on App Service.  We are looking into supporting this scenario, but I don't have a timeline to share other than "not soon".

As a recommendation (and please reply if this can't support your requirement), while this does not use Oryx, consider: https://azure.microsoft.com/en-us/services/app-service/containers/

**Comment by FScaccheri** [comment]
I will try to deploy my application using Web App for Containers, and come back with an update if it either did or didn't work. Thanks for the reply!
