### ISSUE TITLE
Build Error Azure Static Web Apps

### ISSUE THREAD

**Issue by TheDev6** [microsoft/Oryx#986]
### Bug Report

- At what date and time did you most recently experience the problem?
- -Tuesday 4-13-21 8AM Pacific

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
-- Azure Web Apps

- If your repo is publicly available please share its URL:
- -https://github.com/TheDev6/vue-nuxt

- What happened?
- -Won't deploy to Azure Static web apps and potential 'work arounds' are catch 22, 'add setting' can't if you don't need an api layer.

- What did you expect or want to happen?
-- Successful build and deploy that matches ANY popular demo guide

- How can we reproduce it?
- Examine the build logs. Try this documentation https://nuxtjs.org/docs/2.x/deployment/deployment-azure-static-web-apps/

- Do you have log output? Please include between the backticks:

```
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20210322.1, Commit: 4cf867db3013ec00acf62faac22d09667e0fa8d6, ReleaseTagName: 20210322.1

Build Operation ID: |xSt8T6Fu1yU=.d0fa1df7_
Repository Commit : 6419195b7ab6aec9cfcdb70daddfd393f8c92e47

Detecting platforms...
Could not detect any platform in the source directory.
Error: Could not detect the language from repo.


---End of Oryx build logs---
Oryx was unable to determine the build steps. Continuing assuming the assets in this folder are already built. If this is an unexpected behavior please contact support.
Finished building app with Oryx
Failed to find a default file in the app artifacts folder (/). Valid default files: index.html,Index.html.
If your application contains purely static content, please verify that the variable 'app_location' in your workflow file (located in .github/workflows) points to the root of your application.
If your application requires build steps, please validate that a default file exists in the build output directory.
```

**Comment by qianz2** [comment]
Hi @TheDev6 , I see that you have a `sample ` folder which is the root repo of your nodejs app, so it should be your `app_location`. Looks that something wrong when you set up the `app_location `or `api_location ` in your workflows. Could you check them to make sure they're all correct?

**Comment by TheDev6** [comment]
Thank you for responding :) I did get this to work. It's the classic path problem when I setup azure static web sites with '/' instead of '/sample' or '/dist'.
