### ISSUE TITLE
Cannot use native node.js modules in Linux App Services

### ISSUE THREAD

**Issue by markwolff** [microsoft/Oryx#99]
### Bug Report

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.

During deployment

- If your repo is publicly available please share its URL:

You can repro this in the App Service SSH blade and installing any native node module. I've used [bcrypt](https://github.com/kelektiv/node.bcrypt.js) in my example, but any other native node.js module will have the same result.
I'm using a *Linux* App Service instance with a runtime of **Node 10.14**
```
mkdir test && cd test
npm init
npm install bcrypt
```

- What happened?

Complains about python not being available.
```
a74961f3ac98:~/test# npm install bcrypt

> bcrypt@3.0.6 install /root/test/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v64-linux-x64-musl.tar.gz
node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.6 and node@10.14.1 (node-v64 ABI, musl) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Linux 4.4.0-128-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/root/test/node_modules/bcrypt/lib/binding
/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/root/test/node_modules/bcrypt/lib/binding" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v6
4"
gyp ERR! cwd /root/test/node_modules/bcrypt
gyp ERR! node -v v10.14.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/test/node_mo
dules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/root/test/node_modules/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_l
abel=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/test/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Linux 4.4.0-128-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/root/test/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /root/test/node_modules/bcrypt
node-pre-gyp ERR! node -v v10.14.1
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/test/node_modules/bcrypt/lib/binding/bcrypt
_lib.node --module_name=bcrypt_lib --module_path=/root/test/node_modules/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@3.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@3.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-25T18_48_06_167Z-debug.log
```

**Comment by arroyc** [comment]
Thanks @markwolff .. we are working on this and will update you soon

**Comment by arroyc** [comment]
yeah long story short >> need to use single image for build and runtime .. else native node modules will always be a problem, need to plan to roll out this on our end

**Comment by arroyc** [comment]
@markwolff  .. we have updated our images, but it may take some time to roll out .. please feel free to post here if you still see this issue after 2 weeks (approx.)

**Comment by capraynor** [comment]
@arroyc
FYI 
Seems that I can use `node-pre-gyp` when I installing `nodegit` in app service, but node-pre-gyp not works so good when I set `BUILD_FLAGS` to `Off`.

**Comment by arroyc** [comment]
@capraynor .. I see …  it will be nice if you can share your sample app or package dependencies so that we can troubleshoot more

**Comment by arroyc** [comment]
@markwolff @capraynor  I'm closing this issue for now.... feel free to log any new issues you find

**Comment by kevinjamesbaker** [comment]
is this still an open issue?  I am on an azure app linux service.

canvas@2.5.0 install /home/site/wwwroot/node_modules/canvas
2019-07-01T06:09:18.393598073Z: [INFO]  > node-pre-gyp install --fallback-to-build
2019-07-01T06:09:18.393606673Z: [INFO]
2019-07-01T06:09:27  No new trace in the past 1 min(s).
2019-07-01T06:09:28.528773780Z: [ERROR]  node-pre-gyp WARN Using request for node-pre-gyp https download
2019-07-01T06:09:29.756288948Z: [ERROR]  node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.5.0/canvas-v2.5.0-node-v64-linux-musl-x64.tar.gz
2019-07-01T06:09:29.766796887Z: [ERROR]  node-pre-gyp WARN Pre-built binaries not found for canvas@2.5.0 and node@10.14.1 (node-v64 ABI, musl) (falling back to source compile with node-gyp)
2019-07-01T06:09:31.372629556Z: [ERROR]  gyp ERR! configure error
2019-07-01T06:09:31.394873886Z: [ERROR]  gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

**Comment by arroyc** [comment]
@kevinjamesbaker can you tell us which version are you using? you can simply do `oryx --version`  and share the output here

**Comment by kevinjamesbaker** [comment]
This is the version that comes preinstalled on azure linux web app with node LTS (10.14)

Oryx Version : 0.2.20190427.2, Commit: 67e4df8c66720a3f939e764c766ef8cda1fb1c85

**Comment by arroyc** [comment]
@kevinjamesbaker , thanks for reporting the issue … I did a quick look at the releases and it seems the fix is on June releases, and the version you are using is still pointing to the old April release (20190427), I will follow up and post here once I know when the latest version (with fix) is available for use. I'm reopening this for tracking till then !

**Comment by arroyc** [comment]
@kevinjamesbaker this should have been fixed now. Please reach back if you still see this issue.
Note: ssh-ing into your environment and manually installing node packages won't work because ssh-ing will take you to run images. To build (npm install or yarn add) you need to keep your packages listed in package.json wither as package dependency or as a script (pre or post build etc)
