### ISSUE TITLE
Not working with dotnet 5

### ISSUE THREAD

**Issue by ffMathy** [microsoft/Oryx#994]
In this repo, my `main` branch builds successfully, but this branch does not (which has updated to dotnet 5):
https://github.com/sponsorkit/sponsorkit.io/runs/2384318944?check_suite_focus=true

I have no idea of what to do about this.

**Comment by arroyc** [comment]
Can you please share the logs?

**Comment by ffMathy** [comment]
It's an open source repo. The logs should be public?

**Comment by sujithq** [comment]
I have exact the same issue: a static web app with an .NET 5 Api and a Blazor Client

Logs: https://github.com/sujithq/ColdStart-Challenge-2021/actions/runs/791786690

**Comment by qianz2** [comment]
Hello, I saw from the logging that you have a .NET app using 5.05 but Oryx downloaded 5.02 SDK, I think that may be the reason why metadata generation failed.. We'll investigate our SDKs to see if 5.05 is included.

**Comment by sujithq** [comment]
> Hello, I saw from the logging that you have a .NET app using 5.05 but Oryx downloaded 5.02 SDK, I think that may be the reason why metadata generation failed.. We'll investigate our SDKs to see if 5.05 is included.

I don think that is the issue: 
I try to build a static web app
Api: Function App using net5 (this part fails .NET app using 5.05 but Oryx downloaded 5.02 SDK but still expected net core 3.1 for some reason)
App: Blazor Webassembly using net5 (this part is ok: .NET app using 5.05 but Oryx downloaded 5.02 SDK)

I did some tests again: one using a reference to Microsoft.Azure.Functions.Worker.Sdk 1.0.2 and one omitting it.

This one fails (with sdk reference)
https://github.com/sujithq/ColdStart-Challenge-2021/actions/runs/795287699
This one succeeds (no sdk reference)
https://github.com/sujithq/ColdStart-Challenge-2021/actions/runs/795298109

So I think it is an issue for the SDK team: If you try to build their samples (functionapp) using this docker container mcr.microsoft.com/dotnet/sdk:5.0 its fails too. If you change the sdk package reference to a project reference then it is successful.

I hope this helps.

**Comment by NDMWonsil** [comment]
I, too, am having an issue with deploying the standard Getting Started Blazor Static app from the Docs.
https://docs.microsoft.com/en-us/azure/static-web-apps/deploy-blazor

My build errors out with a different message: 
```
Detecting platforms...
Could not detect any platform in the source directory.
Error: Could not detect the language from repo.
```
Here's the [Build](https://github.com/NDMWonsil/blazor-starter/runs/2588085304). 

It may be more of an issue with the Static Web code in the tutorial than with Oryx but I wanted to let you know that the tutorial fails in the deployment step and not running locally.

**Comment by awentzel** [comment]
I have the same issue no matter if it's Node or PHP on a brand new app service (Linux).  I'm attempting to deploy from VS Code using App Service package.  I select the files to deploy from a `www` folder and get the exact same message.

```
9:36:34 AM fast-tooling: Creating zip package...
9:36:41 AM fast-tooling: Updating submodules.
9:36:42 AM fast-tooling: Preparing deployment for commit id 'a7e3bb53-8'.
9:36:42 AM fast-tooling: Repository path is /tmp/zipdeploy/extracted
9:36:42 AM fast-tooling: Running oryx build...
9:36:43 AM fast-tooling: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform php --platform-version 7.4 -i /tmp/8d91951f3f0b7be --log-file /tmp/build-debug.log 
9:36:45 AM fast-tooling: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
9:36:45 AM fast-tooling: You can report issues at https://github.com/Microsoft/Oryx/issues
9:36:45 AM fast-tooling: Oryx Version: 0.2.20210225.2, Commit: f7b557f29a83aa078cc94c0056e7337c07f14271, ReleaseTagName: 20210225.2
9:36:45 AM fast-tooling: Build Operation ID: |3vRZSGktAnE=.7e45ca8c_
9:36:45 AM fast-tooling: Repository Commit : a7e3bb53-8692-4780-855e-4ef4ee09fe0d
9:36:45 AM fast-tooling: Detecting platforms...
9:36:45 AM fast-tooling: Could not detect any platform in the source directory.
9:36:45 AM fast-tooling: Error: Couldn't detect a version for the platform 'php' in the repo.
9:36:48 AM fast-tooling: /opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform php --platform-version 7.4 -i /tmp/8d91951f3f0b7be --log-file /tmp/build-debug.log 
9:36:50 AM fast-tooling: Deployment failed.
```

**Comment by qianz2** [comment]
> I, too, am having an issue with deploying the standard Getting Started Blazor Static app from the Docs.
> https://docs.microsoft.com/en-us/azure/static-web-apps/deploy-blazor
> 
> My build errors out with a different message:
> 
> ```
> Detecting platforms...
> Could not detect any platform in the source directory.
> Error: Could not detect the language from repo.
> ```
> 
> Here's the [Build](https://github.com/NDMWonsil/blazor-starter/runs/2588085304).
> 
> It may be more of an issue with the Static Web code in the tutorial than with Oryx but I wanted to let you know that the tutorial fails in the deployment step and not running locally.

Could you check if your `app_location` or `api_location` is correct, from the logging information, it looks that the default files could not be found at your `app_location`.

**Comment by qianz2** [comment]
> I have the same issue no matter if it's Node or PHP on a brand new app service (Linux). I'm attempting to deploy from VS Code using App Service package. I select the files to deploy from a `www` folder and get the exact same message.
> 
> ```
> 9:36:34 AM fast-tooling: Creating zip package...
> 9:36:41 AM fast-tooling: Updating submodules.
> 9:36:42 AM fast-tooling: Preparing deployment for commit id 'a7e3bb53-8'.
> 9:36:42 AM fast-tooling: Repository path is /tmp/zipdeploy/extracted
> 9:36:42 AM fast-tooling: Running oryx build...
> 9:36:43 AM fast-tooling: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform php --platform-version 7.4 -i /tmp/8d91951f3f0b7be --log-file /tmp/build-debug.log 
> 9:36:45 AM fast-tooling: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
> 9:36:45 AM fast-tooling: You can report issues at https://github.com/Microsoft/Oryx/issues
> 9:36:45 AM fast-tooling: Oryx Version: 0.2.20210225.2, Commit: f7b557f29a83aa078cc94c0056e7337c07f14271, ReleaseTagName: 20210225.2
> 9:36:45 AM fast-tooling: Build Operation ID: |3vRZSGktAnE=.7e45ca8c_
> 9:36:45 AM fast-tooling: Repository Commit : a7e3bb53-8692-4780-855e-4ef4ee09fe0d
> 9:36:45 AM fast-tooling: Detecting platforms...
> 9:36:45 AM fast-tooling: Could not detect any platform in the source directory.
> 9:36:45 AM fast-tooling: Error: Couldn't detect a version for the platform 'php' in the repo.
> 9:36:48 AM fast-tooling: /opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform php --platform-version 7.4 -i /tmp/8d91951f3f0b7be --log-file /tmp/build-debug.log 
> 9:36:50 AM fast-tooling: Deployment failed.
> ```

Hi, did you include php composer file or `*.php` extension files in your apps?

**Comment by qianz2** [comment]
Closing it, feel free to reopen one if you have other questions.

**Comment by ffMathy** [comment]
It was indeed found @qianz2. Please re-open.

However, I switched away from Azure Functions and static web apps now entirely, so I can't reproduce much anymore. Perhaps the others experiencing the issue can?
