### ISSUE TITLE
Detecting platforms... Error: Oops... An unexpected error has occurred.

### ISSUE THREAD

**Issue by kasuteru** [microsoft/Oryx#997]
### Bug Report

Error occured today, when trying to deploy a very simple Django WebApp (basically, the first page of the tutorial) to Azure via Github Actions.

The error is really unhelpful unfortunately, basically the title already contains all the information I have:

> Oryx Version: 0.2.20201112.1, Commit: a120bb248aa8d208ca5e02d7d9d075196e79cffd, ReleaseTagName: 20201112.1
> 
> Build Operation ID: |e0tNYKVwD8c=.de115edd_
> Repository Commit : dd6342a3329d0d085725a4e48236a55a1384e00e
> 
> Detecting platforms...
> Error: Oops... An unexpected error has occurred.

This might have to do something with proxy configuration / VPNs - I am working in a corporate environment and afaik, the webapp is configured to run inside a VNet and the github runner might not have full internet connectivity. Is there any way to get more information on what line of code exactly failed and why, so that I can investigate?

When deploying the exact same code to the WebApp directly (with git push), the WebApp deploys correctly.

This seems related to #971 or #848

**Comment by drumph33** [comment]
I am having this same issue.  What seems to be happening is that the oryx build command needs access to the internet.  A common reason people are running function apps in vnet integrations is to restrict outbound traffic.  

**If we know what IPs the oryx build command is hitting then we could allow it in the NSG which should fix the problem.** 

I had a DenyAll rule as my only rule in the NSG.  I added a rule to allow internet from vnet on 443 and it deploys now.

**Comment by arroyc** [comment]
duplicate #971
