### ISSUE TITLE
api_build_command is not overriding regular Oryx deployment commands

### ISSUE THREAD

**Issue by skenway** [microsoft/Oryx#999]
We are blocked due to the the following exception during the Static Web App deployment process.  

`error azure-function-express@2.0.0: The engine "node" is incompatible with this module. Expected version ">=6.11.2 <11". Got "14.15.1"`

To resolve this issue, we are attempting to override the api build commands.  We would like to add the --ignore-engines flag to avoid the error.  See the yaml below. 

--------------yaml----------------------
name: Azure Static Web Apps CI/CD - jolly-plant-XXXXXXXX

on:
  push:
    branches:
      - development
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - development

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_PLANT_XXXXXXX }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          api_build_command: yarn install --ignore-engines --prefer-offline --production && yarn run start
          ###### End of Repository/Build Configurations ######
-----------------------------------------------

The yaml returns the log below.  The api_build_command is executed but the regular command is also executed after. 

--------Build Log---------------
Finished building app with Oryx
Starting to build function app with Oryx
Oryx will build function app with the following custom override command: yarn install --ignore-engines --prefer-offline --production && yarn run start
---Oryx build logs---

Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20210410.1, Commit: XXXXXXXXX, ReleaseTagName: 20210410.1

Build Operation ID: |YiIX4BOunKQ=.501af64f_
Repository Commit : XXXXXXXXX

Detecting platforms...
Detected following platforms:
  nodejs: 14.15.1

Source directory     : /github/workspace/api
Destination directory: /bin/staticsites/ss-oryx/api

Using Node version:
v14.15.1

Using Yarn version:
1.22.10

Installing production dependencies in '/github/workspace/api/.oryx_prod_node_modules'...

Running 'yarn install --prefer-offline --production'...

yarn install v1.22.10
warning package.json: No license field
warning ../package.json: No license field
warning api@1.0.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
error azure-function-express@2.0.0: The engine "node" is incompatible with this module. Expected version ">=6.11.2 <11". Got "14.15.1"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Found incompatible module.

---End of Oryx build logs---
Oryx has failed to build the solution.
-------------------------------------

**Comment by qianz2** [comment]
A workaround for it will be setting up `CUSTOM_BUILD_COMMAND ` to be `yarn install --ignore-engines --prefer-offline --production && yarn run start` and do not add `prune_dev_dependencies` so that Oryx will skip this command: `yarn install --prefer-offline --production`

**Comment by skenway** [comment]
Thanks for the response.  @qianz2 how and where I do exclude prune_dev_dependencies?  Is this explicitly added to the api_build_command?  

Also for clarification on syntax, when you state CUSTOM_BUILD_COMMAND, are you referring to api_build_command?

**Comment by qianz2** [comment]
`CUSTOM_BUILD_COMMAND `is an environment variable that you could add into your workflows, it's not `api_build_command`.
I don't know how static web app use Oryx command, it looks that the `--prune_dev_dependencies` property key is added into the command when they called it.

**Comment by qianz2** [comment]
`PRUNE_DEV_DEPENDENCIES` can be also passed in as an env variable, and it will override. So you can try to set it up in your workflows to see if it can resolve your case. Thank you!
